### ISSUE TITLE
visuals.SurfacePlot not accepting correctly shaped colors

### ISSUE THREAD

**Issue by michaelaye** [vispy/vispy#1006]
According to the docstring colors should be:

``` python
colors : ndarray
    (width, height, 4) array of vertex colors.
```

My input array is:

``` python
colors.shape
(455, 397, 4)
```

and it fits to the surface z data:

``` python
container['dem'].shape
(455, 397)
```

The error:

``` python
/Users/klay6683/Dropbox/src/vispy/vispy/color/color_array.py in _user_to_rgba(color, expand, clip)
     55     color = np.atleast_2d(color).astype(np.float32)
     56     if color.shape[1] not in (3, 4):
---> 57         raise ValueError('color must have three or four elements')
     58     if expand and color.shape[1] == 3:  # only expand if requested
     59         color = np.concatenate((color, np.ones((color.shape[0], 1))),

ValueError: color must have three or four elements
```

**Comment by michaelaye** [comment]
As colormap does not return (w, h, 4) but (w*h, 4) I was trying to provide that shape to colors, but then I get a different error that indicates that color_array demands the first dimensions to be == 1 which does not fit to the requested shape either:
```python
/Users/klay6683/Dropbox/src/vispy/vispy/color/color_array.py in __init__(self, color, alpha, clip)
    388         rgba = _user_to_rgba(color, clip=clip)
    389         if rgba.shape[0] != 1:
--> 390             raise ValueError('color must be of correct shape')
    391         if alpha is not None:
    392             rgba[:, 3] = alpha

ValueError: color must be of correct shape
```

**Comment by michaelaye** [comment]
Can you provide a guideline where we should refactor and/or reimplement to make this work? Should we maybe split off a colormap module that does the same stuff in all plotting systems? Probably one cannot generalize for everybody, but some calculations should be really always the same.

**Comment by dsmbgu8** [comment]
I'm running into this exact issue as well, and it wasn't immediately apparent to me how to resolve the colormap shape requirements. 

It seems to me that, when the color argument passed to the SurfacePlot class is an array with the same shape as the vertices, SurfacePlot should pass the color array to the MeshVisual as 'vertex_colors', rather than 'colors', but when I do that the MeshData object errors out since its vertices_indexed_by_faces member is None. 

```python
Traceback (most recent call last):
  File "scene/surface_plot.py", line 29, in <module>
    p1 = scene.visuals.SurfacePlot(z=z, colors=c)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/visuals.py", line 126, in __init__
    subclass.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/visuals/surface_plot.py", line 50, in __init__
    self.set_data(x, y, z, colors)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/visuals/surface_plot.py", line 127, in set_data
    self.__meshdata.set_vertex_colors(colors)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/geometry/meshdata.py", line 388, in set_vertex_colors
    if colors.shape[0] != self.n_vertices:
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/geometry/meshdata.py", line 473, in n_vertices
    self._compute_unindexed_vertices()
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/geometry/meshdata.py", line 488, in _compute_unindexed_vertices
    self._faces = np.empty(faces.shape[:2], dtype=np.uint32)
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by MaxNoe** [comment]
I'm having a similar issue.

The docstring clearly says 
```
colors : ndarray
    (width, height, 4) array of vertex colors.
```

But when I provide that to the `SurfacePlot` function, I get:
```
ValueError: colors must be 2D if indexed is None
```

**Comment by orodbhen** [comment]
Same issue as @MaxNoe 
`````
   fig[0, 0].surface(z, x=x, y=y, colors=colors)
  File "/home/me/workspace/vispy/vispy/plot/plotwidget.py", line 362, in surface
    surf = scene.SurfacePlot(z=zdata, **kwargs)
  File "/home/me/workspace/vispy/vispy/scene/visuals.py", line 126, in __init__
    subclass.__init__(self, *args, **kwargs)
  File "/home/me/workspace/vispy/vispy/visuals/surface_plot.py", line 50, in __init__
    self.set_data(x, y, z, colors)
  File "/home/me/workspace/vispy/vispy/visuals/surface_plot.py", line 127, in set_data
    self.__meshdata.set_vertex_colors(colors)
  File "/home/me/workspace/vispy/vispy/geometry/meshdata.py", line 387, in set_vertex_colors
    raise ValueError('colors must be 2D if indexed is None')
ValueError: colors must be 2D if indexed is None
`````

Changing to 2D results in the `NoneType` exception mentioned by @dsmbgu8.

**Comment by pocdn** [comment]
One must set the colors on a per vertex basis ie vertex_colors. One way this can be accomplished is as follows;        

```
import vispy.plot as vp
from vispy import color
from vispy.util.filter import gaussian_filter
import numpy as np

z = np.random.normal(size=(250, 250), scale=200)
z[100, 100] += 50000
z = gaussian_filter(z, (10, 10))

fig = vp.Fig(show=False)
cnorm = z / abs(np.amax(z))
c = color.get_colormap("hsl").map(cnorm).reshape(z.shape + (-1,))
c = c.flatten().tolist()
c=list(map(lambda x,y,z,w:(x,y,z,w), c[0::4],c[1::4],c[2::4],c[3::4]))

#p1 = fig[0, 0].surface(z, vertex_colors=c) # why doesn't vertex_colors=c work?
p1 = fig[0, 0].surface(z)
p1.mesh_data.set_vertex_colors(c) # but explicitly setting vertex colors does work?

fig.show()
```

Note the use of the explicit setter set_vertex_colors worked fine. Unfortunately (a bug possibly) when passing c to surface(z, vertex_colors=c) ran without error but did not change the per vertex colors. Conclusion: use explicit set_vertex_colors.

**Comment by djhoese** [comment]
This issue is very old and I was just helping someone with a similar per-vertex color issue on gitter. Due to the age of this issue I'm going to say this is being replaced by #2001.
