### ISSUE TITLE
Traceback: wxGLCanvasBase::SetCurrent(): can't make hidden GL canvas current

### ISSUE THREAD

**Issue by daverz** [vispy/vispy#1020]
This is with wxpython 3.0.2.0 and several of the examples that I tried.

C:...\vispy\examples\basics\plotting>python scatter_histogram.py
INFO: Could not import backend "PyQt4":
No module named PyQt4
INFO: Could not import backend "PyQt5":
No module named PyQt5
INFO: Could not import backend "PySide":
No module named PySide
INFO: Could not import backend "Pyglet":
No module named pyglet
INFO: Could not import backend "Glfw":
GLFW library not found
INFO: Could not import backend "SDL2":
No module named sdl2
Traceback (most recent call last):
  File "scatter_histogram.py", line 18, in <module>
    fig = vp.Fig(show=False)
  File "C:\Python27\lib\site-packages\vispy-0.5.0.dev0-py2.7.egg\vispy\plot\fig.py", line 39, in **init**
    show=show, size=size)
  File "C:\Python27\lib\site-packages\vispy-0.5.0.dev0-py2.7.egg\vispy\scene\canvas.py", line 128, in **init**
    always_on_top, px_scale)
  File "C:\Python27\lib\site-packages\vispy-0.5.0.dev0-py2.7.egg\vispy\app\canvas.py", line 206, in **init**
    self.set_current()
  File "C:\Python27\lib\site-packages\vispy-0.5.0.dev0-py2.7.egg\vispy\app\canvas.py", line 406, in set_current
    self._backend._vispy_set_current()
  File "C:\Python27\lib\site-packages\vispy-0.5.0.dev0-py2.7.egg\vispy\app\backends_wx.py", line 294, in _vispy_set_current
    self.SetCurrent(self._gl_context)
  File "C:\Python27\lib\site-packages\wx-3.0-msw\wx\glcanvas.py", line 140, in SetCurrent
    return _glcanvas.GLCanvas_SetCurrent(*args)
wx._core.PyAssertionError: C++ assertion "IsShown()" failed at ....\src\common\glcmn.cpp(59) in wxGLCanvasBase::SetCurrent(): can't make hidden GL canvas current

This is with 64-bit Python 2.7.10 on windows 7.  Installed packages:

C:...>pip list
backports.ssl-match-hostname (3.4.0.2)
certifi (2015.4.28)
decorator (3.4.2)
functools32 (3.2.3.post2)
ipython (3.2.1)
Jinja2 (2.7.3)
jsonschema (2.5.1)
MarkupSafe (0.23)
matplotlib (1.4.3)
numpy (1.9.2)
pip (7.1.0)
py2exe (0.6.10a1)
PyAudio (0.2.8)
PyOpenGL (3.1.1a1)
PyOpenGL-accelerate (3.1.1a1)
pyparsing (2.0.3)
python-dateutil (2.4.2)
pytz (2015.4)
pywin32 (219)
pyzmq (14.7.0)
scipy (0.16.0rc1)
setuptools (16.0)
six (1.9.0)
tornado (4.2.1)
vispy (0.5.0.dev0)
wxPython (3.0.2.0)
wxPython-common (3.0.2.0)

**Comment by Eric89GXL** [comment]
Thanks. I wonder if we need to always show the `wx` canvas when creating it, then hide it if `show=False` or something...

**Comment by mattip** [comment]
For me (python 2.7.10 on win7) it was enough to add  ``if show: self.set_current()``
instead of ``self.set_current()`` in  ``canvas.py``
