### ISSUE TITLE
OpenGL error on Windows in Python 2.7

### ISSUE THREAD

**Issue by astrofrog** [vispy/vispy#1054]
I have run into an OpenGL error when using Volume rendering on Windows. Strangely, the issue happens with Python 2.7 but not 3.4. I've manage to boil this down to a minimal example:

``` python
import numpy as np
from PyQt4 import QtGui
from vispy import scene


class QtVispyWidget(QtGui.QWidget):
    def __init__(self, parent=None, data=None):
        super(QtVispyWidget, self).__init__(parent=parent)
        self.canvas = scene.SceneCanvas(show=True)
        view = self.canvas.central_widget.add_view()
        volume = scene.visuals.Volume(data, parent=view.scene)
        view.camera = scene.cameras.TurntableCamera(parent=view.scene)

# Start up Qt application
qapp = QtGui.QApplication([''])
qapp.setQuitOnLastWindowClosed(True)

# Create fake data
data = np.arange(1000).reshape((10, 10, 10))

# Set up widget
w = QtVispyWidget(data=data)
w.canvas.render()
```

I placed this example in the following repository:

https://github.com/astrofrog/debug-windows-vispy

and set it to run on AppVeyor. Note that I included the downloading of OpenGL as in the AppVeyor file for VisPy.

The error I get is:

``` python
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    w.canvas.render()
  File "C:\conda\envs\test\lib\site-packages\vispy\scene\canvas.py", line 221, in render
    self._draw_scene(viewport=(0, 0) + size)
  File "C:\conda\envs\test\lib\site-packages\vispy\scene\canvas.py", line 232, in _draw_scene
    self.draw_visual(self.scene, viewport=viewport)
  File "C:\conda\envs\test\lib\site-packages\vispy\scene\canvas.py", line 282, in draw_visual
    visual.draw(scene_event)
  File "C:\conda\envs\test\lib\site-packages\vispy\scene\subscene.py", line 50, in draw
    self.process_system(event, 'draw')
  File "C:\conda\envs\test\lib\site-packages\vispy\scene\subscene.py", line 60, in process_system
    self._systems[system_name].process(event, self)
  File "C:\conda\envs\test\lib\site-packages\vispy\scene\systems.py", line 37, in process
    self.process(event, sub_node)
  File "C:\conda\envs\test\lib\site-packages\vispy\scene\systems.py", line 37, in process
    self.process(event, sub_node)
  File "C:\conda\envs\test\lib\site-packages\vispy\scene\systems.py", line 28, in process
    _handle_exception(False, 'reminders', self, node=node)
  File "C:\conda\envs\test\lib\site-packages\vispy\scene\systems.py", line 23, in process
    node.draw(event)
  File "C:\conda\envs\test\lib\site-packages\vispy\scene\widgets\viewbox.py", line 324, in draw
    self.scene.draw(event)
  File "C:\conda\envs\test\lib\site-packages\vispy\scene\subscene.py", line 50, in draw
    self.process_system(event, 'draw')
  File "C:\conda\envs\test\lib\site-packages\vispy\scene\subscene.py", line 60, in process_system
    self._systems[system_name].process(event, self)
  File "C:\conda\envs\test\lib\site-packages\vispy\scene\systems.py", line 37, in process
    self.process(event, sub_node)
  File "C:\conda\envs\test\lib\site-packages\vispy\scene\systems.py", line 28, in process
    _handle_exception(False, 'reminders', self, node=node)
  File "C:\conda\envs\test\lib\site-packages\vispy\scene\systems.py", line 23, in process
    node.draw(event)
  File "C:\conda\envs\test\lib\site-packages\vispy\visuals\volume.py", line 676, in draw
    self._program.draw('triangle_strip', self._index_buffer)
  File "C:\conda\envs\test\lib\site-packages\vispy\visuals\shaders\program.py", line 89, in draw
    Program.draw(self, *args, **kwargs)
  File "C:\conda\envs\test\lib\site-packages\vispy\gloo\program.py", line 467, in draw
    canvas.context.flush_commands()
  File "C:\conda\envs\test\lib\site-packages\vispy\gloo\context.py", line 170, in flush_commands
    self.glir.flush(self.shared.parser)
  File "C:\conda\envs\test\lib\site-packages\vispy\gloo\glir.py", line 231, in flush
    self._shared.flush(parser)
  File "C:\conda\envs\test\lib\site-packages\vispy\gloo\glir.py", line 145, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "C:\conda\envs\test\lib\site-packages\vispy\gloo\glir.py", line 457, in parse
    self._parse(command)
  File "C:\conda\envs\test\lib\site-packages\vispy\gloo\glir.py", line 429, in _parse
    ob.set_size(*args)  # Texture[1D, 2D, 3D], RenderBuffer
  File "C:\conda\envs\test\lib\site-packages\vispy\gloo\glir.py", line 1197, in set_size
    gl.GL_BYTE, shape[:3])
  File "C:\conda\envs\test\lib\site-packages\vispy\gloo\glir.py", line 1146, in glTexImage3D
    width, height, depth, border, format, type, None)
  File "C:\conda\envs\test\lib\site-packages\OpenGL\latebind.py", line 45, in __call__
    return self._finalCall( *args, **named )
  File "C:\conda\envs\test\lib\site-packages\OpenGL\wrapper.py", line 867, in wrapperCall
    pyArgs = tuple( calculate_pyArgs( args ))
  File "C:\conda\envs\test\lib\site-packages\OpenGL\wrapper.py", line 438, in calculate_pyArgs
    yield converter(args[index], self, args)
  File "C:\conda\envs\test\lib\site-packages\OpenGL\GL\images.py", line 454, in __call__
    images.setupDefaultTransferMode()
  File "C:\conda\envs\test\lib\site-packages\OpenGL\images.py", line 69, in setupDefaultTransferMode
    _simple.glPixelStorei(_simple.GL_PACK_SWAP_BYTES, 0)
  File "C:\conda\envs\test\lib\site-packages\OpenGL\platform\baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "C:\conda\envs\test\lib\site-packages\OpenGL\error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
    err = 1282,
    description = 'invalid operation',
    baseOperation = glPixelStorei,
    cArguments = (GL_PACK_SWAP_BYTES, 0)
)
```

The full logs (comparing 2.7 and 3.4) can be found here:

https://ci.appveyor.com/project/astrofrog/debug-windows-vispy/build/1.0.12

Conda is installing vispy-0.4.0.106.gf8a69d0

**Comment by Eric89GXL** [comment]
Does the example actually require Qt to fail? In other words, can you get that without explicitly using Qt?

**Comment by Eric89GXL** [comment]
Also could you please try the latest `master` version instead of the `conda` version?

**Comment by astrofrog** [comment]
@Eric89GXL - the error still happens without Qt:

```python
from vispy import scene

import numpy as np

data = np.arange(1000).reshape((10, 10, 10))

canvas = scene.SceneCanvas(show=True)
view = canvas.central_widget.add_view()
volume = scene.visuals.Volume(data, parent=view.scene)
view.camera = scene.cameras.TurntableCamera(parent=view.scene)

canvas.render()
```

See https://ci.appveyor.com/project/astrofrog/debug-windows-vispy/build/1.0.13/job/91cw66wagi7m3gut

I have also updated https://github.com/astrofrog/debug-windows-vispy to use VisPy from ``master`` and the error still happens:

https://ci.appveyor.com/project/astrofrog/debug-windows-vispy/build/1.0.16/job/icx4c9s3qmstarc0

**Comment by astrofrog** [comment]
@Eric89GXL - any idea what this could be due to?

**Comment by Eric89GXL** [comment]
Not really sure. Can you try using emulated 3d texture mode (`emulate_texture=True`) on the volume visual to see if it works that way?

**Comment by astrofrog** [comment]
@Eric89GXL - ``emulate_texture=True`` works. Are there any downsides to this?

**Comment by Eric89GXL** [comment]
It's very strange that it happens on only on of 2.7 and 3.4, but if the workaround works, I'll take it :) The emulation mode will probably be a little bit slower but maybe not noticeable. It uses a 2D texture to emulate a 3D texture. It might also have smaller volume-size limits, I'm not sure.

**Comment by astrofrog** [comment]
@Eric89GXL - I'm now seeing the same issue with:

```python
axis = scene.visuals.XYZAxis(parent=view.scene)
```

but this time, there is of course no emulate_texture option. Do you have any suggestions for how to fix this? The full error now is:

```
Executing: python test.py
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    canvas.render()
  File "C:\conda\envs\test\lib\site-packages\vispy\scene\canvas.py", line 244, in render
    self._draw_scene(bgcolor=bgcolor)
  File "C:\conda\envs\test\lib\site-packages\vispy\scene\canvas.py", line 253, in _draw_scene
    self.draw_visual(self.scene)
  File "C:\conda\envs\test\lib\site-packages\vispy\scene\canvas.py", line 291, in draw_visual
    node.draw()
  File "C:\conda\envs\test\lib\site-packages\vispy\scene\visuals.py", line 98, in draw
    self._visual_superclass.draw(self)
  File "C:\conda\envs\test\lib\site-packages\vispy\visuals\visual.py", line 588, in draw
    v.draw()
  File "C:\conda\envs\test\lib\site-packages\vispy\visuals\visual.py", line 432, in draw
    if self._prepare_draw(view=self) is False:
  File "C:\conda\envs\test\lib\site-packages\vispy\visuals\line\line.py", line 353, in _prepare_draw
    GL.glDisable(GL.GL_LINE_SMOOTH)
  File "C:\conda\envs\test\lib\site-packages\OpenGL\platform\baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "C:\conda\envs\test\lib\site-packages\OpenGL\error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1282,
	description = 'invalid operation',
	baseOperation = glDisable,
	cArguments = (GL_LINE_SMOOTH,)
)
```

**Comment by Eric89GXL** [comment]
I think that one is just a series of lines so it's not supposed to do anything complicated. I wonder if there is some ordering issue where GL commands are being sent before the context is ready or something silly. Can you try in your `test.py` putting your `canvas.render()` call inside a `with canvas:` context manager (it will try to ensure the context is ready before drawing, then close the canvas when it's done) and it might help.

**Comment by Eric89GXL** [comment]
This wouldn't be a permanent fix, but it would give us some indication of a potential fix/workaround.

**Comment by astrofrog** [comment]
@Eric89GXL - no luck with the context manager unfortunately. Here's the current version of the script I have:

https://github.com/astrofrog/debug-windows-vispy/blob/master/test.py

**Comment by djhoese** [comment]
This is an old issue and python 2.7 support will be dropped soon. So much has changed from 2015 that I can't think this is relevant anymore.
