### ISSUE TITLE
WARNING: Traceback : event.py", line 448, in _invoke_callback cb(event)

### ISSUE THREAD

**Issue by dlezcano** [vispy/vispy#1078]
Hi,

I modified the real_signals.py example to fit my needs. The program takes from stdin a list of values and plot them.

I am experiencing systematically a backtrace [1]. I used the dev version but the program does no longer work.

I can provide the source code and the data to be displayed.

ps: I am new to vispy *and* python :)

[1] WARNING: Traceback (most recent call last):
  File "rt.py", line 319, in <module>
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.4.0-py2.7.egg/vispy/app/_default_app.py", line 61, in run
    return default_app.run()
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.4.0-py2.7.egg/vispy/app/application.py", line 123, in run
    return self._backend._vispy_run()
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.4.0-py2.7.egg/vispy/app/backends/_qt.py", line 217, in _vispy_run
    return app.exec_()
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.4.0-py2.7.egg/vispy/app/backends/_qt.py", line 631, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.4.0-py2.7.egg/vispy/util/event.py", line 436, in __call__
    self._invoke_callback(cb, event)
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.4.0-py2.7.egg/vispy/util/event.py", line 452, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.4.0-py2.7.egg/vispy/util/event.py", line 448, in _invoke_callback
    cb(event)
  File "rt.py", line 217, in on_draw
    self.text_a57_0_cpu_energy.draw(self.tr_sys)
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.4.0-py2.7.egg/vispy/visuals/text/text.py", line 470, in draw
    self._program.bind(self._vertices)
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.4.0-py2.7.egg/vispy/gloo/program.py", line 235, in bind
    raise ValueError('Program.bind() requires a VertexBuffer.')
ValueError: Program.bind() requires a VertexBuffer.
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PySide) at 0xb5cfd64cL>> for DrawEvent
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PySide) at 0xb5cfd64cL>> repeat 2

**Comment by Eric89GXL** [comment]
Can you try on latest master? The easiest way to do it would be to something like:
```
$ sudo pip uninstall vispy
$ cd ~ # or wherever you want to clone the repo
$ git clone git://github.com/vispy/vispy.git
$ cd vispy
$ python setup.py develop --user
```
Now you will be up to date with the `master` branch here, and any changes you make to `~/vispy/vispy/` will be reflected next time you start the interpreter and `import vispy`.

Specifically, here it would be useful if you could modify `program.py` to do something like:
```
raise ValueError('Program.bind() requires a VertexBuffer, got %s' % type(whatever))
```
It would help shed some light on this, and make a great first PR, too :)

**Comment by dlezcano** [comment]
Hi Eric,

I tried on the latest master. The symptom is worst and my program is not working anymore.
The call trace is different [1]

I did the change you asked me but it does not appear with the currrent git head and when trying to reproduce with vispy-4.0.0, the 'whatever' type raise an error.

[1] Traceback (most recent call last):
WARNING: Traceback (most recent call last):
  File "rt.py", line 319, in <module>
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/app/_default_app.py", line 62, in run
    return default_app.run()
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/app/application.py", line 137, in run
    return self._backend._vispy_run()
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/app/backends/_qt.py", line 229, in _vispy_run
    return app.exec_()
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/app/backends/_qt.py", line 646, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "rt.py", line 214, in on_draw
    self.text_board_energy.draw(self.tr_sys)
TypeError: draw() takes exactly 1 argument (2 given)
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PySide) at 0xb5c7d56cL>> for DrawEvent
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PySide) at 0xb5c7d56cL>> repeat 2
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PySide) at 0xb5c7d56cL>> repeat 4
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PySide) at 0xb5c7d56cL>> repeat 8
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PySide) at 0xb5c7d56cL>> repeat 16
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PySide) at 0xb5c7d56cL>> repeat 32
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PySide) at 0xb5c7d56cL>> repeat 64
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PySide) at 0xb5c7d56cL>> repeat 128
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PySide) at 0xb5c7d56cL>> repeat 256
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PySide) at 0xb5c7d56cL>> repeat 512

**Comment by Eric89GXL** [comment]
The `whatever` was a placeholder for the variable name that is being used at that point in the function :) Looking at the 0.4 code, in this case that would be `data`, so something like this should work:
```
raise ValueError('Program.bind() requires a VertexBuffer, got %s' % type(data))
```
It looks like instead of doing `python setup.py develop --user` you did `sudo python setup.py install`, which makes it a bit more difficult to work with versions and development. If you go with `python setup.py develop --user`, then you can do `git checkout v0.4.0` to immediately switch back to `0.4` from current master, and do `git checkout master` to switch back.

For now, though, you'll probably have to `sudo pip uninstall vispy` again (or maybe `sudo rm -rf /usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg` if `pip` doesn't do it), then change version with the `checkout` line above, and then install in your manner of choice. But if you are modifying/developing code, it will probably become annoying to have to `python setup.py` all the time or set `sys.path` / PYTHONPATH, so I highly recommend using `develop`.

Coming back to 0.5, though -- the way visuals are constructed did change a bit from 0.4 to current `master`. It brought a lot of performance improvements, but it also required some changes to visuals. Is your code short/simple enough that you could paste it into a `gist`? That way we could look at it and possibly help translate the visual to the new system. You can also look at the [line_prototype.py example] (https://github.com/vispy/vispy/blob/master/examples/basics/visuals/line_prototype.py#L19) to see the sorts of changes required.

**Comment by dlezcano** [comment]
:)

Ok, I added the trace for 0.4 and I have [1].

I copied the program to https://gist.github.com/dlezcano/6d091a68fbdd6f4e1732

It is based on realtime_signals.py which works with 0.5dev.

[1]

WARNING: Traceback (most recent call last):
  File "rt.py", line 317, in <module>
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.4.0-py2.7.egg/vispy/app/_default_app.py", line 61, in run
    return default_app.run()
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.4.0-py2.7.egg/vispy/app/application.py", line 123, in run
    return self._backend._vispy_run()
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.4.0-py2.7.egg/vispy/app/backends/_qt.py", line 217, in _vispy_run
    return app.exec_()
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.4.0-py2.7.egg/vispy/app/backends/_qt.py", line 631, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.4.0-py2.7.egg/vispy/util/event.py", line 436, in __call__
    self._invoke_callback(cb, event)
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.4.0-py2.7.egg/vispy/util/event.py", line 452, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.4.0-py2.7.egg/vispy/util/event.py", line 448, in _invoke_callback
    cb(event)
  File "rt.py", line 224, in on_draw
    self.text_a57_0_cpu_energy.draw(self.tr_sys)
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.4.0-py2.7.egg/vispy/visuals/text/text.py", line 470, in draw
    self._program.bind(self._vertices)
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.4.0-py2.7.egg/vispy/gloo/program.py", line 236, in bind
    raise ValueError('Program.bind() requires a VertexBuffer, got %s' % type(data))
ValueError: Program.bind() requires a VertexBuffer, got <type 'NoneType'>
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PySide) at 0x41a0c74c>> for DrawEvent
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PySide) at 0x41a0c74c>> repeat 2
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PySide) at 0x41a0c74c>> repeat 3
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PySide) at 0x41a0c74c>> repeat 4
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PySide) at 0x41a0c74c>> repeat 5
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PySide) at 0x41a0c74c>> repeat 6
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PySide) at 0x41a0c74c>> repeat 7
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PySide) at 0x41a0c74c>> repeat 8
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PySide) at 0x41a0c74c>> repeat 9

**Comment by Eric89GXL** [comment]
It didn't actually print the type -- that's strange.

Instead of making a custom visual, do you think you could make use of the newer example:

https://github.com/vispy/vispy/blob/master/examples/demo/scene/scrolling_plots.py

?

**Comment by dlezcano** [comment]
I tried scrolling_plots but it fails with:

INFO: Could not import backend "PyQt4":
cannot import name QtOpenGL
INFO: Could not import backend "PyQt5":
No module named PyQt5
WARNING: Error drawing visual <ScrollingLines at 0xac19a2ec>
WARNING: Traceback (most recent call last):
  File "examples/demo/scene/scrolling_plots.py", line 55, in <module>
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/app/_default_app.py", line 62, in run
    return default_app.run()
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/app/application.py", line 137, in run
    return self._backend._vispy_run()
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/app/backends/_qt.py", line 229, in _vispy_run
    return app.exec_()
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/app/backends/_qt.py", line 646, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/canvas.py", line 207, in on_draw
    self._draw_scene()
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/canvas.py", line 253, in _draw_scene
    self.draw_visual(self.scene)
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/canvas.py", line 291, in draw_visual
    node.draw()
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/visuals.py", line 98, in draw
    self._visual_superclass.draw(self)
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/visuals/visual.py", line 440, in draw
    self._vshare.index_buffer)
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/visuals/shaders/program.py", line 77, in draw
    Program.draw(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/program.py", line 470, in draw
    canvas.context.flush_commands()
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/context.py", line 171, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/glir.py", line 232, in flush
    self._shared.flush(parser)
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/glir.py", line 146, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/glir.py", line 458, in parse
    self._parse(command)
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/glir.py", line 430, in _parse
    ob.set_size(*args)  # Texture[1D, 2D, 3D], RenderBuffer
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/glir.py", line 1071, in set_size
    gl.GL_BYTE, shape[:1])
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/glir.py", line 1162, in glTexImage1D
    width, border, format, type, None)
  File "/usr/lib/python2.7/dist-packages/OpenGL/latebind.py", line 45, in __call__
    return self._finalCall( *args, **named )
  File "/usr/lib/python2.7/dist-packages/OpenGL/wrapper.py", line 792, in wrapperCall
    raise err
GLError: GLError(
	err = 1281,
	description = 'invalid value',
	baseOperation = glTexImage1D,
	pyArgs = (
		GL_TEXTURE_1D,
		0,
		GL_RGB32F,
		10000,
		0,
		GL_RGB,
		GL_BYTE,
		None,
	),
	cArgs = (
		GL_TEXTURE_1D,
		0,
		GL_RGB32F,
		10000,
		0,
		GL_RGB,
		GL_BYTE,
		None,
	),
	cArguments = (
		GL_TEXTURE_1D,
		0,
		GL_RGB32F,
		10000,
		0,
		GL_RGB,
		GL_BYTE,
		None,
	)
)
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PySide) at 0xb5c7fd2cL>> for DrawEvent
WARNING: Error drawing visual <ScrollingLines at 0xac19a2ec>
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PySide) at 0xb5c7fd2cL>> repeat 2
INFO: Program has unset variables: set([u'u_trans_max', u'u_mag', u'u_trans', u'pos_size', u'u_enabled', u'u_translate', u'u_center', u'pos_offset', u'u_id_color', u'u_scale_2', u'u_view', u'u_filter', u'u_scale_1', u'u_color', u'u_radii', u'offset', u'u_scale', u'u_translate_2', u'u_translate_1', u'position'])
Texture unit 0 is accessed both as sampler2D and sampler1D
WARNING: Error drawing visual <ScrollingLines at 0xac19a2ec>
WARNING: Error drawing visual <ScrollingLines at 0xac19a2ec>

**Comment by Eric89GXL** [comment]
Ahh, looks like there's a bug in our code for that somewhere, that most GPUs tolerate. What is your `vispy.sys_info()` (without the long GL extensions list).

**Comment by dlezcano** [comment]
Sorry I feel a bit idiot :)  how can I show the output of vispy.sys_info ?

**Comment by Eric89GXL** [comment]
You can do `print(vispy.sys_info())` from within Python, or `python -c "import vispy; print(vispy.sys_info())" ` from a shell.

**Comment by dlezcano** [comment]
Platform: Linux-3.13.0-61-generic-i686-with-Ubuntu-14.04-trusty
Python:   2.7.6 (default, Jun 22 2015, 18:00:18)  [GCC 4.8.2]
Backend:  PyQt4
pyqt4:    ('PyQt4', '4.10.4', '4.8.6')
pyqt5:    None
pyside:   None
pyglet:   None
glfw:     None
sdl2:     None
wx:       wxPython 2.8.12.1
egl:      EGL 1.4 (Gallium) Mesa Project: OpenGL OpenGL_ES OpenGL_ES2 OpenVG
_test:    None

GL version:  u'3.0 Mesa 10.1.3'

**Comment by dlezcano** [comment]
Any news ? Can I provide anything to help ?

**Comment by Eric89GXL** [comment]
No, nothing yet. Somebody needs to find time to dig into the issue. It looks like we have some bug with treating a Texture2D as a Texture1D that should be fixed.

**Comment by dlezcano** [comment]
Ok, thanks for the answer. Let me know if I can help on something.

**Comment by macrocosme** [comment]
Hi Eric, 

I get a similar issue with Texture3D:

WARNING: Error drawing visual <RenderVolume at 0x11b182e10>
WARNING: Traceback (most recent call last):
  File "/Users/danyvohl/Documents/Etudes/Doctorat/Australie/code/shaded_cubes/volume_interface.py", line 668, in <module>
    appQt.exec_()
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/app/backends/_qt.py", line 431, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/app/backends/_qt.py", line 703, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/canvas.py", line 207, in on_draw
    self._draw_scene()
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/canvas.py", line 253, in _draw_scene
    self.draw_visual(self.scene)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/canvas.py", line 291, in draw_visual
    node.draw()
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/visuals.py", line 98, in draw
    self._visual_superclass.draw(self)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/visuals/visual.py", line 440, in draw
    self._vshare.index_buffer)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/visuals/shaders/program.py", line 77, in draw
    Program.draw(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/program.py", line 470, in draw
    canvas.context.flush_commands()
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/context.py", line 171, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/glir.py", line 232, in flush
    self._shared.flush(parser)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/glir.py", line 146, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/glir.py", line 458, in parse
    self._parse(command)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/glir.py", line 430, in _parse
    ob.set_size(*args)  # Texture[1D, 2D, 3D], RenderBuffer
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/glir.py", line 1200, in set_size
    gl.GL_BYTE, shape[:3])
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/glir.py", line 1149, in glTexImage3D
    width, height, depth, border, format, type, None)
  File "/usr/local/lib/python2.7/site-packages/OpenGL/latebind.py", line 45, in __call__
    return self._finalCall( *args, **named )
  File "/usr/local/lib/python2.7/site-packages/OpenGL/wrapper.py", line 875, in wrapperCall
    raise err
GLError: GLError(
	err = 1281,
	description = 'invalid value',
	baseOperation = glTexImage3D,
	pyArgs = (
		GL_TEXTURE_3D,
		0,
		GL_LUMINANCE,
		320,
		4096,
		80,
		0,
		GL_LUMINANCE,
		GL_BYTE,
		None,
	),
	cArgs = (
		GL_TEXTURE_3D,
		0,
		GL_LUMINANCE,
		320,
		4096,
		80,
		0,
		GL_LUMINANCE,
		GL_BYTE,
		None,
	),
	cArguments = (
		GL_TEXTURE_3D,
		0,
		GL_LUMINANCE,
		320,
		4096,
		80,
		0,
		GL_LUMINANCE,
		GL_BYTE,
		None,
	)
)
ERROR: Invoking <bound method Canvas3D.on_draw of <Canvas3D (PyQt4) at 0x115153550>> for DrawEvent


---

Here is what I get through vispy.sys_info():

Platform: Darwin-15.5.0-x86_64-i386-64bit
Python:   2.7.11 (default, Jan 22 2016, 08:29:18)  [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
Backend:  PyQt4
pyqt4:    ('PyQt4', '4.11.1', '4.8.6')
pyqt5:    None
pyside:   None
pyglet:   None
glfw:     glfw (3, 1, 2)
sdl2:     sdl2 0.9.3
wx:       None
egl:      None
osmesa:   None
_test:    None

GL version:  u'2.1 NVIDIA-10.10.10 310.42.25f01'
MAX_TEXTURE_SIZE: 16384
Extensions: u'GL_ARB_color_buffer_float GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_draw_buffers GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_instanced_arrays GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_provoking_vertex GL_ARB_seamless_cube_map GL_ARB_shader_objects GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shadow GL_ARB_sync GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_mirrored_repeat GL_ARB_texture_non_power_of_two GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_transpose_matrix GL_ARB_vertex_array_bgra GL_ARB_vertex_blend GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_window_pos GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_clip_volume_hint GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_depth_bounds_test GL_EXT_draw_buffers2 GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_APPLE_aux_depth_stencil GL_APPLE_client_storage GL_APPLE_element_array GL_APPLE_fence GL_APPLE_float_pixels GL_APPLE_flush_buffer_range GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_packed_pixels GL_APPLE_pixel_buffer GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_specular_vector GL_APPLE_texture_range GL_APPLE_transform_hint GL_APPLE_vertex_array_object GL_APPLE_vertex_array_range GL_APPLE_vertex_point_size GL_APPLE_vertex_program_evaluators GL_APPLE_ycbcr_422 GL_ATI_separate_stencil GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_ATI_texture_mirror_once GL_IBM_rasterpos_clip GL_NV_blend_square GL_NV_conditional_render GL_NV_depth_clamp GL_NV_fog_distance GL_NV_fragment_program_option GL_NV_fragment_program2 GL_NV_light_max_exponent GL_NV_multisample_filter_hint GL_NV_point_sprite GL_NV_texgen_reflection GL_NV_texture_barrier GL_NV_vertex_program2_option GL_NV_vertex_program3 GL_SGIS_generate_mipmap GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod '

**Comment by macrocosme** [comment]
I think I pinpointed the issue. One detail that didn't show in the vispy.sis_info() was GL_MAX_3D_TEXTURE. 

glxinfo -l | grep "GL_MAX_TEXTURE_SIZE\|GL_MAX_3D_TEXTURE_SIZE\|OpenGL renderer string\|core profile version string"
OpenGL renderer string: NVIDIA GeForce GT 750M OpenGL Engine
    GL_MAX_TEXTURE_SIZE = 16384
    GL_MAX_3D_TEXTURE_SIZE = 2048

As one dimension is larger than 2048, it triggers the error. If I limit to 2048, the file renders properly. We may need to combine multiple textures for large volumes! Should this be added as a seperate issue?

**Comment by Eric89GXL** [comment]
Sure, but I think we already have an issue for it somewhere
