### ISSUE TITLE
SceneCanvas.native.renderPixmap crashing

### ISSUE THREAD

**Issue by astrofrog** [vispy/vispy#1159]
In order to implement a workaround for #1158, I need to render the OpenGL buffer to a `QPixmap`. However, the following code:

``` python
from vispy import scene

canvas = scene.SceneCanvas(keys='interactive', show=False)
view = canvas.central_widget.add_view()
view.parent = canvas.scene

axis = scene.visuals.XYZAxis(parent=view.scene)

cam = scene.cameras.TurntableCamera(parent=view.scene,
                                    fov=60.,
                                    name='Turntable')

view.camera = cam

canvas.show()

pixmap = canvas.native.renderPixmap(100, 100)
```

results in the following error:

```
WARNING: Error drawing visual <vispy.visuals.line.line._GLLineVisual object at 0x109ecf5f8>
WARNING: Traceback (most recent call last):
  File "render.py", line 17, in <module>
    pixmap = canvas.native.renderPixmap(100, 100)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/app/backends/_qt.py", line 703, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/canvas.py", line 207, in on_draw
    self._draw_scene()
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/canvas.py", line 253, in _draw_scene
    self.draw_visual(self.scene)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/canvas.py", line 291, in draw_visual
    node.draw()
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/scene/visuals.py", line 98, in draw
    self._visual_superclass.draw(self)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/visuals/visual.py", line 588, in draw
    v.draw()
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/visuals/visual.py", line 440, in draw
    self._vshare.index_buffer)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/visuals/shaders/program.py", line 77, in draw
    Program.draw(self, *args, **kwargs)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/gloo/program.py", line 470, in draw
    canvas.context.flush_commands()
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/gloo/context.py", line 171, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/gloo/glir.py", line 232, in flush
    self._shared.flush(parser)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/gloo/glir.py", line 146, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/gloo/glir.py", line 458, in parse
    self._parse(command)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/gloo/glir.py", line 420, in _parse
    ob.draw(*args)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/gloo/glir.py", line 898, in draw
    gl.check_error('Check before draw')
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/vispy-0.5.0.dev0-py3.4.egg/vispy/gloo/gl/__init__.py", line 211, in check_error
    raise err
RuntimeError: OpenGL got errors (Check before draw): GL_INVALID_VALUE
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt4) at 0x1006a7c88>> for DrawEvent
```

What could I be missing?

**Comment by astrofrog** [comment]
Just to clarify, this is due to the rendering being done twice in a row:

```python
from vispy import scene

canvas = scene.SceneCanvas(keys='interactive', show=False, size=(100, 100))
view = canvas.central_widget.add_view()
view.parent = canvas.scene

axis = scene.visuals.XYZAxis(parent=view.scene)

cam = scene.cameras.TurntableCamera(parent=view.scene,
                                    fov=60.,
                                    name='Turntable')

view.camera = cam

pixmap = canvas.native.renderPixmap(100, 100)
pixmap = canvas.native.renderPixmap(100, 100)
```

The ``show`` was misleading before.

**Comment by astrofrog** [comment]
It looks like the error occurs because in ``GlirBuffer.set_size``, when called the second time, the ``if nbytes != self._buffer_size`` statement returns ``False`` so it assumes it doesn't need to change the buffer size, when in fact the following call to ``glBufferSubData`` returns ``GL_INVALID_VALUE`` which indicates that the buffer is the wrong size. If I change ``nbytes != self._buffer_size`` to ``True``, then the program proceeds further but encounters another error, in a similar vein.

Essentially, it looks like the true state of the GL buffer (and other properties) may no longer be in sync with the Python code?

**Comment by astrofrog** [comment]
During the second call to ``renderPixmap``, it looks like ``gl.glUseProgram(self._handle)`` also fails, which indicates that the program no longer exists.

**Comment by astrofrog** [comment]
@campagnola, @nippoo suggested you might have some insight into this?

**Comment by queenish001** [comment]
@djhoese
