### ISSUE TITLE
Error in VolumeVisual if cube has a dimension > 2048

### ISSUE THREAD

**Issue by astrofrog** [vispy/vispy#1197]
For the James Webb Space Telescope, we need to be able to visualize cubes that are very long in one dimension, so that the overall cubes are not huge but one dimension will be > 2048.

Unfortunately, it looks like VolumeVisual currently crashes if one of the dimensions is > 2048. For example:

```python
import numpy as np
from vispy import app, scene

canvas = scene.SceneCanvas(keys='interactive', size=(800, 600), show=True)
canvas.measure_fps()

view = canvas.central_widget.add_view()

LENGTH = 2049

data = np.ones(LENGTH * 100 * 100).reshape(LENGTH, 100, 100)

volume = scene.visuals.Volume(data, parent=view.scene, clim=(0, 2))

cam2 = scene.cameras.TurntableCamera(parent=view.scene, fov=60)

app.run()
```

produces the following error:

```
WARNING: OpenGL version 3.0 or higher recommended, got 2.1 NVIDIA-8.16.80 310.40.00.20f04. Some functionality may fail.
WARNING: Traceback (most recent call last):
  File "volume.py", line 17, in <module>
    app.run()
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/app/_default_app.py", line 61, in run
    return default_app.run()
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/app/application.py", line 123, in run
    return self._backend._vispy_run()
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/app/backends/_qt.py", line 217, in _vispy_run
    return app.exec_()
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/app/backends/_qt.py", line 631, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/util/event.py", line 436, in __call__
    self._invoke_callback(cb, event)
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/util/event.py", line 452, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/OpenGL/latebind.py", line 41, in __call__
    return self._finalCall( *args, **named )
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/util/event.py", line 448, in _invoke_callback
    cb(event)
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/scene/canvas.py", line 189, in on_draw
    self._draw_scene()
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/scene/canvas.py", line 232, in _draw_scene
    self.draw_visual(self.scene, viewport=viewport)
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/scene/canvas.py", line 282, in draw_visual
    visual.draw(scene_event)
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/scene/subscene.py", line 50, in draw
    self.process_system(event, 'draw')
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/scene/subscene.py", line 60, in process_system
    self._systems[system_name].process(event, self)
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/scene/systems.py", line 37, in process
    self.process(event, sub_node)
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/scene/systems.py", line 37, in process
    self.process(event, sub_node)
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/scene/systems.py", line 28, in process
    _handle_exception(False, 'reminders', self, node=node)
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/scene/systems.py", line 23, in process
    node.draw(event)
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/scene/widgets/viewbox.py", line 324, in draw
    self.scene.draw(event)
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/scene/subscene.py", line 50, in draw
    self.process_system(event, 'draw')
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/scene/subscene.py", line 60, in process_system
    self._systems[system_name].process(event, self)
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/scene/systems.py", line 37, in process
    self.process(event, sub_node)
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/scene/systems.py", line 28, in process
    _handle_exception(False, 'reminders', self, node=node)
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/scene/systems.py", line 23, in process
    node.draw(event)
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/visuals/volume.py", line 676, in draw
    self._program.draw('triangle_strip', self._index_buffer)
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/visuals/shaders/program.py", line 89, in draw
    Program.draw(self, *args, **kwargs)
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/gloo/program.py", line 467, in draw
    canvas.context.flush_commands()
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/gloo/context.py", line 170, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/gloo/glir.py", line 231, in flush
    self._shared.flush(parser)
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/gloo/glir.py", line 145, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/gloo/glir.py", line 457, in parse
    self._parse(command)
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/gloo/glir.py", line 429, in _parse
    ob.set_size(*args)  # Texture[1D, 2D, 3D], RenderBuffer
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/gloo/glir.py", line 1197, in set_size
    gl.GL_BYTE, shape[:3])
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/vispy/gloo/glir.py", line 1146, in glTexImage3D
    width, height, depth, border, format, type, None)
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/OpenGL/latebind.py", line 45, in __call__
    return self._finalCall( *args, **named )
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/OpenGL/wrapper.py", line 877, in wrapperCall
    raise err
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/OpenGL/wrapper.py", line 870, in wrapperCall
    result = wrappedOperation( *cArguments )
  File "/Users/tom/miniconda3/envs/stable-glue-071/lib/python3.5/site-packages/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1281,
	description = b'invalid value',
	baseOperation = glTexImage3D,
	pyArgs = (
		GL_TEXTURE_3D,
		0,
		GL_LUMINANCE,
		100,
		100,
		2049,
		0,
		GL_LUMINANCE,
		GL_BYTE,
		None,
	),
	cArgs = (
		GL_TEXTURE_3D,
		0,
		GL_LUMINANCE,
		100,
		100,
		2049,
		0,
		GL_LUMINANCE,
		GL_BYTE,
		None,
	),
	cArguments = (
		GL_TEXTURE_3D,
		0,
		GL_LUMINANCE,
		100,
		100,
		2049,
		0,
		GL_LUMINANCE,
		GL_BYTE,
		None,
	)
)
```

Of course, we could pre-process the data to avoid this, but it would be best to avoid this and I wanted to check whether this is a bug or a fundamental limitation of OpenGL?

**Comment by rougier** [comment]
There is actually an hardware limit to the size of a texture. You can try to query `GL_MAX_TEXTURE_SIZE` using glGet but 2048 seems to be a reasonable value for such limit. Note that this limit refers to the maximum size in any dimension and not the total size of your texture.Even a 2049x1 texture would be considered too large.

**Comment by astrofrog** [comment]
@rougier - thanks - is there a way in VisPy to automatically handle this case by downsampling the texture on-the-fly or is this something I have to do with the input data?

**Comment by rougier** [comment]
I don't think there is something in VisPy for this specific case but for the case of volume rendering, it should be possible to use two textures but this requires hacking the VisPy code.
@almarklein @campagnola What do you think ?

**Comment by rossant** [comment]
On recent GPUs the limit may be higher no?
https://forums.geforce.com/default/topic/872971/geforce-900-series/970-owners-we-have-been-duped-twice-any-other-card-holders-have-been-duped-at-least-once-/2/
