### ISSUE TITLE
problem with basic plot example

### ISSUE THREAD

**Issue by geraldstanje** [vispy/vispy#1207]
Hi,

I have some issues to run the following example:
https://github.com/vispy/vispy/blob/master/examples/basics/plotting/colorbar.py:

Im on OS X Yosemite:
```
$ python --version
Python 2.7.6

vispy.sys_info():
Platform: Darwin-14.5.0-x86_64-i386-64bit
Python:   2.7.6 (default, Apr 10 2014, 13:40:11)  [GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.38)]
Backend:  PyQt5
pyqt4:    None
pyqt5:    ('PyQt5', '5.6', '5.3.0')
pyside:   None
pyglet:   None
glfw:     None
sdl2:     None
wx:       None
egl:      None
osmesa:   None
_test:    None

GL version:  u'2.1 NVIDIA-10.4.2 310.41.35f01'
MAX_TEXTURE_SIZE: 16384
Extensions: u'GL_ARB_color_buffer_float GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_draw_buffers GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_instanced_arrays GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_provoking_vertex GL_ARB_seamless_cube_map GL_ARB_shader_objects GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shadow GL_ARB_sync GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_mirrored_repeat GL_ARB_texture_non_power_of_two GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_transpose_matrix GL_ARB_vertex_array_bgra GL_ARB_vertex_blend GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_window_pos GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_clip_volume_hint GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_depth_bounds_test GL_EXT_draw_buffers2 GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_APPLE_aux_depth_stencil GL_APPLE_client_storage GL_APPLE_element_array GL_APPLE_fence GL_APPLE_float_pixels GL_APPLE_flush_buffer_range GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_packed_pixels GL_APPLE_pixel_buffer GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_specular_vector GL_APPLE_texture_range GL_APPLE_transform_hint GL_APPLE_vertex_array_object GL_APPLE_vertex_array_range GL_APPLE_vertex_point_size GL_APPLE_vertex_program_evaluators GL_APPLE_ycbcr_422 GL_ATI_separate_stencil GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_ATI_texture_mirror_once GL_IBM_rasterpos_clip GL_NV_blend_square GL_NV_conditional_render GL_NV_depth_clamp GL_NV_fog_distance GL_NV_fragment_program_option GL_NV_fragment_program2 GL_NV_light_max_exponent GL_NV_multisample_filter_hint GL_NV_point_sprite GL_NV_texgen_reflection GL_NV_texture_barrier GL_NV_vertex_program2_option GL_NV_vertex_program3 GL_SGIS_generate_mipmap GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod '

('Numpy version:', '1.11.0')
('Qt version:', '5.3.0')
('SIP version:', '4.18')
('PyQt version:', '5.6')
```

Could you tell me what is wrong about my installation? It seems there is some issue with PyQt. Why does it search for PyQt4 if I installed PyQt5?
```
$ $ python colorbar.py
INFO: Could not import backend "PyQt4":
No module named PyQt4
WARNING: Traceback (most recent call last):
  File "colorbar.py", line 48, in <module>
    fig.show(run=True)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/app/canvas.py", line 429, in show
    self._backend._vispy_set_visible(visible)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/app/backends/_qt.py", line 335, in _vispy_set_visible
    self.showNormal()
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/app/backends/_qt.py", line 431, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/app/backends/_qt.py", line 703, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/canvas.py", line 207, in on_draw
    self._draw_scene()
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/canvas.py", line 253, in _draw_scene
    self.draw_visual(self.scene)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/canvas.py", line 291, in draw_visual
    node.draw()
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/visuals.py", line 98, in draw
    self._visual_superclass.draw(self)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/visuals/visual.py", line 588, in draw
    v.draw()
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/visuals/visual.py", line 588, in draw
    v.draw()
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/visuals/visual.py", line 432, in draw
    if self._prepare_draw(view=self) is False:
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/visuals/text/text.py", line 443, in _prepare_draw
    self._font._lowres_size) for t in text])
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/visuals/text/text.py", line 157, in _text_to_vbo
    glyph = font[char]
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/visuals/text/text.py", line 69, in __getitem__
    self._load_char(char)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/visuals/text/text.py", line 83, in _load_char
    _load_glyph(self._font, char, self._glyphs)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/fonts/_quartz.py", line 87, in _load_glyph
    font = _load_font(f['face'], f['bold'], f['italic'])
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/fonts/_quartz.py", line 46, in _load_font
    return _load_vispy_font(face, bold, italic)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/fonts/_quartz.py", line 24, in _load_vispy_font
    fname = _get_vispy_font_filename(face, bold, italic)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/fonts/_vispy_fonts.py", line 20, in _get_vispy_font_filename
    return load_data_file('fonts/%s' % name)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/fetching.py", line 68, in load_data_file
    _fetch_file(url, fname)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/fetching.py", line 243, in _fetch_file
    'Dataset fetching aborted (%s)' % (url, e))
RuntimeError: Error while fetching file https://github.com/vispy/demo-data/raw/master/fonts/OpenSans-Regular.ttf.
Dataset fetching aborted (<urlopen error unknown url type: https>)
ERROR: Invoking <bound method Fig.on_draw of <Fig (PyQt5) at 0x10992d050>> for DrawEvent
ERROR: Invoking <bound method Fig.on_draw of <Fig (PyQt5) at 0x10992d050>> repeat 2
ERROR: Invoking <bound method Fig.on_draw of <Fig (PyQt5) at 0x10992d050>> repeat 4
```

**Comment by scottpaine** [comment]
It appears the error isn't with using PyQt4 here: you can see that that's just a warning. It searches for PyQt4 just because that's a backend, and raises an error when it doesn't find it.

However, your program DOES find PyQt5 and use it - the last 3 lines in your traceback show the error in Fig (PyQt5). The REAL problem comes from trying to fetch OpenSans-Regular.ttf from [here](https://github.com/vispy/demo-data/tree/master/fonts). For whatever reason, there was a failure with urllib running urllib.request.urlopen on that link to the font. Specifically, it dislikes the https at the start of the url fetch file.

It's possible you could fix this by just dropping the 's' from the _url_root string on line 46 of vispy/util/fetching.py. Overall, this may just be a problem with whatever urllib VisPy is trying to import.
