### ISSUE TITLE
gloo.Program.draw() problem on PyQt5 and Intel HD Graphics 4600

### ISSUE THREAD

**Issue by ombschervister** [vispy/vispy#1246]
For PyQt5 and Intel HD Graphics 4600:
1) Create canvas, remove canvas
2) If i try to create new canvas, then exception raised:

```
WARNING: Traceback (most recent call last):
  File "D:/rexlab/source/rex/vispy/test/denis/gloo/points/simple_circle.py", line 76, in <module>
    qapp.exec_()
  File "C:\python3\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\lib\site-packages\vispy-0.5.0.dev0-py3.4.egg\vispy\app\backends\_qt.py", line 431, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "C:\python3\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\lib\site-packages\vispy-0.5.0.dev0-py3.4.egg\vispy\app\backends\_qt.py", line 703, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "C:\python3\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\lib\site-packages\vispy-0.5.0.dev0-py3.4.egg\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "C:\python3\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\lib\site-packages\vispy-0.5.0.dev0-py3.4.egg\vispy\util\event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "C:\python3\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\lib\site-packages\vispy-0.5.0.dev0-py3.4.egg\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "D:/rexlab/source/rex/vispy/test/denis/gloo/points/simple_circle.py", line 40, in on_draw
    self.program.draw('points')
  File "C:\python3\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\lib\site-packages\vispy-0.5.0.dev0-py3.4.egg\vispy\gloo\program.py", line 470, in draw
    canvas.context.flush_commands()
  File "C:\python3\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\lib\site-packages\vispy-0.5.0.dev0-py3.4.egg\vispy\gloo\context.py", line 171, in flush_commands
    self.glir.flush(self.shared.parser)
  File "C:\python3\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\lib\site-packages\vispy-0.5.0.dev0-py3.4.egg\vispy\gloo\glir.py", line 232, in flush
    self._shared.flush(parser)
  File "C:\python3\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\lib\site-packages\vispy-0.5.0.dev0-py3.4.egg\vispy\gloo\glir.py", line 146, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "C:\python3\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\lib\site-packages\vispy-0.5.0.dev0-py3.4.egg\vispy\gloo\glir.py", line 458, in parse
    self._parse(command)
  File "C:\python3\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\lib\site-packages\vispy-0.5.0.dev0-py3.4.egg\vispy\gloo\glir.py", line 428, in _parse
    ob.set_data(*args)
  File "C:\python3\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\lib\site-packages\vispy-0.5.0.dev0-py3.4.egg\vispy\gloo\glir.py", line 957, in set_data
    gl.check_error('periodic check')
  File "C:\python3\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\lib\site-packages\vispy-0.5.0.dev0-py3.4.egg\vispy\gloo\gl\__init__.py", line 211, in check_error
    raise err
RuntimeError: OpenGL got errors (periodic check): GL_INVALID_ENUM
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PyQt5) at 0x4512748>> for DrawEvent
INFO: Program has unset variables: {'a_position'}
```

Program work fine on nvidia gtx970.

code:

``` python
import numpy as np
from vispy import gloo, app
from vispy.gloo import set_viewport, set_state, clear

vert = """
#version 120
attribute vec3  a_position;
void main (void) {
    gl_Position = vec4(a_position,1.0);
    gl_PointSize = 100.0;
}
"""

frag = """
#version 120
void main()
{
    gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);
}
"""

class Canvas(app.Canvas):

    def __init__(self):
        app.Canvas.__init__(self)
        self.program = gloo.Program(vert, frag)
        set_viewport(0, 0, *self.physical_size)
        self.program['a_position'] = np.array([[0, 0, 0]], dtype=np.float32)

    def on_draw(self, event):
        clear(color=True)
        self.program.draw('points')

if __name__ == "__main__":
    from PyQt5 import QtWidgets as QtGui
    import vispy.gloo.context as context
    qapp = QtGui.QApplication([])

    mw = QtGui.QWidget()
    l = QtGui.QVBoxLayout(mw)

    container = QtGui.QWidget()
    c_l = QtGui.QVBoxLayout(container)
    l.addWidget(container)

    cv = Canvas()
    c_l.addWidget(cv.native)

    def reset_canvas():
        global cv

        # delete old canvas
        if cv is not None:
            cv.native.setParent(None)
            # context.forget_canvas(cv)
            cv = None

        # create new canvas
        else:
            cv = Canvas()
            c_l.addWidget(cv.native)


    b = QtGui.QPushButton()
    b.clicked.connect(reset_canvas)
    l.addWidget(b)
    mw.show()

    qapp.exec_()
```

**Comment by davidh-ssec** [comment]
This is a weird one. I don't have an intel GPU available so I can't test this and this is also an old issue so it's possible anything buggy on vispy's part has been fixed. The other likely cause could have been bad/old intel drivers that could have also been fixed in this time. I'm closing this for now, but if someone can reproduce this issue feel free to reopen.
