### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by akshaybabloo** [vispy/vispy#1258]
Hi,

I am using Python 3.5 and tried the basic example https://github.com/vispy/vispy/blob/master/examples/basics/gloo/start.py, But I get `UnicodeDecodeError`. Here is the full stack:

```
Traceback (most recent call last):
  File "C:/Users/aksha/Box Sync/MyDrive/Projects/Akshay-GitHub/NeuCubePy/main1.py", line 50, in <module>
    from vispy import app, gloo
  File "C:\Users\aksha\Anaconda3\lib\site-packages\vispy\app\__init__.py", line 15, in <module>
    from .canvas import Canvas, MouseEvent, KeyEvent  # noqa
  File "C:\Users\aksha\Anaconda3\lib\site-packages\vispy\app\canvas.py", line 17, in <module>
    from ..gloo.context import (GLContext, set_current_canvas, forget_canvas)
  File "C:\Users\aksha\Anaconda3\lib\site-packages\vispy\gloo\__init__.py", line 47, in <module>
    from . import gl  # noqa
  File "C:\Users\aksha\Anaconda3\lib\site-packages\vispy\gloo\gl\__init__.py", line 32, in <module>
    from ._constants import *  # noqa
  File "C:\Users\aksha\Anaconda3\lib\site-packages\vispy\gloo\gl\_constants.py", line 326, in <module>
    if repr(ob).startswith('GL_'):
  File "C:\Users\aksha\Anaconda3\lib\_sitebuiltins.py", line 61, in __repr__
    self.__setup()
  File "C:\Users\aksha\Anaconda3\lib\_sitebuiltins.py", line 51, in __setup
    data = fp.read()
  File "C:\Users\aksha\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 203: character maps to <undefined>
```

**Comment by kmuehlbauer** [comment]
@akshaybabloo Did you have any success with this?

**Comment by QuLogic** [comment]
Looks like #1330.

**Comment by davidh-ssec** [comment]
@QuLogic Agreed, this looks like the same issue. If either @akshaybabloo or @ronpandolfi can give more information on how they installed their version of python (changed system encoding after?) or some way of reproducing this issue I'm going to assume it is an issue with their installation and not technically related to vispy. I mentioned the quick test in the other issue: `print(repr(copyright))`. Even though this issue is older I'm going to mark it as the duplicate since there is more information on the other issue.

Dup of #1330
