### ISSUE TITLE
Expand AxisVisual to 3D (support Z-Axis)

### ISSUE THREAD

**Issue by frmdstryr** [vispy/vispy#1263]
When trying to add a Z - axis to the [surface_plot ](https://github.com/vispy/vispy/blob/master/examples/basics/scene/surface_plot.py) example by adding:

``` python

zax = scene.Axis(pos=[[0.5, -0.5, 0], [0.5, -0.5, 1]], tick_direction=(0, 0, -1),
                 font_size=16, axis_color='k', tick_color='k', text_color='k',
                 parent=view.scene)
zax.transform = scene.STTransform(translate=(0, 0, -0.2))

```

I get an error related to the ticks. 

```

WARNING: Traceback (most recent call last):
  File "C:\Users\Me\Documents\workspace2\scratch\surface_plot.py", line 85, in <module>
    app.run()
  File "C:\Users\Me\Documents\workspace\vispy\vispy\app\_default_app.py", line 62, in run
    return default_app.run()
  File "C:\Users\Me\Documents\workspace\vispy\vispy\app\application.py", line 137, in run
    return self._backend._vispy_run()
  File "C:\Users\Me\Documents\workspace\vispy\vispy\app\backends\_qt.py", line 229, in _vispy_run
    return app.exec_()
  File "C:\Users\Me\Documents\workspace\vispy\vispy\app\backends\_qt.py", line 431, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "C:\Users\Me\Documents\workspace\vispy\vispy\app\backends\_qt.py", line 431, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "C:\Users\Me\Documents\workspace\vispy\vispy\app\backends\_qt.py", line 703, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "C:\Users\Me\Documents\workspace\vispy\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "C:\Users\Me\Documents\workspace\vispy\vispy\util\event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "C:\Users\Me\Documents\workspace\vispy\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "C:\Users\Me\Documents\workspace\vispy\vispy\scene\canvas.py", line 207, in on_draw
    self._draw_scene()
  File "C:\Users\Me\Documents\workspace\vispy\vispy\scene\canvas.py", line 253, in _draw_scene
    self.draw_visual(self.scene)
  File "C:\Users\Me\Documents\workspace\vispy\vispy\scene\canvas.py", line 291, in draw_visual
    node.draw()
  File "C:\Users\Me\Documents\workspace\vispy\vispy\scene\visuals.py", line 98, in draw
    self._visual_superclass.draw(self)
  File "C:\Users\Me\Documents\workspace\vispy\vispy\visuals\visual.py", line 583, in draw
    if self._prepare_draw(view=self) is False:
  File "C:\Users\Me\Documents\workspace\vispy\vispy\visuals\axis.py", line 125, in _prepare_draw
    self._update_subvisuals()
  File "C:\Users\Me\Documents\workspace\vispy\vispy\visuals\axis.py", line 111, in _update_subvisuals
    tick_pos, labels, label_pos, anchors = self.ticker.get_update()
  File "C:\Users\Me\Documents\workspace\vispy\vispy\visuals\axis.py", line 150, in get_update
    major_tick_fractions, minor_tick_fractions)
  File "C:\Users\Me\Documents\workspace\vispy\vispy\visuals\axis.py", line 185, in _get_tick_positions
    dtype=float)
ValueError: setting an array element with a sequence.

```

It seems as if the Ticker does not support a 3D point.  

I can get it to work by doing a 2D axis then a rotation transform, but that seems really hackish.

Any ideas?

**Comment by kmuehlbauer** [comment]
@frmdstryr You are correct, the [AxisVisual](https://github.com/vispy/vispy/blob/master/vispy/visuals/axis.py#L16) doesn't support 3D out of the box atm.

**Comment by AlexCoul** [comment]
Hi,
Thank you I was just starting to think that I was the only one needing that kind of axes! :)
I left a message here: https://groups.google.com/forum/#!topic/vispy/SFiPsVwobu8 and meanwhile I tried to implement the 3d axes, but without success.So far I got to something enough to "survive" but not so good:
`def vpscatter(xdata, ydata, zdata):
    # build your visuals
    Scatter3D = scene.visuals.create_visual_node(visuals.MarkersVisual)
    
    # The real-things : plot using scene
    # build canvas
    canvas = scene.SceneCanvas(keys='interactive', show=True)
    
    # Add a ViewBox to let the user zoom/rotate
    view = canvas.central_widget.add_view()
    view.camera = 'turntable'
    view.camera.fov = 45
    view.camera.distance = 2*zdata.max()

    # data
    n = xdata.size
    pos = np.zeros((n, 3))
    pos[:,0] = xdata.ravel()
    pos[:,1] = ydata.ravel()
    pos[:,2] = zdata.ravel()
    colors = np.ones((n, 4), dtype=np.float32)

    
    # plot XYZ data
    p1 = Scatter3D(parent=view.scene)
    p1.set_gl_state('translucent', blend=True, depth_test=True)
    p1.set_data(pos, face_color=colors)
    p1.symbol = 'o' 
        
    # plot XYZ axes
    Plot3DAxis = scene.visuals.create_visual_node(visuals.LinePlotVisual)
    axes_colors = ['red','green','blue']
    axes_labels = ['X axis','Y axis','Z axis']
    axis_symbol = '|'
    for i,data in enumerate([xdata,ydata,zdata]):
        ticks_values = compute_ticks(data)
        ticks = np.zeros((ticks_values.size,3))
        ticks[:,i] = ticks_values
        if i==2:
            axis_symbol = '-'
        Plot3DAxis(ticks, width=2.0, color=axes_colors[i], edge_color='w', symbol=axis_symbol, face_color=(0.2, 0.2, 1, 0.8), parent=view.scene)
        axis_label_pos = [0,0,0]
        axis_label_pos[i] = (data.max()+data.min())/2
        axislabel = scene.Text(axes_labels[i], bold=True, font_size=24, color='w',pos=axis_label_pos, parent=view.scene)
        
    # run
    app.run()

vpscatter(x,y,z)
`

Now I'll try to have a look at the AxisVisual class definition in vispy/visuals/axis.py but I've not even managed to use it so far! ^^
I you're making progress please tell me.
