### ISSUE TITLE
Invalid operation: GL.glDisable(GL.GL_LINE_SMOOTH)

### ISSUE THREAD

**Issue by astrofrog** [vispy/vispy#1277]
The following code:

```
from vispy import scene


canvas = scene.SceneCanvas(keys=None, size=(800, 600), show=True)
view = canvas.central_widget.add_view()
scene_transform = scene.STTransform()
view.camera = scene.cameras.TurntableCamera(parent=view.scene,
                                            fov=0., distance=4.0)

ax = scene.visuals.Axis(pos=[[-1.0, 0], [1.0, 0]],
                        tick_direction=(0, -1),
                        parent=view.scene, axis_label='X',
                        anchors=['center', 'middle'])

canvas.render()
```

produces the following error on AppVeyor (in another application):

```
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    canvas.render()
  File "C:\conda\envs\test\lib\site-packages\vispy\scene\canvas.py", line 244, in render
    self._draw_scene(bgcolor=bgcolor)
  File "C:\conda\envs\test\lib\site-packages\vispy\scene\canvas.py", line 253, in _draw_scene
    self.draw_visual(self.scene)
  File "C:\conda\envs\test\lib\site-packages\vispy\scene\canvas.py", line 291, in draw_visual
    node.draw()
  File "C:\conda\envs\test\lib\site-packages\vispy\scene\visuals.py", line 98, in draw
    self._visual_superclass.draw(self)
  File "C:\conda\envs\test\lib\site-packages\vispy\visuals\visual.py", line 588, in draw
    v.draw()
  File "C:\conda\envs\test\lib\site-packages\vispy\visuals\visual.py", line 588, in draw
    v.draw()
  File "C:\conda\envs\test\lib\site-packages\vispy\visuals\visual.py", line 432, in draw
    if self._prepare_draw(view=self) is False:
  File "C:\conda\envs\test\lib\site-packages\vispy\visuals\line\line.py", line 353, in _prepare_draw
    GL.glDisable(GL.GL_LINE_SMOOTH)
  File "C:\conda\envs\test\lib\site-packages\OpenGL\platform\baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "C:\conda\envs\test\lib\site-packages\OpenGL\error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glDisable,
	cArguments = 
```

What could be causing this?

**Comment by rougier** [comment]
`GL_LINE_SMOOTH` has been deprecated in gl 3.0  and removed in 3.1. Is there a chance appveyor is using a 3.1 GL context ?

**Comment by astrofrog** [comment]
@rougier - how can I find out the GL context?

**Comment by rougier** [comment]
Good question. I don't know actually. One other possibility would be to force the context to 2.1 and check if the problem is still here. But I don't remember either how to set the option during initialization...

**Comment by davidh-ssec** [comment]
@rougier @astrofrog If `GL_LINE_SMOOTH` has been removed should vispy stop using it?

**Comment by Bram94** [comment]
Also getting this error (error 1 below) after upgrading to version 0.6.0, which I didn't get when using a dev-0.5 version. 
I checked whether the problem would be solved when removing the lines in which GL_LINE_SMOOTH is enabled/disabled, in the function _prepare_draw in visuals/line/line.py. This of course removed the error related to GL_LINE_SMOOTH, but then I got another error related to setting the line width (error 2).
After removing also those lines, just to check whether that would work, I got however another error (error 3).
I don't know whether this is al related to the same bug (with GL_LINE_SMOOTH), or if it involves multiple bugs. I put it here because the first error is the same as the one in this issue, but if it involves multiple bugs, then it could be moved.
Does anyone have ideas about how to solve this?

1:
`  File "D:\Python\NLradar_eigen\Python_files\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "D:\Python\NLradar_eigen\Python_files\vispy\util\event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "D:\Python\NLradar_eigen\Python_files\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "D:\Python\NLradar_eigen\Python_files\vispy\scene\canvas.py", line 208, in on_draw
    self._draw_scene()
  File "D:\Python\NLradar_eigen\Python_files\vispy\scene\canvas.py", line 254, in _draw_scene
    self.draw_visual(self.scene)
  File "D:\Python\NLradar_eigen\Python_files\vispy\scene\canvas.py", line 292, in draw_visual
    node.draw()
  File "D:\Python\NLradar_eigen\Python_files\vispy\scene\visuals.py", line 98, in draw
    self._visual_superclass.draw(self)
  File "D:\Python\NLradar_eigen\Python_files\vispy\visuals\visual.py", line 588, in draw
    v.draw()
  File "D:\Python\NLradar_eigen\Python_files\vispy\visuals\visual.py", line 432, in draw
    if self._prepare_draw(view=self) is False:
  File "D:\Python\NLradar_eigen\Python_files\vispy\visuals\line\line.py", line 356, in _prepare_draw
    GL.glDisable(GL.GL_LINE_SMOOTH)
  File "C:\Anaconda3\lib\site-packages\OpenGL\platform\baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "C:\Anaconda3\lib\site-packages\OpenGL\error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'ongeldige bewerking',
        baseOperation = glDisable,
        cArguments = (GL_LINE_SMOOTH,)`

2:
`OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'ongeldige bewerking',
        baseOperation = glLineWidth,
        cArguments = (1.0,)`

3:
`D:\Python\NLradar_eigen\Python_files\vispy\visuals\visual.py:442: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn("Error drawing visual %r" % self)
WARNING: Error drawing visual <vispy.visuals.line.line._GLLineVisual object at 0x000001E803483828>
WARNING: Traceback (most recent call last):
  File "nlr.py", line 2367, in <module>
    main()
  File "nlr.py", line 2364, in main
    sys.exit(app.exec_())
  File "D:\Python\NLradar_eigen\Python_files\vispy\app\backends\_qt.py", line 435, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "D:\Python\NLradar_eigen\Python_files\vispy\app\backends\_qt.py", line 707, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "D:\Python\NLradar_eigen\Python_files\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "D:\Python\NLradar_eigen\Python_files\vispy\util\event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "D:\Python\NLradar_eigen\Python_files\vispy\gloo\gl\_gl2.py", line 735, in glGetShaderInfoLog
    nativefunc = glGetShaderInfoLog._native
AttributeError: 'function' object has no attribute '_native'`

**Comment by Bram94** [comment]
An addition:
I get these errors not only with the new v.0.6 version, but also infrequently with the previous dev v.0.5 version that I used. When displaying 8 panels simultaneously, then it takes on average about 2-5 minutes of constant use of my application until it crashes because of an error. With v.0.6 my application always crashes on startup, during the plotting of line visuals. 
Sometimes this is the error related to GL_LINE_SMOOTH, which is shown above, but sometimes it is one the 2 errors shown below. 

Because with the previous v.0.5 version, the call of glDisable(GL_LINE_SMOOTH) usually does not lead to errors, it might in fact be the case that it is not the main call that causes the errors. I have also noticed that the occurrence of this error is always accompanied by another error when setting glLinewidth (error 2 in my post above), further strengthening the idea that the problem is not just the call of glDisable(GL_LINE_SMOOTH). 

It is a very frustrating bug, among others because it is difficult to reproduce due to the infrequent occurrence. I also don't have any idea about where to look for causes unfortunately, due to my lack of knowledge of OpenGL, and my limited knowledge of vispy. I will now continue using the old dev v.0.5 version, and will try to properly catch the errors mentioned above, to prevent the crashing of my application upon encountering them.

Finally, I hope that I am not polluting this issue too much. I have thought about creating a new issue, but didn't do so because it seemed too much related to this issue by astrofog.

`WARNING: Traceback (most recent call last):
  File "nlr.py", line 2716, in <module>
    main()
  File "nlr.py", line 2713, in main
    sys.exit(app.exec_())
  File "D:\Python\NLradar_eigen\Python_files\vispy\app\backends\_qt.py", line 433, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "D:\Python\NLradar_eigen\Python_files\vispy\app\backends\_qt.py", line 433, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "D:\Python\NLradar_eigen\Python_files\vispy\app\backends\_qt.py", line 705, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "D:\Python\NLradar_eigen\Python_files\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "D:\Python\NLradar_eigen\Python_files\vispy\util\event.py", line 476, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "D:\Python\NLradar_eigen\Python_files\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "D:\Python\NLradar_eigen\Python_files\vispy\scene\canvas.py", line 214, in on_draw
    self._draw_scene()
  File "D:\Python\NLradar_eigen\Python_files\vispy\scene\canvas.py", line 259, in _draw_scene
    self.draw_visual(self.scene)
  File "D:\Python\NLradar_eigen\Python_files\vispy\scene\canvas.py", line 293, in draw_visual
    node.draw()
  File "D:\Python\NLradar_eigen\Python_files\vispy\scene\visuals.py", line 98, in draw
    self._visual_superclass.draw(self)
  File "D:\Python\NLradar_eigen\Python_files\vispy\visuals\visual.py", line 433, in draw
    if self._prepare_draw(view=self) is False:
  File "D:\Python\NLradar_eigen\Python_files\vispy\visuals\markers.py", line 621, in _prepare_draw
    view.view_program['u_viewport']=gl.glGetParameter(gl.GL_VIEWPORT)
  File "D:\Python\NLradar_eigen\Python_files\vispy\gloo\program.py", line 317, in __setitem__
    'not %i.' % (name, numel, data.size))
ValueError: Uniform 'u_viewport' needs 4 elements, not 0.`

`WARNING: Error drawing visual <Text at 0x17c118739b0>
WARNING: Traceback (most recent call last):
  File "nlr.py", line 2716, in <module>
    main()
  File "nlr.py", line 2713, in main
    sys.exit(app.exec_())
  File "D:\Python\NLradar_eigen\Python_files\vispy\app\backends\_qt.py", line 433, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "D:\Python\NLradar_eigen\Python_files\vispy\app\backends\_qt.py", line 433, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "D:\Python\NLradar_eigen\Python_files\vispy\app\backends\_qt.py", line 705, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "D:\Python\NLradar_eigen\Python_files\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "D:\Python\NLradar_eigen\Python_files\vispy\util\event.py", line 476, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "D:\Python\NLradar_eigen\Python_files\vispy\gloo\gl\_gl2.py", line 403, in glDisableVertexAttribArray
    nativefunc = glDisableVertexAttribArray._native
AttributeError: 'function' object has no attribute '_native'`
