### ISSUE TITLE
Testing fails

### ISSUE THREAD

**Issue by prashantdomadiya** [vispy/vispy#1289]
Hello I have installed the vispy. While I was testing it, I got following error,

> > > ## vispy.test()
> > > ## Skipping backend pyqt4, not installed or working properly
> > > ---
> > > ## Skipping backend pyqt5, not installed or working properly
> > > ---
> > > ## Skipping backend pyside, not installed or working properly
> > > ---
> > > ## Skipping backend pyglet, not installed or working properly
> > > ---
> > > ## Skipping backend glfw, not installed or working properly
> > > ---
> > > ## Skipping backend sdl2, not installed or working properly
> > > ---
> > > ## Skipping backend wx, not installed or working properly
> > > ---
> > > ## Skipping backend egl, not installed or working properly
> > > ---
> > > ## Skipping backend osmesa, not installed or working properly
> > > ---
> > > ## Skipping backend ipynb_webgl, not installed or working properly
> > > ---
> > > ## Skipping backend _test, not installed or working properly
> > > ---
> > > 
> > > Running tests with no backend:
> > > _VISPY_TESTING_APP=nobackend   -a "!vispy_app_test"
> > > Failed: unit failure (1)
> > > Skipping example test: Cannot test examples unless in vispy git directory
> > > Running line endings check... 
> > > Passed

Skipping flake8 test, flake8 not installed
Passed

Testing failed (['nobackend'] failed, ['pyqt4', 'pyqt5', 'pyside', 'pyglet', 'glfw', 'sdl2', 'wx', 'egl', 'osmesa', 'ipynb_webgl', '_test', 'examples'] skipped) in 40.702 seconds

Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    vispy.test()
  File "/home/prashant/.local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/testing/_runners.py", line 420, in test
    raise RuntimeError('FAILURE')
RuntimeError: FAILURE

**Comment by davidh-ssec** [comment]
@prashantdomadiya I know this is more than a year over due, but the above information doesn't show what test actually failed. Given that vispy has changed quite a bit since you originally made this issue I'm going to close it. If you install the newest version of vispy and still have issues then you can provide us with that new information and we can reopen this.

**Comment by thepunitsingh** [comment]
I am getting a similar issue. Please find the result of `vispy.test()` below.

```
----------------------------------------------------------------------
Skipping backend pyqt4, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Running tests with pyqt5 backend:
_VISPY_TESTING_APP=pyqt5   -m vispy_app_test
Failed: unit failure (2)
----------------------------------------------------------------------
Skipping backend pyside, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend pyglet, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend glfw, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend sdl2, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend wx, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend egl, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend osmesa, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Running tests with ipynb_webgl backend:
_VISPY_TESTING_APP=ipynb_webgl   -m vispy_app_test
Failed: unit failure (2)
----------------------------------------------------------------------
Skipping backend _test, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Running tests with no backend:
_VISPY_TESTING_APP=nobackend   -m "not vispy_app_test"
Failed: unit failure (2)
Skipping example test: Cannot test examples unless in vispy git directory
Running line endings check... 
Passed

Skipping flake8 test, flake8 not installed
Passed

Testing failed (['pyqt5', 'ipynb_webgl', 'nobackend'] failed, ['pyqt4', 'pyside', 'pyglet', 'glfw', 'sdl2', 'wx', 'egl', 'osmesa', '_test', 'examples'] skipped) in 8.463 seconds
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-e78e52328cb1> in <module>()
----> 1 vispy.test()

~/anaconda3/lib/python3.6/site-packages/vispy/testing/_runners.py in test(label, extra_arg_string, coverage)
    444     sys.stdout.flush()
    445     if len(fail) > 0:
--> 446         raise RuntimeError('FAILURE')

RuntimeError: FAILURE
```

I am unable to understand what happened with the installation. Tha output of `print(vispy.sys_info())` is:

```
Platform: Linux-4.10.0-28-generic-x86_64-with-debian-stretch-sid
Python:   3.6.3 |Anaconda custom (64-bit)| (default, Oct 13 2017, 12:02:49)  [GCC 7.2.0]
NumPy:    1.13.3
Backend:  PyQt5
pyqt4:    None
pyqt5:    ('PyQt5', '5.6', '5.6.2')
pyside:   None
pyglet:   None
glfw:     None
sdl2:     None
wx:       None
egl:      None
osmesa:   None
_test:    None

GL version:  '3.0 Mesa 17.0.7'
MAX_TEXTURE_SIZE: 8192
Extensions: 'GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_polygon_offset GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_ATI_fragment_shader GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_depth_clamp GL_NV_fog_distance GL_APPLE_packed_pixels GL_APPLE_vertex_array_object GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_MESA_ycbcr_texture GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_ATI_texture_compression_3dc GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_ATI_texture_mirror_once GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_texture_array GL_EXT_texture_compression_latc GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_conservative_depth GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_ARB_ES2_compatibility GL_ARB_blend_func_extended GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_stencil_export GL_ARB_shader_texture_lod GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_multisample GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_ARB_get_program_binary GL_ARB_robustness GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_base_instance GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_ARB_transform_feedback_instanced GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_transform_feedback GL_AMD_shader_trinary_minmax GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_clear_buffer_object GL_ARB_copy_image GL_ARB_explicit_uniform_location GL_ARB_invalidate_subdata GL_ARB_program_interface_query GL_ARB_stencil_texturing GL_ARB_texture_query_levels GL_ARB_texture_storage_multisample GL_ARB_texture_view GL_ARB_vertex_attrib_binding GL_KHR_debug GL_ARB_buffer_storage GL_ARB_internalformat_query2 GL_ARB_multi_bind GL_ARB_seamless_cubemap_per_texture GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_stencil8 GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_shader_integer_mix GL_ARB_clip_control GL_ARB_conditional_render_inverted GL_ARB_cull_distance GL_ARB_get_texture_sub_image GL_EXT_polygon_offset_clamp GL_KHR_context_flush_control GL_MESA_shader_integer_functions '
```

**Comment by Miiike89** [comment]
Hey!
I have the same Problem.

Platform: Windows-7-6.1.7601-SP1
Python:   3.5.4 |Anaconda, Inc.| (default, Sep 30 2017, 11:07:29) [MSC v.1900 64 bit (AMD64)]
NumPy:    1.13.3
Backend:  PyQt5
pyqt4:    None
pyqt5:    ('PyQt5', '5.6', '5.6.0')
pyside:   None
pyglet:   None
glfw:     None
sdl2:     None
wx:       None
egl:      None
osmesa:   None
_test:    None

GL version:  '4.4.0'
MAX_TEXTURE_SIZE: 16384


@thepunitsingh  Nevertheless vispy works fine in use for me, althoug the tests fail.
Do you have any problems using vispy other then the failure of tests?

**Comment by kmuehlbauer** [comment]
@thepunitsingh Please do the following in a terminal:

You might be missing the packages `nose`, `pytest` and `pytest-cov` as well as `coverage`.
Also `pyqt5` has some problems.

You might create a dedicated environment like this:

```bash
$ conda create -n vispy -c conda-forge vispy python=3.6 pyqt=5* scipy nose, pytest, pytest-cov coverage
$ source activate vispy
(vispy) $ python
>>> import vispy
>>> vispy.test() 
```
This runs moste of the tests fine on my machine. Some packages are reported missing, you easily can ` `conda install` them into your new `vispy` environment. If this doesn' work for you, try `pyqt=4*` in the above command.
