### ISSUE TITLE
Mesh/OpenGL crashes after upgrade of osx from 10.11 to 10.12 (Sierra)

### ISSUE THREAD

**Issue by macrocosme** [vispy/vispy#1290]
Trying the grid_mesh.py example (or any of my code that include mesh) triggers the following error:

```
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7 /Users/danyvohl/Documents/Etudes/Doctorat/Australie/code/vispy/examples/basics/visuals/grid_mesh.py
WARNING: Error drawing visual <GridMesh at 0x115851410>
WARNING: Traceback (most recent call last):
  File "/Users/.../code/vispy/examples/basics/visuals/grid_mesh.py", line 49, in <module>
    canvas.show()
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/app/canvas.py", line 429, in show
    self._backend._vispy_set_visible(visible)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/app/backends/_qt.py", line 335, in _vispy_set_visible
    self.showNormal()
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/app/backends/_qt.py", line 431, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/app/backends/_qt.py", line 703, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/canvas.py", line 207, in on_draw
    self._draw_scene()
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/canvas.py", line 253, in _draw_scene
    self.draw_visual(self.scene)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/canvas.py", line 291, in draw_visual
    node.draw()
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/visuals.py", line 98, in draw
    self._visual_superclass.draw(self)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/visuals/mesh.py", line 385, in draw
    Visual.draw(self, *args, **kwds)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/visuals/visual.py", line 440, in draw
    self._vshare.index_buffer)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/visuals/shaders/program.py", line 77, in draw
    Program.draw(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/program.py", line 470, in draw
    canvas.context.flush_commands()
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/context.py", line 171, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/glir.py", line 232, in flush
    self._shared.flush(parser)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/glir.py", line 146, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/glir.py", line 458, in parse
    self._parse(command)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/glir.py", line 420, in _parse
    ob.draw(*args)
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/glir.py", line 898, in draw
    gl.check_error('Check before draw')
  File "/usr/local/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/gl/__init__.py", line 211, in check_error
    raise err
RuntimeError: OpenGL got errors (Check before draw): GL_INVALID_FRAMEBUFFER_OPERATION
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt4) at 0x109c60650>> for DrawEvent

Process finished with exit code 0
```

If you have any hint as to what I should be looking for, I welcome any suggestions while I dig for a fix! 

Thanks

**Comment by macrocosme** [comment]
This might be a deeper issue with Vispy as other examples result in similar crash. 
Example from examples/visual/text_visual.py: 
```
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7 /Users/.../vispy/examples/basics/visuals/text_visual.py
WARNING: Traceback (most recent call last):
  File "/Users/.../vispy/examples/basics/visuals/text_visual.py", line 44, in <module>
    c.show()
  File "/Users/.../vispy/vispy/app/canvas.py", line 429, in show
    self._backend._vispy_set_visible(visible)
  File "/Users/.../vispy/vispy/app/backends/_qt.py", line 335, in _vispy_set_visible
    self.showNormal()
  File "/Users/.../vispy/vispy/app/backends/_qt.py", line 431, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "/Users/.../vispy/vispy/app/backends/_qt.py", line 703, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/Users/.../vispy/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/Users/.../vispy/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/Users/.../vispy/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/Users/.../vispy/examples/basics/visuals/text_visual.py", line 21, in on_draw
    self.text.draw()
  File "/Users/.../vispy/vispy/visuals/visual.py", line 432, in draw
    if self._prepare_draw(view=self) is False:
  File "/Users/.../vispy/vispy/visuals/text/text.py", line 443, in _prepare_draw
    self._font._lowres_size) for t in text])
  File "/Users/.../vispy/vispy/visuals/text/text.py", line 157, in _text_to_vbo
    glyph = font[char]
  File "/Users/.../vispy/vispy/visuals/text/text.py", line 69, in __getitem__
    self._load_char(char)
  File "/Users/.../vispy/vispy/visuals/text/text.py", line 102, in _load_char
    self._renderer.render_to_texture(data, self._atlas, (x, y), (w, h))
  File "/Users/.../vispy/vispy/visuals/text/_sdf.py", line 272, in render_to_texture
    edf_neg_tex = self._render_edf(orig_tex)
  File "/Users/.../vispy/vispy/visuals/text/_sdf.py", line 308, in _render_edf
    self.program_seed.draw('triangle_strip')
  File "/Users/.../vispy/vispy/gloo/program.py", line 470, in draw
    canvas.context.flush_commands()
  File "/Users/.../vispy/vispy/gloo/context.py", line 171, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/Users/.../vispy/vispy/gloo/glir.py", line 232, in flush
    self._shared.flush(parser)
  File "/Users/.../vispy/vispy/gloo/glir.py", line 146, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/Users/.../vispy/vispy/gloo/glir.py", line 458, in parse
    self._parse(command)
  File "/Users/.../vispy/vispy/gloo/glir.py", line 420, in _parse
    ob.draw(*args)
  File "/Users/.../vispy/vispy/gloo/glir.py", line 898, in draw
    gl.check_error('Check before draw')
  File "/Users/.../vispy/vispy/gloo/gl/__init__.py", line 211, in check_error
    raise err
RuntimeError: OpenGL got errors (Check before draw): GL_INVALID_FRAMEBUFFER_OPERATION
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PyQt4) at 0x10a7b1810>> for DrawEvent
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PyQt4) at 0x10a7b1810>> repeat 2
```

**Comment by macrocosme** [comment]
It seems that moving from PyQt4 to PyQt5 (and hence from Python2 to Python3) got rid of the issue. More testing to come, but so far, it doesn't crash on init anymore.

**Comment by merlinmah** [comment]
Another data point: PyQt5 used with Python 2 (homebrew's `--without-python3 --with-python`) produces this error for me.

**Comment by davidh-ssec** [comment]
FYI I am now seeing this on almost every example after upgrading to High Sierra (10.13). The odd thing with my bug is that the applications/examples seem to work fine after the initial error. I'm using an Anaconda Python 3.6 environment that was created on my previous version of the OS.

**Comment by davidh-ssec** [comment]
Additionally I think it might be related to glClear as described here: https://lists.apple.com/archives/mac-opengl/2012/Jul/msg00041.html

**Comment by j9ac9k** [comment]
I'm seeing this identical issue in pyqtgraph, I don't support a fix/workaround for this issue was implemented?

**Comment by djhoese** [comment]
@j9ac9k Are you using PyQt5? What version of Qt? What version of python? I think I've mostly seen these things going away as I upgrade to using PyQt5 in my own personal work.

**Comment by j9ac9k** [comment]
Right now I'm seeing these errors on 10.13 and 10.14 when using python 2.7 _and_ Qt4.x bindings (both pyqt4 and pyside1) on azure pipelines (and can reproduce locally on macOS 10.14).

I haven't been able to replicate this issue with using either Qt5 bindings _or_ going to Python 3.  

As we are trying to support python2.7/qt4 for the next release of pyqtgraph, figured I should give it a shot to address this issue, but if this has become a non-issue for you guys due to upping your dependency requirements, that's a good argument I can use to try and cut off python 2.7/Qt4 ourselves.

**Comment by djhoese** [comment]
Yeah with the end of life of python 2.7 and given how old Qt4 is (not built by conda-forge anymore) I think it is best to advise users to move to Python 3 and Qt5 if at all possible.

**Comment by j9ac9k** [comment]
> Yeah with the end of life of python 2.7 and given how old Qt4 is (not built by conda-forge anymore) I think it is best to advise users to move to Python 3 and Qt5 if at all possible.

Sounds good, I'll make a motion to skip those tests in our CI runs for the time being then 👍
