### ISSUE TITLE
Using wxPython 4.0.0b2 problem

### ISSUE THREAD

**Issue by eldarkg** [vispy/vispy#1357]
```
Python 3.5.3 (default, Sep  7 2017, 16:23:57) 
[GCC 6.3.0 20170406] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vispy
>>> vispy.use('wx')
>>> print(vispy.sys_info())
Platform: Linux-4.10.0-35-generic-x86_64-with-Ubuntu-17.04-zesty
Python:   3.5.3 (default, Sep  7 2017, 16:23:57)  [GCC 6.3.0 20170406]
NumPy:    1.13.1
Backend:  wx
pyqt4:    None
pyqt5:    None
pyside:   ('PySide', '1.2.2', '4.8.7')
pyglet:   None
glfw:     None
sdl2:     sdl2 0.9.3
wx:       wxPython 4.0.0b2
egl:      None
osmesa:   OSMesa
_test:    None

App info-gathering error:
Traceback (most recent call last):
  File "/home/eldar/src/vispy/vispy/util/config.py", line 432, in sys_info
    canvas = Canvas('Test', (10, 10), show=False, app=app)
  File "/home/eldar/src/vispy/vispy/app/canvas.py", line 205, in __init__
    self.create_native()
  File "/home/eldar/src/vispy/vispy/app/canvas.py", line 222, in create_native
    self._app.backend_module.CanvasBackend(self, **self._backend_kwargs)
  File "/home/eldar/src/vispy/vispy/app/backends/_wx.py", line 227, in __init__
    p.size, style)
TypeError: Frame(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 4 has unexpected type 'NoneType'
```

**Comment by davidh-ssec** [comment]
See #1358 for reason to wait for 0.6 release of vispy.
