### ISSUE TITLE
examples/tutorial/app/simple_wx.py issue

### ISSUE THREAD

**Issue by eldarkg** [vispy/vispy#1361]
```
Traceback (most recent call last):
  File "simple_wx.py", line 58, in <module>
    frame = TestFrame()
  File "simple_wx.py", line 49, in __init__
    self.canvas = Canvas(app="wx", parent=self, show=True)
  File "simple_wx.py", line 20, in __init__
    app.Canvas.__init__(self, *args, **kwargs)
  File "/home/eldar/src/vispy/vispy/app/canvas.py", line 208, in __init__
    self.set_current()
  File "/home/eldar/src/vispy/vispy/app/canvas.py", line 406, in set_current
    self._backend._vispy_set_current()
  File "/home/eldar/src/vispy/vispy/app/backends/_wx.py", line 302, in _vispy_set_current
    self.SetCurrent(self._gl_context)
wx._core.wxAssertionError: C++ assertion "xid" failed at /home/eldar/src/wx/wxPython_Phoenix/wxPython-4.0.0b2/ext/wxWidgets/src/unix/glx11.cpp(194) in SetCurrent(): window must be shown
```

**Comment by davidh-ssec** [comment]
I assumed with your previous PRs that you had gotten a working Canvas with wx. Did something change?

**Comment by eldarkg** [comment]
@davidh-ssec It isn't related bug.
