### ISSUE TITLE
AttributeError: module 'vispy.scene' has no attribute 'Label'

### ISSUE THREAD

**Issue by Datoclement** [vispy/vispy#1368]
Trying to run script of basic example [https://github.com/vispy/vispy/blob/master/examples/basics/scene/axes_plot.py](https://github.com/vispy/vispy/blob/master/examples/basics/scene/axes_plot.py)

get error:

Traceback (most recent call last):
  File "main.py", line 33, in <module>
    title = scene.Label("Plot Title", color='white')
AttributeError: module 'vispy.scene' has no attribute 'Label'

> python --version
Python 3.6.0

> pip3 show vispy
Name: vispy
Version: 0.4.0
Summary: Interactive visualization in Python
Home-page: http://vispy.org
Author: Vispy contributors
Author-email: vispy@googlegroups.com
License: (new) BSD
Location: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requires: numpy

Could some explain me what I should do to solve this?

**Comment by kmuehlbauer** [comment]
@Datoclement vispy 0.4.0 is terribly outdated. So most likely you will get things working by using the latest github master.

Note, that there are ongoing efforts to release 0.5.0 later this year.

**Comment by Datoclement** [comment]
Thank you. I then install the 0.5.0 version. 

Since I do not have pyqt4 in my computer, I actually call app.use_app('pyqt5') to indicate that it is pyqt5 to search. Otherwise, I run exactly the same script.

I get a new error: 

>WARNING: Traceback (most recent call last):
  File "main.py", line 143, in <module>
    app.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/app/_default_app.py", line 62, in run
    return default_app.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/app/application.py", line 142, in run
    return self._backend._vispy_run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/app/backends/_qt.py", line 229, in _vispy_run
    return app.exec_()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/app/backends/_qt.py", line 431, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/app/backends/_qt.py", line 431, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/app/backends/_qt.py", line 703, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/util/fetching.py", line 239, in _fetch_file
    data = urllib.request.urlopen(url, timeout=15.)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/scene/canvas.py", line 207, in on_draw
    self._draw_scene()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/scene/canvas.py", line 253, in _draw_scene
    self.draw_visual(self.scene)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/scene/canvas.py", line 291, in draw_visual
    node.draw()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/scene/visuals.py", line 98, in draw
    self._visual_superclass.draw(self)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/visuals/visual.py", line 588, in draw
    v.draw()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/visuals/visual.py", line 432, in draw
    if self._prepare_draw(view=self) is False:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/visuals/text/text.py", line 446, in _prepare_draw
    self._font._lowres_size) for t in text])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/visuals/text/text.py", line 446, in <listcomp>
    self._font._lowres_size) for t in text])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/visuals/text/text.py", line 157, in _text_to_vbo
    glyph = font[char]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/visuals/text/text.py", line 69, in __getitem__
    self._load_char(char)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/visuals/text/text.py", line 83, in _load_char
    _load_glyph(self._font, char, self._glyphs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/util/fonts/_quartz.py", line 87, in _load_glyph
    font = _load_font(f['face'], f['bold'], f['italic'])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/util/fonts/_quartz.py", line 46, in _load_font
    return _load_vispy_font(face, bold, italic)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/util/fonts/_quartz.py", line 24, in _load_vispy_font
    fname = _get_vispy_font_filename(face, bold, italic)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/util/fonts/_vispy_fonts.py", line 20, in _get_vispy_font_filename
    return load_data_file('fonts/%s' % name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/util/fetching.py", line 68, in load_data_file
    _fetch_file(url, fname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/util/fetching.py", line 243, in _fetch_file
    'Dataset fetching aborted (%s)' % (url, e))
RuntimeError: Error while fetching file http://github.com/vispy/demo-data/raw/master/fonts/OpenSans-Regular.ttf.
Dataset fetching aborted (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>)
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt5) at 0x101ca2cc0>> for DrawEvent
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt5) at 0x101ca2cc0>> repeat 2
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt5) at 0x101ca2cc0>> repeat 4

Could you help me about this, please?

**Comment by davidh-ssec** [comment]
@Datoclement The demo you are running tries to download data to run the example. It seems it is having trouble doing this. Could you try going to this URL in your browser: `http://github.com/vispy/demo-data/raw/master/fonts/OpenSans-Regular.ttf`

Does that work? If not then it looks like you have a connection issue to github. You may have more luck here following the suggestions in this stackoverflow answer: https://stackoverflow.com/a/42334357/433202

FYI I don't get this error using Python 3.6 via Anaconda on my mac.

**Comment by kmuehlbauer** [comment]
Thanks @davidh-ssec, I was about to fiddle with my phone, to get things explained. In #1266 there was mentioned, that also firewall issues could lead to this behaviour.

One more point to think about bundling needed data.

**Comment by Datoclement** [comment]
@kmuehlbauer @davidh-ssec Thank you. 

Since I am using the Internet from my campus, there are usually firewall issues. I think it is a general problem in the campus. 

To not to get distracted, I will just concentrate on what I want to build with vispy other than looking into the connection issue.

Anyway, thank you very much!
