### ISSUE TITLE
Travis tests fail with llvm 3.3 and mesa from conda forge

### ISSUE THREAD

**Issue by davidh-ssec** [vispy/vispy#1401]
The Travis CI tests have recently started failing due to a weird interaction between wxpython and llvm. I'm making this issue so we at least have a reference when it likely comes up again. See https://travis-ci.org/vispy/vispy/jobs/315021619

Typically OSMesa is installed as a separate dependency in a special separate travis environment. I recently added "wxpython" as a dependency. It seems wx depends on mesa which means that any travis environment that installs `wxpython` now installs OSMesa. While this isn't necessarily an issue, there does seem to be an issue with llvm 3.3 and the combination of EGL (system) and OSMesa (conda). With a miniconda environment on Ubuntu Trusty (via travis's docker images), llvm 3.3 and mesa 10.5.4, running the following code causes the segmentation fault seen below:

```
In [1]: import ctypes
In [2]: _egl_file = "/usr/lib/x86_64-linux-gnu/mesa-egl/libEGL.so.1"
In [3]: _osmesa_file = "/home/travis/anaconda/envs/testenv/lib/libOSMesa.so.8"
In [4]: _egl_lib = ctypes.CDLL(_egl_file)
In [5]: _EGL_DISPLAY = _egl_lib.eglGetDisplay(0); majorVersion = (ctypes.c_int*1)(); minorVersion = (ctypes.c_int*1)(); _egl_lib.eglInitialize(_EGL_DISPLAY, majorVersion, minorVersion)
Out[5]: 1
In [6]: _osmesa_lib = ctypes.CDLL(_osmesa_file)
Two passes with the same argument (-alloca-hoisting) attempted to be registered!
Segmentation fault
```

Downgrading to llvm 3.2 fixes the segmentation fault.

**Comment by davidh-ssec** [comment]
Even after forcing llvm to 3.2 we get different errors.

```
0.19s$ python -c "import vispy; print(vispy.sys_info())"
Platform: Linux-4.4.0-93-generic-x86_64-with-debian-jessie-sid
Python:   2.7.14 | packaged by conda-forge | (default, Dec  9 2017, 16:18:43)  [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
NumPy:    1.12.1
App info-gathering error:
Traceback (most recent call last):
  File "vispy/util/config.py", line 416, in sys_info
    from ..app import use_app, Canvas
  File "vispy/app/__init__.py", line 15, in <module>
    from .canvas import Canvas, MouseEvent, KeyEvent  # noqa
  File "vispy/app/canvas.py", line 17, in <module>
    from ..gloo.context import (GLContext, set_current_canvas, forget_canvas)
  File "vispy/gloo/__init__.py", line 47, in <module>
    from . import gl  # noqa
  File "vispy/gloo/gl/__init__.py", line 235, in <module>
    from . import gl2 as default_backend  # noqa
  File "vispy/gloo/gl/gl2.py", line 51, in <module>
    _lib = ctypes.cdll.LoadLibrary(_fname)
  File "/home/travis/anaconda/envs/testenv/lib/python2.7/ctypes/__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
  File "/home/travis/anaconda/envs/testenv/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: undefined symbol: _glapi_tls_Dispatch
```

```
0.21s$ if [ "${TEST}" == "osmesa" ]; then make osmesa; fi;
Cleaning build, pyc, ctags, and cache
python make test osmesa
libLLVM-3.3.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "make/make.py", line 198, in test
    test(args[0], ' '.join(args[1:]), coverage=True)
  File "/home/travis/build/vispy/vispy/vispy/testing/_runners.py", line 382, in test
    from ..app.backends import BACKEND_NAMES as backend_names
  File "/home/travis/build/vispy/vispy/vispy/app/__init__.py", line 15, in <module>
    from .canvas import Canvas, MouseEvent, KeyEvent  # noqa
  File "/home/travis/build/vispy/vispy/vispy/app/canvas.py", line 17, in <module>
    from ..gloo.context import (GLContext, set_current_canvas, forget_canvas)
  File "/home/travis/build/vispy/vispy/vispy/gloo/__init__.py", line 47, in <module>
    from . import gl  # noqa
  File "/home/travis/build/vispy/vispy/vispy/gloo/gl/__init__.py", line 235, in <module>
    from . import gl2 as default_backend  # noqa
  File "/home/travis/build/vispy/vispy/vispy/gloo/gl/gl2.py", line 28, in <module>
    _lib = ctypes.cdll.LoadLibrary(_lib)
  File "/home/travis/anaconda/envs/testenv/lib/python2.7/ctypes/__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
  File "/home/travis/anaconda/envs/testenv/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
type: libLLVM-3.3.so: cannot open shared object file: No such file or directory
make: *** [osmesa] Error 1
```

**Comment by davidh-ssec** [comment]
Comparing previously passing environments to the new failing environments show that `libgl1-mesa-dri` is no longer installed. I'm not sure why this has changed. Removing the `wxpython` dependency in the tests allows travis tests to pass. This is not preferable since we're removing a previously passing backend (most of the time at least). I'm currently attempting to force install `libgl1-mesa-dri` with apt with `wxpython` and `mesa!=3.3` installed. If that all passes then I will try to remove the `mesa` restriction.

**Comment by davidh-ssec** [comment]
This has been "fixed" by removing `wxpython` from the travis environments and adding `libgl1-mesa-dri` to the apt dependencies. I believe with the `wxpython` dependency installed in conda and therefore installing its `mesa` dependency, `vispy` is seeing this install as a `osmesa` compatibly library install which I don't think it is. Things like getting glGetParameter are returning None instead of bytes/strings.
