### ISSUE TITLE
Incorrect output when resetting data on a Volume visual

### ISSUE THREAD

**Issue by astrofrog** [vispy/vispy#1412]
The following example illustrates that if changing the data of a Volume visual, the output looks incorrect (this is on MacOS X):

```python
import numpy as np

from vispy import scene, app
from vispy.color import BaseColormap


def get_translucent_cmap(r, g, b):

    class TranslucentCmap(BaseColormap):
        glsl_map = """
        vec4 translucent_fire(float t) {{
            return vec4({0}, {1}, {2}, t);
        }}
        """.format(r, g, b)

    return TranslucentCmap()


canvas = scene.SceneCanvas(keys=None, show=False, bgcolor=(1, 1, 1))

view = canvas.central_widget.add_view()
view.parent = canvas.scene

view.camera = scene.cameras.TurntableCamera(parent=view.scene, fov=0., distance=4.0)

volume = scene.visuals.Volume(np.zeros((40, 640, 640)), clim=(0, 2),
                              cmap=get_translucent_cmap(0.5, 0.5, 0.5))

volume.transform = scene.STTransform(translate=(-1, -1, -1),
                                     scale=(0.003, 0.003, 0.05))

view.add(volume)

canvas.native.show()

volume.set_data(np.ones((40, 640, 640)))

app.run()
```

The output is:

<img width="833" alt="screen shot 2018-01-08 at 17 32 23" src="https://user-images.githubusercontent.com/314716/34683424-e98a60b8-f499-11e7-86f7-9eff6896de74.png">

**Comment by davidh-ssec** [comment]
I am not able to run your example on my mac on High Sierra. I normally get some framebuffer exceptions due to an OSX bug in High Sierra, but this one is different:
```
  File "/Users/davidh/anaconda/envs/vispy_test_36/lib/python3.6/site-packages/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1286,
	description = b'invalid framebuffer operation',
	baseOperation = glPixelStorei,
	cArguments = (GL_PACK_SWAP_BYTES, 0)
)
```

I'll keep looking.

**Comment by davidh-ssec** [comment]
@astrofrog I got your example to work by doing `show=True` in the canvas init (removed the redundant show at the bottom of the code) and it seems to work fine for me for `(40, 408, 408)` and `(40, 409, 408)` and `(40, 640, 640)`. I'm not sure if I can help much more with debugging this.

**Comment by davidh-ssec** [comment]
Do you get anything different if you move the show to the init?

**Comment by astrofrog** [comment]
@davidh-ssec - I'm using High Sierra too, are you using PyQt5? Here is my environment:

```
conda create -n vispy-bug-3 python=3.6 numpy pyqt=5
source activate vispy-bug-3
pip install vispy pyopengl
```

Can you try this and see if you can get the example to run as-is?

Moving show to the init works for this specific example but that doesn't work in my application so I don't think it's a proper solution for my use case.

**Comment by davidh-ssec** [comment]
The above works for me with show at the end of the script. Note that alpha/transparency is a known issue #1393 and #1394 which is why your screen is seen behind the canvas. I see similar things as far as the transparency goes, but the cube looks fine on my display in the environment created.

**Comment by astrofrog** [comment]
I've investigated this in more detail - for the the bug only occurs for certain array shapes. To figure out what the pattern is, I tried running this with many different random shapes, and for each one output a grayscale image. I then counted up the number of non-white pixels. 

Script to make the plots:

<details>
```python
import numpy as np

from vispy import scene
from vispy.color import BaseColormap
from vispy import io


def get_translucent_cmap(r, g, b):

    class TranslucentCmap(BaseColormap):
        glsl_map = """
        vec4 translucent_fire(float t) {{
            return vec4({0}, {1}, {2}, t);
        }}
        """.format(r, g, b)

    return TranslucentCmap()


for iter in range(1000):

    SHAPE = list(np.random.randint(1, 500, 3))

    canvas = scene.SceneCanvas(keys=None, show=False, bgcolor=(1, 1, 1))

    view = canvas.central_widget.add_view()
    view.parent = canvas.scene

    view.camera = scene.cameras.TurntableCamera(parent=view.scene, fov=0., distance=4.0)

    volume = scene.visuals.Volume(np.zeros(SHAPE).copy(), clim=(0, 2),
                                  cmap=get_translucent_cmap(0.5, 0.5, 0.5))

    volume.transform = scene.STTransform(translate=(-0.5, -0.5, -0.5),
                                         scale=1 / np.array(SHAPE[::-1]))

    view.add(volume)

    canvas.native.show()

    volume.set_data(np.ones(SHAPE).copy())

    img = canvas.render()
    img = img.min(axis=2)
    io.imsave('frames/{0}_{1}_{2}.png'.format(*SHAPE), img)
    canvas.native.close()
```
</details>

Script to count up the pixels:

<details>
```python
import os
import glob
import numpy as np
from PIL import Image


def to_array(filename):
    return np.array(Image.open(filename), dtype=float)


with open('pixels.log', 'w') as f:

    f.write('s1,s2,s3,s1*s2,s2*s3,s1*s3,s1*s2*s3,number\n')

    for filename in glob.glob(os.path.join('frames', '*.png')):

        array = to_array(filename)

        s1, s2, s3 = [int(s) for s in os.path.basename(filename).split('.')[0].split('_')]

        f.write("{0:d},{1:d},{2:d},{3:d},{4:d},{5:d},{6:d},{7:d}\n".format(s1, s2, s3, s1*s2, s2*s3, s1*s3, s1*s2*s3, np.sum(array < 250)))
        f.flush()
```
</details>

Here is an example plot:

![figure_0](https://user-images.githubusercontent.com/314716/38610734-ab43fe76-3d79-11e8-8f26-840a11332a23.png)

s1 is the first dimension of the shape. The horizontal line at the top are all the images that are fine, the ones below are ones that are bad. Let's select these and take a look at s2 * s3 vs s1:

![figure_0-2](https://user-images.githubusercontent.com/314716/38610829-ef7ff4b4-3d79-11e8-9c1b-367d10321204.png)

![figure_0-1](https://user-images.githubusercontent.com/314716/38610835-f30f0746-3d79-11e8-8b12-d4311c14aaf0.png)

It looks like all the ones that are bad occur for s1 > 50-ish and s2 * s3 > 130000-ish.

I then ran this again but zooming in to the region where this problem starts happening:

![figure_3](https://user-images.githubusercontent.com/314716/38611074-a147f71e-3d7a-11e8-9bae-3c6af5345cf4.png)

![figure_0-3](https://user-images.githubusercontent.com/314716/38611077-a3db9076-3d7a-11e8-8047-58e9d93fb0fe.png)

So it seem that whether there are issues or not is very related to the shape/size of the array. This in turn may be dependent on the graphics card used, so it would be interesting if people do not see the issue with the example I gave at the top of this issue to try and run the script and see if they see the issue for any other combination of shape.

**Comment by astrofrog** [comment]
Just to add another datapoint, I don't see an issue on a Mac with an ``NVIDIA GeForce GT 750M 2048 MB`` and MacOS X 10.11.6.

**Comment by astrofrog** [comment]
I can work around this issue by sending the data to OpenGL in chunks - e.g. in ``texture.py`` if I replace:

```
        self._glir.command('DATA', self._id, offset, data)
```

by

```
        self._glir.command('DATA', self._id, offset, data[:,:300,:300])
        self._glir.command('DATA', self._id, (0, 300, 300), data[:,300:,300:])
        self._glir.command('DATA', self._id, (0, 0, 300), data[:,:300,300:])
        self._glir.command('DATA', self._id, (0, 300, 0), data[:,300:,:300])
```

when the array is (40, 640, 640) (as in the original example in this issue), then things work fine. So the issue seems to come from sending too much data in one go.

**Comment by davidh-ssec** [comment]
@astrofrog So how many systems do you see this on? What operating systems? What GPUs? And you said this was PyQt5?

**Comment by astrofrog** [comment]
For now I see it on my own, though I've had other users report this issue too but I need to ask them for more hardware details. For me it occurs on MacOS X 10.13.3 (and 10.13.4) with the ``Intel Iris Graphics 6100 1536 MB`` graphics card, but I don't see it on a machine with 10.11 and an NVIDIA card. I see it with PyQt5 but I don't think it's related to that. The last workaround I found above suggests this might be due to the graphics card (or the OpenGL driver) not coping well with too much data being passed at a time under certain circumstances.

**Comment by astrofrog** [comment]
Note that if I send the data in chunks like this:

```
        for i in range(40):
            self._glir.command('DATA', self._id, (i, 0, 0), data[i:i+1,:,:])
```

then again it fails, so it does seem that if the data is too large along the second and third dimension combined then it fails.

**Comment by nsinh008** [comment]
> I am not able to run your example on my mac on High Sierra. I normally get some framebuffer exceptions due to an OSX bug in High Sierra, but this one is different:
> 
> ```
>   File "/Users/davidh/anaconda/envs/vispy_test_36/lib/python3.6/site-packages/OpenGL/error.py", line 232, in glCheckError
>     baseOperation = baseOperation,
> OpenGL.error.GLError: GLError(
> 	err = 1286,
> 	description = b'invalid framebuffer operation',
> 	baseOperation = glPixelStorei,
> 	cArguments = (GL_PACK_SWAP_BYTES, 0)
> )
> ```
> I'll keep looking.

Hi @djhoese 
Saw your comment and needed help.
I am also facing this issue of GLError "invalid framebuffer operation" while using GLClear, glBegin or glEnd.
How did you resolve the error?
I tried many things but none worked.

Can you please help?

**Comment by djhoese** [comment]
@nsinh008 Sorry, but I don't remember. My comment after the one you quoted talks about how I moved `show` around which seemed to get rid of the above error. As mentioned in the comment you quoted there is a bug in OSX related to Qt4 (maybe Qt5 too) where the first draw always shows these errors but subsequent draws work fine. That said, are you using vispy? glBegin and glEnd are deprecated OpenGL functions (correct me if I'm wrong) and I don't think are used anywhere in vispy.

**Comment by nsinh008** [comment]
I am actually using pyCharm IDE for my Computer animation project and was using glClear() which is throwing invalid framebuffer operation error. It goes in infinite loop.
2018-10-29 10:12:12.620 Python[5866:1496057] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)
Traceback (most recent call last):
  File "/Users/nidhisinha/PycharmProjects/assignment2/assign1_1.py", line 43, in OnDraw
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
  File "/Users/nidhisinha/Library/Python/3.7/lib/python/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/Users/nidhisinha/Library/Python/3.7/lib/python/site-packages/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1286,
	description = b'invalid framebuffer operation',
	baseOperation = glClear,
	cArguments = (16640,)
)


I also tried setting "defaults write org.python.python ApplePersistenceIgnoreState NO" but doesnt help.

**Comment by djhoese** [comment]
If you are not using vispy I would recommend posting on an opengl forum, specifically pyopengl. If you are using vispy then start by testing some of our existing examples. If you have issues with those or your own vispy code then please create a separate issue. Good luck.

**Comment by djhoese** [comment]
@astrofrog How does this issue look now that vispy 0.6 has been out for a while?

**Comment by astrofrog** [comment]
I'm still seeing this issue with VisPy 0.6.2
