### ISSUE TITLE
Can attach but not detach alpha filter

### ISSUE THREAD

**Issue by JPFrancoia** [vispy/vispy#1434]
Hi,

I'm writing some sort of STL viewer with PyQt5 + vispy. Here is my Canvas widget:

```python
#!/usr/bin/python
# coding: utf-8

import os
from vispy import app, geometry
import vispy.scene
from vispy.scene import visuals
from vispy.app import use_app
from typing import Tuple, Union
from vispy.visuals.filters import Alpha


# TODO: remove trimesh, vispy should soon be able to load STL files
import trimesh

use_app('PyQt5')


class MyCanvas(vispy.scene.SceneCanvas):

    """"
    Class to view a STL file. Camera is embedded, so rotations/translations are
    possible
    https://github.com/vispy/vispy/issues/1425#issuecomment-365369727
    """

    def __init__(self, size: Tuple[int, int]=(800, 500)):

        """
        size is the size in pixels (x, y). watch_dir is the path to watch
        for new STL files
        """

        vispy.scene.SceneCanvas.__init__(self, keys='interactive',
                                         size=size, bgcolor='white')

        # Unfreeze the class, so adding attributes is possible
        self.unfreeze()

        # Create a dict to store several meshes
        # Meshes are stored with their names so they can be reloaded/reviewed
        # namely
        self.meshes = dict()

        # Add an 'arcball' camera
        self.view = self.central_widget.add_view()
        self.view.camera = 'arcball'

        self.translucent_filter = Alpha(0.3)

        self.viewMesh("test")

        # Freeze the class again. Might not be necessary
        self.freeze()

        self.setTranslucent(True)
        self.setTranslucent(False)

        self.show()


    def viewMesh(self, file_name: str):

        """
        Will load the file file_name in the STL viewer. If the mesh didn't
        exist before, it will be created. Else, it will be updated
        """

        # file_name is passed wo extension, so add .stl
        file_name = file_name + ".stl"

        file_to_view = file_name

        # Load the stl file. Works with binary or ascii stl files
        mesh = trimesh.load(file_to_view)
        mdata = geometry.MeshData(mesh.vertices, mesh.faces)

        # Create a Mesh visual, with the view as parent
        self.meshes[file_name] = visuals.Mesh(meshdata=mdata,
                                              shading='flat',
                                              parent=self.view.scene,)


    def setTranslucent(self, translucent: bool):

        for mesh in self.meshes.values():
            if translucent:
                mesh.attach(self.translucent_filter)
            else:
                mesh.detach(self.translucent_filter)


if __name__ == '__main__':
    win = MyCanvas()
    win.viewMesh("test")

    import sys
    if sys.flags.interactive != 1:
        app.run()
        print(app)
```

It should be a working example. Here is a file ```test.stl``` if you want to run the code:

[test.stl.txt](https://github.com/vispy/vispy/files/1748729/test.stl.txt)

If you run this code with ```setTranslucent(False)``` commented, it will work perfectly and the mesh should be translucent. If ```setTranslucent(False)``` is executed, the script crashes with:

```
Traceback (most recent call last):
  File "canvas.py", line 94, in <module>
    win = MyCanvas()
  File "canvas.py", line 57, in __init__
    self.setTranslucent(False)
  File "canvas.py", line 90, in setTranslucent
    mesh.detach(self.translucent_filter)
  File "/home/djipey/.local/share/virtualenvs/cad/lib/python3.6/site-packages/vispy/visuals/visual.py", line 499, in detach
    filt._detach(view)
AttributeError: 'Alpha' object has no attribute '_detach'
```

So it seems I can attach an Alpha filter to a mesh, but not detach it. Am I doing something wrong ?

**Comment by kmuehlbauer** [comment]
@JPFrancoia The filter is missing the '_detach'-method. It should be fairly easy to implement. Want to give it a stab? PR always welcome.

**Comment by JPFrancoia** [comment]
Ok, I'm trying to implement the detach method. I made it work already, but I don't understand the original implementation of the ```Alpha``` class, so maybe I'm doing something wrong.

It all comes down to the ```Alpha``` class that is here: https://github.com/vispy/vispy/blob/a48cc6abff743cfaaadf3c3c3c092d72e046dab5/vispy/visuals/filters/color.py#L113

```python
class Alpha(object):
    def __init__(self, alpha=1.0):
        self.shader = Function("""
            void apply_alpha() {
                gl_FragColor.a = gl_FragColor.a * $alpha;
            }
        """)
        self.alpha = alpha

    @property
    def alpha(self):
        return self._alpha

    @alpha.setter
    def alpha(self, a):
        self._alpha = a
        self.shader['alpha'] = a

    def _attach(self, visual):
        self._visual = weakref.ref(visual)
        hook = visual._get_hook('frag', 'post')
        hook.add(self.shader())
```

I don't really understand what the ```self.shader()``` instruction does. From what I could figure out, it creates a ```FunctionCall of 'apply_alpha'``` object of some sort.

So the line ```hook.add(self.shader())``` of the ```_attach``` function creates an item in a dictionary of the ```hook``` object created one line earlier. Here is what this dict looks like in my case:

```
{<FunctionCall of 'apply_color_filter' at 0x7f16ac6ee080>: 8, <FunctionCall of 'picking_filter' at 0x7f16ac6eea20>: 10, <FunctionCall of 'apply_alpha' at 0x7f16ac6eea90>: 5}
```

The ```hook``` object is a ```StatementList```, and can be found here: https://github.com/vispy/vispy/blob/a48cc6abff743cfaaadf3c3c3c092d72e046dab5/vispy/visuals/shaders/function.py#L741

That's perfect, this object has a ```remove``` method, so I basically just need to pass the ```FunctionCall of 'apply_alpha'``` object, and job done.

The problem is, the ```Alpha``` object doesn't store the ```FunctionCall of 'apply_alpha'``` object it created with the ```_attach``` method. Each call to ```self.shader()``` returns a new ```FunctionCall of 'apply_alpha'``` object.

So here is my new implementation:

```python
class Alpha(object):
    def __init__(self, alpha=1.0):
        self.shader = Function("""
            void apply_alpha() {
                gl_FragColor.a = gl_FragColor.a * $alpha;
            }
        """)
        self.alpha = alpha

    @property
    def alpha(self):
        return self._alpha

    @alpha.setter
    def alpha(self, a):
        self._alpha = a
        self.shader['alpha'] = a

    def _attach(self, visual):
        self._visual = weakref.ref(visual)
        hook = visual._get_hook('frag', 'post')
        self.filt = self.shader()
        hook.add(self.filt)

    def _detach(self, visual):
        self._visual = weakref.ref(visual)
        hook = visual._get_hook('frag', 'post')
        hook.remove(self.filt)
```

I basically create a ```self.filt``` attribute to store the object returned by ```self.shader()```, so I can delete it later in the ```_detach``` function.

But maybe there is a better way to get this object ?

**Comment by JPFrancoia** [comment]
Well at the moment I don't use attach/detach for the alpha filter, I don't like having "non-approved" in production.

For now, I just attach an alpha filter to any mesh I want to display. When I want to make it transparent, I just set the alpha value to 0. Opaque: I turn it to one.

```python
    def toggleTranslucent(self):

        """Toggle the translucent state of all the meshes. Called X-ray in GUI"""

        self.translucent = not self.translucent

        for mesh in self.meshes.values():

            # Change the alpha value of the mesh's alpha filter
            # Disable depht_test when translucent, better visual
            # https://github.com/vispy/vispy/issues/1482
            if self.translucent:
                mesh.filter.alpha = self.TRANSPARENT_ALPHA_CST
                mesh.set_gl_state(depth_test=False)
            else:
                mesh.filter.alpha = 1
                mesh.set_gl_state(depth_test=True)

        # Update the scene immediately
        self.view.scene.update()
```
