### ISSUE TITLE
Vispy, Qt and Windows: 'LooseVersion' object has no attribute 'version'

### ISSUE THREAD

**Issue by JPFrancoia** [vispy/vispy#1450]
Hello,

I'm currently developing a multi-platform software that uses Vispy. It runs fine on Linux, and I'm trying to port it on Windows. I run Windows 10 64 bits in Virtual Box, and here is the error I get when I start my software:

```
WARNING: Traceback (most recent call last):
  File ".\main.py", line 826, in <module>
    app.processEvents()
  File "C:\Users\djipey\AppData\Local\Programs\Python\Python35\lib\site-packages\vispy\app\backends\_qt.py", line 436, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "C:\Users\djipey\AppData\Local\Programs\Python\Python35\lib\site-packages\vispy\app\backends\_qt.py", line 708, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "C:\Users\djipey\AppData\Local\Programs\Python\Python35\lib\site-packages\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "C:\Users\djipey\AppData\Local\Programs\Python\Python35\lib\site-packages\vispy\util\event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "C:\Users\djipey\AppData\Local\Programs\Python\Python35\lib\site-packages\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "C:\Users\djipey\AppData\Local\Programs\Python\Python35\lib\site-packages\vispy\gloo\context.py", line 170, in flush_commands
    self.shared.parser.parse([('CURRENT', 0)])
  File "C:\Users\djipey\AppData\Local\Programs\Python\Python35\lib\site-packages\vispy\gloo\glir.py", line 477, in parse
    self._parse(command)
  File "C:\Users\djipey\AppData\Local\Programs\Python\Python35\lib\site-packages\vispy\gloo\glir.py", line 404, in _parse
    self._gl_initialize()
  File "C:\Users\djipey\AppData\Local\Programs\Python\Python35\lib\site-packages\vispy\gloo\glir.py", line 502, in _gl_initialize
    if this_version < '2.1':
  File "C:\Users\djipey\AppData\Local\Programs\Python\Python35\lib\distutils\version.py", line 52, in __lt__
    c = self._cmp(other)
  File "C:\Users\djipey\AppData\Local\Programs\Python\Python35\lib\distutils\version.py", line 335, in _cmp
    if self.version == other.version:
AttributeError: 'LooseVersion' object has no attribute 'version'
ERROR: Invoking <bound method GLContext.flush_commands of <GLContext at 0x1fbf42078d0>> for DrawEvent
ERROR: Invoking <bound method GLContext.flush_commands of <GLContext at 0x1fbf42078d0>> repeat 2
```

My software doesn't crash and I can use it, apart from the Canvas made with Vispy. Any idea what's going wrong ?

Best

**Comment by kmuehlbauer** [comment]
@JPFrancoia Sorry, no idea so far. Although we had a similar issue recently #1342.

Might also be related: https://github.com/dask/dask-searchcv/issues/64

Maybe @larsoner has seen this before.

**Comment by JPFrancoia** [comment]
I'm investigating the issue. It might be because I run windows in a virtual box, and not sure virtual box is available in a virtual machine.

I'm trying to fine a computer running windows to test that. Will keep you posted.

**Comment by larsoner** [comment]
I have never seen this

**Comment by JPFrancoia** [comment]
Ok vispy actually runs fine on a 64 bits "normal" Windows (not running in virtualbox).

Actually on windows in virtualbox, opengl version is limited to 1.1, as far as I understand. The graphics are rendered with directX. There is no driver available for a more recent version of Opengl in virtual box.

I guess my isssue is solved.
