### ISSUE TITLE
_glGetIntegerv is not defined

### ISSUE THREAD

**Issue by j-schroeder-schetelig** [vispy/vispy#1466]
I get the following error with my own visual:

> WARNING:vispy:Error drawing visual <PolygonalMesh at 0x2040b66d940>
> WARNING: Traceback (most recent call last):
>   File "C:/Users/johannes/Documents/PythonAnalyser/pvmain.py", line 143, in <module>
>     run_batch_immediately=not arg.batch_insert)
>   File "C:\Users\johannes\Documents\PythonAnalyser\pythonanalyser\MainApplication.py", line 155, in __init__
>     sys.exit(self.exec_())
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\app\backends\_qt.py", line 436, in event
>     out = super(QtBaseCanvasBackend, self).event(ev)
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\app\backends\_qt.py", line 436, in event
>     out = super(QtBaseCanvasBackend, self).event(ev)
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\app\backends\_qt.py", line 708, in paintGL
>     self._vispy_canvas.events.draw(region=None)
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\util\event.py", line 455, in __call__
>     self._invoke_callback(cb, event)
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\util\event.py", line 475, in _invoke_callback
>     self, cb_event=(cb, event))
>   << caught exception here: >>
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\util\event.py", line 471, in _invoke_callback
>     cb(event)
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\scene\canvas.py", line 207, in on_draw
>     self._draw_scene()
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\scene\canvas.py", line 253, in _draw_scene
>     self.draw_visual(self.scene)
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\scene\canvas.py", line 291, in draw_visual
>     node.draw()
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\scene\visuals.py", line 98, in draw
>     self._visual_superclass.draw(self)
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\visuals\visual.py", line 440, in draw
>     self._vshare.index_buffer)
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\visuals\shaders\program.py", line 77, in draw
>     Program.draw(self, *args, **kwargs)
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\gloo\program.py", line 470, in draw
>     canvas.context.flush_commands()
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\gloo\context.py", line 170, in flush_commands
>     self.shared.parser.parse([('CURRENT', 0)])
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\gloo\glir.py", line 477, in parse
>     self._parse(command)
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\gloo\glir.py", line 404, in _parse
>     self._gl_initialize()
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\gloo\glir.py", line 499, in _gl_initialize
>     gl.glGetParameter(gl.GL_MAX_TEXTURE_SIZE)
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\gloo\gl\_pyopengl2.py", line 153, in glGetParameter
>     return _glGetIntegerv(pname)
> NameError: name '_glGetIntegerv' is not defined
> WARNING:vispy:Traceback (most recent call last):
>   File "C:/Users/johannes/Documents/PythonAnalyser/pvmain.py", line 143, in <module>
>     run_batch_immediately=not arg.batch_insert)
>   File "C:\Users\johannes\Documents\PythonAnalyser\pythonanalyser\MainApplication.py", line 155, in __init__
>     sys.exit(self.exec_())
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\app\backends\_qt.py", line 436, in event
>     out = super(QtBaseCanvasBackend, self).event(ev)
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\app\backends\_qt.py", line 436, in event
>     out = super(QtBaseCanvasBackend, self).event(ev)
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\app\backends\_qt.py", line 708, in paintGL
>     self._vispy_canvas.events.draw(region=None)
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\util\event.py", line 455, in __call__
>     self._invoke_callback(cb, event)
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\util\event.py", line 475, in _invoke_callback
>     self, cb_event=(cb, event))
>   << caught exception here: >>
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\util\event.py", line 471, in _invoke_callback
>     cb(event)
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\scene\canvas.py", line 207, in on_draw
>     self._draw_scene()
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\scene\canvas.py", line 253, in _draw_scene
>     self.draw_visual(self.scene)
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\scene\canvas.py", line 291, in draw_visual
>     node.draw()
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\scene\visuals.py", line 98, in draw
>     self._visual_superclass.draw(self)
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\visuals\visual.py", line 440, in draw
>     self._vshare.index_buffer)
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\visuals\shaders\program.py", line 77, in draw
>     Program.draw(self, *args, **kwargs)
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\gloo\program.py", line 470, in draw
>     canvas.context.flush_commands()
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\gloo\context.py", line 170, in flush_commands
>     self.shared.parser.parse([('CURRENT', 0)])
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\gloo\glir.py", line 477, in parse
>     self._parse(command)
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\gloo\glir.py", line 404, in _parse
>     self._gl_initialize()
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\gloo\glir.py", line 499, in _gl_initialize
>     gl.glGetParameter(gl.GL_MAX_TEXTURE_SIZE)
>   File "C:\Users\johannes\Anaconda3\lib\site-packages\vispy\gloo\gl\_pyopengl2.py", line 153, in glGetParameter
>     return _glGetIntegerv(pname)
> NameError: name '_glGetIntegerv' is not defined

My current workaround is to replace the undefined function call with GL.glGetIntegerv, which works for me.

However, the comment at the top of the file _pyopengl2.py says

> """
> 
> THIS CODE IS AUTO-GENERATED. DO NOT EDIT.
> 
> Proxy API for GL ES 2.0 subset, via the PyOpenGL library.
> 
> """

therefore the bug should be fixed somewhere else.

**Comment by davidh-ssec** [comment]
Hi @j-schroeder-schetelig. Thanks for filing the bug report. Could you provide a small example that causes this error that I could run on my own machine for further testing?

The nature of the error makes me wonder if your GPU is either too old or too new or that your video drivers need to be updated. Do you know what type of GPU you have and what version of Windows you are running?

**Comment by j-schroeder-schetelig** [comment]
Hi David,
thanks for the quick reply.

I am running Windows 10 Pro, 64bit, and Python 3.5.
My laptop has two GPUs:
Intel Core i7-7820HQ CPU with Intel HD Graphics 630
NVIDIA Quadro M1200, driver version 388.16
Using the NVidia control panel, I have specified that python.exe should use the high-performance GPU.

Tomorrow I can try to boil down the code to a small example reproducing the error.
- Johannes

**Comment by Tillsten** [comment]
Note that this bug vanishes when replacing `'_glGetIntegerv` with `'GL.glGetIntegerv`

**Comment by djhoese** [comment]
I could be wrong but last time I read this source code and the comments around it the pyopengl GL backend is for debugging mostly. I'm wondering if this GL backend isn't fully tested or if there is a reason that `_glGetIntegerv` was preferred in other backends over `glGetIntegerv`.
