### ISSUE TITLE
Mesa backend fails

### ISSUE THREAD

**Issue by f0k** [vispy/vispy#1517]
First of all, thanks for making this available! After being pointed to vispy by a colleague, I tried to run the demo at https://github.com/liubenyuan/vispy-tutorial/blob/master/examples/scatter.py.

I got the following wall of error messages, afterwards it ran in a tight loop that I could exit with CTRL+C:
<details><summary>Wall of error messages</summary>

```
WARNING: Error drawing visual <Markers at 0x7f9478296390>
WARNING: Traceback (most recent call last):
  File "../code/show_embedding.py", line 122, in <module>
    main()
  File "../code/show_embedding.py", line 115, in main
    scatter3d(data, meta)
  File "../code/show_embedding.py", line 73, in scatter3d
    app.run()
  File "/home/jan/install/vispy-git/vispy/app/_default_app.py", line 62, in run
    return default_app.run()
  File "/home/jan/install/vispy-git/vispy/app/application.py", line 152, in run
    return self._backend._vispy_run()
  File "/home/jan/install/vispy-git/vispy/app/backends/_osmesa.py", line 75, in _vispy_run
    self._vispy_process_events()
  File "/home/jan/install/vispy-git/vispy/app/backends/_osmesa.py", line 70, in _vispy_process_events
    win._on_draw()
  File "/home/jan/install/vispy-git/vispy/app/backends/_osmesa.py", line 216, in _on_draw
    self._vispy_canvas.events.draw(region=None)  # (0, 0, w, h)
  File "/home/jan/install/vispy-git/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/home/jan/install/vispy-git/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/home/jan/install/vispy-git/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/home/jan/install/vispy-git/vispy/scene/canvas.py", line 217, in on_draw
    self._draw_scene()
  File "/home/jan/install/vispy-git/vispy/scene/canvas.py", line 266, in _draw_scene
    self.draw_visual(self.scene)
  File "/home/jan/install/vispy-git/vispy/scene/canvas.py", line 304, in draw_visual
    node.draw()
  File "/home/jan/install/vispy-git/vispy/scene/visuals.py", line 98, in draw
    self._visual_superclass.draw(self)
  File "/home/jan/install/vispy-git/vispy/visuals/visual.py", line 440, in draw
    self._vshare.index_buffer)
  File "/home/jan/install/vispy-git/vispy/visuals/shaders/program.py", line 77, in draw
    Program.draw(self, *args, **kwargs)
  File "/home/jan/install/vispy-git/vispy/gloo/program.py", line 470, in draw
    canvas.context.flush_commands()
  File "/home/jan/install/vispy-git/vispy/gloo/context.py", line 170, in flush_commands
    self.shared.parser.parse([('CURRENT', 0)])
  File "/home/jan/install/vispy-git/vispy/gloo/glir.py", line 477, in parse
    self._parse(command)
  File "/home/jan/install/vispy-git/vispy/gloo/glir.py", line 404, in _parse
    self._gl_initialize()
  File "/home/jan/install/vispy-git/vispy/gloo/glir.py", line 502, in _gl_initialize
    if this_version < '2.1':
  File "/usr/lib/python3.5/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/usr/lib/python3.5/distutils/version.py", line 335, in _cmp
    if self.version == other.version:
AttributeError: 'LooseVersion' object has no attribute 'version'
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (osmesa) at 0x7f94764ceac8>> for DrawEvent
WARNING: Traceback (most recent call last):
  File "../code/show_embedding.py", line 122, in <module>
    main()
  File "../code/show_embedding.py", line 115, in main
    scatter3d(data, meta)
  File "../code/show_embedding.py", line 73, in scatter3d
    app.run()
  File "/home/jan/install/vispy-git/vispy/app/_default_app.py", line 62, in run
    return default_app.run()
  File "/home/jan/install/vispy-git/vispy/app/application.py", line 152, in run
    return self._backend._vispy_run()
  File "/home/jan/install/vispy-git/vispy/app/backends/_osmesa.py", line 75, in _vispy_run
    self._vispy_process_events()
  File "/home/jan/install/vispy-git/vispy/app/backends/_osmesa.py", line 70, in _vispy_process_events
    win._on_draw()
  File "/home/jan/install/vispy-git/vispy/app/backends/_osmesa.py", line 216, in _on_draw
    self._vispy_canvas.events.draw(region=None)  # (0, 0, w, h)
  File "/home/jan/install/vispy-git/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/home/jan/install/vispy-git/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/home/jan/install/vispy-git/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/home/jan/install/vispy-git/vispy/gloo/context.py", line 171, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/home/jan/install/vispy-git/vispy/gloo/glir.py", line 232, in flush
    self._shared.flush(parser)
  File "/home/jan/install/vispy-git/vispy/gloo/glir.py", line 146, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/home/jan/install/vispy-git/vispy/gloo/glir.py", line 477, in parse
    self._parse(command)
  File "/home/jan/install/vispy-git/vispy/gloo/glir.py", line 455, in _parse
    ob.set_shaders(*args)
  File "/home/jan/install/vispy-git/vispy/gloo/glir.py", line 651, in set_shaders
    (type_ + ' shader', errormsg))
RuntimeError: Shader compilation error in vertex shader:
ERROR: Invoking <bound method GLContext.flush_commands of <GLContext at 0x7f9478225080>> for DrawEvent
^CTraceback (most recent call last):
  File "../code/show_embedding.py", line 122, in <module>
    main()
  File "../code/show_embedding.py", line 115, in main
    scatter3d(data, meta)
  File "../code/show_embedding.py", line 73, in scatter3d
    app.run()
  File "/home/jan/install/vispy-git/vispy/app/_default_app.py", line 62, in run
    return default_app.run()
  File "/home/jan/install/vispy-git/vispy/app/application.py", line 152, in run
    return self._backend._vispy_run()
  File "/home/jan/install/vispy-git/vispy/app/backends/_osmesa.py", line 74, in _vispy_run
    while not all(w.closed for w in wins):
KeyboardInterrupt
```

</details>

Tracing through it in `pdb`, I found that the first error is thrown because `gl.glGetParameter(gl.GL_VERSION)` returns an empty string for me ([in `glir.py`](https://github.com/vispy/vispy/blob/b8a4bca/vispy/gloo/glir.py#L497)). All the others are probably due to similar problems with `libGL.so` not returning what it should.

After some more research, I was able to fix this with `pip install pyglet`, but this was not exactly obvious from the error messages I received -- it required me to understand that there are different backends to choose from, that the Mesa backend is probably the last one that's tried, and that installing the requirements for any of the other backends will circumvent the error.

It might be useful to add some more error catching to the mesa backend, to tell that something is wrong, and to point towards `vispy.use()`. Also it probably should not get in the tight `while not all(w.closed for w in wins)` loop if none of the backends is working?

Thanks, and keep up the good work!

**Comment by djhoese** [comment]
Hi, thanks for making this issue. I'll try to answer your points/questions in order:

1. Glad you figured out the issue. It seems something was wrong with your GL drivers on your system.
2. I agree that the error messages could be improved in this case. We don't run in to this issue very much though because it only shows up when someones environment is corrupt in some way (bad GPU drivers, badly built backend, etc).
3. If you think about what vispy is attempting to do I think the looping through backends shouldn't ever be an issue. In 90% of environments you should be able to have multiple backends installed and vispy could properly use whichever one you wanted (using `vispy.use`). For anyone who doesn't know which one they want to use vispy can guess which one to use and tries to use the first one that works. 

I'm not sure which exact line you are talking about with `all(...)` but if you have ideas for how the error messages could be improved and since you've looked at the code, maybe you could submit a pull request for something better? It would be much appreciated. Thank you.

**Comment by f0k** [comment]
Looking at the code to figure out where the exceptions are intercepted, I found [the following](https://github.com/vispy/vispy/blob/master/vispy/app/backends/_osmesa.py#L175-L186):
```python
    def _vispy_close(self):
        if self.closed:
            return
        # We do not set self._native_context = None here because this causes
        # trouble in case a canvas is closed multiple times (as in
        # app.test_run()). The problem occurs in gloo's glir._gl_initialize
        # when it tries to call glGetString(GL_VERSION).
        # But OSMesa requires a context to be attached when calling
        # glGetString otherwise it returns an empty string, which gloo doesn't
        # like
        self._closed = True
        return
```
This is the problem I experienced -- `glGetString(GL_VERSION)` returns an empty string. Could still be a problem with how the machine is set up, but I tried it on different Ubuntu machines with the same result.

> I'm not sure which exact line you are talking about with `all(...)`

The one from the backtrace: https://github.com/vispy/vispy/blob/master/vispy/app/backends/_osmesa.py#L74
It seems that the exception thrown by gloo is intercepted somewhere and merely printed to the console, without changing the window state to be closed, so the app runs an endless loop.

> If you think about what vispy is attempting to do I think the looping through backends shouldn't ever be an issue.

Yes, looping through the backends is good. However, the loop only checks if the backend can be imported. If it can, it assumes everything will work fine.

I'm happy to submit a PR, but I'm not sure what's the best solution yet. I think the gloo exception should not be silently ignored. In addition, it might be good to do a quick check on importing `_osmesa` and throw an exception if it seems it won't work, so the backend testing loop can react. I don't know what this check would entail, though. According to the comment I pasted above, merely calling `glGetString` is doomed to fail without creating a Context first. Any suggestions?

**Comment by djhoese** [comment]
> Yes, looping through the backends is good. However, the loop only checks if the backend can be imported. If it can, it assumes everything will work fine.

The loop is checking if the module/backend exists. I think it is a fair assumption that if something exists that it will work. If it doesn't then that is a problem with the environment. If I was in the opposite position and had PyQt5 installed, didn't specifically ask to use the PyQt5 backend, and then ended up using some other backend because the PyQt5 was corrupt/broken then I would be upset that some other backend was automatically chosen instead. The special case here is examples where it is best for users to just have something work, but I'm 50/50 on "find the first working backend" versus "tell the user there is something wrong with their environment as soon as possible".

As for the mesa version being an empty string and the comment in the code mentioning it I wonder if @campagnola, @larsoner, @rougier, or @almarklein have any experience with this or know who originally added that backend. I'm currently dealing with a similar issue with the new PyQt5 backend.

As for the exception being hidden from the user and/or having shortened output, I think there is a way to disable this behavior but I can't find it at the moment. It may also not be something that is builtin right now. I remember doing it a month or so ago but I may have modified the vispy source to do it (it == showing the entire traceback for the backend exception).

**Comment by rougier** [comment]
Not quite sure either what to do in that situation.  How do you know the mesa import has failed?
