### ISSUE TITLE
running vispy on deep-learning server and only using it to generate png file not display 

### ISSUE THREAD

**Issue by Super-Tree** [vispy/vispy#1529]
I want to use the vispy on an deep learning server(ubuntu14.04),it doesn't have desktop, and other stuffs about display. But it has many gpus. I try to use vispy to generate screenshot PNG files without really display,
`import vispy `
`import vispy.app`
`import vispy.scene`
`import numpy as np`

`pc=np.arange(300).reshape(-1,3)`
`# v = vispy.app.Canvas()`
`canvas=vispy.scene.SceneCanvas(title="name", keys='interactive', show=False)`
`res = canvas.render(bgcolor='black')[:,:,0:3]`
`vispy.io.write_png("demo.png", res)`

but it failed.

> WARNING: QXcbConnection: Could not connect to display 
> WARNING: Could not connect to any X display.

**Comment by Super-Tree** [comment]
here is the result when i run 
`vispy.test()`


> Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 23:32:55) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import vispy
>>> vispy.test()
----------------------------------------------------------------------
Skipping backend pyqt4, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Running tests with pyqt5 backend:
_VISPY_TESTING_APP=pyqt5   -m vispy_app_test /mnt/lustre/hexindong/anaconda2/lib/python2.7/site-packages/vispy
============================================================= test session starts =============================================================
platform linux2 -- Python 2.7.15, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /mnt/lustre/hexindong/anaconda2/lib/python2.7/site-packages, inifile:
collected 0 items / 1 errors                                                                                                                  

=================================================================== ERRORS ====================================================================
______________________________________________________________ ERROR collecting  ______________________________________________________________
py/_path/common.py:377: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
py/_path/common.py:419: in gen
    if p.check(dir=1) and (rec is None or rec(p))])
_pytest/main.py:434: in _recurse
    ihook = self.gethookproxy(path)
_pytest/main.py:338: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
_pytest/config.py:348: in _getconftestmodules
    mod = self._importconftest(conftestpath)
_pytest/config.py:387: in _importconftest
    self.consider_conftest(mod)
_pytest/config.py:410: in consider_conftest
    self.register(conftestmodule, name=conftestmodule.__file__)
_pytest/config.py:261: in register
    self.consider_module(plugin)
_pytest/config.py:416: in consider_module
    self._import_plugin_specs(getattr(mod, 'pytest_plugins', []))
_pytest/config.py:421: in _import_plugin_specs
    self.import_plugin(import_spec)
_pytest/config.py:450: in import_plugin
    self.register(mod, modname)
_pytest/config.py:255: in register
    ret = super(PytestPluginManager, self).register(plugin, name)
pluggy/__init__.py:254: in register
    hook._maybe_apply_history(hookimpl)
pluggy/__init__.py:650: in _maybe_apply_history
    res = self._hookexec(self, [method], kwargs)
pluggy/__init__.py:222: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
pluggy/__init__.py:216: in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
astropy/extern/plugins/pytest_doctestplus/plugin.py:56: in pytest_configure
    (config.getini('doctest_plus') or config.option.doctest_plus)):
E   AttributeError: 'Namespace' object has no attribute 'doctest_plus'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================== 1 error in 42.08 seconds ===========================================================
Failed: unit failure (2)
----------------------------------------------------------------------
Skipping backend pyside, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend pyglet, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend glfw, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend sdl2, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend wx, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend egl, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend osmesa, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Running tests with ipynb_webgl backend:
_VISPY_TESTING_APP=ipynb_webgl   -m vispy_app_test /mnt/lustre/hexindong/anaconda2/lib/python2.7/site-packages/vispy
============================================================= test session starts =============================================================
platform linux2 -- Python 2.7.15, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /mnt/lustre/hexindong/anaconda2/lib/python2.7/site-packages, inifile:
collected 0 items / 1 errors                                                                                                                  

=================================================================== ERRORS ====================================================================
______________________________________________________________ ERROR collecting  ______________________________________________________________
py/_path/common.py:377: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
py/_path/common.py:419: in gen
    if p.check(dir=1) and (rec is None or rec(p))])
_pytest/main.py:434: in _recurse
    ihook = self.gethookproxy(path)
_pytest/main.py:338: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
_pytest/config.py:348: in _getconftestmodules
    mod = self._importconftest(conftestpath)
_pytest/config.py:387: in _importconftest
    self.consider_conftest(mod)
_pytest/config.py:410: in consider_conftest
    self.register(conftestmodule, name=conftestmodule.__file__)
_pytest/config.py:261: in register
    self.consider_module(plugin)
_pytest/config.py:416: in consider_module
    self._import_plugin_specs(getattr(mod, 'pytest_plugins', []))
_pytest/config.py:421: in _import_plugin_specs
    self.import_plugin(import_spec)
_pytest/config.py:450: in import_plugin
    self.register(mod, modname)
_pytest/config.py:255: in register
    ret = super(PytestPluginManager, self).register(plugin, name)
pluggy/__init__.py:254: in register
    hook._maybe_apply_history(hookimpl)
pluggy/__init__.py:650: in _maybe_apply_history
    res = self._hookexec(self, [method], kwargs)
pluggy/__init__.py:222: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
pluggy/__init__.py:216: in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
astropy/extern/plugins/pytest_doctestplus/plugin.py:56: in pytest_configure
    (config.getini('doctest_plus') or config.option.doctest_plus)):
E   AttributeError: 'Namespace' object has no attribute 'doctest_plus'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================== 1 error in 13.60 seconds ===========================================================
Failed: unit failure (2)
----------------------------------------------------------------------
Skipping backend _test, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Running tests with no backend:
_VISPY_TESTING_APP=nobackend   -m "not vispy_app_test" /mnt/lustre/hexindong/anaconda2/lib/python2.7/site-packages/vispy
============================================================= test session starts =============================================================
platform linux2 -- Python 2.7.15, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /mnt/lustre/hexindong/anaconda2/lib/python2.7/site-packages, inifile:
collected 0 items / 1 errors                                                                                                                  

=================================================================== ERRORS ====================================================================
______________________________________________________________ ERROR collecting  ______________________________________________________________
py/_path/common.py:377: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
py/_path/common.py:419: in gen
    if p.check(dir=1) and (rec is None or rec(p))])
_pytest/main.py:434: in _recurse
    ihook = self.gethookproxy(path)
_pytest/main.py:338: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
_pytest/config.py:348: in _getconftestmodules
    mod = self._importconftest(conftestpath)
_pytest/config.py:387: in _importconftest
    self.consider_conftest(mod)
_pytest/config.py:410: in consider_conftest
    self.register(conftestmodule, name=conftestmodule.__file__)
_pytest/config.py:261: in register
    self.consider_module(plugin)
_pytest/config.py:416: in consider_module
    self._import_plugin_specs(getattr(mod, 'pytest_plugins', []))
_pytest/config.py:421: in _import_plugin_specs
    self.import_plugin(import_spec)
_pytest/config.py:450: in import_plugin
    self.register(mod, modname)
_pytest/config.py:255: in register
    ret = super(PytestPluginManager, self).register(plugin, name)
pluggy/__init__.py:254: in register
    hook._maybe_apply_history(hookimpl)
pluggy/__init__.py:650: in _maybe_apply_history
    res = self._hookexec(self, [method], kwargs)
pluggy/__init__.py:222: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
pluggy/__init__.py:216: in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
astropy/extern/plugins/pytest_doctestplus/plugin.py:56: in pytest_configure
    (config.getini('doctest_plus') or config.option.doctest_plus)):
E   AttributeError: 'Namespace' object has no attribute 'doctest_plus'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=========================================================== 1 error in 4.10 seconds ===========================================================
Failed: unit failure (2)
Skipping example test: Cannot test examples unless in vispy git directory
Running line endings check... 
Passed

Skipping flake8 test, flake8 not installed
Passed

Testing failed (['pyqt5', 'ipynb_webgl', 'nobackend'] failed, ['pyqt4', 'pyside', 'pyglet', 'glfw', 'sdl2', 'wx', 'egl', 'osmesa', '_test', 'examples'] skipped) in 103.956 seconds
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/lustre/hexindong/anaconda2/lib/python2.7/site-packages/vispy/testing/_runners.py", line 445, in test
    raise RuntimeError('FAILURE')
RuntimeError: FAILURE

**Comment by Super-Tree** [comment]
here is part of gpu info:

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.90                 Driver Version: 384.90                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN Xp            On   | 00000000:04:00.0 Off |                  N/A |
| 26%   45C    P2    60W / 250W |   1651MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by kmuehlbauer** [comment]
@Super-Tree How did you install `VisPy`? For the testing machinery to work correctly, you need to install `pytest`/`pytest-cov` and maybe some more packages. Unfortunately this is not reflected in the docs atm.

I'm not really sure why the `astropy` bundled `doctest_plugin` shows up in the error message.

To work in headless mode you would need to run something like `xvfb` to get the images rendered.

**Comment by kmuehlbauer** [comment]
@Super-Tree Is this still an issue for you? Could this be closed?

**Comment by hubert0527** [comment]
I had the same issue, and by install xvfb with `apt-get install xvfb`, then setup the environment with:
```
Xvfb :1 -screen 0 1024x768x24 2>&1 >/dev/null &
export DISPLAY=:0.0
```
I can run vispy remotely with headless mode now.

**Comment by asnt** [comment]
Note: This can be automated and shortened with
```bash
$ xvfb-run --auto-servernum COMMAND
# Or, in short form:
$ xvfb-run -a COMMAND
```
where `COMMAND` is the program to run, e.g. `python my_vispy_script.py`.

**Comment by asnt** [comment]
@djhoese Not sure at all, but Xvfb seems to have been part of the X server for a long time, originally for testing purposes it seems.
Indeed, an entry in the FAQ you started would be useful.
Also, we should try to clarify the usage of the osmesa/egl backends. (Which are alternatives to Xvfb, right?)

**Comment by djhoese** [comment]
> (Which are alternatives to Xvfb, right?)

I don't know if I'd say alternatives, but they can be used for a similar purpose. Obviously those backends are backends and Xvfb is just hiding the fact that there isn't a real/physical display.

**Comment by Super-Tree** [comment]
I try this command`xvfb-run --auto-servernum python3 vispy_gen.py` on my Server which has no display, I meet an error
  vis xvfb-run --auto-servernum python3 vispy_gen.py

Traceback (most recent call last):
  File "vispy_gen.py", line 8, in <module>
    canvas=vispy.scene.SceneCanvas(title="name", keys='interactive', show=False)
  File "/home/xindong.he/.local/lib/python3.8/site-packages/vispy/scene/canvas.py", line 134, in __init__
    super(SceneCanvas, self).__init__(
  File "/home/xindong.he/.local/lib/python3.8/site-packages/vispy/app/canvas.py", line 205, in __init__
    self.create_native()
  File "/home/xindong.he/.local/lib/python3.8/site-packages/vispy/app/canvas.py", line 222, in create_native
    self._app.backend_module.CanvasBackend(self, **self._backend_kwargs)
  File "/home/xindong.he/.local/lib/python3.8/site-packages/vispy/app/backends/_egl.py", line 161, in __init__
    self._native_config = egl.eglChooseConfig(_EGL_DISPLAY, attribs)[0]
  File "/home/xindong.he/.local/lib/python3.8/site-packages/vispy/ext/egl.py", line 295, in eglChooseConfig
    raise RuntimeError('Could not find any suitable config.')
RuntimeError: Could not find any suitable config.

**Comment by djhoese** [comment]
I really don't know anything about EGL. @asnt might know, but I think he's busy right now. Have you read the new FAQ question about this: https://vispy.org/faq.html#egl

There may also be information from the documentation on the function that is failing: https://www.khronos.org/registry/EGL/sdk/docs/man/html/eglChooseConfig.xhtml

My understanding from what @asnt wrote in the FAQ is that you should either use xvfb **or** EGL. Not both. Not sure if that is a problem though.
