### ISSUE TITLE
Change markers color

### ISSUE THREAD

**Issue by JoeXinfa** [vispy/vispy#1537]
```
>>> from vispy.plot import Fig
>>> fig = Fig()
>>> ax = fig[0, 0]
>>> data = [[0,0], [1,1]]
>>> markers = ax.plot(data, symbol='o', width=0, edge_color=None, face_color='r')
>>> markers.set_data(face_color='b')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joe/anaconda3/lib/python3.5/site-packages/vispy/visuals/line_plot.py", line 126, in set_data
    self._markers.set_data(pos=pos, **marker_kwargs)
  File "/home/joe/anaconda3/lib/python3.5/site-packages/vispy/visuals/markers.py", line 534, in set_data
    pos.ndim == 2 and pos.shape[1] in (2, 3))
AssertionError
```

**Comment by djhoese** [comment]
It looks like `set_data` requires you to provide the position data (`pos`) regardless of whether it has changed or not. Since it doesn't hold on to the original `pos` array you'll have to do that yourself. I'd be open to pull requests that change this but I wouldn't be surprised if there are reasons the original position isn't held on to.

Side note: If you have any choice you should move to python 3.6 or 3.7 as conda-forge (the conda channel where vispy is coming from) is dropping the builds for python 3.5 very very soon if not already.

**Comment by JoeXinfa** [comment]
Thanks @djhoese . I saw that. The `set_data` method has `pos=None` in arguments but requires it inside, which is conflicting.

The 2nd issue is that it reverts to other defaults. Try the snippet below. The last line, which intends to update the face color only, also changes the symbol and edge color to the keyword argument defaults. In my app, I have to supply all the arguments when I just need change one.

```
>>> from vispy.plot import Fig
>>> import numpy as np
>>> fig = Fig()
>>> ax = fig[0, 0]
>>> data = np.array([[0,0], [1,1]])
>>> line = ax.plot(data, symbol='+', width=0, edge_color=None, face_color='r')
>>> line._markers.set_data(pos=data, face_color='g')
```

I will think about how to make a PR on this, but it may take some time as I'm a newbie. I hope someone more experienced is interested in this. Thanks in advance.

**Comment by djhoese** [comment]
Make sure any testing you do is based on the github master as things in the Markers/MeshVisuals may have changed recently.
