### ISSUE TITLE
Image re-draw failed

### ISSUE THREAD

**Issue by thomasdeneux** [vispy/vispy#1540]
Hello, i have many elements in a single canvas, including a 700x350 ImageVisual. I get the following error when the canvas is being redrawn upon call to its `update` method (which calls `on_draw` which calls the image `draw` method, see below: `self.img_ab.draw()`). 

Any idea what this can be??!!

Note that the error happens most of the time, but is not systematic.

```
WARNING: Error drawing visual <vispy.visuals.image.ImageVisual object at 0x0000024B7ECA0278>
WARNING: Traceback (most recent call last):
  File "E:/Users/Thomas/Python/Naivia/AlphaI/Main_Server.py", line 227, in <module>
    app.run()
  File "E:\Users\Thomas\Python\external\vispy\vispy\app\_default_app.py", line 62, in run
    return default_app.run()
  File "E:\Users\Thomas\Python\external\vispy\vispy\app\application.py", line 152, in run
    return self._backend._vispy_run()
  File "E:\Users\Thomas\Python\external\vispy\vispy\app\backends\_qt.py", line 237, in _vispy_run
    return app.exec_()
  File "E:\Users\Thomas\Python\external\vispy\vispy\app\backends\_qt.py", line 448, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "E:\Users\Thomas\Python\external\vispy\vispy\app\backends\_qt.py", line 448, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "E:\Users\Thomas\Python\external\vispy\vispy\app\backends\_qt.py", line 720, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "E:\Users\Thomas\Python\external\vispy\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "E:\Users\Thomas\Python\external\vispy\vispy\util\event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "E:\Users\Thomas\Python\external\vispy\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "E:\Users\Thomas\Python\Naivia\AlphaI\GUI\Widget.py", line 129, in on_draw
    widget.draw()
  File "E:\Users\Thomas\Python\Naivia\AlphaI\GUI\Input.py", line 94, in draw
    self.img_ab.draw()
  File "E:\Users\Thomas\Python\external\vispy\vispy\visuals\visual.py", line 440, in draw
    self._vshare.index_buffer)
  File "E:\Users\Thomas\Python\external\vispy\vispy\visuals\shaders\program.py", line 77, in draw
    Program.draw(self, *args, **kwargs)
  File "E:\Users\Thomas\Python\external\vispy\vispy\gloo\program.py", line 470, in draw
    canvas.context.flush_commands()
  File "E:\Users\Thomas\Python\external\vispy\vispy\gloo\context.py", line 171, in flush_commands
    self.glir.flush(self.shared.parser)
  File "E:\Users\Thomas\Python\external\vispy\vispy\gloo\glir.py", line 232, in flush
    self._shared.flush(parser)
  File "E:\Users\Thomas\Python\external\vispy\vispy\gloo\glir.py", line 146, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "E:\Users\Thomas\Python\external\vispy\vispy\gloo\glir.py", line 477, in parse
    self._parse(command)
  File "E:\Users\Thomas\Python\external\vispy\vispy\gloo\glir.py", line 439, in _parse
    ob.draw(*args)
  File "E:\Users\Thomas\Python\external\vispy\vispy\gloo\glir.py", line 935, in draw
    gl.glDrawArrays(mode, first, count)
  File "E:\Users\Thomas\Python\external\vispy\vispy\gloo\gl\_gl2.py", line 415, in glDrawArrays
    nativefunc(mode, first, count)
OSError: exception: access violation reading 0x0000000000000000
ERROR: Invoking <bound method WidgetsCanvas.on_draw of <WidgetsCanvas (PyQt5) at 0x24b7e873cf8>> for DrawEvent
```

**Comment by djhoese** [comment]
Are you able to reproduce this with just the ImageVisual? My guess would be either a PyQt5 issue, OpenGL library issue, or something else I'm not sure of. I don't think I've ever seen this before and the fact that it is such a low-level error makes me think there isn't anything we can do.

You could try doing just a single ImageVisual and see if you can reproduce it. Or try using PyQt4 as a test to see if that fixes it. Or try using the branch in this PR to use the new PyQt5 GL API: https://github.com/vispy/vispy/pull/1394

If any of that fixes things, let me know.

**Comment by thomasdeneux** [comment]
@djhoese Thanks, I am currently working on making a standalone version of the bug, but it is definitely a complex one: it happens only when another specific graphic element is also present on the canvas: a collection of lines for which i wrote my own shaders (very simple ones by the way). I will post it once i've made it. But i will also try this PR you point at me.

**Comment by djhoese** [comment]
I should have mentioned, if not obvious, the mentioned PR is the future of the PyQt5 backend. I've just had a lot of trouble getting all of the unit tests passing for it including getting `vispy.sys_info()` to print usable information when no widget is shown.

**Comment by thomasdeneux** [comment]
Sure. I just tried it but it did not help, so i switch back to the master branch and continue my work on simplifying the program that reproduces the bug.

**Comment by thomasdeneux** [comment]
The problem might be related to having 2 different canvas. I was making sure that the canvases `on_draw` and `on_resize` functions start by `self.set_current()`, but this was not enough. At the end i could work out the but by putting all my displays inside a single canvas, but this is not ideal.

**Comment by djhoese** [comment]
It should be possible to have two canvases that behave separately. If you need two views of the same canvas then that is possible too. There are examples of both in the repository examples. You just need to make sure that you address the canvases separately.

**Comment by kmuehlbauer** [comment]
@djhoese I'm not sure if two views of the same canvas is possible. The one example supposed to show this is broken AFAIK. I remember a comment where @campagnola was describing how that can be achieved. I did not find it yet. I'm also interested in this if it works.

**Comment by kmuehlbauer** [comment]
@djhoese Found the issue concerning two views of the same canvas: https://github.com/vispy/vispy/issues/1124

**Comment by kmuehlbauer** [comment]
Seems as a dup of #1124. Please reopen, if needed.
