### ISSUE TITLE
Error when removing a gloo program

### ISSUE THREAD

**Issue by thomasdeneux** [vispy/vispy#1611]
I am struggling with the removal of a gloo program. After reducing the code to the minimum that reproduces the problem, it looks like that:
- a canvas displays 2 programs, each of them simply draws one black triangle
- some time later one of the 2 programs is removed (link to it is set to None, will not be drawn any more)
- on the second next canvas redraw an OSError is raised, access violation reading

Note that:
- this bug appears only when there is a second attribute to the second program (called 'a_dummy' here), even it has no effect on the display
- unfortunately this bugs occurs only on my Windows machine, but not on my linux machine, so i am afraid that it is configuration dependent and will not reproduce for everyone

Code:
```
import numpy as np
from vispy import app, gloo

# vispy backend
v_app = app.use_app('PyQt5')


VERT_SHADER1 = """
attribute vec2 a_position;
void main() {
    gl_Position = vec4(a_position, 0., 1.);
}
"""

VERT_SHADER2 = """
attribute vec2 a_position;
attribute float a_dummy;

void main() {
    if (a_dummy > 0)
        gl_Position = vec4(a_position, 0., 1.);
    else
        gl_Position = vec4(a_position, 0., 1.);
}
"""

FRAG_SHADER = """
void main() {
    int integer_part;
    gl_FragColor = vec4(0., 0., 0., 1.);
}
"""


class TestCanvas(app.Canvas):

    # Constructor
    def __init__(self):
        super(TestCanvas, self).__init__()

        # Program1 = will stand
        self.program1 = gloo.Program(VERT_SHADER1, FRAG_SHADER)
        pos1 = np.array([[0, 0], [0, -1], [-1, 0]], dtype=np.float32)
        self.program1['a_position'] = pos1

        # Program2 = will be drawn once, then will be removed
        self.program2 = gloo.Program(VERT_SHADER2, FRAG_SHADER)
        pos2 = np.array([[0, 0], [0, 1], [1, 0]], dtype=np.float32)
        dummy = np.zeros(3, dtype=np.float32)
        self.program2['a_position'] = pos2
        self.program2['a_dummy'] = dummy

    def _remove_program2(self):
        del self.program2
        self.program2 = None

    # Canvas events
    def on_draw(self, ev=None):
        gloo.clear('white')

        # Display image
        print('draw program1')
        self.program1.draw()

        if self.program2:
            print('draw program2')
            self.program2.draw()


canvas = TestCanvas()
canvas.show()

v_app.sleep(.5)
canvas._remove_program2()
canvas.update()

v_app.sleep(.5)
canvas.update()


# Run the event loop
app.run()
```

Error:
```
draw program1
draw program2
draw program1
draw program2
draw program1
draw program1
WARNING: Traceback (most recent call last):
  File "E:/Users/Thomas/Python/Naivia/AlphaI/test.py", line 82, in <module>
    app.run()
  File "E:\Users\Thomas\Python\external\vispy\vispy\app\_default_app.py", line 62, in run
    return default_app.run()
  File "E:\Users\Thomas\Python\external\vispy\vispy\app\application.py", line 152, in run
    return self._backend._vispy_run()
  File "E:\Users\Thomas\Python\external\vispy\vispy\app\backends\_qt.py", line 272, in _vispy_run
    return app.exec_()
  File "E:\Users\Thomas\Python\external\vispy\vispy\app\backends\_qt.py", line 501, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "E:\Users\Thomas\Python\external\vispy\vispy\app\backends\_qt.py", line 501, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "E:\Users\Thomas\Python\external\vispy\vispy\app\backends\_qt.py", line 818, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "E:\Users\Thomas\Python\external\vispy\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "E:\Users\Thomas\Python\external\vispy\vispy\util\event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "E:\Users\Thomas\Python\external\vispy\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "E:/Users/Thomas/Python/Naivia/AlphaI/test.py", line 63, in on_draw
    self.program1.draw()
  File "E:\Users\Thomas\Python\external\vispy\vispy\gloo\program.py", line 470, in draw
    canvas.context.flush_commands()
  File "E:\Users\Thomas\Python\external\vispy\vispy\gloo\context.py", line 176, in flush_commands
    self.glir.flush(self.shared.parser)
  File "E:\Users\Thomas\Python\external\vispy\vispy\gloo\glir.py", line 232, in flush
    self._shared.flush(parser)
  File "E:\Users\Thomas\Python\external\vispy\vispy\gloo\glir.py", line 146, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "E:\Users\Thomas\Python\external\vispy\vispy\gloo\glir.py", line 478, in parse
    self._parse(command)
  File "E:\Users\Thomas\Python\external\vispy\vispy\gloo\glir.py", line 440, in _parse
    ob.draw(*args)
  File "E:\Users\Thomas\Python\external\vispy\vispy\gloo\glir.py", line 936, in draw
    gl.glDrawArrays(mode, first, count)
  File "E:\Users\Thomas\Python\external\vispy\vispy\gloo\gl\_gl2.py", line 415, in glDrawArrays
    nativefunc(mode, first, count)
OSError: exception: access violation reading 0x0000000000000000
ERROR: Invoking <bound method TestCanvas.on_draw of <TestCanvas (PyQt5) at 0x227b4c2fd30>> for DrawEvent

Process finished with exit code -1073741819 (0xC0000005)
```

**Comment by djhoese** [comment]
This is a little odd. I'm not sure I've ever tested this with PyQt5 but I have an application that I create for my work that creates visuals and the user can delete them later. It was using PyQt4 on Mac, Windows, and Linux and I never saw this issue. It now uses PyQt5 but hasn't been as heavily tested yet.

I double checked and I don't think there is anything special in `Program` or in the `Visual`s API that handles garbage collection in any special way. We could possibly be more careful about deleting things, but I'm not sure it is in our control all the time.

Do you think you could try this with PyQt4? Or what if you use conda/conda-forge for your installation? What version of vispy are you using?

**Comment by thomasdeneux** [comment]
Hello, i am on an Anaconda distribution of python 3.6.7. PyQt5 came with this distribution, i don't have PyQt4, but in general i would not go back to PyQt4 for my program (though i understand it could be worth checking if the error still happens with PyQt4).

If i keep the program and just stop displaying it, the error stops.
```
    def _remove_program2(self):
        self._keep_it_alive = self.program2
        self.program2 = None
```

This means that some specific garbage collection action causes the error (probably by removing some ressources also necessary to program1).

It could be a solution for me to keep pointers on the programs which i don't want to display (basically each program is an image, the number of them varies during the course of using the program, a previous program for an image which is not displayed any more can be recycled for a new image). But it is not very satisfying to do like this.

Any way to further investigate on this?

**Comment by djhoese** [comment]
How did you install vispy? The current master branch has major changes to the PyQt5 backend. It would be good to test using this version of the code.

Another thing you could try is to try to do the equivalent with the Scene API and Visual objects (ImageVisuals perhaps?). If you remove an image visual (`my_img.parent = None`) I'd be curious if it behaves better.

**Comment by thomasdeneux** [comment]
Yes i forgot to answer the question: i am using the very latest version of vispy master (i just pulled and still have the error).
I will try later what to suggest with removing Visual objects in the Scence API. But note that it is well possible that removing visuals does not cause error: the error i got is very specific to some custom displays i program with gloo (when i said "basically each program is an image", in reality it is more than just an image): for example if removing the lines relating to `a_dummy` in `VERT_SHADER2`, the error disappears.

**Comment by codypiersall** [comment]
Whenever I run this example code, I'm not getting an exception.  This is Win 10.  That doesn't mean there's not a bug, just that I can't reproduce it.  Do you get this exception every time you run it?

**Comment by thomasdeneux** [comment]
Yes i get the exception systematically, but as i said i don't get it on a second computer with linux. I could indeed try to upgrade python / PyQt5 / other toolboxes, yet i will first continue debugging and check whether there is one specific vispy garbage collection instruction that is the cause for the problem.
