### ISSUE TITLE
Vispy load glsl path incorrectly when run Pyinstaller released app in .exe

### ISSUE THREAD

**Issue by gitzhzhg** [vispy/vispy#1643]
I use PyQt5 and Vispy on Windows. I can run my desktop app successfully in debug mode using VS Code, however, when I tried to use Pyinstaller to release the app as a single xx.exe, the .exe file cannot run correctly and prompted the error below:
```
lines/agg.vert
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\zhao\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "package\app.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\zhao\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "package\gui\mainwindow.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\zhao\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "package\gui\canvas3d.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\zhao\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\vispy\scene\__init__.py", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\zhao\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\vispy\scene\visuals.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\zhao\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\vispy\visuals\__init__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\zhao\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\vispy\visuals\axis.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\zhao\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\vispy\visuals\line\__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\zhao\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\vispy\visuals\line\line.py", line 388, in <module>
  File "site-packages\vispy\visuals\line\line.py", line 397, in _AggLineVisual
  File "site-packages\vispy\glsl\__init__.py", line 40, in get

  File "site-packages\vispy\glsl\__init__.py", line 27, in find
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\WINDOWS\\TEMP\\_MEI134802\\vispy\\glsl'
[844] Failed to execute script main
```

The above indicated that vispy.glsl installed or loaded in 'C:\\WINDOWS\\TEMP\\_MEI134802\\vispy\\glsl', but actually, I installed vispy in 'C:\Users\ZHAO\AppData\Local\Programs\Python\Python37\Lib\site-packages\vispy'. When I run the app via VS code, it can finds the site-package path and function correctly. I'm not sure why in rutime Vispy need to find glsl in 'C:\\WINDOWS\\TEMP\\.

The code trying to import vispy is here:
```
from vispy.scene import SceneCanvas
from vispy.scene.visuals import Markers, Line, XYZAxis
from vispy.visuals.filters import Clipper, Alpha, ColorFilter
from vispy.visuals.transforms import STTransform, MatrixTransform
```

My system info is as below:
```
44 INFO: PyInstaller: 3.4
44 INFO: Python: 3.7.1
45 INFO: Platform: Windows-10-10.0.17134-SP0, with NVIDIA QUADRO M4000 

vispy.sys_info()
Platform: Windows-10-10.0.17134-SP0
Python:   3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)]
NumPy:    1.15.4
Backend:  PyQt5
pyqt4:    None
pyqt5:    ('PyQt5', '5.12.2', '5.12.3')
pyside:   None
pyglet:   None
glfw:     None
sdl2:     None
wx:       None
egl:      None
osmesa:   None
_test:    None

GL version:  '4.6.0 NVIDIA 388.16'
```
Any one can help me out this? Much appreciated for your help.

**Comment by djhoese** [comment]
`vispy` is not officially supported by pyinstaller the last time I checked. However, I have a large GUI application that I distribute using pyinstaller that also uses vispy. I haven't had time to add an official hook to pyinstaller. You can find the important part of my spec file below:

1. Vispy data files: https://github.com/ssec/sift/blob/master/sift.spec#L17-L18
2. Vispy hidden imports: https://github.com/ssec/sift/blob/master/sift.spec#L28-L29

I think everything else in the spec file is for handling other packages. Hopefully this helps you a little bit.

**Comment by gitzhzhg** [comment]
> `vispy` is not officially supported by pyinstaller the last time I checked. However, I have a large GUI application that I distribute using pyinstaller that also uses vispy. I haven't had time to add an official hook to pyinstaller. You can find the important part of my spec file below:
> 
> 1. Vispy data files: https://github.com/ssec/sift/blob/master/sift.spec#L17-L18
> 2. Vispy hidden imports: https://github.com/ssec/sift/blob/master/sift.spec#L28-L29
> 
> I think everything else in the spec file is for handling other packages. Hopefully this helps you a little bit.

@djhoese  Thanks a lot mate. Yes, I did find a solution from your sift.spec and my app now can be released and run successfully.  Here're the correct main.spec I modified based on your suggestions, it did solve the glsl issue and backends._pyqt5 issue too.
```
# -*- mode: python -*-
import sys
from PyInstaller.compat import is_win, is_darwin, is_linux
from PyInstaller.utils.hooks import collect_submodules
import vispy.glsl
import vispy.io
import distributed


block_cipher = None

data_files = [
    (os.path.dirname(vispy.glsl.__file__), os.path.join("vispy", "glsl")),
    (os.path.join(os.path.dirname(vispy.io.__file__), "_data"), os.path.join("vispy", "io", "_data")),
    (os.path.join(os.path.dirname(distributed.__file__)), 'distributed'),
]

hidden_imports = [
    "vispy.ext._bundled.six",
    "vispy.app.backends._pyqt5",
    "sqlalchemy.ext.baked"
    
]

if is_win:
    hidden_imports += collect_submodules("encodings")

a = Analysis(['main.py'],
             pathex=['C:\\DeepListen'],
             binaries=[],
             datas=data_files,
             hiddenimports=hidden_imports,
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='main',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True , icon='logo.ico')
```
For comparison purposes, i would also like to post the malfuction old main.spec as below, which has no hidden imports specified. 
```
# -*- mode: python -*-

block_cipher = None


a = Analysis(['main.py'],
             pathex=['C:\\DeepListen'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='main',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=False , icon='logo.ico')

```

**Comment by shlomok613** [comment]
This solution works well for vispy 0.5.3 but fails for 0.6.0 due to missing freetype

I have tried adding it to the hidden_imports but I get a crash. Can anybody help?

**Comment by djhoese** [comment]
@shlomok613 Dang, I didn't even think about pyinstaller when we removed freetype as an external dependency. Have you tried installing the `freetype-py` package and listing that as a dependency? If I recall correctly, pyinstaller was using vispy's `load_library('freetype')` to know that it needed to be bundled. We just need to find a way to do the same with freetype-py.

**Comment by shlomok613** [comment]
Thanks for you quick response.I am still a beginner WRT to pyinstaller. I have a few questions:
1. How exactly do I list it as a dependency. I tried importing it and adding to the list of hidden imports but I have a problem on initialization.
2. I think that for windows the filename for load_library should be libfreetype.

Please could show me a more detailed example.

**Comment by djhoese** [comment]
You mentioned you tried adding a hidden import, what happens if you specify `freetype` as a hidden import? This should find the python `freetype-py` library and hopefully see the `load_library` call here: https://github.com/rougier/freetype-py/blob/master/freetype/raw.py#L39

This assumes that vispy is running for you normally already before pyinstaller'ing it.

**Comment by shlomok613** [comment]
here is is what I tried:
import sys
from PyInstaller.compat import is_win, is_darwin, is_linux
from PyInstaller.utils.hooks import collect_submodules,collect_dynamic_libs
import vispy.glsl
import vispy.io
import freetype

block_cipher = None

data_files = [
    (os.path.dirname(vispy.glsl.__file__), os.path.join("vispy", "glsl")),
    (os.path.join(os.path.dirname(vispy.io.__file__), "_data"), os.path.join("vispy", "io", "_data")),
    (os.path.dirname(freetype.__file__), os.path.join("freetype")),
]

hidden_imports = [
    "vispy.ext._bundled.six",
    "vispy.app.backends._wx",
    "freetype"
]

if is_win:
    hidden_imports += collect_submodules("encodings")

Here is what I got when I ran my program:

 File "site-packages\vispy\visuals\text\text.py", line 95, in _load_char
  File "site-packages\vispy\util\fonts\_freetype.py", line 50, in _load_glyph
  File "site-packages\vispy\util\fonts\_freetype.py", line 37, in _load_font
  File "site-packages\freetype\__init__.py", line 991, in __init__
freetype.ft_errors.FT_Exception: FT_Exception:  (cannot open resource)

Any ideas?

**Comment by djhoese** [comment]
I updated your comment to add three back ticks (`) before and after each block to format them more clearly.

You get this exception when you are running the frozen application? Does your program/script run before freezing it? Do you have freetype (the C library) installed? Do you see warnings about not finding the freetype library when freezing (running pyinstaller) your application?

**Comment by shlomok613** [comment]
You get this exception when you are running the frozen application?
Yes
Does your program/script run before freezing it? 
Yes
Do you have freetype (the C library) installed? 
only the python freetype_py package

Do you see warnings about not finding the freetype library when freezing (running pyinstaller) your application?
No

I see libfreetype dll in EXE-00.toc as
```('freetype\\libfreetype.dll',
   'c:\\users\\owner\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\freetype\\libfreetype.dll',
   'DATA'),```

**Comment by djhoese** [comment]
Is there a hard reason for why you are using the 32-bit version of python? Have you tried the 64-bit version? I don't think this should be a huge problem based on what I see from `freetype-py` but it is something I've never dealt with.

I should also note I have not tried using pyinstaller on the new version of vispy yet. There isn't much I can do from here. You'll have to see if the `.dll` is copied to your frozen application properly. We may also need to patch freetype-py when it is frozen or specify an environment variable to point it to the frozen freetype C .dll.

**Comment by shlomok613** [comment]
Now working. The vispy fonts weren't being included in the build.

I added this line to the data_files section of the spec file:

(os.path.dirname(vispy.util.__file__), os.path.join("vispy", "util")),

Here is my final spec file:

```
# -*- mode: python -*-
import sys
from PyInstaller.compat import is_win, is_darwin, is_linux
from PyInstaller.utils.hooks import collect_submodules,collect_dynamic_libs
import vispy.glsl
import vispy.io
import freetype

block_cipher = None

data_files = [
    (os.path.dirname(vispy.glsl.__file__), os.path.join("vispy", "glsl")),
    (os.path.join(os.path.dirname(vispy.io.__file__), "_data"), os.path.join("vispy", "io", "_data")),
    (os.path.dirname(vispy.util.__file__), os.path.join("vispy", "util")),
    (os.path.dirname(freetype.__file__), os.path.join("freetype")),
]

hidden_imports = [
    "vispy.ext._bundled.six",
    "vispy.app.backends._wx",
    "freetype"
]

if is_win:
    hidden_imports += collect_submodules("encodings")

a = Analysis(['vispyplot.py'],
             pathex=['C:\\sixdof\\telegraph2'],
             datas=data_files,
             hiddenimports=hidden_imports,
             binaries=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)

pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='vispyplot',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True)
```

**Comment by SestoAle** [comment]
Hi,

I am having a similar problem. I use vispy==0.9 and pyinstaller==4.3, changed .spec file like you did, but I got this error:

```
Traceback (most recent call last):
  File "/Users/alessandrosestini/miniconda3/envs/prova/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/Users/alessandrosestini/miniconda3/envs/prova/lib/python3.6/site-packages/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/alessandrosestini/miniconda3/envs/prova/lib/python3.6/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/alessandrosestini/miniconda3/envs/prova/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Users/alessandrosestini/miniconda3/envs/prova/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 684, in build
    exec(code, spec_namespace)
  File "main.spec", line 23, in <module>
    noarchive=False)
  File "/Users/alessandrosestini/miniconda3/envs/prova/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 242, in __init__
    self.__postinit__()
  File "/Users/alessandrosestini/miniconda3/envs/prova/lib/python3.6/site-packages/PyInstaller/building/datastruct.py", line 160, in __postinit__
    self.assemble()
  File "/Users/alessandrosestini/miniconda3/envs/prova/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 468, in assemble
    redirects=self.binding_redirects))
  File "/Users/alessandrosestini/miniconda3/envs/prova/lib/python3.6/site-packages/PyInstaller/depend/bindepend.py", line 226, in Dependencies
    for lib, npth in selectImports(pth, xtrapath):
  File "/Users/alessandrosestini/miniconda3/envs/prova/lib/python3.6/site-packages/PyInstaller/depend/bindepend.py", line 500, in selectImports
    dlls = getImports(pth)
  File "/Users/alessandrosestini/miniconda3/envs/prova/lib/python3.6/site-packages/PyInstaller/depend/bindepend.py", line 752, in getImports
    return _getImports_macholib(pth)
  File "/Users/alessandrosestini/miniconda3/envs/prova/lib/python3.6/site-packages/PyInstaller/depend/bindepend.py", line 630, in _getImports_macholib
    m = MachO(pth)
  File "/Users/alessandrosestini/miniconda3/envs/prova/lib/python3.6/site-packages/macholib/MachO.py", line 117, in __init__
    with open(filename, "rb") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'GLESv2.framework/GLESv2'
```

**Comment by Terminator-b777** [comment]
> 现在正在工作。vispy 字体未包含在构建中。
> 
> 我将这一行添加到 spec 文件的 data_files 部分：
> 
> （os.path.dirname（vispy.util.**file**）、os.path.join（“vispy”， “util”））、
> 
> 这是我的最终 spec 文件：
> 
> ```
> # -*- mode: python -*-
> import sys
> from PyInstaller.compat import is_win, is_darwin, is_linux
> from PyInstaller.utils.hooks import collect_submodules,collect_dynamic_libs
> import vispy.glsl
> import vispy.io
> import freetype
> 
> block_cipher = None
> 
> data_files = [
>     (os.path.dirname(vispy.glsl.__file__), os.path.join("vispy", "glsl")),
>     (os.path.join(os.path.dirname(vispy.io.__file__), "_data"), os.path.join("vispy", "io", "_data")),
>     (os.path.dirname(vispy.util.__file__), os.path.join("vispy", "util")),
>     (os.path.dirname(freetype.__file__), os.path.join("freetype")),
> ]
> 
> hidden_imports = [
>     "vispy.ext._bundled.six",
>     "vispy.app.backends._wx",
>     "freetype"
> ]
> 
> if is_win:
>     hidden_imports += collect_submodules("encodings")
> 
> a = Analysis(['vispyplot.py'],
>              pathex=['C:\\sixdof\\telegraph2'],
>              datas=data_files,
>              hiddenimports=hidden_imports,
>              binaries=[],
>              runtime_hooks=[],
>              excludes=[],
>              win_no_prefer_redirects=False,
>              win_private_assemblies=False,
>              cipher=block_cipher,
>              noarchive=False)
> 
> pyz = PYZ(a.pure, a.zipped_data,
>              cipher=block_cipher)
> exe = EXE(pyz,
>           a.scripts,
>           a.binaries,
>           a.zipfiles,
>           a.datas,
>           [],
>           name='vispyplot',
>           debug=False,
>           bootloader_ignore_signals=False,
>           strip=False,
>           upx=True,
>           runtime_tmpdir=None,
>           console=True)
> ```

i add this , but still raise error
'''  raise FT_Exception(error)
freetype.ft_errors.FT_Exception: FT_Exception:  (cannot open resource)'''

**Comment by djhoese** [comment]
@Terminator-b777 Please file a new issue with more details on your situation including a copy of your spec file. Also note that the line you said you copied is poorly formatted on github. It should be:

```
(os.path.dirname(vispy.util.__file__), os.path.join("vispy", "util")),
```

Note the double `_` around `file`.

**Comment by Terminator-b777** [comment]
'''
import sys
import numpy as np
from PyQt5 import QtWidgets
from vispy import  scene
from vispy.app import use_app

use_app('PyQt5')  
N = 500


class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.canvas = scene.SceneCanvas(keys='interactive', show=True)
        self.canvas.unfreeze()  
        self.canvas.create_native()
        self.canvas.native.setParent(self)
        self.main_widget = QtWidgets.QWidget(self)
        self.setCentralWidget(self.main_widget)
        layout = QtWidgets.QVBoxLayout(self.main_widget)
        layout.addWidget(self.canvas.native)
        button_layout = QtWidgets.QHBoxLayout()
        layout.addLayout(button_layout)
 
        grid = self.canvas.central_widget.add_grid(margin=10)
        self.xaxis = scene.AxisWidget(orientation='bottom')
        self.xaxis.height_max = 80
        grid.add_widget(self.xaxis, row=1, col=1)

if __name__ == '__main__':
    appQt = QtWidgets.QApplication(sys.argv)
    win = MainWindow()
    win.show()
    appQt.exec_()

WARNING: Traceback (most recent call last):
  File "ls.py", line 231, in <module>
  File "D:\YLC\work\osc\gup加速\dist\ls\_internal\vispy\app\backends\_qt.py", line 626, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "D:\YLC\work\osc\gup加速\dist\ls\_internal\vispy\app\backends\_qt.py", line 626, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "D:\YLC\work\osc\gup加速\dist\ls\_internal\vispy\app\backends\_qt.py", line 928, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "vispy\util\event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "vispy\util\event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  << caught exception here: >>
  File "vispy\util\event.py", line 469, in _invoke_callback
    cb(event)
  File "vispy\scene\canvas.py", line 219, in on_draw
    self._draw_scene()
  File "vispy\scene\canvas.py", line 278, in _draw_scene
    self.draw_visual(self.scene)
  File "vispy\scene\canvas.py", line 316, in draw_visual
    node.draw()
  File "vispy\scene\visuals.py", line 106, in draw
    self._visual_superclass.draw(self)
  File "vispy\visuals\visual.py", line 668, in draw
    v.draw()
  File "vispy\visuals\visual.py", line 668, in draw
    v.draw()
  File "vispy\visuals\visual.py", line 505, in draw
    if self._prepare_draw(view=self) is False:
  File "vispy\visuals\text\text.py", line 533, in _prepare_draw
    self._vertices = np.concatenate([
  File "vispy\visuals\text\text.py", line 534, in <listcomp>
    _text_to_vbo(t, self._font, self._anchors[0], self._anchors[1],
  File "vispy\visuals\text\text.py", line 264, in _text_to_vbo
    glyph = font[char]
  File "vispy\visuals\text\text.py", line 81, in __getitem__
    self._load_char(char)
  File "vispy\visuals\text\text.py", line 95, in _load_char
    _load_glyph(self._font, char, self._glyphs)
  File "vispy\util\fonts\_freetype.py", line 50, in _load_glyph
    flags = FT_LOAD_RENDER | FT_LOAD_NO_HINTING | FT_LOAD_NO_AUTOHINT
  File "vispy\util\fonts\_freetype.py", line 37, in _load_font
    fname = find_font(face, bold, italic)
  File "freetype\__init__.py", line 1192, in __init__
    raise FT_Exception(error)
'''
It works with code，but when I use Pyinstaller to package it I get this error

**Comment by Terminator-b777** [comment]
```

import sys
import numpy as np
from PyQt5 import QtWidgets
from vispy import  scene
from vispy.app import use_app


use_app('PyQt5') 
N = 500


class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.canvas = scene.SceneCanvas(keys='interactive', show=True)
        self.canvas.unfreeze()  
        self.canvas.create_native()
        self.canvas.native.setParent(self)
        self.main_widget = QtWidgets.QWidget(self)
        self.setCentralWidget(self.main_widget)
        layout = QtWidgets.QVBoxLayout(self.main_widget)
        layout.addWidget(self.canvas.native)
        button_layout = QtWidgets.QHBoxLayout()
        layout.addLayout(button_layout)
 
        grid = self.canvas.central_widget.add_grid(margin=10)
        self.xaxis = scene.AxisWidget(orientation='bottom')
        self.xaxis.height_max = 80
        grid.add_widget(self.xaxis, row=1, col=1)

if __name__ == '__main__':
    appQt = QtWidgets.QApplication(sys.argv)
    win = MainWindow()
    win.show()
    appQt.exec_()
```

```
WARNING: Traceback (most recent call last):
File "ls.py", line 231, in
File "D:\YLC\work\osc\gup加速\dist\ls_internal\vispy\app\backends_qt.py", line 626, in event
out = super(QtBaseCanvasBackend, self).event(ev)
File "D:\YLC\work\osc\gup加速\dist\ls_internal\vispy\app\backends_qt.py", line 626, in event
out = super(QtBaseCanvasBackend, self).event(ev)
File "D:\YLC\work\osc\gup加速\dist\ls_internal\vispy\app\backends_qt.py", line 928, in paintGL
self._vispy_canvas.events.draw(region=None)
File "vispy\util\event.py", line 453, in call
self._invoke_callback(cb, event)
File "vispy\util\event.py", line 471, in _invoke_callback
_handle_exception(self.ignore_callback_errors,
<< caught exception here: >>
File "vispy\util\event.py", line 469, in _invoke_callback
cb(event)
File "vispy\scene\canvas.py", line 219, in on_draw
self._draw_scene()
File "vispy\scene\canvas.py", line 278, in _draw_scene
self.draw_visual(self.scene)
File "vispy\scene\canvas.py", line 316, in draw_visual
node.draw()
File "vispy\scene\visuals.py", line 106, in draw
self._visual_superclass.draw(self)
File "vispy\visuals\visual.py", line 668, in draw
v.draw()
File "vispy\visuals\visual.py", line 668, in draw
v.draw()
File "vispy\visuals\visual.py", line 505, in draw
if self._prepare_draw(view=self) is False:
File "vispy\visuals\text\text.py", line 533, in _prepare_draw
self._vertices = np.concatenate([
File "vispy\visuals\text\text.py", line 534, in
_text_to_vbo(t, self._font, self._anchors[0], self._anchors[1],
File "vispy\visuals\text\text.py", line 264, in _text_to_vbo
glyph = font[char]
File "vispy\visuals\text\text.py", line 81, in getitem
self._load_char(char)
File "vispy\visuals\text\text.py", line 95, in _load_char
_load_glyph(self._font, char, self._glyphs)
File "vispy\util\fonts_freetype.py", line 50, in _load_glyph
flags = FT_LOAD_RENDER | FT_LOAD_NO_HINTING | FT_LOAD_NO_AUTOHINT
File "vispy\util\fonts_freetype.py", line 37, in load_font
fname = find_font(face, bold, italic)
File "freetype_init.py", line 1192, in init
raise FT_Exception(error)
```

It works with code，but when I use Pyinstaller to package it I get this error

**Comment by Terminator-b777** [comment]
```
import sys
import numpy as np
from PyQt5 import QtWidgets
from vispy import  scene
from vispy.app import use_app


use_app('PyQt5') 
N = 500


class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.canvas = scene.SceneCanvas(keys='interactive', show=True)
        self.canvas.unfreeze()  
        self.canvas.create_native()
        self.canvas.native.setParent(self)
        self.main_widget = QtWidgets.QWidget(self)
        self.setCentralWidget(self.main_widget)
        layout = QtWidgets.QVBoxLayout(self.main_widget)
        layout.addWidget(self.canvas.native)
        button_layout = QtWidgets.QHBoxLayout()
        layout.addLayout(button_layout)
 
        grid = self.canvas.central_widget.add_grid(margin=10)
        self.xaxis = scene.AxisWidget(orientation='bottom')
        self.xaxis.height_max = 80
        grid.add_widget(self.xaxis, row=1, col=1)

if __name__ == '__main__':
    appQt = QtWidgets.QApplication(sys.argv)
    win = MainWindow()
    win.show()
    appQt.exec_()
```
```
WARNING: Traceback (most recent call last):
  File "ls2.py", line 40, in <module>
  File "D:\YLC\work\osc\gup加速\dist\ls\_internal\vispy\app\backends\_qt.py", line 626, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "D:\YLC\work\osc\gup加速\dist\ls\_internal\vispy\app\backends\_qt.py", line 626, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "D:\YLC\work\osc\gup加速\dist\ls\_internal\vispy\app\backends\_qt.py", line 928, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "vispy\util\event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "vispy\util\event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  << caught exception here: >>
  File "vispy\util\event.py", line 469, in _invoke_callback
    cb(event)
  File "vispy\scene\canvas.py", line 219, in on_draw
    self._draw_scene()
  File "vispy\scene\canvas.py", line 278, in _draw_scene
    self.draw_visual(self.scene)
  File "vispy\scene\canvas.py", line 316, in draw_visual
    node.draw()
  File "vispy\scene\visuals.py", line 106, in draw
    self._visual_superclass.draw(self)
  File "vispy\visuals\visual.py", line 668, in draw
    v.draw()
  File "vispy\visuals\visual.py", line 668, in draw
    v.draw()
  File "vispy\visuals\visual.py", line 505, in draw
    if self._prepare_draw(view=self) is False:
  File "vispy\visuals\text\text.py", line 533, in _prepare_draw
    self._vertices = np.concatenate([
  File "vispy\visuals\text\text.py", line 534, in <listcomp>
    _text_to_vbo(t, self._font, self._anchors[0], self._anchors[1],
  File "vispy\visuals\text\text.py", line 264, in _text_to_vbo
    glyph = font[char]
  File "vispy\visuals\text\text.py", line 81, in __getitem__
    self._load_char(char)
  File "vispy\visuals\text\text.py", line 95, in _load_char
    _load_glyph(self._font, char, self._glyphs)
  File "vispy\util\fonts\_freetype.py", line 50, in _load_glyph
    flags = FT_LOAD_RENDER | FT_LOAD_NO_HINTING | FT_LOAD_NO_AUTOHINT
  File "vispy\util\fonts\_freetype.py", line 37, in _load_font
    fname = find_font(face, bold, italic)
  File "freetype\__init__.py", line 1192, in __init__
    raise FT_Exception(error)
freetype.ft_errors.FT_Exception: FT_Exception:  (cannot open resource)
```
It works with code，but when I use Pyinstaller to package it I get this error

**Comment by djhoese** [comment]
> a new issue

> including a copy of your spec file.

**Comment by Terminator-b777** [comment]
pyinstaller can run exe on other people's computers after packaging, but not on mine

**Comment by djhoese** [comment]
Please, file a new github issue for your problem @Terminator-b777. Include the pyinstaller spec file you have and any other relevant information (operating systems that work and don't work, python versions, vispy versions, etc).

I'm locking this conversation as my above requests don't seem to be understood.
