### ISSUE TITLE
Issue with simple_glut.py

### ISSUE THREAD

**Issue by mahmoodn** [vispy/vispy#1687]
While `pyopengl` has been installed via pip, I get the following error while running benchmark/simple_glut.py 

```
$ python simple_glut.py 
Traceback (most recent call last):
  File "simple_glut.py", line 37, in <module>
    glut.glutInit(sys.argv)
  File "/home/mahmood/.local/lib/python2.7/site-packages/OpenGL/GLUT/special.py", line 333, in glutInit
    _base_glutInit( ctypes.byref(count), holder )
  File "/home/mahmood/.local/lib/python2.7/site-packages/OpenGL/platform/baseplatform.py", line 407, in __call__
    self.__name__, self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling
```

**Comment by mahmoodn** [comment]
I installed `freeglut3-dev` via apt and re run again. I see that a black window is opened and the following lines are printed on terminal

```
FPS : 1073.57 (2685 frames in 2.50 second)
FPS : 1056.78 (2643 frames in 2.50 second)

```
Is that correct?

**Comment by djhoese** [comment]
No, based on the code in the example it isn't actually drawing anything. Just clearing the canvas and counting how long it is idle (not drawing).
