### ISSUE TITLE
Problem with geometry shader

### ISSUE THREAD

**Issue by cmoralesmx** [vispy/vispy#1715]
I am having the following errors while trying to execute the geometry shader [example](https://github.com/vispy/vispy/blob/master/examples/basics/gloo/geometry_shader.py)  
```
WARNING: Traceback (most recent call last):
  File "./vispy_example.py", line 79, in <module>
    app.run()
  File "/home/cmoralesmx/git/ev_diffusion_simpleVis/vispy_venv/lib/python3.6/site-packages/vispy/app/_default_app.py", line 62, in run
    return default_app.run()
  File "/home/cmoralesmx/git/ev_diffusion_simpleVis/vispy_venv/lib/python3.6/site-packages/vispy/app/application.py", line 152, in run
    return self._backend._vispy_run()
  File "/home/cmoralesmx/git/ev_diffusion_simpleVis/vispy_venv/lib/python3.6/site-packages/vispy/app/backends/_glfw.py", line 194, in _vispy_run
    self._vispy_process_events()
  File "/home/cmoralesmx/git/ev_diffusion_simpleVis/vispy_venv/lib/python3.6/site-packages/vispy/app/backends/_glfw.py", line 181, in _vispy_process_events
    glfw.glfwPollEvents()
  File "/home/cmoralesmx/git/ev_diffusion_simpleVis/vispy_venv/lib/python3.6/site-packages/vispy/app/backends/_glfw.py", line 410, in _on_draw
    self._vispy_canvas.events.draw(region=None)  # (0, 0, w, h))
  File "/home/cmoralesmx/git/ev_diffusion_simpleVis/vispy_venv/lib/python3.6/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/home/cmoralesmx/git/ev_diffusion_simpleVis/vispy_venv/lib/python3.6/site-packages/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/home/cmoralesmx/git/ev_diffusion_simpleVis/vispy_venv/lib/python3.6/site-packages/OpenGL/latebind.py", line 41, in __call__
    return self._finalCall( *args, **named )
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cmoralesmx/git/ev_diffusion_simpleVis/vispy_venv/lib/python3.6/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "./vispy_example.py", line 74, in on_draw
    self.program.draw('points')
  File "/home/cmoralesmx/git/ev_diffusion_simpleVis/vispy_venv/lib/python3.6/site-packages/vispy/gloo/program.py", line 533, in draw
    canvas.context.flush_commands()
  File "/home/cmoralesmx/git/ev_diffusion_simpleVis/vispy_venv/lib/python3.6/site-packages/vispy/gloo/context.py", line 176, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/home/cmoralesmx/git/ev_diffusion_simpleVis/vispy_venv/lib/python3.6/site-packages/vispy/gloo/glir.py", line 572, in flush
    self._shared.flush(parser)
  File "/home/cmoralesmx/git/ev_diffusion_simpleVis/vispy_venv/lib/python3.6/site-packages/vispy/gloo/glir.py", line 494, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/home/cmoralesmx/git/ev_diffusion_simpleVis/vispy_venv/lib/python3.6/site-packages/vispy/gloo/glir.py", line 819, in parse
    self._parse(command)
  File "/home/cmoralesmx/git/ev_diffusion_simpleVis/vispy_venv/lib/python3.6/site-packages/vispy/gloo/glir.py", line 787, in _parse
    ob.set_data(*args)
  File "/home/cmoralesmx/git/ev_diffusion_simpleVis/vispy_venv/lib/python3.6/site-packages/vispy/gloo/glir.py", line 927, in set_data
    errors = gl.glGetShaderInfoLog(self._handle)
  File "/home/cmoralesmx/git/ev_diffusion_simpleVis/vispy_venv/lib/python3.6/site-packages/vispy/gloo/gl/_pyopengl2.py", line 122, in glGetShaderInfoLog
    res = GL.glGetShaderInfoLog(shader)
  File "/home/cmoralesmx/git/ev_diffusion_simpleVis/vispy_venv/lib/python3.6/site-packages/OpenGL/latebind.py", line 61, in __call__
    return self.wrapperFunction( self.baseFunction, *args, **named )
  File "/home/cmoralesmx/git/ev_diffusion_simpleVis/vispy_venv/lib/python3.6/site-packages/OpenGL/GL/VERSION/GL_2_0.py", line 320, in glGetShaderInfoLog
    length = int(glGetShaderiv(obj, GL_INFO_LOG_LENGTH))
  File "/home/cmoralesmx/git/ev_diffusion_simpleVis/vispy_venv/lib/python3.6/site-packages/OpenGL/latebind.py", line 61, in __call__
    return self.wrapperFunction( self.baseFunction, *args, **named )
  File "/home/cmoralesmx/git/ev_diffusion_simpleVis/vispy_venv/lib/python3.6/site-packages/OpenGL/GL/VERSION/GL_2_0.py", line 271, in glGetShaderiv
    shader, pname, status
  File "/home/cmoralesmx/git/ev_diffusion_simpleVis/vispy_venv/lib/python3.6/site-packages/OpenGL/latebind.py", line 45, in __call__
    return self._finalCall( *args, **named )
  File "/home/cmoralesmx/git/ev_diffusion_simpleVis/vispy_venv/lib/python3.6/site-packages/OpenGL/wrapper.py", line 664, in wrapperCall
    raise err
  File "/home/cmoralesmx/git/ev_diffusion_simpleVis/vispy_venv/lib/python3.6/site-packages/OpenGL/wrapper.py", line 657, in wrapperCall
    result = wrappedOperation( *cArguments )
  File "/home/cmoralesmx/git/ev_diffusion_simpleVis/vispy_venv/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/home/cmoralesmx/git/ev_diffusion_simpleVis/vispy_venv/lib/python3.6/site-packages/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1280,
	description = b'invalid enumerant',
	baseOperation = glGetShaderiv,
	pyArgs = (
		0,
		GL_INFO_LOG_LENGTH,
		array([1], dtype=int32),
	),
	cArgs = (
		0,
		GL_INFO_LOG_LENGTH,
		array([1], dtype=int32),
	),
	cArguments = (
		0,
		GL_INFO_LOG_LENGTH,
		array([1], dtype=int32),
	)
)
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (Glfw) at 0x7fc484f66b00>> for DrawEvent
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (Glfw) at 0x7fc484f66b00>> repeat 2
Segmentation fault
```  

Executing `vispy.sys_info()`  gives  
```
Platform: Linux-4.19.0-5-amd64-x86_64-with-debian-9.11
Python:   3.6.9 (default, Oct  2 2019, 09:10:33)  [GCC 6.3.0 20170516]
NumPy:    1.17.2
Backend:  Glfw
pyqt4:    None
pyqt5:    None
pyside:   None
pyside2:  None
pyglet:   None
glfw:     glfw (3, 2, 1)
sdl2:     None
wx:       None
egl:      EGL 1.4 (DRI2) Mesa Project: OpenGL OpenGL_ES
osmesa:   None
_test:    None

GL version:  '3.0 Mesa 18.2.6'
MAX_TEXTURE_SIZE: 16384
```  
`pip list` gives:  
```
Package     Version    
----------- -----------
freetype-py 2.1.0.post1
numpy       1.17.2     
pip         19.2.3     
PyOpenGL    3.1.0      
setuptools  40.6.2     
vispy       0.6.1 
```
However, in C++ with GLFW3 I have no problem using glsl 1.5+ in the same system.

Any idea what may be wrong?

I had the same error using version 0.6.1 from pip and with the current master.

**Comment by djhoese** [comment]
Geometry shaders were first added to core OpenGL in version 4.6. See https://www.khronos.org/opengl/wiki/Geometry_Shader

This page mentions that you should be able to get the functionality if you have the GL extension `ARB_geometry_shader4` available. In the `sys_info` output do you see this extension? If not, then you will need a system with a newer version of OpenGL (either drivers or a newer GPU whose drivers have this functionality available).

**Comment by cmoralesmx** [comment]
I can confirm it is possible to use geometry shaders with no problem in C/C++. Actually, I was able to get the same functionality using an alternative OpenGL library in python which does not depend on PyOpenGL.

**Comment by djhoese** [comment]
Ok, but could you verify the extension that I asked about being in the sys_info output? If it is present in that list it means that the OpenGL drivers that vispy is finding *should* be able to do this. Is your C++ GLFW3 using the *same* GLFW3 installation as the vispy installation? Do you have any environment variables set that may be interfering with things (`LD_LIBRARY_PATH`, `PYTHONPATH`, etc)?

Note: VisPy doesn't actually depend on pyopengl for most of what it does unless you explicitly ask it to. In the case of the geometry shader example it is explicitly doing this by calling `gloo.gl.use_gl('gl+')` which reimplements the same logic that pyopengl does.

**Comment by djhoese** [comment]
On my own Ubuntu based laptop with `GL version:  '3.0 Mesa 19.0.8'` I do *not* have the geometry shader extension and get an error when vispy tries to compile the shader code because GLSL 3.30 is not available.

**Comment by cmoralesmx** [comment]
Thanks for the follow up. I have been trying to understand this issue.   

My first difficulty was trying to interpet the box 
![image](https://user-images.githubusercontent.com/1790200/66223326-19604580-e6cb-11e9-9c0e-c23222d35a84.png)

Luckly, the [Guide to the OpenGL Wiki](https://www.khronos.org/opengl/wiki/Guide_to_the_OpenGL_Wiki) helps with the following description
> The "Core in version" value states the highest version of core profile OpenGL that supports this feature. The "Core since version" states the lowest version of core profile OpenGL that supports the feature.  

Then, I did not understand why an extension is mentioned at all if the functionality is part of the core. Yet, the next paragraph from the same page contains the following clue  
> Some core features start their life as OpenGL extensions, or have an extension that provides similar if not exactly identical functionality. The box depicted here shows how such a feature is presented. The "Core ARB extension" lists the name of the extension that it was derived from, if that extension is a core extension.

So, it seems the extension is listed because the features that became part of the core were based on that extension. This is made clear in the [specification for v3.2 core](https://www.khronos.org/registry/OpenGL/specs/gl/glspec32.core.pdf) 

> New features in OpenGL 3.2, including the extension or extensions if any on which they were based, include... Geometry shaders (GL_ARB_geometry_shader4).

Therefore, I understand that Geometry Shaders have been part of the core since v3.2 and before that  the functionality was accessible by using the extension. To confirm this, I found some [examples of glsl version 120 using the geometry shader functionality](https://www.khronos.org/opengl/wiki/Geometry_Shader_Examples). The examples explicitly declare the extension to enable such features.  
It seems, this explicit declaration should be done when targetting OpenGL versions prior to 3.2 core, as shown [here](https://www.khronos.org/opengl/wiki/OpenGL_Extension).

Having established the minimum version of OpenGL I should be looking for, I proceeded to check the hardware supports such version.  
According to the [List_of_Intel_graphics_processing_units](https://en.wikipedia.org/wiki/List_of_Intel_graphics_processing_units), 6th gen GPUs already support OpenGL 3.3 in Linux and Mac whereas in Windows, 7th gen GPUs are required.  
Luckly, the system under consideration has a 9th gen GPU, so, this should not be a problem.  

Next, I checked the software. According to the [mesamatrix](https://mesamatrix.net/), the mesa driver already supports the functionality of interests. This was confirmed by the reporting tool `inxi`
```
OpenGL: renderer: Mesa DRI Intel HD Graphics 620 (Kaby Lake GT2) 
  v: 4.5 Mesa 18.2.6 direct render: Yes 
```
by `glxinfo | grep OpenGL`  
```
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.2.6
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 18.2.6
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 18.2.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```
and by the fact that I can access geometry shaders or higher versions of OpenGL in the same system.  

Yet, as the first post shows, `vispy.sys_info()` seems to only be able to detects the non-core and lower version of OpenGL and does not list the extension either. Perhaps the detection process is failing at some point?  

The following answers [1](https://askubuntu.com/a/993046), [2](https://unix.stackexchange.com/a/464065/374251) suggest the underlying problem may be introduced by requesting a non-core profile when the OpenGL context is created.  
However, after a shallow search, I could not find a way to request a specific version of the context in vispy with glfw3, any ideas?  

I almost forgot, in this system, `LD_LIBRARY_PATH=/usr/local/lib`, `PYTHON_PATH` is empty.  
I am using a virtual environment for vispy, its content is listed in the first post.  
And there is only one instance of glfw  
```
sudo ldconfig -p | grep glfw
libglfw.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libglfw.so.3
libglfw.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libglfw.so
```
Thanks

**Comment by djhoese** [comment]
Do you get any different results (I'm hoping for no seg faults) if you unset `LD_LIBRARY_PATH`? The python variable I was referring to doesn't have an underscore, can you check `PYTHONPATH`?

Glad you found out so much information about your system and OpenGL in general. I don't have a lot of experience with GLFW so I'm not sure how vispy would need to be modified to make this work for you. In the past I had tried updating the PyQt5 backend to use the core profile on my old macbook and ran in to issues where the core profile for my machine required initializing GL and using GL objects in a newer way than what vispy was doing. This made it impossible for me to use geometry shaders because the compatibility profile didn't have the proper extensions/functionality, but the core profile required vispy to use GL objects in a completely different way. Updating vispy to work with the core in this way would require a lot of work and make it incompatible with the compatibility profiles on systems (which are usually the default).

**Comment by cmoralesmx** [comment]
Sorry, this issue went under my radar for long, I haven't used vispy in the last few years. I'll close this now.
Feel free to open i again if needed.
