### ISSUE TITLE
MeshVisual example

### ISSUE THREAD

**Issue by pcpatfire** [vispy/vispy#1717]
Is there a very simple example of a script for drawing a polyhedron in 3D with MeshVisual? For instance a polyhedron with 4 vertices like (0,0,0), (1,0,0), (0,1,0), (0,0,1).

**Comment by djhoese** [comment]
I don't think there is. The examples we have that use the Mesh/MeshVisual seem to be more complex than that. Are you running in to issues getting things to work? Can you provide the code you have so far? Have you tried adapting one of the existing examples?

**Comment by pcpatfire** [comment]
I was starting adapting the mesh.py example, but the problem is that I need a visual because I have to use a camera. I was trying to modify an old mesh.py with scene.visual, but it is not working. Here is the code, as modified by me. I get just a black window. Maybe a problem with the timer? Actually I don't need the timer in my application. I just need to draw many static polyhedra around atoms. For each polyhedron I know the vertices' coordinates.
```import vispy.app
from vispy import gloo, scene
from vispy.scene.visuals import Mesh
from vispy.geometry import create_sphere
from vispy.visuals.transforms import (STTransform, MatrixTransform,
                                    ChainTransform)

class Canvas(scene.SceneCanvas):
    def __init__(self):
        self.meshes = []
        self.rotation = MatrixTransform()

        # Generate some data to work with
        global mdata
        mdata = create_sphere(20, 40, 1.0)

        # Mesh with pre-indexed vertices, uniform color
        self.meshes.append(Mesh(meshdata=mdata, color='r'))
        #mesh.transform = STTransform(scale=(1, 1, .001), translate=(400, 400))

        ## Mesh with pre-indexed vertices, per-face color
        ##   Because vertices are pre-indexed, we get a different color
        ##   every time a vertex is visited, resulting in sharp color
        ##   differences between edges.
        verts = mdata.get_vertices(indexed='faces')
        nf = verts.size//9
        fcolor = np.ones((nf, 3, 4), dtype=np.float32)
        fcolor[..., 0] = np.linspace(1, 0, nf)[:, np.newaxis]
        fcolor[..., 1] = np.random.normal(size=nf)[:, np.newaxis]
        fcolor[..., 2] = np.linspace(0, 1, nf)[:, np.newaxis]
        mesh = Mesh(vertices=verts, face_colors=fcolor)
        self.meshes.append(mesh)

        ## Mesh with unindexed vertices, per-vertex color
        ##   Because vertices are unindexed, we get the same color
        ##   every time a vertex is visited, resulting in no color differences
        ##   between edges.
        verts = mdata.get_vertices()
        faces = mdata.get_faces()
        nv = verts.size//3
        vcolor = np.ones((nv, 4), dtype=np.float32)
        vcolor[:, 0] = np.linspace(1, 0, nv)
        vcolor[:, 1] = np.random.normal(size=nv)
        vcolor[:, 2] = np.linspace(0, 1, nv)
        self.meshes.append(Mesh(verts, faces, vcolor))
        self.meshes.append(Mesh(verts, faces, vcolor, shading='flat'))
        self.meshes.append(Mesh(verts, faces, vcolor, shading='smooth'))

        # Lay out meshes in a grid
        grid = (3, 3)
        s = 300. / max(grid)
        for i, mesh in enumerate(self.meshes):
            x = 800. * (i % grid[0]) / grid[0] + 400. / grid[0] - 2
            y = 800. * (i // grid[1]) / grid[1] + 400. / grid[1] + 2
            mesh.transform = ChainTransform([STTransform(translate=(x, y),
                                                         scale=(s, s, 1)),
                                             self.rotation])

        scene.SceneCanvas.__init__(self, keys='interactive')

        self.size = (800, 800)
        self.show()

        self.unfreeze()
        self.timer = vispy.app.Timer(connect=self.rotate)
        self.timer.start(0.016)
        self.freeze()

    def rotate(self, event):
        self.rotation.rotate(1, (0, 1, 0))
        # TODO: altering rotation should trigger this automatically.
        for m in self.meshes:
            m._program._need_build = True
        self.update()

    def on_draw(self, ev):
        gloo.set_clear_color('black')
        gloo.clear(color=True, depth=True)
        for mesh in self.meshes:
            self.draw_visual(mesh)


if __name__ == '__main__':
    win = Canvas()
    import sys
    if sys.flags.interactive != 1:
        vispy.app.run()`

**Comment by djhoese** [comment]
How are you executing this? I get a lot of undefined (`np` and `vispy`) when running the above code.

**Comment by djhoese** [comment]
Ah ok, I see the main problem. You took a regular Canvas example and converted it to use the SceneCanvas. The SceneCanvas requires making things like a viewbox and adding child visuals to that. Take a look at one of the SceneCanvas-based examples and you'll see the different. All of the stuff from the original example with `gloo` and rotating things (accessing `_program`) should not be part of a SceneCanvas based program.

**Comment by pcpatfire** [comment]
I was referring to an old mesh.py where SceneCanvas and gloo were mixed:
https://vispy.readthedocs.io/en/v0.3.0/examples/basics/visuals/mesh.html
I have my own SceneCanvas-based application that is working fine with Markers. My problem is how to add the MeshVisual to the the Canvas. The documentation is not so clear for me, and I cannot find a simple example.

**Comment by pcpatfire** [comment]
I was executing the code from inside eclipse and it was running without any error. I just got no spheres and a black window.

**Comment by pcpatfire** [comment]
I found a solution using Mesh instead of MeshVisual. It was not possible to add a MeshVisual object to the view. I got the following errors:
```Traceback (most recent call last):
  File "C:\Users\pc\eclipse-workspace\CrysPy (qt+vispy)\vispy_example\triangle.py", line 67, in <module>
    win = MainWindow()
  File "C:\Users\pc\eclipse-workspace\CrysPy (qt+vispy)\vispy_example\triangle.py", line 58, in __init__
    self.canvas = Canvas()
  File "C:\Users\pc\eclipse-workspace\CrysPy (qt+vispy)\vispy_example\triangle.py", line 43, in __init__
    self.view.add(poly)
  File "C:\Program Files\Python37\lib\site-packages\vispy\scene\widgets\viewbox.py", line 182, in add
    node.parent = self.scene
  File "C:\Program Files\Python37\lib\site-packages\vispy\util\frozen.py", line 16, in __setattr__
    'attributes' % (key, self))
AttributeError: 'parent' is not an attribute of class <vispy.visuals.mesh.MeshVisual object at 0x0000013848DDC888>. Call "unfreeze()" to allow addition of new attributes

**Comment by pcpatfire** [comment]
Here is the working code with Mesh (using also PyQt5).
```import sys
import numpy as np
from vispy import scene

from PyQt5.QtWidgets import QMainWindow, QApplication
from PyQt5.Qt import QVBoxLayout
from vispy.scene.visuals import Markers, Line, Mesh

class Canvas(scene.SceneCanvas):

    def __init__(self):
        scene.SceneCanvas.__init__(self, bgcolor='white', size=(800,800))
        
        self.unfreeze()
        self.view = self.central_widget.add_view()
        self.view.camera = 'turntable'
        print('<__init__ canvas> scale_factor =', self.view.camera.scale_factor)
        print('<__init__ canvas> center       =', self.view.camera.center)
        print('<__init__ canvas> app          =', self.app)
        self.view.camera.scale_factor = 3

        verts = np.array([[0, 0, 0], [0, 1, 0], [1, 0, 0], [0, 0, 1]])
        faces = np.array([[0,1,3],[0,2,3],[1,2,3],[0,1,2]])
        
        self.scatter = Markers()
        self.scatter.set_data(verts, symbol='disc', edge_color='blue', face_color='red', 
                              edge_width=3, size=30)
        
        lines = np.array([[0, 0, 0],[0, 1, 0],
                         [0, 1, 0],[0, 0, 1],
                         [0, 0, 1],[0, 0, 0],
                         [0, 0, 0],[1, 0, 0],
                         [1, 0, 0],[0, 0, 1],
                         [1, 0, 0],[0, 1, 0]])
        
        self.lines = Line(pos=lines, width=3, color='green', connect='segments', method='gl')
        
        self.view.add(self.scatter)
        self.view.add(self.lines)
        
        poly = Mesh(verts, faces)
        self.view.add(poly)
        
        self.freeze()
        
        
class MainWindow(QMainWindow):

    def __init__(self):
        QMainWindow.__init__(self)

        self.resize(800, 800)
        self.setWindowTitle('Visual test')

        vbox = QVBoxLayout()

        self.canvas = Canvas()
        self.canvas.create_native()
        self.canvas.native.setParent(self)

        vbox.addWidget(self.canvas.native)
        

if __name__ == '__main__':
    appQt = QApplication(sys.argv)
    win = MainWindow()
    win.show()
    appQt.exec_()

**Comment by djhoese** [comment]
Glad you got some working code together. Let me try clarifying a couple points so this makes a little more sense in the future:

1. I would advise against using any examples that aren't in repository for the version of vispy you are using. Vispy changes a lot from version to version especially for anything before v0.5 so it is likely that things from old examples won't work with the new versions of the code.
2. All visuals in Vispy have a "node-ified" version of the visual where the `Visual` part of the name is removed so `vispy.visuals.MeshVisual` becomes `vispy.scene.visuals.Mesh`. Only the visual objects from the `vispy.scene.visuals` module should be used with the Scene. These visuals are wrapped in a special way (combined with a special Node class) so that they can be used with the Scene and take advantage of all of the benefits the Scene provides like the transform system and parent/child relationships.

If you have any ideas on where this type of information could be placed in the current documentation I'm all ears. I've been trying to think of the best way to document these types of things. Maybe a FAQ page?

**Comment by pcpatfire** [comment]
Probably more information of this kind could be added to the overviews of each section of the API Reference.  As the Vispy package can be be used at different levels with different functionalities, a scheme with the sets of classes that need to be used together in an application would be very useful.

**Comment by queenish001** [comment]
@djhoese This can be closed.
