### ISSUE TITLE
GL_INVALID_VALUE in PySide2 app

### ISSUE THREAD

**Issue by mfrigerio17** [vispy/vispy#1736]
Hi,
The following simple program does display a window, but draw() fails:

```python
from PySide2 import QtWidgets, QtCore

import numpy as np
import vispy
from vispy import gloo, app
from vispy.gloo import set_viewport, set_state, clear

vertex = """
attribute vec2 a_position;
void main()
{
    gl_Position = vec4(a_position, 0.0, 1.0);
}
"""

fragment = """
void main()
{
    gl_FragColor = vec4(0.0, 0.0, 0.0, 1.0);
}
"""

class Canvas(app.Canvas):
    def __init__(self, **kwargs):
        app.Canvas.__init__(self, **kwargs)
        program = gloo.Program(vertex, fragment)
        program['a_position'] = [(-1, -1), (-1, +1), (+1, -1), (+1, +1)]

        self.program = program
        self.show()

    def on_resize(self, event):
        gloo.set_viewport(0, 0, *event.size)

    def on_draw(self, event):
        gloo.clear((0.2,0.2,0.2,1))   # make a gray background - works
        self.program.draw('line_strip')  # does not work

if __name__ == '__main__':
    appl = QtWidgets.QApplication()
    win = QtWidgets.QMainWindow()
    canvas = Canvas()
    win.setCentralWidget(canvas.native)
    win.show()
#    print(vispy.sys_info())
    appl.exec_()
```

Fails with this error:
```
WARNING: Traceback (most recent call last):
  File "myvispy.py", line 44, in <module>
    win.show()
  File "/usr/local/lib/python3.5/dist-packages/vispy/app/backends/_qt.py", line 501, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "/usr/local/lib/python3.5/dist-packages/vispy/app/backends/_qt.py", line 501, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "/usr/local/lib/python3.5/dist-packages/vispy/app/backends/_qt.py", line 818, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/usr/local/lib/python3.5/dist-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/usr/local/lib/python3.5/dist-packages/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/usr/local/lib/python3.5/dist-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "sucavispy.py", line 37, in on_draw
    self.program.draw('line_strip')
  File "/usr/local/lib/python3.5/dist-packages/vispy/gloo/program.py", line 533, in draw
    canvas.context.flush_commands()
  File "/usr/local/lib/python3.5/dist-packages/vispy/gloo/context.py", line 176, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/usr/local/lib/python3.5/dist-packages/vispy/gloo/glir.py", line 572, in flush
    self._shared.flush(parser)
  File "/usr/local/lib/python3.5/dist-packages/vispy/gloo/glir.py", line 494, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/usr/local/lib/python3.5/dist-packages/vispy/gloo/glir.py", line 819, in parse
    self._parse(command)
  File "/usr/local/lib/python3.5/dist-packages/vispy/gloo/glir.py", line 779, in _parse
    ob.draw(*args)
  File "/usr/local/lib/python3.5/dist-packages/vispy/gloo/glir.py", line 1341, in draw
    gl.check_error('Check after draw')
  File "/usr/local/lib/python3.5/dist-packages/vispy/gloo/gl/__init__.py", line 207, in check_error
    raise err
RuntimeError: OpenGL got errors (Check after draw): GL_INVALID_VALUE
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PySide2) at 0x7f3ccd951390>> for DrawEvent
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PySide2) at 0x7f3ccd951390>> repeat 2
```

My setup:
```
Platform: Linux-4.15.0-54-generic-x86_64-with-Ubuntu-16.04-xenial
Python:   3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
NumPy:    1.15.0
Backend:  PySide2
pyqt4:    None
pyqt5:    None
pyside:   None
pyside2:  ('PySide2', '5.13.1', '5.13.1')
pyglet:   None
glfw:     glfw (3, 1, 2)
sdl2:     None
wx:       None
egl:      EGL 1.4 (DRI2) Mesa Project: OpenGL OpenGL_ES
osmesa:   OSMesa
_test:    None
```
Vispy: `0.6.2.dev25+g876a0d3`

The same program works when I let vispy use its own app:
```python
if __name__ == '__main__':
    canvas = Canvas()
    vispy.app.run()  # creates the windows and draw()s successfully
```
Any suggestion?
Thanks

**Comment by djhoese** [comment]
Do any of the vispy examples display for you? Especially the more basic gloo ones?

**Comment by mfrigerio17** [comment]
I tried `high_requency.py`, which is not so basic I guess, and it works fine. Is it a good test?

As I said, even my example works, when I let vispy create the main app. But I have an existing gui application, and I want to use vispy only for some widgets.

The code I posted reproduces the problem: when the app is created with the PySide2 api, and the vispy canvas is added as a widget, the draw() fails.

Thanks for your help

**Comment by mfrigerio17** [comment]
The QApplication is created elsewhere in existing code.
I am adding a widget to an existing gui application, so I need vispy to pick the existing QApplication.
I don't want to modify the existing "main" file and replace the creation of the QApp using vispy; that would introduce a dependency and a reference to vispy where it is not really needed.

**Comment by djhoese** [comment]
Understood. Makes sense.

It looks like vispy is trying to use `QApplication.instance()` to get any existing instances of the application (https://github.com/vispy/vispy/blob/master/vispy/app/backends/_qt.py#L279). Is this maybe not true for PySide2?

**Comment by thoebert** [comment]
I had the same error. @mfrigerio17's code also failed on my system with the same error. I fixed it by removing the `self.show()` in the `Canvas` constructor. Works like a charm :)

System info:
Platform: Linux-4.18.0-25-generic-x86_64-with-Ubuntu-18.04-bionic
Python:   3.6.8 (default, Aug 20 2019, 17:12:48)  [GCC 8.3.0]
NumPy:    1.18.2
Backend:  PySide2
pyqt4:    None
pyqt5:    None
pyside:   None
pyside2:  ('PySide2', '5.14.2', '5.14.2')
pyglet:   None
glfw:     glfw (3, 2, 1)
sdl2:     None
wx:       None
egl:      EGL 1.4 Mesa Project: OpenGL OpenGL_ES
osmesa:   None
_test:    None

GL version:  '3.0 Mesa 19.0.8'
