### ISSUE TITLE
Weird ax.mesh bug when loading numpy array from file

### ISSUE THREAD

**Issue by ktritz** [vispy/vispy#1741]
Greetings,

I can plot a 3d mesh successfully when reading mesh vertices and triangles faces from a text file into numpy arrays. Relevant code:

`    def plot(self, vert_colors=None, face_colors='random'):
        fig = Fig()
        ax = fig[0, 0]
        verts = self.points
        if vert_colors == 'random':
            vnum = verts.shape[0]
            vert_colors = np.ones((vnum, 4))
            vert_colors[:, 0:3] = np.random.uniform(size=(vnum, 3))
            face_colors = None
        faces = self.tris
        if face_colors == 'random':
            fnum = faces.shape[0]
            face_colors = np.ones((fnum, 4))
            face_colors[:, 0:3] = np.random.uniform(size=(fnum, 3))
        ax.mesh(vertices=verts, faces=faces, vertex_colors=vert_colors,
                face_colors=face_colors)`

Now, if I save self.points using pickle, or numpy dump/save, and then load it again, plotting the mesh fails with the following error:
KeyError: 'There are no fields in dtype float64.'
ERROR: Invoking <bound method SceneCanvas.on_draw of <Fig (PyQt5) at 0x1e724abf188>> for DrawEvent

The only difference I've found is that when I read the array from the text file, the flag OWNDATA is False. When I read the data in from the saved pickle/numpy save, OWNDATA is True.

**Comment by ktritz** [comment]
Sorry, screwed up the formatting, here's the code:

```python
    def plot(self, vert_colors=None, face_colors='random'):
        fig = Fig()
        ax = fig[0, 0]
        verts = self.points
        if vert_colors == 'random':
            vnum = verts.shape[0]
            vert_colors = np.ones((vnum, 4))
            vert_colors[:, 0:3] = np.random.uniform(size=(vnum, 3))
            face_colors = None
        faces = self.tris
        if face_colors == 'random':
            fnum = faces.shape[0]
            face_colors = np.ones((fnum, 4))
            face_colors[:, 0:3] = np.random.uniform(size=(fnum, 3))
        ax.mesh(vertices=verts, faces=faces, vertex_colors=vert_colors,
                face_colors=face_colors)```

**Comment by djhoese** [comment]
Wow, that's definitely odd. I would have assumed that the OWNDATA being False was a bad thing, but its a good thing it seems for you.

As a quickcheck, can you try doing `verts.copy()`, `faces.copy()`, `vert_colors.copy()`, and `face_colors.copy()` when passing these variables to `mesh` and see if that makes a difference?

My guess, based on issues brought up recently for some visuals is that the visual is trying to do a "lazy copy" and only copying if it needs to. In this case, it doesn't need to for your second non-text file case and that's causing issues for some reason.

**Comment by ktritz** [comment]
I tried your suggestion and it didn't seem to help. The OWNDATA flag might be a red herring. I loaded the data from the text file, it plots fine. I then did self.points = self.points.copy(). This changes the OWNDATA flag to true, and it still plots fine. But then loading it from the pickle file or using numpy dump/load still fails. Here's the error message in full:

> In [24]: WARNING: Traceback (most recent call last):
  File "C:\Users\ktritz\Anaconda3\Scripts\ipython-script.py", line 10, in <module>
    sys.exit(start_ipython())
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\IPython\__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\IPython\terminal\ipapp.py", line 356, in start
    self.shell.mainloop()
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\IPython\terminal\interactiveshell.py", line 498, in mainloop
    self.interact()
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\IPython\terminal\interactiveshell.py", line 481, in interact
    code = self.prompt_for_code()
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\IPython\terminal\interactiveshell.py", line 410, in prompt_for_code
    **self._extra_prompt_options())
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 738, in prompt
    return run_sync()
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 727, in run_sync
    return self.app.run(inputhook=self.inputhook, pre_run=pre_run2)
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\prompt_toolkit\application\application.py", line 709, in run
    return run()
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\prompt_toolkit\application\application.py", line 682, in run
    run_until_complete(f, inputhook=inputhook)
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\prompt_toolkit\eventloop\defaults.py", line 123, in run_until_complete
    return get_event_loop().run_until_complete(future, inputhook=inputhook)
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\prompt_toolkit\eventloop\win32.py", line 68, in run_until_complete
    self._run_once(inputhook)
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\prompt_toolkit\eventloop\win32.py", line 87, in _run_once
    self._inputhook_context.call_inputhook(ready, inputhook)
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\prompt_toolkit\eventloop\inputhook.py", line 81, in call_inputhook
    inputhook(self)
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\IPython\terminal\interactiveshell.py", line 513, in inputhook
    self._inputhook(context)
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\IPython\terminal\pt_inputhooks\qt.py", line 38, in inputhook
    event_loop.exec_()
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\vispy\app\backends\_qt.py", line 501, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\vispy\app\backends\_qt.py", line 818, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\vispy\util\event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\vispy\scene\canvas.py", line 217, in on_draw
    self._draw_scene()
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\vispy\scene\canvas.py", line 266, in _draw_scene
    self.draw_visual(self.scene)
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\vispy\scene\canvas.py", line 304, in draw_visual
    node.draw()
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\vispy\scene\visuals.py", line 99, in draw
    self._visual_superclass.draw(self)
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\vispy\visuals\mesh.py", line 519, in draw
    Visual.draw(self, *args, **kwds)
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\vispy\visuals\visual.py", line 435, in draw
    if self._prepare_draw(view=self) is False:
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\vispy\visuals\mesh.py", line 514, in _prepare_draw
    if self._update_data() is False:
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\vispy\visuals\mesh.py", line 405, in _update_data
    self.shared_program.vert['position'] = self._vertices
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\vispy\visuals\shaders\multiprogram.py", line 141, in __setitem__
    getattr(p, self._shader)[key] = value
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\vispy\visuals\shaders\function.py", line 234, in __setitem__
    val = ShaderObject.create(val, ref=key)
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\vispy\visuals\shaders\shader_object.py", line 45, in create
    obj = Variable(ref, obj)
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\vispy\visuals\shaders\variable.py", line 63, in __init__
    self.value = value
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\vispy\visuals\shaders\variable.py", line 126, in value
    elif getattr(value, 'glsl_type', None) is not None:
  File "C:\Users\ktritz\Anaconda3\lib\site-packages\vispy\gloo\buffer.py", line 234, in glsl_type
    dtshape = self.dtype[0].shape
KeyError: 'There are no fields in dtype float64.'

**Comment by djhoese** [comment]
What version of numpy are you using? Based on your error message this seems to be based on the vertices generated inside MeshVisual. What is the difference between `print(data_arr.dtype)` for the different data loading methods?

Side note: I changed the formatting in your above comment by using three backticks (```) before and after the part of the message that I wanted to be a "literal block".

**Comment by ktritz** [comment]
Numpy version 1.16.5

Both arrays have a dtype of 'float64', and both give the same KeyError as above if I try:

self.points.dtype[0]

Interestingly, if I explicitly copy the data into a new array:
```python
        verts = self.points
        nv = np.empty(verts.shape)
        nv[:, :] = verts[:, :]
        verts = nv
```
ax.mesh works fine for both loaded arrays, even though using 'verts.copy()' in the ax.mesh function does not work.

**Comment by djhoese** [comment]
What are the other flags set to for the two different ways of loading the data? Can you paste the output here? You're not on a system with a "non standard" processor are you? Are you on a 32-bit system? Are you saving the data with any other special flags?

**Comment by ktritz** [comment]
For the pickle loaded arrays:  
```
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
```
For the text loaded arrays:
```
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
```
Intel processor, Windows 64-bit system, using a stright 'dump' command without any keywords
```python
    def save(self):
        filename = 'sphere{}.bin'.format(self.dist)
        path = os.path.join(mod_path, 'grids', filename)
        joblib.dump((self.radius, self.points, self.tris), path)

    def load(self):
        filename = 'sphere{}.bin'.format(self.dist)
        path = os.path.join(mod_path, 'grids', filename)
        self.radius, self.points, self.tris = joblib.load(path)
```
I'm showing joblib, but it's basically the same with pickle and numpy dump/load.

**Comment by djhoese** [comment]
I'm not really sure where to go from here. There are PRs sitting around to change some of the behavior internally to how the MeshVisual data is handled, but I don't think any of them have been merged yet so I don't think this is a new bug. Could you do more tests without involving joblib?

**Comment by hubert0527** [comment]
I faced the same issue (pickle the arrays then got the same error).
The problem is actually happened at the `array.dtype.isisbuiltin` check here:
https://github.com/vispy/vispy/blob/303afb99addfe07f57975c70fcd64e65be220c2a/vispy/gloo/buffer.py#L437

It seems like `numpy.ndarray` default sets `isbuiltin` to `1` (which indicates the data is not native type). However, after pickle, such a field is set to `0` (perhaps some magics in the pickle implementation).

I'm not sure the purpose of checking `isbuiltin` here. But a workaround from the user side can be brute-forcely update the `isbuiltin` field of array with:
```
# arr: the vertices, faces, colors, ... whatsoever
equi_type = getattr(np, str(arr.dtype))
arr = arr.astype(equi_type)
```

**Comment by djhoese** [comment]
Nice work @hubert0527. Looks like this pickling bug has been in numpy for a long time: https://github.com/numpy/numpy/issues/4317

If you/we can track down the various __setstate__, __getstate__, __reduce__ (I think, right?) in the numpy source it will probably be easier to debug this.

I think the idea with that if statement (*I think*) is that we assume if the array is a multi-field dtype that it came from vispy's own data handling and is good as-is (it has been copied already, it is contiguous, it is the dtype it needs to be). This is a guess. This is old vispy code.

**Comment by djhoese** [comment]
Looking through old commits, it looks like this `isbuiltin` check has been there since 2014, the original development of vispy, and was intended to check if the data was already structured (a numpy dtype with named fields). Based on the discussion on the numpy issue, I think the more long term solution would be to update this if statement to be `if data.dtype.fields is None:`.
