### ISSUE TITLE
vispy.test() failure with jupyter notebook and lab (keeps trying to open a spyder console)

### ISSUE THREAD

**Issue by Sh4zKh4n** [vispy/vispy#1754]
Hi Sorry, I posted without adding info. (now edited with code blocks, as suggested by @djhoese . Thank you for the suggestion (Ill remember it and go read up the info on Git Comments!

So the issue I have is that when I run ```python vispy.test() ``` with either julyter notebook or labs, during the test I just keep getting a flashing window that is from spyder. Which is weird and the test fails.

This is what I get from notebook:
```python
----------------------------------------------------------------------`

Skipping backend pyqt4, not installed or working properly:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
        default_app = Application(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 49, in __init__
        self._use(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 235, in _use
        raise RuntimeError(msg)
    RuntimeError: Could not import backend "PyQt4":
    No module named 'PyQt4'
    
----------------------------------------------------------------------
----------------------------------------------------------------------
msg:
_VISPY_TESTING_APP=pyqt5 C:\Users\shaz\Anaconda3\python.exe -m pytest -m vispy_app_test C:\Users\shaz\Anaconda3\lib\site-packages\vispy
Failed: unit failure (1)
----------------------------------------------------------------------
Skipping backend pyside, not installed or working properly:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
        default_app = Application(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 49, in __init__
        self._use(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 235, in _use
        raise RuntimeError(msg)
    RuntimeError: Could not import backend "PySide":
    No module named 'PySide'
    
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend pyside2, not installed or working properly:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
        default_app = Application(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 49, in __init__
        self._use(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 235, in _use
        raise RuntimeError(msg)
    RuntimeError: Could not import backend "PySide2":
    No module named 'PySide2'
    
----------------------------------------------------------------------
----------------------------------------------------------------------
msg:
_VISPY_TESTING_APP=pyglet C:\Users\shaz\Anaconda3\python.exe -m pytest -m vispy_app_test C:\Users\shaz\Anaconda3\lib\site-packages\vispy
Failed: unit failure (1)
----------------------------------------------------------------------
Skipping backend glfw, not installed or working properly:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
        default_app = Application(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 49, in __init__
        self._use(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 235, in _use
        raise RuntimeError(msg)
    RuntimeError: Could not import backend "Glfw":
    GLFW library not found
    
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend sdl2, not installed or working properly:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
        default_app = Application(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 49, in __init__
        self._use(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 235, in _use
        raise RuntimeError(msg)
    RuntimeError: Could not import backend "SDL2":
    No module named 'sdl2'
    
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend wx, not installed or working properly:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
        default_app = Application(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 49, in __init__
        self._use(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 235, in _use
        raise RuntimeError(msg)
    RuntimeError: Could not import backend "wx":
    No module named 'wx'
    
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend egl, not installed or working properly:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
        default_app = Application(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 49, in __init__
        self._use(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 235, in _use
        raise RuntimeError(msg)
    RuntimeError: Could not import backend "EGL":
    EGL library not found
    
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend osmesa, not installed or working properly:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
        default_app = Application(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 49, in __init__
        self._use(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 235, in _use
        raise RuntimeError(msg)
    RuntimeError: Could not import backend "osmesa":
    OSMesa library not found
    
----------------------------------------------------------------------
----------------------------------------------------------------------
msg:
_VISPY_TESTING_APP=ipynb_webgl C:\Users\shaz\Anaconda3\python.exe -m pytest -m vispy_app_test C:\Users\shaz\Anaconda3\lib\site-packages\vispy
Passed

----------------------------------------------------------------------
Skipping backend _test, not installed or working properly:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
        default_app = Application(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 49, in __init__
        self._use(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 235, in _use
        raise RuntimeError(msg)
    RuntimeError: Could not import backend "_test":
    test backend should be skipped
    
----------------------------------------------------------------------
----------------------------------------------------------------------
msg:
_VISPY_TESTING_APP=nobackend C:\Users\shaz\Anaconda3\python.exe -m pytest -m "not vispy_app_test" C:\Users\shaz\Anaconda3\lib\site-packages\vispy
Failed: unit failure (1)
Skipping example test: Cannot test examples unless in vispy git directory
Skipping line endings check on Windows
Passed

Skipping flake8 test, flake8 not installed
Passed

Testing failed (['pyqt5', 'pyglet', 'nobackend'] failed, ['pyqt4', 'pyside', 'pyside2', 'glfw', 'sdl2', 'wx', 'egl', 'osmesa', '_test', 'examples'] skipped) in 130.270 seconds
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-e78e52328cb1> in <module>
----> 1 vispy.test()

~\Anaconda3\lib\site-packages\vispy\testing\_runners.py in test(label, extra_arg_string, coverage)
    447     sys.stdout.flush()
    448     if len(fail) > 0:
--> 449         raise RuntimeError('FAILURE')

RuntimeError: FAILURE
```

**Then from jupyter labs **
```python
----------------------------------------------------------------------
Skipping backend pyqt4, not installed or working properly:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
        default_app = Application(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 49, in __init__
        self._use(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 235, in _use
        raise RuntimeError(msg)
    RuntimeError: Could not import backend "PyQt4":
    No module named 'PyQt4'
    
----------------------------------------------------------------------
----------------------------------------------------------------------
msg:
_VISPY_TESTING_APP=pyqt5 C:\Users\shaz\Anaconda3\python.exe -m pytest -m vispy_app_test C:\Users\shaz\Anaconda3\lib\site-packages\vispy
Failed: unit failure (1)
----------------------------------------------------------------------
Skipping backend pyside, not installed or working properly:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
        default_app = Application(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 49, in __init__
        self._use(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 235, in _use
        raise RuntimeError(msg)
    RuntimeError: Could not import backend "PySide":
    No module named 'PySide'
    
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend pyside2, not installed or working properly:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
        default_app = Application(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 49, in __init__
        self._use(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 235, in _use
        raise RuntimeError(msg)
    RuntimeError: Could not import backend "PySide2":
    No module named 'PySide2'
    
----------------------------------------------------------------------
----------------------------------------------------------------------
msg:
_VISPY_TESTING_APP=pyglet C:\Users\shaz\Anaconda3\python.exe -m pytest -m vispy_app_test C:\Users\shaz\Anaconda3\lib\site-packages\vispy
Failed: unit failure (1)
----------------------------------------------------------------------
Skipping backend glfw, not installed or working properly:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
        default_app = Application(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 49, in __init__
        self._use(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 235, in _use
        raise RuntimeError(msg)
    RuntimeError: Could not import backend "Glfw":
    GLFW library not found
    
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend sdl2, not installed or working properly:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
        default_app = Application(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 49, in __init__
        self._use(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 235, in _use
        raise RuntimeError(msg)
    RuntimeError: Could not import backend "SDL2":
    No module named 'sdl2'
    
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend wx, not installed or working properly:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
        default_app = Application(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 49, in __init__
        self._use(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 235, in _use
        raise RuntimeError(msg)
    RuntimeError: Could not import backend "wx":
    No module named 'wx'
    
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend egl, not installed or working properly:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
        default_app = Application(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 49, in __init__
        self._use(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 235, in _use
        raise RuntimeError(msg)
    RuntimeError: Could not import backend "EGL":
    EGL library not found
    
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend osmesa, not installed or working properly:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
        default_app = Application(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 49, in __init__
        self._use(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 235, in _use
        raise RuntimeError(msg)
    RuntimeError: Could not import backend "osmesa":
    OSMesa library not found
    
----------------------------------------------------------------------
----------------------------------------------------------------------
msg:
_VISPY_TESTING_APP=ipynb_webgl C:\Users\shaz\Anaconda3\python.exe -m pytest -m vispy_app_test C:\Users\shaz\Anaconda3\lib\site-packages\vispy
Passed

----------------------------------------------------------------------
Skipping backend _test, not installed or working properly:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
        default_app = Application(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 49, in __init__
        self._use(backend_name)
      File "C:\Users\shaz\Anaconda3\lib\site-packages\vispy\app\application.py", line 235, in _use
        raise RuntimeError(msg)
    RuntimeError: Could not import backend "_test":
    test backend should be skipped
    
----------------------------------------------------------------------
----------------------------------------------------------------------
msg:
_VISPY_TESTING_APP=nobackend C:\Users\shaz\Anaconda3\python.exe -m pytest -m "not vispy_app_test" C:\Users\shaz\Anaconda3\lib\site-packages\vispy
Failed: unit failure (1)
Skipping example test: Cannot test examples unless in vispy git directory
Skipping line endings check on Windows
Passed

Skipping flake8 test, flake8 not installed
Passed

Testing failed (['pyqt5', 'pyglet', 'nobackend'] failed, ['pyqt4', 'pyside', 'pyside2', 'glfw', 'sdl2', 'wx', 'egl', 'osmesa', '_test', 'examples'] skipped) in 130.212 seconds
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-e78e52328cb1> in <module>
----> 1 vispy.test()

~\Anaconda3\lib\site-packages\vispy\testing\_runners.py in test(label, extra_arg_string, coverage)
    447     sys.stdout.flush()
    448     if len(fail) > 0:
--> 449         raise RuntimeError('FAILURE')

RuntimeError: FAILURE
```
heres the info from vispy.sys_info():

```python
'Platform: Windows-10-10.0.18362-SP0\nPython:   3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 22:01:29) [MSC v.1900 64 bit (AMD64)]\nNumPy:    1.17.3\nBackend:  ipynb_webgl\npyqt4:    None\npyqt5:    (\'PyQt5\', \'5.12.3\', \'5.12.5\')\npyside:   None\npyside2:  None\npyglet:   pyglet 1.4.7\nglfw:     None\nsdl2:     None\nwx:       None\negl:      None\nosmesa:   None\n_test:    None\n\nGL version:  \'4.6.0 NVIDIA 436.15\'\nMAX_TEXTURE_SIZE: 32768\nExtensions: \'GL_AMD_multi_draw_indirect GL_AMD_seamless_cubemap_per_texture GL_AMD_vertex_shader_viewport_index GL_AMD_vertex_shader_layer GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_fragment_shader_interlock GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_post_depth_coverage GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_locations GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shader_viewport_layer_array GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_sparse_buffer GL_ARB_sparse_texture GL_ARB_sparse_texture2 GL_ARB_sparse_texture_clamp GL_ARB_spirv_extensions GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_filter_anisotropic GL_ARB_texture_filter_minmax GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ARB_window_pos GL_ATI_draw_buffers GL_ATI_texture_float GL_ATI_texture_mirror_once GL_S3_s3tc GL_EXT_texture_env_add GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_Cg_shader GL_EXT_depth_bounds_test GL_EXT_direct_state_access GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXTX_framebuffer_mixed_formats GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_multiview_texture_multisample GL_EXT_multiview_timer_query GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_polygon_offset_clamp GL_EXT_post_depth_coverage GL_EXT_provoking_vertex GL_EXT_raster_multisample GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_shader_objects GL_EXT_separate_specular_color GL_EXT_shader_image_load_formatted GL_EXT_shader_image_load_store GL_EXT_shader_integer_mix GL_EXT_shadow_funcs GL_EXT_sparse_texture2 GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture3D GL_EXT_texture_array GL_EXT_texture_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_latc GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_filter_minmax GL_EXT_texture_integer GL_EXT_texture_lod GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_object GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_decode GL_EXT_texture_storage GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback2 GL_EXT_vertex_array GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_EXT_window_rectangles GL_EXT_import_sync_object GL_IBM_rasterpos_clip GL_IBM_texture_mirrored_repeat GL_KHR_context_flush_control GL_KHR_debug GL_EXT_memory_object GL_EXT_memory_object_win32 GL_EXT_win32_keyed_mutex GL_KHR_parallel_shader_compile GL_KHR_no_error GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_EXT_semaphore GL_EXT_semaphore_win32 GL_KHR_shader_subgroup GL_KTX_buffer_region GL_NV_alpha_to_coverage_dither_control GL_NV_bindless_multi_draw_indirect GL_NV_bindless_multi_draw_indirect_count GL_NV_bindless_texture GL_NV_blend_equation_advanced GL_NV_blend_equation_advanced_coherent GL_NVX_blend_equation_advanced_multi_draw_buffers GL_NV_blend_minmax_factor GL_NV_blend_square GL_NV_clip_space_w_scaling GL_NV_command_list GL_NV_compute_program5 GL_NV_conditional_render GL_NV_conservative_raster GL_NV_conservative_raster_dilate GL_NV_conservative_raster_pre_snap_triangles GL_NV_copy_depth_to_color GL_NV_copy_image GL_NV_depth_buffer_float GL_NV_depth_clamp GL_NV_draw_texture GL_NV_draw_vulkan_image GL_NV_ES1_1_compatibility GL_NV_ES3_1_compatibility GL_NV_explicit_multisample GL_NV_feature_query GL_NV_fence GL_NV_fill_rectangle GL_NV_float_buffer GL_NV_fog_distance GL_NV_fragment_coverage_to_color GL_NV_fragment_program GL_NV_fragment_program_option GL_NV_fragment_program2 GL_NV_fragment_shader_interlock GL_NV_framebuffer_mixed_samples GL_NV_framebuffer_multisample_coverage GL_NV_geometry_shader4 GL_NV_geometry_shader_passthrough GL_NV_gpu_program4 GL_NV_internalformat_sample_query GL_NV_gpu_program4_1 GL_NV_gpu_program5 GL_NV_gpu_program5_mem_extended GL_NV_gpu_program_fp64 GL_NV_gpu_shader5 GL_NV_half_float GL_NV_light_max_exponent GL_NV_memory_attachment GL_NV_multisample_coverage GL_NV_multisample_filter_hint GL_NV_occlusion_query GL_NV_packed_depth_stencil GL_NV_parameter_buffer_object GL_NV_parameter_buffer_object2 GL_NV_path_rendering GL_NV_path_rendering_shared_edge GL_NV_pixel_data_range GL_NV_point_sprite GL_NV_primitive_restart GL_NV_query_resource GL_NV_query_resource_tag GL_NV_register_combiners GL_NV_register_combiners2 GL_NV_sample_locations GL_NV_sample_mask_override_coverage GL_NV_shader_atomic_counters GL_NV_shader_atomic_float GL_NV_shader_atomic_float64 GL_NV_shader_atomic_fp16_vector GL_NV_shader_atomic_int64 GL_NV_shader_buffer_load GL_NV_shader_storage_buffer_object GL_NV_shader_subgroup_partitioned GL_NV_stereo_view_rendering GL_NV_texgen_reflection GL_NV_texture_barrier GL_NV_texture_compression_vtc GL_NV_texture_env_combine4 GL_NV_texture_multisample GL_NV_texture_rectangle GL_NV_texture_rectangle_compressed GL_NV_texture_shader GL_NV_texture_shader2 GL_NV_texture_shader3 GL_NV_transform_feedback GL_NV_transform_feedback2 GL_NV_uniform_buffer_unified_memory GL_NV_vertex_array_range GL_NV_vertex_array_range2 GL_NV_vertex_attrib_integer_64bit GL_NV_vertex_buffer_unified_memory GL_NV_vertex_program GL_NV_vertex_program1_1 GL_NV_vertex_program2 GL_NV_vertex_program2_option GL_NV_vertex_program3 GL_NV_viewport_array2 GL_NV_viewport_swizzle GL_NVX_conditional_render GL_NVX_linked_gpu_multicast GL_NV_gpu_multicast GL_NVX_gpu_multicast2 GL_NVX_progress_fence GL_NVX_gpu_memory_info GL_NVX_multigpu_info GL_NVX_nvenc_interop GL_NV_shader_thread_group GL_NV_shader_thread_shuffle GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OVR_multiview GL_OVR_multiview2 GL_SGIS_generate_mipmap GL_SGIS_texture_lod GL_SGIX_depth_texture GL_SGIX_shadow GL_SUN_slice_accum GL_WIN_swap_hint WGL_EXT_swap_control \'\nApp info-gathering error:\nTraceback (most recent call last):\n  File "C:\\Users\\shaz\\Anaconda3\\lib\\site-packages\\vispy\\util\\config.py", line 438, in sys_info\n    canvas.close()\n  File "C:\\Users\\shaz\\Anaconda3\\lib\\site-packages\\vispy\\app\\canvas.py", line 457, in close\n    self._backend._vispy_close()\n  File "C:\\Users\\shaz\\Anaconda3\\lib\\site-packages\\vispy\\app\\backends\\_ipynb_webgl.py", line 203, in _vispy_close\n    raise NotImplementedError()\nNotImplementedError\n' 
```

**Comment by Sh4zKh4n** [comment]
Any thoughts on what the problem is?

**Comment by djhoese** [comment]
Short answer: Don't run tests from a jupyter notebook.

Long answer: The notebook widget is not a complete implementation of every feature of vispy. It only has a limited set of tests. All other backends should pass most tests when run from the command line. It is hard to read your output because of the formatting. Could you try editing your post and make sure you have three backticks (```) before and after the entire pasted output? The warnings about some backends missing is completely fine if you don't have those backends installed.

**Comment by Sh4zKh4n** [comment]
Thank you @djhoese  for the tip their, its much easier to read now! I followed the instructions from the vispy docs, which suggest running the test. Ive completed all the steps and i havent actually tried vispy out yet. Since the test runs didn't work. Are you advising they may do? I have PyQt5 and when i noticed this was not as stable as 4. I decided to install pyglet. Which also seems to not work on ``` vispy.test()```. 

If your advising that it's an issue with test and Jupyter. Ill try running vispy in the notebook and see what happens...but the weird thing of it trying, during testing of PyQt5 and Pyglet, of successive attempts of opening a spyder window is weird. 

As a background. There seems to be different instructions around on the vispy websites on install. Initially I ran as pip , this just failed all the way through, even though i had this installed in my environment, but then found the conda install. So I uninstalled and tried the conda install instead. But unfortunately the same problem. Any help would be appreciated! Ive activated all the extension (well i think i have but ill look again!

**Comment by Sh4zKh4n** [comment]
So, i tried out the Voronoi example and it works, its using the GPU! I re read your comment and tried out of a comman line python interface and the test are running fine! Thank you. One day i wont be a newb!

**Comment by djhoese** [comment]
Thanks so much for sticking with this and getting things to work. I'm glad you were able to figure it out.

After your previous message I was going to ask that you verify that you are running the most recent version of vispy. Starting with vispy 0.6 PyQt5 is the preferred backend to use (in my opinion at least). it is the one used by most of our automated tests and it is the one I use for my own projects.

The jupyter widget in vispy is still considered experimental and I would not suggest it for anything serious. There are performance issues and limitations due to the design of vispy and the way jupyter notebooks have to communicate with the python kernel that actually runs the code. Right now, the widget just won't be able to do all things well without a complete rewrite.

As for the installation instructions, if you could point out (or make a pull request fixing it :wink: ) where the confusion is in a separate issue it would be much appreciated. To clarify some stuff, the idea is that you use the conda install if you are using a conda environment and pip otherwise.
