### ISSUE TITLE
RuntimeError when PlotWidget inside QDockWidget is floated

### ISSUE THREAD

**Issue by tlambert03** [vispy/vispy#1759]
I'm working on incorporating a variant of the `vispy.PlotWidget` into some features in napari (see https://github.com/napari/napari/pull/675#issuecomment-554102325 for a working example of what I'm doing).
This may be more about using Qt and vispy together ... but I'm struggling to debug and thought someone here might be able to help me debug.  Any thoughts greatly appreciated.

I'm having an issue when a `vispy.PlotWidget` inside of a `QWidget` is added to a `QDockWidget`.  At first, everything works fine, but when the `QDockWidget` is floated, I get an error drawing `vispy.visuals.line.line._GLLineVisual` (which i think is part of the `AxisWidget` inside of the `PlotWidget`), which culminates in a `RuntimeError: OpenGL got errors (Check before draw): GL_INVALID_VALUE`.  If I then re-attach the `QDockWidget`, things continue working.

here's an example gif demonstrating the issue, followed by code to reproduce it, and the full stack trace (note, drawing the histogram is not necessary, it has the same bug with the PlotWidget alone):

![ezgif-3-5a9e9f758275](https://user-images.githubusercontent.com/1609449/69097538-bf220680-0a24-11ea-98c2-a4c4cbeff701.gif)

```python
"""
An example of a rendering issue when putting a SceneCanvas into a  QDockWidget
"""

import sys
import numpy as np

from vispy import scene
from vispy.plot import PlotWidget

from qtpy.QtCore import Qt, QSize
from qtpy import QtWidgets


class QtPlotWidget(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.canvas = scene.SceneCanvas(bgcolor='k', keys=None, vsync=True)
        self.canvas.native.setMinimumSize(QSize(300, 100))
        self.setLayout(QtWidgets.QHBoxLayout())
        self.layout().addWidget(self.canvas.native)
        self.plot = self.canvas.central_widget.add_widget(
            PlotWidget(fg_color='w')
        )
        self.plot.histogram(np.random.randn(10000), bins=100, color='b')
        # the histogram is just an example, but the axes alone are sufficient:
        # self.plot._configure_2d()


class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.resize(700, 500)
        dock_widget = QtWidgets.QDockWidget(self)
        self.plot = QtPlotWidget()
        dock_widget.setWidget(self.plot)
        self.addDockWidget(Qt.BottomDockWidgetArea, dock_widget)


if __name__ == '__main__':
    appQt = QtWidgets.QApplication(sys.argv)
    win = MainWindow()
    win.show()
    appQt.exec_()
```

here is the stack trace: 
```
WARNING: Error drawing visual <vispy.visuals.line.line._GLLineVisual object at 0x1213ff6d0>
WARNING: Traceback (most recent call last):
  File "examples/vispy_dock.py", line 44, in <module>
    appQt.exec_()
  File "/Users/talley/anaconda/envs/napdev/lib/python3.7/site-packages/vispy/app/backends/_qt.py", line 501, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "/Users/talley/anaconda/envs/napdev/lib/python3.7/site-packages/vispy/app/backends/_qt.py", line 501, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "/Users/talley/anaconda/envs/napdev/lib/python3.7/site-packages/vispy/app/backends/_qt.py", line 818, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/Users/talley/anaconda/envs/napdev/lib/python3.7/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/Users/talley/anaconda/envs/napdev/lib/python3.7/site-packages/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/Users/talley/anaconda/envs/napdev/lib/python3.7/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/Users/talley/anaconda/envs/napdev/lib/python3.7/site-packages/vispy/scene/canvas.py", line 217, in on_draw
    self._draw_scene()
  File "/Users/talley/anaconda/envs/napdev/lib/python3.7/site-packages/vispy/scene/canvas.py", line 266, in _draw_scene
    self.draw_visual(self.scene)
  File "/Users/talley/anaconda/envs/napdev/lib/python3.7/site-packages/vispy/scene/canvas.py", line 304, in draw_visual
    node.draw()
  File "/Users/talley/anaconda/envs/napdev/lib/python3.7/site-packages/vispy/scene/visuals.py", line 99, in draw
    self._visual_superclass.draw(self)
  File "/Users/talley/anaconda/envs/napdev/lib/python3.7/site-packages/vispy/visuals/visual.py", line 595, in draw
    v.draw()
  File "/Users/talley/anaconda/envs/napdev/lib/python3.7/site-packages/vispy/visuals/visual.py", line 595, in draw
    v.draw()
  File "/Users/talley/anaconda/envs/napdev/lib/python3.7/site-packages/vispy/visuals/visual.py", line 595, in draw
    v.draw()
  File "/Users/talley/anaconda/envs/napdev/lib/python3.7/site-packages/vispy/visuals/visual.py", line 443, in draw
    self._vshare.index_buffer)
  File "/Users/talley/anaconda/envs/napdev/lib/python3.7/site-packages/vispy/visuals/shaders/program.py", line 101, in draw
    Program.draw(self, *args, **kwargs)
  File "/Users/talley/anaconda/envs/napdev/lib/python3.7/site-packages/vispy/gloo/program.py", line 533, in draw
    canvas.context.flush_commands()
  File "/Users/talley/anaconda/envs/napdev/lib/python3.7/site-packages/vispy/gloo/context.py", line 176, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/Users/talley/anaconda/envs/napdev/lib/python3.7/site-packages/vispy/gloo/glir.py", line 572, in flush
    self._shared.flush(parser)
  File "/Users/talley/anaconda/envs/napdev/lib/python3.7/site-packages/vispy/gloo/glir.py", line 494, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/Users/talley/anaconda/envs/napdev/lib/python3.7/site-packages/vispy/gloo/glir.py", line 819, in parse
    self._parse(command)
  File "/Users/talley/anaconda/envs/napdev/lib/python3.7/site-packages/vispy/gloo/glir.py", line 779, in _parse
    ob.draw(*args)
  File "/Users/talley/anaconda/envs/napdev/lib/python3.7/site-packages/vispy/gloo/glir.py", line 1322, in draw
    gl.check_error('Check before draw')
  File "/Users/talley/anaconda/envs/napdev/lib/python3.7/site-packages/vispy/gloo/gl/__init__.py", line 207, in check_error
    raise err
RuntimeError: OpenGL got errors (Check before draw): GL_INVALID_VALUE
```
and the output of `vispy.sys_info`:
```
Platform: Darwin-18.2.0-x86_64-i386-64bit
Python:   3.7.5 (default, Oct 25 2019, 10:52:18)  [Clang 4.0.1 (tags/RELEASE_401/final)]
NumPy:    1.17.4
Backend:  PySide2
pyqt4:    None
pyqt5:    None
pyside:   None
pyside2:  ('PySide2', '5.13.2', '5.13.2')
pyglet:   None
glfw:     None
sdl2:     None
wx:       None
egl:      None
osmesa:   None
_test:    None
```

**Comment by djhoese** [comment]
Do you if this only happens with the PlotWidget or would something simpler like only a LineVisual trigger this? I'll try to find time to look at this tomorrow, but if you could try out a different visual that may help narrow this down even further. Have you tried PyQt5? I wonder if there is a chance we missed something PySide2 specific in the semi-recent updates to the Qt5 backend.

**Comment by tlambert03** [comment]
both good questions.  let me see both how simple I can make it, and whether it's backend specific.

**Comment by tlambert03** [comment]
still happens with PyQt5, and with a simple `LineVisual` added to a `SceneCanvas`

i changed the `QPlotWidget` in the above example to this:

```python
class QtPlotWidget(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.canvas = scene.SceneCanvas(bgcolor='k', keys=None, vsync=True)
        self.canvas.native.setMinimumSize(QSize(300, 100))
        self.setLayout(QtWidgets.QHBoxLayout())
        self.layout().addWidget(self.canvas.native)
        line = scene.visuals.Line(
            pos=np.array([[0, 0], [700, 500]]),
            color='w',
            parent=self.canvas.scene,
        )
```

and got more or less the same stack trace when floating the dock widget.
```
WARNING: Error drawing visual <vispy.visuals.line.line._GLLineVisual object at 0x12dbfa358>
WARNING: Traceback (most recent call last):

... same stack trace as above ...

RuntimeError: OpenGL got errors (Check before draw): GL_INVALID_VALUE
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt5) at 0x128eded68>> for DrawEvent
```

 For what it's worth, if I further remove the `LineVisual` from the `SceneCanvas` in this example, I no longer get the error, upon floating the `QDockWidget`, however when I re-attach the DockWidget to the mainwindow, the scene canvas background is transparent (I see fully through the main window to my desktop), until I resize the window or mouse-scroll on it, and then the scene background gets filled in black again.  (but simply moving it is not sufficient)

**Comment by djhoese** [comment]
Hm, well this should be a fun one to figure out. Can you start your script/application with `--vispy-log=debug --vispy-gl-debug` and see if you get any more useful information?

**Comment by tlambert03** [comment]
> Hm, well this should be a fun one to figure out.

hah, yeah, I'm sorry 😔... thanks for helping!  if you run out of ideas soon that's fine, I can keep hacking at it.   With the suggested debug logging, here's what I get (starting from the moment I click the float button on the dockwidget).  This is still with a single LineVisual on a canvas:
```
vispy.scene.canvas:SceneCanvas.on_draw(212): DEBUG: Canvas draw
vispy.visuals.shaders.program:ModularProgram.update_variables(145): DEBUG: Apply variables:
vispy.visuals.shaders.program:ModularProgram.update_variables(154): DEBUG:     a_position = <VertexBuffer size=2 last_dim=2>
vispy.visuals.shaders.program:ModularProgram.update_variables(154): DEBUG:     u_alpha = 1.0
vispy.visuals.shaders.program:ModularProgram.update_variables(154): DEBUG:     u_color = [1. 1. 1. 1.]
vispy.visuals.shaders.program:ModularProgram.update_variables(154): DEBUG:     u_enabled = 0
vispy.visuals.shaders.program:ModularProgram.update_variables(154): DEBUG:     u_id_color = [0.00392156862745098, 0.0, 0.0, 0.0]
vispy.visuals.shaders.program:ModularProgram.update_variables(154): DEBUG:     u_scale = [ 2. -2.  1.  1.]
vispy.visuals.shaders.program:ModularProgram.update_variables(154): DEBUG:     u_scale_1 = [1. 1. 1. 1.]
vispy.visuals.shaders.program:ModularProgram.update_variables(152): DEBUG:     u_scale_2 = [0.00147929 0.00210084 1.         1.        ] **
vispy.visuals.shaders.program:ModularProgram.update_variables(152): DEBUG:     u_translate = [  0. 952.   0.   0.] **
vispy.visuals.shaders.program:ModularProgram.update_variables(154): DEBUG:     u_translate_1 = [0. 0. 0. 0.]
vispy.visuals.shaders.program:ModularProgram.update_variables(154): DEBUG:     u_translate_2 = [-1. -1.  0.  0.]
vispy.visuals.shaders.program:ModularProgram.update_variables(160): DEBUG: Discarding unused variables before draw: dict_keys([])
vispy.gloo.program:ModularProgram.draw(526): DEBUG: Program drawing 'line_strip' with (0, 2)
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glEnable(34370)
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glEnable(34913)
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glBindFramebuffer(GL_FRAMEBUFFER, 1)
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glViewport(0, 0, 1352, 952)
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glClearColor(0.0, 0.0, 0.0, 1.0)
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glClear(17664)
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glDisable(GL_CULL_FACE)
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glEnable(GL_DEPTH_TEST)
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glEnable(GL_BLEND)
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glBlendFuncSeparate(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA, GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glBindBuffer(GL_ARRAY_BUFFER, 1)
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glBufferSubData(GL_ARRAY_BUFFER, 0, array:2x1)
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glBufferData(GL_ARRAY_BUFFER, array:2x1, GL_DYNAMIC_DRAW)
vispy.gloo.glir:GlirVertexBuffer.set_data(1392): DEBUG: Using glBufferData instead of glBufferSubData (known ATI bug).
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glUseProgram(1)
vispy.visuals.visual:_GLLineVisual.draw(445): WARNING: Error drawing visual <vispy.visuals.line.line._GLLineVisual object at 0x12188e128>
vispy.util.logs:log_exception(271): WARNING: Traceback (most recent call last):
  File "examples/vispy_dock.py", line 51, in <module>
    appQt.exec_()
  File "vispy/app/backends/_qt.py", line 501, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "vispy/app/backends/_qt.py", line 501, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "vispy/app/backends/_qt.py", line 818, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "vispy/scene/canvas.py", line 217, in on_draw
    self._draw_scene()
  File "vispy/scene/canvas.py", line 266, in _draw_scene
    self.draw_visual(self.scene)
  File "vispy/scene/canvas.py", line 304, in draw_visual
    node.draw()
  File "vispy/scene/visuals.py", line 99, in draw
    self._visual_superclass.draw(self)
  File "vispy/visuals/visual.py", line 595, in draw
    v.draw()
  File "vispy/visuals/visual.py", line 443, in draw
    self._vshare.index_buffer)
  File "vispy/visuals/shaders/program.py", line 101, in draw
    Program.draw(self, *args, **kwargs)
  File "vispy/gloo/program.py", line 533, in draw
    canvas.context.flush_commands()
  File "vispy/gloo/context.py", line 176, in flush_commands
    self.glir.flush(self.shared.parser)
  File "vispy/gloo/glir.py", line 572, in flush
    self._shared.flush(parser)
  File "vispy/gloo/glir.py", line 494, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "vispy/gloo/glir.py", line 819, in parse
    self._parse(command)
  File "vispy/gloo/glir.py", line 783, in _parse
    ob.set_uniform(*args)
  File "vispy/gloo/glir.py", line 1216, in set_uniform
    self.activate()
  File "vispy/gloo/glir.py", line 1070, in activate
    gl.glUseProgram(self._handle)
  File "vispy/gloo/gl/__init__.py", line 177, in gl_debug_wrapper
    check_error(fn.__name__)
  File "vispy/gloo/gl/__init__.py", line 207, in check_error
    raise err
RuntimeError: OpenGL got errors (glUseProgram): GL_INVALID_VALUE
vispy.util.logs:_handle_exception(325): ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt5) at 0x11ca7b978>> for DrawEvent
vispy.scene.canvas:SceneCanvas.on_draw(212): DEBUG: Canvas draw
vispy.visuals.shaders.program:ModularProgram.update_variables(145): DEBUG: Apply variables:
vispy.visuals.shaders.program:ModularProgram.update_variables(154): DEBUG:     a_position = <VertexBuffer size=2 last_dim=2>
vispy.visuals.shaders.program:ModularProgram.update_variables(154): DEBUG:     u_alpha = 1.0
vispy.visuals.shaders.program:ModularProgram.update_variables(154): DEBUG:     u_color = [1. 1. 1. 1.]
vispy.visuals.shaders.program:ModularProgram.update_variables(154): DEBUG:     u_enabled = 0
vispy.visuals.shaders.program:ModularProgram.update_variables(154): DEBUG:     u_id_color = [0.00392156862745098, 0.0, 0.0, 0.0]
vispy.visuals.shaders.program:ModularProgram.update_variables(154): DEBUG:     u_scale = [ 2. -2.  1.  1.]
vispy.visuals.shaders.program:ModularProgram.update_variables(154): DEBUG:     u_scale_1 = [1. 1. 1. 1.]
vispy.visuals.shaders.program:ModularProgram.update_variables(154): DEBUG:     u_scale_2 = [0.00147929 0.00210084 1.         1.        ]
vispy.visuals.shaders.program:ModularProgram.update_variables(154): DEBUG:     u_translate = [  0. 952.   0.   0.]
vispy.visuals.shaders.program:ModularProgram.update_variables(154): DEBUG:     u_translate_1 = [0. 0. 0. 0.]
vispy.visuals.shaders.program:ModularProgram.update_variables(154): DEBUG:     u_translate_2 = [-1. -1.  0.  0.]
vispy.visuals.shaders.program:ModularProgram.update_variables(160): DEBUG: Discarding unused variables before draw: dict_keys([])
vispy.gloo.program:ModularProgram.draw(526): DEBUG: Program drawing 'line_strip' with (0, 2)
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glEnable(34370)
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glEnable(34913)
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glBindFramebuffer(GL_FRAMEBUFFER, 1)
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glClearColor(0.0, 0.0, 0.0, 1.0)
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glClear(17664)
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glDisable(GL_CULL_FACE)
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glEnable(GL_DEPTH_TEST)
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glEnable(GL_BLEND)
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glBlendFuncSeparate(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA, GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glBindBuffer(GL_ARRAY_BUFFER, 1)
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glBufferSubData(GL_ARRAY_BUFFER, 0, array:2x1)
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glUseProgram(1)
vispy.visuals.visual:_GLLineVisual.draw(445): WARNING: Error drawing visual <vispy.visuals.line.line._GLLineVisual object at 0x12188e128>
vispy.util.logs:_handle_exception(331): ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt5) at 0x11ca7b978>> repeat 2


```

**Comment by tlambert03** [comment]
actually... I think this line is unique when it has the error:
```
vispy.gloo.gl:gl_debug_wrapper(167): DEBUG: glBufferData(GL_ARRAY_BUFFER, array:2x1, GL_DYNAMIC_DRAW)
vispy.gloo.glir:GlirVertexBuffer.set_data(1392): DEBUG: Using glBufferData instead of glBufferSubData (known ATI bug).
```

**Comment by marty-dy** [comment]
I assume no one is actively working this but as an additional note if `AA_ShareOpenGLContexts` is used the problem seems to go away.
```py
QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_ShareOpenGLContexts)
appQt = QtWidgets.QApplication(sys.argv)
```

**Comment by djhoese** [comment]
@marty-dy Very interesting. Is that in a PyQt5 application (not pyqt4)? We specifically turned off sharing opengl contexts for the pyqt5 backend if I remember correctly because it caused a lot of failures in our testing. If it seems to work with newer versions of PyQt5 then maybe we should try re-enabling it.

**Comment by marty-dy** [comment]
@djhoese I have not extensively tested it in vispy just using the above example and my own code, but it seems to work in PyQt5 5.9.6 and PySide2 5.15.1

**Comment by cboulay** [comment]
I'm using Linux Ubuntu, python 3.8.5, with pyqt5.15.1 (qtpy API), PyOpenGL 3.1.4, and vispy 0.6.5 (from GitHub today).

The two_qt_widgets.py has a similar error:
```
RuntimeError: OpenGL got errors (Check before draw): GL_INVALID_VALUE
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PyQt5) at 0x7f22800d1ac0>> for DrawEvent
```

Adding @marty-dy 's line fixes it.

**Comment by Czaki** [comment]
@brisvag Could you take a look at this? The error is still present https://forum.image.sc/t/multiple-viewer-in-one-napari-window-example/69627/6

**Comment by brisvag** [comment]
Uhm... but why would this be solved by sharing context? It seems like a strange solution.

Anyways, re-enabling sharing context is in the plans (to allow multicanvas in napari) but it might require a bit more work than just changing a line.

**Comment by Czaki** [comment]
> Uhm... but why would this be solved by sharing context? It seems like a strange solution.

because in Qt context is connected to the current window. So when you undock the widget, it is put in a separate window and needs its OpenGL context. You may check this by running multiple viewer examples. When you undock, it stop rendering and printing errors, but when you dock it again, it starts working with the proper view. 

So shared context or creating new context on undock widget is required to allow undock widgets with canvas.

**Comment by brisvag** [comment]
Oh, I see! It seems that I misunderstood what shared context meant so far: I thought that different *canvases* would require a different context, but you're saying that different canvases *in the same widget* don't? Cool!

**Comment by Czaki** [comment]
Yes. Until they are in the same window, I do not see any error.
