### ISSUE TITLE
Unpin numpy in pyproject.toml

### ISSUE THREAD

**Issue by anntzer** [vispy/vispy#1795]
Currently, pyproject.toml pins the supported numpy for Py3:
```
    "numpy==1.13.3; python_version=='3.5'",
￼    "numpy==1.13.3; python_version=='3.6'",
￼    "numpy==1.14.5; python_version>='3.7'",
```

Locally (Arch Linux Py38, system python), this causes a build failure in a clean venv:
```
Processing /tmp/foo/vispy
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /tmp/testenv/bin/python /tmp/testenv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpe2zfosrb
       cwd: /tmp/pip-req-build-yhub7l48
  Complete output (42 lines):
  Traceback (most recent call last):
    File "/tmp/pip-build-env-r9nw4ay2/overlay/lib/python3.8/site-packages/numpy/core/__init__.py", line 16, in <module>
      from . import multiarray
  ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/testenv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/tmp/testenv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/testenv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 91, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-r9nw4ay2/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-r9nw4ay2/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-r9nw4ay2/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 236, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-r9nw4ay2/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 36, in <module>
      import numpy as np
    File "/tmp/pip-build-env-r9nw4ay2/overlay/lib/python3.8/site-packages/numpy/__init__.py", line 142, in <module>
      from . import add_newdocs
    File "/tmp/pip-build-env-r9nw4ay2/overlay/lib/python3.8/site-packages/numpy/add_newdocs.py", line 13, in <module>
      from numpy.lib import add_newdoc
    File "/tmp/pip-build-env-r9nw4ay2/overlay/lib/python3.8/site-packages/numpy/lib/__init__.py", line 8, in <module>
      from .type_check import *
    File "/tmp/pip-build-env-r9nw4ay2/overlay/lib/python3.8/site-packages/numpy/lib/type_check.py", line 11, in <module>
      import numpy.core.numeric as _nx
    File "/tmp/pip-build-env-r9nw4ay2/overlay/lib/python3.8/site-packages/numpy/core/__init__.py", line 26, in <module>
      raise ImportError(msg)
  ImportError:
  Importing the multiarray numpy extension module failed.  Most
  likely you are trying to import a failed build of numpy.
  If you're working with a numpy git repo, try `git clean -xdf` (removes all
  files not under version control).  Otherwise reinstall numpy.
  
  Original error was: libopenblas.so.0: cannot open shared object file: No such file or directory
  
  ----------------------------------------
ERROR: Command errored out with exit status 1: /tmp/testenv/bin/python /tmp/testenv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpe2zfosrb Check the logs for full command output.
```

Unpinning numpy appears to fix the issue.

Is there a specific reason for the pin?

**Comment by djhoese** [comment]
Interesting...

I suppose this is an issue with the version of openblas that numpy was built with and the version installed on your system or by another package. I can't remember if @larsoner and I picked those versions from some other project or if there was a reason those exact versions were chosen.

I think starting with vispy 0.7.x we will drop python 2.7 and 3.5 support. I could see dropping 3.6 direct support shortly after. I'm guessing the main issue for you is that we don't have a python 3.8 version defined? Any idea how we define a fallback version for numpy?

What do you think about making a PR to add a fallback numpy version? If that isn't possible maybe a python 3.8 specific numpy version?

**Comment by anntzer** [comment]
The line
```
￼    "numpy==1.14.5; python_version>='3.7'",
```
also applies to py3.8.  I don't actually know what version would work across all distros for py3.8 (sure I can try locally for Arch Linux but that's not guaranteed to work on other systems).

**Comment by djhoese** [comment]
:man_facepalming: Oops didn't see the `>=`, nevermind then. Distro/platform compatibility should be something that numpy is concerned with.

So, what about a pull request changing that `>=3.7` line to allow for `>=1.14.5` of numpy?

**Comment by anntzer** [comment]
done in https://github.com/vispy/vispy/pull/1796.

**Comment by kmuehlbauer** [comment]
Closing as solved. Please reopen if needed.
