### ISSUE TITLE
test_functionality_pyopengl Fail

### ISSUE THREAD

**Issue by OverLordGoldDragon** [vispy/vispy#1838]
From `vispy.test()`; running the [galaxy.py](https://github.com/vispy/vispy/blob/master/examples/demo/gloo/galaxy/galaxy.py) example (and others) in JupyterLab yields `Error displaying widget: model not found`. Running straight from Anaconda Powershell Prompt gives the same results, and  Spyder fails even sooner.

Any fixes?

<hr>

**Install info**:

```
conda install -c conda-forge vispy

conda install -c conda-forge nodejs
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install vispy
```

I omitted [this step](http://vispy.org/installation.html#windows): adding Python to Nvidia-console's list of programs. What is "Nvidia console"? The control panel?

<hr>

**Environment info**:

 - Python 3.7.5, pyqt 5.9.2, qt 5.9.7, JupyterLab v1.2.3, conda 4.7.12, numpy 1.17.4
 - pyopengl 3.1.1a1
 - Windows 10 OS, GTX 1070

<hr>

**Code sample**:

```python
%gui qt
!jupyter kernelspec list
```
```
Available kernels:
  python3    D:\Anaconda\envs\viz\share\jupyter\kernels\python3
```
```
import vispy
print(vispy.sys_info())
```

```
Platform: Windows-10-10.0.18362-SP0
Python:   3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]
NumPy:    1.17.4
Backend:  ipynb_webgl
pyqt4:    None
pyqt5:    ('PyQt5', '5.9.2', '5.9.6')
pyside:   None
pyside2:  None
pyglet:   None
glfw:     None
sdl2:     None
wx:       None
egl:      None
osmesa:   None
_test:    None

GL version:  ''
MAX_TEXTURE_SIZE: ()
Extensions: ''
App info-gathering error:
Traceback (most recent call last):
  File "D:\Anaconda\envs\viz\lib\site-packages\vispy\util\config.py", line 438, in sys_info
    canvas.close()
  File "D:\Anaconda\envs\viz\lib\site-packages\vispy\app\canvas.py", line 457, in close
    self._backend._vispy_close()
  File "D:\Anaconda\envs\viz\lib\site-packages\vispy\app\backends\_ipynb_webgl.py", line 203, in _vispy_close
    raise NotImplementedError()
NotImplementedError
```

<hr>

**Terminal log**: 

<details>
  <summary>Click to expand</summary>

```python
_____________________________________________ test_functionality_pyopengl _____________________________________________

self = <OpenGL.platform.baseplatform.glGetActiveAttrib object at 0x000001EDDCE21C88>, args = (2, 0)
named = {'bufSize': 256}

    def __call__( self, *args, **named ):
        """Call self._finalCall, calling finalise() first if not already called

        There's actually *no* reason to unpack and repack the arguments,
        but unfortunately I don't know of a Cython syntax to specify
        that.
        """
        try:
>           return self._finalCall( *args, **named )
E           TypeError: 'NoneType' object is not callable

OpenGL\latebind.py:41: TypeError

During handling of the above exception, another exception occurred:

args = (), kwargs = {}

    def skipper_func(*args, **kwargs):
        """Skipper for normal test functions."""
        if skip_val():
            raise SkipTest(get_msg(f, msg))
        else:
>           return f(*args, **kwargs)

numpy\testing\_private\decorators.py:155:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
vispy\testing\_testing.py:232: in deco
    return f(*args, **kwargs)
numpy\testing\_private\decorators.py:155: in skipper_func
    return f(*args, **kwargs)
vispy\gloo\gl\tests\test_functionality.py:62: in test_functionality_pyopengl
    _test_functionality('pyopengl2')
vispy\gloo\gl\tests\test_functionality.py:96: in _test_functionality
    objects = _prepare_vis()
vispy\gloo\gl\tests\test_functionality.py:295: in _prepare_vis
    name, count, type = gl.glGetActiveAttrib(hprog, i)
vispy\gloo\gl\_pyopengl2.py:88: in glGetActiveAttrib
    name, size, type = GL.glGetActiveAttrib(program, index, bufSize=bufsize)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <OpenGL.platform.baseplatform.glGetActiveAttrib object at 0x000001EDDCE21C88>, args = (2, 0)
named = {'bufSize': 256}

    def __call__( self, *args, **named ):
        """Call self._finalCall, calling finalise() first if not already called

        There's actually *no* reason to unpack and repack the arguments,
        but unfortunately I don't know of a Cython syntax to specify
        that.
        """
        try:
            return self._finalCall( *args, **named )
        except (TypeError,AttributeError) as err:
            if self._finalCall is None:
                self._finalCall = self.finalise()
>           return self._finalCall( *args, **named )
E           TypeError: wrapperCall() got an unexpected keyword argument 'bufSize'

OpenGL\latebind.py:45: TypeError
================================================== warnings summary ===================================================
vispy/visuals/tests/test_axis.py::test_axis_zero_domain
  D:\Anaconda\envs\viz\lib\site-packages\vispy\visuals\axis.py:378: RuntimeWarning: invalid value encountered in true_divide
    major_frac = (major - offset) / scale

vispy/visuals/tests/test_axis.py::test_axis_zero_domain
  D:\Anaconda\envs\viz\lib\site-packages\vispy\visuals\axis.py:379: RuntimeWarning: invalid value encountered in true_divide
    minor_frac = (np.array(minor) - offset) / scale

vispy/visuals/tests/test_axis.py::test_axis_zero_domain
  D:\Anaconda\envs\viz\lib\site-packages\vispy\visuals\axis.py:381: RuntimeWarning: invalid value encountered in greater
    use_mask = (major_frac > -0.0001) & (major_frac < 1.0001)

vispy/visuals/tests/test_axis.py::test_axis_zero_domain
  D:\Anaconda\envs\viz\lib\site-packages\vispy\visuals\axis.py:381: RuntimeWarning: invalid value encountered in less
    use_mask = (major_frac > -0.0001) & (major_frac < 1.0001)

vispy/visuals/tests/test_axis.py::test_axis_zero_domain
  D:\Anaconda\envs\viz\lib\site-packages\vispy\visuals\axis.py:384: RuntimeWarning: invalid value encountered in greater
    minor_frac = minor_frac[(minor_frac > -0.0001) &

vispy/visuals/tests/test_axis.py::test_axis_zero_domain
  D:\Anaconda\envs\viz\lib\site-packages\vispy\visuals\axis.py:385: RuntimeWarning: invalid value encountered in less
    (minor_frac < 1.0001)]

-- Docs: https://docs.pytest.org/en/latest/warnings.html
============== 1 failed, 72 passed, 4 skipped, 447 deselected, 1 xfailed, 6 warnings in 63.99s (0:01:03) ==============
```
</details>

<hr>

**Terminal log 2**: (last test - may be unimportant)

<details>
  <summary>Click to expand</summary>

```python
__________________________________ test_font_glyph[Bahnschrift SemiBold SemiConden] ___________________________________

face = 'Bahnschrift SemiBold SemiConden'

    @pytest.mark.parametrize('face', ['OpenSans'] + sorted(sys_fonts))
    def test_font_glyph(face):
        """Test loading glyphs"""
        if face in known_bad_fonts:
            pytest.xfail()
        font_dict = dict(face=face, size=12, bold=False, italic=False)
        glyphs_dict = dict()
        chars = 'foobar^C&#'
        for char in chars:
            # Warning that Arial might not exist
            with warnings.catch_warnings(record=True):
                warnings.simplefilter('always')
>               _load_glyph(font_dict, char, glyphs_dict)

vispy\util\fonts\tests\test_font.py:40:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
vispy\util\fonts\_freetype.py:50: in _load_glyph
    face = _load_font(f['face'], f['bold'], f['italic'])
vispy\util\fonts\_freetype.py:36: in _load_font
    fname = find_font(face, bold, italic)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

face = 'Bahnschrift SemiBold SemiConden', bold = False, italic = False, orig_face = None

    def find_font(face, bold, italic, orig_face=None):
        style_dict = {'Regular': 0, 'Bold': 1, 'Italic': 2, 'Bold Italic': 3}

        # Figure out which font to actually use by trying to instantiate by name
        dc = user32.GetDC(0)  # noqa, analysis:ignore
        gdi32.SetGraphicsMode(dc, GM_ADVANCED)  # only TT and OT fonts
        logfont = LOGFONT()
        logfont.lfHeight = -12  # conv point to pixels
        logfont.lfWeight = FW_BOLD if bold else FW_NORMAL
        logfont.lfItalic = italic
        logfont.lfFaceName = face  # logfont needs Unicode
        hfont = gdi32.CreateFontIndirectW(byref(logfont))
        original = gdi32.SelectObject(dc, hfont)
        n_byte = gdi32.GetOutlineTextMetricsW(dc, 0, None)
        assert n_byte > 0
        metrics = OUTLINETEXTMETRIC()
        assert sizeof(metrics) >= n_byte
        assert gdi32.GetOutlineTextMetricsW(dc, n_byte, byref(metrics))
        gdi32.SelectObject(dc, original)
        user32.ReleaseDC(None, dc)
        use_face = cast(byref(metrics, metrics.otmpFamilyName), c_wchar_p).value
        if use_face != face:
            warnings.warn('Could not find face match "%s", falling back to "%s"'
                          % (orig_face or face, use_face))
        use_style = cast(byref(metrics, metrics.otmpStyleName), c_wchar_p).value
        use_style = style_dict.get(use_style, 'Regular')
        # AK: I get "Standaard" for use_style, which is Dutch for standard/regular

        # Now we match by creating private font collections until we find
        # the one that was used
        font_dir = op.join(os.environ['WINDIR'], 'Fonts')
        reg = winreg.ConnectRegistry(None, winreg.HKEY_LOCAL_MACHINE)
        key = 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Fonts'
        reg_vals = winreg.OpenKey(reg, key)
        n_values = winreg.QueryInfoKey(reg_vals)[1]
        fname = None
        for vi in range(n_values):
            name, ff = winreg.EnumValue(reg_vals, vi)[:2]
            if name.endswith('(TrueType)'):
                ff = op.join(font_dir, ff) if op.basename(ff) == ff else ff
                assert op.isfile(ff)
                pc = c_void_p()
                assert gdiplus.GdipNewPrivateFontCollection(byref(pc)) == 0
                gdiplus.GdipPrivateAddFontFile(pc, ff)
                family = c_void_p()
                if gdiplus.GdipCreateFontFamilyFromName(use_face, pc,
                                                        byref(family)) == 0:
                    val = BOOL()
                    assert gdiplus.GdipIsStyleAvailable(family, use_style,
                                                        byref(val)) == 0
                    if val.value:
                        buf = create_unicode_buffer(LF_FACESIZE)
                        assert gdiplus.GdipGetFamilyName(family, buf, 0) == 0
>                       assert buf.value == use_face
E                       AssertionError

vispy\util\fonts\_win32.py:79: AssertionError
__________________________________ test_font_glyph[Bahnschrift SemiLight SemiConde] ___________________________________

face = 'Bahnschrift SemiLight SemiConde'

    @pytest.mark.parametrize('face', ['OpenSans'] + sorted(sys_fonts))
    def test_font_glyph(face):
        """Test loading glyphs"""
        if face in known_bad_fonts:
            pytest.xfail()
        font_dict = dict(face=face, size=12, bold=False, italic=False)
        glyphs_dict = dict()
        chars = 'foobar^C&#'
        for char in chars:
            # Warning that Arial might not exist
            with warnings.catch_warnings(record=True):
                warnings.simplefilter('always')
>               _load_glyph(font_dict, char, glyphs_dict)

vispy\util\fonts\tests\test_font.py:40:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
vispy\util\fonts\_freetype.py:50: in _load_glyph
    face = _load_font(f['face'], f['bold'], f['italic'])
vispy\util\fonts\_freetype.py:36: in _load_font
    fname = find_font(face, bold, italic)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

face = 'Bahnschrift SemiLight SemiConde', bold = False, italic = False, orig_face = None

    def find_font(face, bold, italic, orig_face=None):
        style_dict = {'Regular': 0, 'Bold': 1, 'Italic': 2, 'Bold Italic': 3}

        # Figure out which font to actually use by trying to instantiate by name
        dc = user32.GetDC(0)  # noqa, analysis:ignore
        gdi32.SetGraphicsMode(dc, GM_ADVANCED)  # only TT and OT fonts
        logfont = LOGFONT()
        logfont.lfHeight = -12  # conv point to pixels
        logfont.lfWeight = FW_BOLD if bold else FW_NORMAL
        logfont.lfItalic = italic
        logfont.lfFaceName = face  # logfont needs Unicode
        hfont = gdi32.CreateFontIndirectW(byref(logfont))
        original = gdi32.SelectObject(dc, hfont)
        n_byte = gdi32.GetOutlineTextMetricsW(dc, 0, None)
        assert n_byte > 0
        metrics = OUTLINETEXTMETRIC()
        assert sizeof(metrics) >= n_byte
        assert gdi32.GetOutlineTextMetricsW(dc, n_byte, byref(metrics))
        gdi32.SelectObject(dc, original)
        user32.ReleaseDC(None, dc)
        use_face = cast(byref(metrics, metrics.otmpFamilyName), c_wchar_p).value
        if use_face != face:
            warnings.warn('Could not find face match "%s", falling back to "%s"'
                          % (orig_face or face, use_face))
        use_style = cast(byref(metrics, metrics.otmpStyleName), c_wchar_p).value
        use_style = style_dict.get(use_style, 'Regular')
        # AK: I get "Standaard" for use_style, which is Dutch for standard/regular

        # Now we match by creating private font collections until we find
        # the one that was used
        font_dir = op.join(os.environ['WINDIR'], 'Fonts')
        reg = winreg.ConnectRegistry(None, winreg.HKEY_LOCAL_MACHINE)
        key = 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Fonts'
        reg_vals = winreg.OpenKey(reg, key)
        n_values = winreg.QueryInfoKey(reg_vals)[1]
        fname = None
        for vi in range(n_values):
            name, ff = winreg.EnumValue(reg_vals, vi)[:2]
            if name.endswith('(TrueType)'):
                ff = op.join(font_dir, ff) if op.basename(ff) == ff else ff
                assert op.isfile(ff)
                pc = c_void_p()
                assert gdiplus.GdipNewPrivateFontCollection(byref(pc)) == 0
                gdiplus.GdipPrivateAddFontFile(pc, ff)
                family = c_void_p()
                if gdiplus.GdipCreateFontFamilyFromName(use_face, pc,
                                                        byref(family)) == 0:
                    val = BOOL()
                    assert gdiplus.GdipIsStyleAvailable(family, use_style,
                                                        byref(val)) == 0
                    if val.value:
                        buf = create_unicode_buffer(LF_FACESIZE)
                        assert gdiplus.GdipGetFamilyName(family, buf, 0) == 0
>                       assert buf.value == use_face
E                       AssertionError

vispy\util\fonts\_win32.py:79: AssertionError
================================================== warnings summary ===================================================
vispy/app/tests/test_ipython.py::test_webgl_loading
  D:\Anaconda\envs\viz\lib\site-packages\vispy\app\backends\ipython\_widget.py:61: DeprecationWarning: metadata {'value': True} was set from the constructor. With traitlets 4.1, metadata should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='value2')
    resizable = Bool(value=True).tag(sync=True)

vispy/app/tests/test_ipython.py::test_webgl_loading
  D:\Anaconda\envs\viz\lib\site-packages\vispy\ipython\ipython.py:41: DeprecationWarning: InteractiveShell.write() is deprecated, use sys.stdout instead
    ipython.write("Vispy IPython module has loaded successfully")

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=============================== 2 failed, 443 passed, 80 skipped, 2 warnings in 57.75s ================================
```

</details>

**Comment by kmuehlbauer** [comment]
@OverLordGoldDragon Could you upgrade to pyopengl 3.1.4? There have been issues before that version...

**Comment by OverLordGoldDragon** [comment]
@kmuehlbauer That fixed the first terminal log's error, thanks - though second persists, and first shows "1xfailed". Also running galaxy.py and high_frequency.py give same errors (`Error displaying widget: model not found`; didn't test all examples.

**Comment by djhoese** [comment]
Additionally, I'm not sure I would expect the `galaxy.py` example to load in a jupyter lab interface. At least not with a lot of performance.

If `sys_info` isn't giving you an OpenGL version that usually means there is something wrong with the way OpenGL is installed on your system (your GPU drivers). Until we get `sys_info` to work on another backend, could you *not* use the jupyter backend.

**Comment by djhoese** [comment]
Oh also when did you install vispy? Today? Last couple hours? I *just* updated the `vispy.js` library that is uses underneath. This shouldn't have messed anything up but I wouldn't be surprised.

**Comment by OverLordGoldDragon** [comment]
@djhoese Then what's the recommended way to run vispy? Straight from terminal, Spyder, ...? And I installed vispy via [`conda-forge`](https://anaconda.org/conda-forge/vispy), version `0.6.4`, same as [PyPi's](https://pypi.org/project/vispy/).

**Comment by djhoese** [comment]
Yes, but when you install the jupyterlab extension they bring in a `vispy.js` library automatically which I updated ~5 hours ago.

As mentioned in http://vispy.org/installation.html#jupyter-notebook-extension, the Jupyter extension for VisPy is experimental. The recommended way of running VisPy is with a GUI backend like PyQt5/Pyside2 or Wx or other GUI framework.

**Comment by OverLordGoldDragon** [comment]
@djhoese I actually didn't install the Jupyter _notebook_ extension, I thought it's separate from JupyterLab (is it?). So would below undo the jupyterlab installs?

```
jupyter labextension uninstall @jupyter-widgets/jupyterlab-manager
jupyter labextension uninstall vispy
```

**Comment by djhoese** [comment]
> I actually didn't install the Jupyter notebook extension,

They rely on the same javascript and python code but are installed/initialized differently. You don't *need* to uninstall them depending on what your goal is. The first thing to test would be that `sys_info()` from a normal python (or ipython) window works. Spyder is a little iffy and we've had problems with getting things to show up without forcing the backend in the past.

**Comment by OverLordGoldDragon** [comment]
Anaconda Powershell Prompt results below; any insight?


```
Platform: Windows-10-10.0.18362-SP0
Python:   3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]
NumPy:    1.17.4
Backend:  PyQt5
pyqt4:    None
pyqt5:    ('PyQt5', '5.9.2', '5.9.6')
pyside:   None
pyside2:  None
pyglet:   None
glfw:     None
sdl2:     None
wx:       None
egl:      None
osmesa:   None
_test:    None

GL version:  '4.6.0 NVIDIA 436.48'
MAX_TEXTURE_SIZE: 32768
Extensions: 
```

<details>
  <summary>Click to expand</summary>

```
'GL_AMD_multi_draw_indirect
GL_AMD_seamless_cubemap_per_texture
GL_AMD_vertex_shader_viewport_index
GL_AMD_vertex_shader_layer
GL_ARB_arrays_of_arrays
GL_ARB_base_instance
GL_ARB_bindless_texture
GL_ARB_blend_func_extended
GL_ARB_buffer_storage
GL_ARB_clear_buffer_object
GL_ARB_clear_texture
GL_ARB_clip_control
GL_ARB_color_buffer_float
GL_ARB_compatibility
GL_ARB_compressed_texture_pixel_storage
GL_ARB_conservative_depth
GL_ARB_compute_shader
GL_ARB_compute_variable_group_size
GL_ARB_conditional_render_inverted
GL_ARB_copy_buffer
GL_ARB_copy_image
GL_ARB_cull_distance
GL_ARB_debug_output
GL_ARB_depth_buffer_float
GL_ARB_depth_clamp
GL_ARB_depth_texture
GL_ARB_derivative_control
GL_ARB_direct_state_access
GL_ARB_draw_buffers
GL_ARB_draw_buffers_blend
GL_ARB_draw_indirect
GL_ARB_draw_elements_base_vertex
GL_ARB_draw_instanced
GL_ARB_enhanced_layouts
GL_ARB_ES2_compatibility
GL_ARB_ES3_compatibility
GL_ARB_ES3_1_compatibility
GL_ARB_ES3_2_compatibility
GL_ARB_explicit_attrib_location
GL_ARB_explicit_uniform_location
GL_ARB_fragment_coord_conventions
GL_ARB_fragment_layer_viewport
GL_ARB_fragment_program
GL_ARB_fragment_program_shadow
GL_ARB_fragment_shader
GL_ARB_fragment_shader_interlock
GL_ARB_framebuffer_no_attachments
GL_ARB_framebuffer_object
GL_ARB_framebuffer_sRGB
GL_ARB_geometry_shader4
GL_ARB_get_program_binary
GL_ARB_get_texture_sub_image
GL_ARB_gl_spirv
GL_ARB_gpu_shader5
GL_ARB_gpu_shader_fp64
GL_ARB_gpu_shader_int64
GL_ARB_half_float_pixel
GL_ARB_half_float_vertex
GL_ARB_imaging
GL_ARB_indirect_parameters
GL_ARB_instanced_arrays
GL_ARB_internalformat_query
GL_ARB_internalformat_query2
GL_ARB_invalidate_subdata
GL_ARB_map_buffer_alignment
GL_ARB_map_buffer_range
GL_ARB_multi_bind
GL_ARB_multi_draw_indirect
GL_ARB_multisample
GL_ARB_multitexture
GL_ARB_occlusion_query
GL_ARB_occlusion_query2
GL_ARB_parallel_shader_compile
GL_ARB_pipeline_statistics_query
GL_ARB_pixel_buffer_object
GL_ARB_point_parameters
GL_ARB_point_sprite
GL_ARB_polygon_offset_clamp
GL_ARB_post_depth_coverage
GL_ARB_program_interface_query
GL_ARB_provoking_vertex
GL_ARB_query_buffer_object
GL_ARB_robust_buffer_access_behavior
GL_ARB_robustness
GL_ARB_sample_locations
GL_ARB_sample_shading
GL_ARB_sampler_objects
GL_ARB_seamless_cube_map
GL_ARB_seamless_cubemap_per_texture
GL_ARB_separate_shader_objects
GL_ARB_shader_atomic_counter_ops
GL_ARB_shader_atomic_counters
GL_ARB_shader_ballot
GL_ARB_shader_bit_encoding
GL_ARB_shader_clock
GL_ARB_shader_draw_parameters
GL_ARB_shader_group_vote
GL_ARB_shader_image_load_store
GL_ARB_shader_image_size
GL_ARB_shader_objects
GL_ARB_shader_precision
GL_ARB_shader_storage_buffer_object
GL_ARB_shader_subroutine
GL_ARB_shader_texture_image_samples
GL_ARB_shader_texture_lod
GL_ARB_shading_language_100
GL_ARB_shader_viewport_layer_array
GL_ARB_shading_language_420pack
GL_ARB_shading_language_include
GL_ARB_shading_language_packing
GL_ARB_shadow
GL_ARB_sparse_buffer
GL_ARB_sparse_texture
GL_ARB_sparse_texture2
GL_ARB_sparse_texture_clamp
GL_ARB_spirv_extensions
GL_ARB_stencil_texturing
GL_ARB_sync
GL_ARB_tessellation_shader
GL_ARB_texture_barrier
GL_ARB_texture_border_clamp
GL_ARB_texture_buffer_object
GL_ARB_texture_buffer_object_rgb32
GL_ARB_texture_buffer_range
GL_ARB_texture_compression
GL_ARB_texture_compression_bptc
GL_ARB_texture_compression_rgtc
GL_ARB_texture_cube_map
GL_ARB_texture_cube_map_array
GL_ARB_texture_env_add
GL_ARB_texture_env_combine
GL_ARB_texture_env_crossbar
GL_ARB_texture_env_dot3
GL_ARB_texture_filter_anisotropic
GL_ARB_texture_filter_minmax
GL_ARB_texture_float
GL_ARB_texture_gather
GL_ARB_texture_mirror_clamp_to_edge
GL_ARB_texture_mirrored_repeat
GL_ARB_texture_multisample
GL_ARB_texture_non_power_of_two
GL_ARB_texture_query_levels
GL_ARB_texture_query_lod
GL_ARB_texture_rectangle
GL_ARB_texture_rg
GL_ARB_texture_rgb10_a2ui
GL_ARB_texture_stencil8
GL_ARB_texture_storage
GL_ARB_texture_storage_multisample
GL_ARB_texture_swizzle
GL_ARB_texture_view
GL_ARB_timer_query
GL_ARB_transform_feedback2
GL_ARB_transform_feedback3
GL_ARB_transform_feedback_instanced
GL_ARB_transform_feedback_overflow_query
GL_ARB_transpose_matrix
GL_ARB_uniform_buffer_object
GL_ARB_vertex_array_bgra
GL_ARB_vertex_array_object
GL_ARB_vertex_attrib_64bit
GL_ARB_vertex_attrib_binding
GL_ARB_vertex_buffer_object
GL_ARB_vertex_program
GL_ARB_vertex_shader
GL_ARB_vertex_type_10f_11f_11f_rev
GL_ARB_vertex_type_2_10_10_10_rev
GL_ARB_viewport_array
GL_ARB_window_pos
GL_ATI_draw_buffers
GL_ATI_texture_float
GL_ATI_texture_mirror_once
GL_S3_s3tc
GL_EXT_texture_env_add
GL_EXT_abgr
GL_EXT_bgra
GL_EXT_bindable_uniform
GL_EXT_blend_color
GL_EXT_blend_equation_separate
GL_EXT_blend_func_separate
GL_EXT_blend_minmax
GL_EXT_blend_subtract
GL_EXT_compiled_vertex_array
GL_EXT_Cg_shader
GL_EXT_depth_bounds_test
GL_EXT_direct_state_access
GL_EXT_draw_buffers2
GL_EXT_draw_instanced
GL_EXT_draw_range_elements
GL_EXT_fog_coord
GL_EXT_framebuffer_blit
GL_EXT_framebuffer_multisample
GL_EXTX_framebuffer_mixed_formats
GL_EXT_framebuffer_multisample_blit_scaled
GL_EXT_framebuffer_object
GL_EXT_framebuffer_sRGB
GL_EXT_geometry_shader4
GL_EXT_gpu_program_parameters
GL_EXT_gpu_shader4
GL_EXT_multi_draw_arrays
GL_EXT_multiview_texture_multisample
GL_EXT_multiview_timer_query
GL_EXT_packed_depth_stencil
GL_EXT_packed_float
GL_EXT_packed_pixels
GL_EXT_pixel_buffer_object
GL_EXT_point_parameters
GL_EXT_polygon_offset_clamp
GL_EXT_post_depth_coverage
GL_EXT_provoking_vertex
GL_EXT_raster_multisample
GL_EXT_rescale_normal
GL_EXT_secondary_color
GL_EXT_separate_shader_objects
GL_EXT_separate_specular_color
GL_EXT_shader_image_load_formatted
GL_EXT_shader_image_load_store
GL_EXT_shader_integer_mix
GL_EXT_shadow_funcs
GL_EXT_sparse_texture2
GL_EXT_stencil_two_side
GL_EXT_stencil_wrap
GL_EXT_texture3D
GL_EXT_texture_array
GL_EXT_texture_buffer_object
GL_EXT_texture_compression_dxt1
GL_EXT_texture_compression_latc
GL_EXT_texture_compression_rgtc
GL_EXT_texture_compression_s3tc
GL_EXT_texture_cube_map
GL_EXT_texture_edge_clamp
GL_EXT_texture_env_combine
GL_EXT_texture_env_dot3
GL_EXT_texture_filter_anisotropic
GL_EXT_texture_filter_minmax
GL_EXT_texture_integer
GL_EXT_texture_lod
GL_EXT_texture_lod_bias
GL_EXT_texture_mirror_clamp
GL_EXT_texture_object
GL_EXT_texture_shared_exponent
GL_EXT_texture_sRGB
GL_EXT_texture_sRGB_R8
GL_EXT_texture_sRGB_decode
GL_EXT_texture_storage
GL_EXT_texture_swizzle
GL_EXT_timer_query
GL_EXT_transform_feedback2
GL_EXT_vertex_array
GL_EXT_vertex_array_bgra
GL_EXT_vertex_attrib_64bit
GL_EXT_window_rectangles
GL_EXT_import_sync_object
GL_IBM_rasterpos_clip
GL_IBM_texture_mirrored_repeat
GL_KHR_context_flush_control
GL_KHR_debug
GL_EXT_memory_object
GL_EXT_memory_object_win32
GL_EXT_win32_keyed_mutex
GL_KHR_parallel_shader_compile
GL_KHR_no_error
GL_KHR_robust_buffer_access_behavior
GL_KHR_robustness
GL_EXT_semaphore
GL_EXT_semaphore_win32
GL_KHR_shader_subgroup
GL_KTX_buffer_region
GL_NV_alpha_to_coverage_dither_control
GL_NV_bindless_multi_draw_indirect
GL_NV_bindless_multi_draw_indirect_count
GL_NV_bindless_texture
GL_NV_blend_equation_advanced
GL_NV_blend_equation_advanced_coherent
GL_NVX_blend_equation_advanced_multi_draw_buffers
GL_NV_blend_minmax_factor
GL_NV_blend_square
GL_NV_clip_space_w_scaling
GL_NV_command_list
GL_NV_compute_program5
GL_NV_conditional_render
GL_NV_conservative_raster
GL_NV_conservative_raster_dilate
GL_NV_conservative_raster_pre_snap_triangles
GL_NV_copy_depth_to_color
GL_NV_copy_image
GL_NV_depth_buffer_float
GL_NV_depth_clamp
GL_NV_draw_texture
GL_NV_draw_vulkan_image
GL_NV_ES1_1_compatibility
GL_NV_ES3_1_compatibility
GL_NV_explicit_multisample
GL_NV_feature_query
GL_NV_fence
GL_NV_fill_rectangle
GL_NV_float_buffer
GL_NV_fog_distance
GL_NV_fragment_coverage_to_color
GL_NV_fragment_program
GL_NV_fragment_program_option
GL_NV_fragment_program2
GL_NV_fragment_shader_interlock
GL_NV_framebuffer_mixed_samples
GL_NV_framebuffer_multisample_coverage
GL_NV_geometry_shader4
GL_NV_geometry_shader_passthrough
GL_NV_gpu_program4
GL_NV_internalformat_sample_query
GL_NV_gpu_program4_1
GL_NV_gpu_program5
GL_NV_gpu_program5_mem_extended
GL_NV_gpu_program_fp64
GL_NV_gpu_shader5
GL_NV_half_float
GL_NV_light_max_exponent
GL_NV_memory_attachment
GL_NV_multisample_coverage
GL_NV_multisample_filter_hint
GL_NV_occlusion_query
GL_NV_packed_depth_stencil
GL_NV_parameter_buffer_object
GL_NV_parameter_buffer_object2
GL_NV_path_rendering
GL_NV_path_rendering_shared_edge
GL_NV_pixel_data_range
GL_NV_point_sprite
GL_NV_primitive_restart
GL_NV_query_resource
GL_NV_query_resource_tag
GL_NV_register_combiners
GL_NV_register_combiners2
GL_NV_sample_locations
GL_NV_sample_mask_override_coverage
GL_NV_shader_atomic_counters
GL_NV_shader_atomic_float
GL_NV_shader_atomic_float64
GL_NV_shader_atomic_fp16_vector
GL_NV_shader_atomic_int64
GL_NV_shader_buffer_load
GL_NV_shader_storage_buffer_object
GL_NV_shader_subgroup_partitioned
GL_NV_stereo_view_rendering
GL_NV_texgen_reflection
GL_NV_texture_barrier
GL_NV_texture_compression_vtc
GL_NV_texture_env_combine4
GL_NV_texture_multisample
GL_NV_texture_rectangle
GL_NV_texture_rectangle_compressed
GL_NV_texture_shader
GL_NV_texture_shader2
GL_NV_texture_shader3
GL_NV_transform_feedback
GL_NV_transform_feedback2
GL_NV_uniform_buffer_unified_memory
GL_NV_vertex_array_range
GL_NV_vertex_array_range2
GL_NV_vertex_attrib_integer_64bit
GL_NV_vertex_buffer_unified_memory
GL_NV_vertex_program
GL_NV_vertex_program1_1
GL_NV_vertex_program2
GL_NV_vertex_program2_option
GL_NV_vertex_program3
GL_NV_viewport_array2
GL_NV_viewport_swizzle
GL_NVX_conditional_render
GL_NVX_linked_gpu_multicast
GL_NV_gpu_multicast
GL_NVX_gpu_multicast2
GL_NVX_progress_fence
GL_NVX_gpu_memory_info
GL_NVX_multigpu_info
GL_NVX_nvenc_interop
GL_NV_shader_thread_group
GL_NV_shader_thread_shuffle
GL_KHR_blend_equation_advanced
GL_KHR_blend_equation_advanced_coherent
GL_OVR_multiview
GL_OVR_multiview2
GL_SGIS_generate_mipmap
GL_SGIS_texture_lod
GL_SGIX_depth_texture
GL_SGIX_shadow
GL_SUN_slice_accum
GL_WIN_swap_hint
WGL_EXT_swap_control'
```

</details>

**Comment by djhoese** [comment]
That looks good to me. You didn't get any errors and you have an actual GL version listed. If you run `python example_script.py` do they work?

**Comment by OverLordGoldDragon** [comment]
Indeed, all examples work, pretty nice - thanks. So I'm guessing the idea is to run a full script each time from terminal, instead of working on it interactively? I could create some nice timeseries convolutional neural net visuals based on `realtime_signals.py` - glad that one's included.

**Comment by djhoese** [comment]
Because of the nature of GUI framework's event loops, VisPy is typically used in an application/script. Changing the data or visuals over time can be fine, but interactively can get very difficult.
