### ISSUE TITLE
Backend detection failure in NVIDIA-Docker

### ISSUE THREAD

**Issue by guillemglez** [vispy/vispy#1848]
We are trying to Vispy to run some shader code in a GPU-accelerated machine. For this, we use Docker, based on [Nvidia's official images for Python](https://ngc.nvidia.com/catalog/containers/nvidia:tensorflow), in which CUDA libraries are linked out-of-the-box, enabling us to use GPU acceleration within the containers.

Since the only interface is CLI, and we want to perform image processing without an X server, we deemed EGL as the backend we need.

We struggle to make Vispy detect EGL. So far what we tried installing `mesa-utils-extra libegl1-mesa-dev libgles2-mesa-dev` and cloning EGL to `/include/lib` and setting the `EGL_LIBRARY` environment variable, but this does not seem to work.

This is the output we get:

```bash
$ python -c "import vispy; print(vispy.sys_info())"
Platform: Linux-4.9.0-4-amd64-x86_64-with-debian-buster-sid
Python:   3.7.3 (default, Apr  8 2020, 08:58:11)  [GCC 8.4.0]
NumPy:    1.18.2
App info-gathering error:
Traceback (most recent call last):
  File "/home/lumos/.local/share/virtualenvs/nnls_gpu-sSnrWYhY/lib/python3.7/site-packages/vispy/util/config.py", line 422, in sys_info
    app = use_app(call_reuse=False)  # suppress messages
  File "/home/lumos/.local/share/virtualenvs/nnls_gpu-sSnrWYhY/lib/python3.7/site-packages/vispy/app/_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "/home/lumos/.local/share/virtualenvs/nnls_gpu-sSnrWYhY/lib/python3.7/site-packages/vispy/app/application.py", line 49, in __init__
    self._use(backend_name)
  File "/home/lumos/.local/share/virtualenvs/nnls_gpu-sSnrWYhY/lib/python3.7/site-packages/vispy/app/application.py", line 256, in _use
    'PyQt' % [b[0] for b in CORE_BACKENDS])
RuntimeError: Could not import any of the backends. You need to install any of ['PyQt4', 'PyQt5', 'PySide', 'PySide2', 'Pyglet', 'Glfw', 'SDL2', 'wx', 'EGL', 'osmesa']. We recommend PyQt
```

Thank you for your help!

**Comment by djhoese** [comment]
There are some known issues with the EGL backend and it hasn't been thoroughly tested in quite some time (none of the core devs are using it at this time). There are some pull requests and issues that exist to discuss the limitations or future changes that are needed. The most important is this comment from @yogi81 who was the last person to work on the EGL backend:

https://github.com/vispy/vispy/pull/1637#issuecomment-491343195

Things to look for:

https://github.com/vispy/vispy/blob/8387ea1aac961224488657ff57d1794f4e68ab32/vispy/app/backends/_egl.py#L20-L45

And it sounds like you've already looked at:

https://github.com/vispy/vispy/blob/8387ea1aac961224488657ff57d1794f4e68ab32/vispy/app/backends/_egl.py#L20-L45

Could you try running:

```
python -c "import vispy.app; vispy.app.use_app('egl')"
```

And see if that gives you a better error message. If not, maybe `from vispy.app.backends import _egl`. Based on the `_egl.py` module I wouldn't be surprised if you need to create a virtual display (xvfb). Any idea if you are doing that?

**Comment by guillemglez** [comment]
Thank you very much for your detailed advice and help!
Vispy was already being capable of finding EGL on its own (no need to set `EGL_LIBRARY`) but failed to initialize since it could not find any display.

Below the steps I followed:

1. Install `mesa-utils-extra libegl1-mesa-dev libgles2-mesa-dev`

2. Initialize a virtual display:

```bash
Xvfb :0 -screen 0 1024x768x24 -ac +extension GLX +render -noreset &
```

3. Set the DISPLAY variable:

```bash
export DISPLAY=:0
```

4. It works!

```bash
$ python -c "import vispy; print(vispy.sys_info())"
Platform: Linux-4.9.0-4-amd64-x86_64-with-debian-buster-sid
Python:   3.7.3 (default, Apr  8 2020, 08:58:11)  [GCC 8.4.0]
NumPy:    1.18.2
Backend:  egl
pyqt4:    None
pyqt5:    None
pyside:   None
pyside2:  None
pyglet:   None
glfw:     None
sdl2:     None
wx:       None
egl:      EGL 1.4 Mesa Project: OpenGL OpenGL_ES
osmesa:   None
_test:    None

GL version:  '3.1 Mesa 19.2.8'
MAX_TEXTURE_SIZE: 8192
```

I will close the issue the issue since it is already solved. Thank you!

**Comment by djhoese** [comment]
Great! I'm glad you got it working and thanks so much for all the steps you took. This will come in handy the next time we get an EGL question.

**Comment by lxin81** [comment]
I ran Vispy for 3d model screenshots on docker server with Xvfb. This method can be run, but it runs very slowly. Compared with 50 seconds for native MAC, it takes nearly 30 minutes on docker server.  Do you know why？

**Comment by yogi81** [comment]
> I ran Vispy for 3d model screenshots on docker server with Xvfb. This
> method can be run, but it runs very slowly. Compared with 50 seconds for
> native MAC, it takes nearly 30 minutes on docker server.  Do you know
> whyï¼
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/vispy/vispy/issues/1848#issuecomment-641016849

Which OS do you run in docker? Is it Linux? On mac Linux in docker runs
only with a very slow emulation.

**Comment by lxin81** [comment]
> I ran Vispy for 3d model screenshots on docker server with Xvfb. This method can be run, but it runs very slowly. Compared with 50 seconds for native MAC, it takes nearly 30 minutes on docker server. Do you know whyï¼ -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#1848 (comment)](https://github.com/vispy/vispy/issues/1848#issuecomment-641016849)
> Which OS do you run in docker? Is it Linux? On mac Linux in docker runs only with a very slow emulation.

Docker is run on a remote server， Ubuntu systems，with GPU 24G

**Comment by djhoese** [comment]
Same version of python? Same number of cores given to the docker container? Are you sure the docker container has access to the GPU (and isn't falling back to some integrated graphics)? There are a lot of variables here so it is hard to say what's going on. If you can run on the server with Xvfb virtual display or if you can run this on your Mac under docker then that might give us more data points to debug this. We'd need to find out what's causing the slow downs. Is it because it is run in docker? Is it because there are less CPU cores being used? Is it because the wrong GPU is being used? Is it this Ubuntu system for some reason? Is it the virtual display doing something funky?

**Comment by LvJC** [comment]
> Thank you very much for your detailed advice and help! Vispy was already being capable of finding EGL on its own (no need to set `EGL_LIBRARY`) but failed to initialize since it could not find any display.
> 
> Below the steps I followed:
> 
> 1. Install `mesa-utils-extra libegl1-mesa-dev libgles2-mesa-dev xvfb`
> 2. Initialize a virtual display:
> 
> ```shell
> Xvfb :0 -screen 0 1024x768x24 -ac +extension GLX +render -noreset &
> ```
> 
> 3. Set the DISPLAY variable:
> 
> ```shell
> export DISPLAY=:0
> ```
> 
> 4. It works!
> 
> ```shell
> $ python -c "import vispy; print(vispy.sys_info())"
> Platform: Linux-4.9.0-4-amd64-x86_64-with-debian-buster-sid
> Python:   3.7.3 (default, Apr  8 2020, 08:58:11)  [GCC 8.4.0]
> NumPy:    1.18.2
> Backend:  egl
> pyqt4:    None
> pyqt5:    None
> pyside:   None
> pyside2:  None
> pyglet:   None
> glfw:     None
> sdl2:     None
> wx:       None
> egl:      EGL 1.4 Mesa Project: OpenGL OpenGL_ES
> osmesa:   None
> _test:    None
> 
> GL version:  '3.1 Mesa 19.2.8'
> MAX_TEXTURE_SIZE: 8192
> ```
> 
> I will close the issue the issue since it is already solved. Thank you!

Thanks, it really works! But it seems to work much slower than before.

**Comment by djhoese** [comment]
> But it seems to work much slower than before.

Much slower than what? Running it non-docker with a different backend? Or slower than what?

**Comment by LvJC** [comment]
> > But it seems to work much slower than before.
> 
> Much slower than what? Running it non-docker with a different backend? Or slower than what?

Compared docker EGL backend with a virtual display as @guillemglez suggested to non-docker EGL backend, it's 2.3x slower. I can shared the sys info here:
1. docker EGL backend with a virtual display
```
Platform: Linux-4.15.0-42-generic-x86_64-with-Ubuntu-18.04-bionic
Python:   3.7.13 (default, Apr 24 2022, 01:04:09)  [GCC 7.5.0]
NumPy:    1.21.6
Backend:  Glfw
pyqt4:    None
pyqt5:    None
pyside:   None
pyside2:  None
pyglet:   None
glfw:     glfw (3, 2, 1)
sdl2:     None
wx:       None
egl:      EGL 1.4 Mesa Project: OpenGL OpenGL_ES
osmesa:   None
_test:    None

GL version:  '3.1 Mesa 20.0.8'
MAX_TEXTURE_SIZE: 8192
Extensions: 'GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_ATI_fragment_shader GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_depth_clamp GL_NV_fog_distance GL_APPLE_packed_pixels GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_MESA_ycbcr_texture GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_ATI_texture_compression_3dc GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_ATI_texture_mirror_once GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_texture_array GL_EXT_texture_compression_latc GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_EXT_texture_buffer_object GL_AMD_texture_texture4 GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_buffer_object GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_conservative_depth GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_ARB_ES2_compatibility GL_ARB_blend_func_extended GL_ARB_compatibility GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_stencil_export GL_ARB_shader_texture_lod GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_multisample GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_ARB_draw_indirect GL_ARB_get_program_binary GL_ARB_robustness GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_subroutine GL_ARB_texture_compression_bptc GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_viewport_array GL_EXT_direct_state_access GL_AMD_multi_draw_indirect GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_base_instance GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_shader_atomic_counters GL_ARB_shader_image_load_store GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_ARB_transform_feedback_instanced GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_transform_feedback GL_AMD_query_buffer_object GL_AMD_shader_trinary_minmax GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_clear_buffer_object GL_ARB_compute_shader GL_ARB_copy_image GL_ARB_explicit_uniform_location GL_ARB_fragment_layer_viewport GL_ARB_framebuffer_no_attachments GL_ARB_invalidate_subdata GL_ARB_multi_draw_indirect GL_ARB_program_interface_query GL_ARB_shader_image_size GL_ARB_shader_storage_buffer_object GL_ARB_stencil_texturing GL_ARB_texture_buffer_range GL_ARB_texture_query_levels GL_ARB_texture_storage_multisample GL_ARB_texture_view GL_ARB_vertex_attrib_binding GL_KHR_debug GL_KHR_texture_compression_astc_ldr GL_ARB_buffer_storage GL_ARB_clear_texture GL_ARB_enhanced_layouts GL_ARB_indirect_parameters GL_ARB_internalformat_query2 GL_ARB_multi_bind GL_ARB_query_buffer_object GL_ARB_seamless_cubemap_per_texture GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shading_language_include GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_stencil8 GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_shader_integer_mix GL_ARB_clip_control GL_ARB_conditional_render_inverted GL_ARB_cull_distance GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_get_texture_sub_image GL_ARB_pipeline_statistics_query GL_ARB_transform_feedback_overflow_query GL_EXT_polygon_offset_clamp GL_KHR_context_flush_control GL_ARB_parallel_shader_compile GL_ARB_shader_atomic_counter_ops GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_MESA_shader_integer_functions GL_ARB_polygon_offset_clamp GL_KHR_parallel_shader_compile GL_EXT_EGL_image_storage GL_EXT_texture_sRGB_R8 GL_EXT_EGL_sync '
```
2. non-docker, ssh, conda, EGL backend
```
Platform: Linux-4.15.0-42-generic-x86_64-with-debian-stretch-sid
Python:   3.7.11 (default, Jul 27 2021, 14:32:16)  [GCC 7.5.0]
NumPy:    1.21.3
Backend:  egl
pyqt4:    None
pyqt5:    None
pyqt6:    None
pyside:   None
pyside2:  None
pyside6:  None
pyglet:   None
glfw:     None
sdl2:     None
wx:       None
egl:      EGL 1.5 NVIDIA: OpenGL_ES OpenGL
osmesa:   OSMesa
tkinter:  None
jupyter_rfb: None
_test:    None

GL version:  '4.6.0 NVIDIA 440.33.01'
MAX_TEXTURE_SIZE: 32768
Extensions: 'GL_AMD_multi_draw_indirect GL_AMD_seamless_cubemap_per_texture GL_AMD_vertex_shader_viewport_index GL_AMD_vertex_shader_layer GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_fragment_shader_interlock GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_post_depth_coverage GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_locations GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shader_viewport_layer_array GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_sparse_buffer GL_ARB_sparse_texture GL_ARB_sparse_texture2 GL_ARB_sparse_texture_clamp GL_ARB_spirv_extensions GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_filter_anisotropic GL_ARB_texture_filter_minmax GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ARB_window_pos GL_ATI_draw_buffers GL_ATI_texture_float GL_ATI_texture_mirror_once GL_S3_s3tc GL_EXT_texture_env_add GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_Cg_shader GL_EXT_depth_bounds_test GL_EXT_direct_state_access GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_draw_range_elements GL_EXT_EGL_image_storage GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXTX_framebuffer_mixed_formats GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_multiview_texture_multisample GL_EXT_multiview_timer_query GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_polygon_offset_clamp GL_EXT_post_depth_coverage GL_EXT_provoking_vertex GL_EXT_raster_multisample GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_shader_objects GL_EXT_separate_specular_color GL_EXT_shader_image_load_formatted GL_EXT_shader_image_load_store GL_EXT_shader_integer_mix GL_EXT_shadow_funcs GL_EXT_sparse_texture2 GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture3D GL_EXT_texture_array GL_EXT_texture_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_latc GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_filter_minmax GL_EXT_texture_integer GL_EXT_texture_lod GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_object GL_EXT_texture_shadow_lod GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_decode GL_EXT_texture_storage GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback2 GL_EXT_vertex_array GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_EXT_window_rectangles GL_EXT_import_sync_object GL_NV_robustness_video_memory_purge GL_IBM_rasterpos_clip GL_IBM_texture_mirrored_repeat GL_KHR_context_flush_control GL_KHR_debug GL_EXT_memory_object GL_EXT_memory_object_fd GL_KHR_parallel_shader_compile GL_KHR_no_error GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_EXT_semaphore GL_EXT_semaphore_fd GL_KHR_shader_subgroup GL_KTX_buffer_region GL_NV_alpha_to_coverage_dither_control GL_NV_bindless_multi_draw_indirect GL_NV_bindless_multi_draw_indirect_count GL_NV_bindless_texture GL_NV_blend_equation_advanced GL_NV_blend_equation_advanced_coherent GL_NVX_blend_equation_advanced_multi_draw_buffers GL_NV_blend_minmax_factor GL_NV_blend_square GL_NV_clip_space_w_scaling GL_NV_command_list GL_NV_compute_program5 GL_NV_conditional_render GL_NV_conservative_raster GL_NV_conservative_raster_dilate GL_NV_conservative_raster_pre_snap GL_NV_conservative_raster_pre_snap_triangles GL_NV_conservative_raster_underestimation GL_NV_copy_depth_to_color GL_NV_copy_image GL_NV_depth_buffer_float GL_NV_depth_clamp GL_NV_draw_texture GL_NV_draw_vulkan_image GL_NV_ES1_1_compatibility GL_NV_ES3_1_compatibility GL_NV_explicit_multisample GL_NV_feature_query GL_NV_fence GL_NV_fill_rectangle GL_NV_float_buffer GL_NV_fog_distance GL_NV_fragment_coverage_to_color GL_NV_fragment_program GL_NV_fragment_program_option GL_NV_fragment_program2 GL_NV_fragment_shader_interlock GL_NV_framebuffer_mixed_samples GL_NV_framebuffer_multisample_coverage GL_NV_geometry_shader4 GL_NV_geometry_shader_passthrough GL_NV_gpu_program4 GL_NV_internalformat_sample_query GL_NV_gpu_program4_1 GL_NV_gpu_program5 GL_NV_gpu_program5_mem_extended GL_NV_gpu_program_fp64 GL_NV_gpu_shader5 GL_NV_half_float GL_NV_light_max_exponent GL_NV_memory_attachment GL_NV_multisample_coverage GL_NV_multisample_filter_hint GL_NV_occlusion_query GL_NV_packed_depth_stencil GL_NV_parameter_buffer_object GL_NV_parameter_buffer_object2 GL_NV_path_rendering GL_NV_path_rendering_shared_edge GL_NV_point_sprite GL_NV_primitive_restart GL_NV_query_resource GL_NV_query_resource_tag GL_NV_register_combiners GL_NV_register_combiners2 GL_NV_sample_locations GL_NV_sample_mask_override_coverage GL_NV_shader_atomic_counters GL_NV_shader_atomic_float GL_NV_shader_atomic_float64 GL_NV_shader_atomic_fp16_vector GL_NV_shader_atomic_int64 GL_NV_shader_buffer_load GL_NV_shader_storage_buffer_object GL_NV_shader_subgroup_partitioned GL_NV_stereo_view_rendering GL_NV_texgen_reflection GL_NV_texture_barrier GL_NV_texture_compression_vtc GL_NV_texture_env_combine4 GL_NV_texture_multisample GL_NV_texture_rectangle GL_NV_texture_rectangle_compressed GL_NV_texture_shader GL_NV_texture_shader2 GL_NV_texture_shader3 GL_NV_transform_feedback GL_NV_transform_feedback2 GL_NV_uniform_buffer_unified_memory GL_NV_vertex_attrib_integer_64bit GL_NV_vertex_buffer_unified_memory GL_NV_vertex_program GL_NV_vertex_program1_1 GL_NV_vertex_program2 GL_NV_vertex_program2_option GL_NV_vertex_program3 GL_NV_viewport_array2 GL_NV_viewport_swizzle GL_NVX_conditional_render GL_NV_gpu_multicast GL_NVX_progress_fence GL_NVX_gpu_memory_info GL_NV_shader_thread_group GL_NV_shader_thread_shuffle GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OVR_multiview GL_OVR_multiview2 GL_SGIS_generate_mipmap GL_SGIS_texture_lod GL_SGIX_depth_texture GL_SGIX_shadow GL_SUN_slice_accum '
```

**Comment by djhoese** [comment]
Interesting. Looks like the NVIDIA GPU drivers aren't being accessed from within docker. I'm really not sure how that kind of thing works or if it is supposed to so hopefully others can chime in.

**Comment by wwdok** [comment]
> Thank you very much for your detailed advice and help! Vispy was already being capable of finding EGL on its own (no need to set `EGL_LIBRARY`) but failed to initialize since it could not find any display.
> 
> Below the steps I followed:
> 
> 1. Install `mesa-utils-extra libegl1-mesa-dev libgles2-mesa-dev xvfb`
> 2. Initialize a virtual display:
> 
> ```shell
> Xvfb :0 -screen 0 1024x768x24 -ac +extension GLX +render -noreset &
> ```
> 
> 3. Set the DISPLAY variable:
> 
> ```shell
> export DISPLAY=:0
> ```
> 
> 4. It works!
> 
> ```shell
> $ python -c "import vispy; print(vispy.sys_info())"
> Platform: Linux-4.9.0-4-amd64-x86_64-with-debian-buster-sid
> Python:   3.7.3 (default, Apr  8 2020, 08:58:11)  [GCC 8.4.0]
> NumPy:    1.18.2
> Backend:  egl
> pyqt4:    None
> pyqt5:    None
> pyside:   None
> pyside2:  None
> pyglet:   None
> glfw:     None
> sdl2:     None
> wx:       None
> egl:      EGL 1.4 Mesa Project: OpenGL OpenGL_ES
> osmesa:   None
> _test:    None
> 
> GL version:  '3.1 Mesa 19.2.8'
> MAX_TEXTURE_SIZE: 8192
> ```
> 
> I will close the issue the issue since it is already solved. Thank you!

  I follow above step, but at the end I execute `python -c "import vispy; print(vispy.sys_info())"`, it throw error:
```
WARNING: could not determine DPI
WARNING: Could not load the Qt platform plugin "xcb" in "" even though it was found.
WARNING: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
```
my environment is docker with ubuntu 20.0.4

**Comment by djhoese** [comment]
@wwdok please create a new issue and describe your installation steps, build steps, and all versions (including host OS and docker image tag).
