### ISSUE TITLE
Initialize ColorArray from list of color fail 

### ISSUE THREAD

**Issue by Czaki** [vispy/vispy#1858]
When initialising `CollorArray` from list of `Colors` it fails. It works if on list there is at least one definition color with string.

This works:
```python
array1 = ColorArray(["b", "w"])
array2 = ColorArray(["black", "white"])
array3 = ColorArray(["black", Color((1, 1, 1))])
```

This fails:
```python
array4 = ColorArray([Color((0,0,0)), Color((1, 1, 1))])
```
with:
```
TypeError: float() argument must be a string or a number, not 'ColorArray'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/czaki/Projekty/partseg/vispy_test.py", line 6, in <module>
    array4 = ColorArray([Color((0,0,0)), Color((1, 1, 1))])
  File "/home/czaki/.pyenv/versions/partseg3.6-pyside/lib/python3.6/site-packages/vispy/color/color_array.py", line 148, in __init__
    rgba = _user_to_rgba(color, clip=clip)
  File "/home/czaki/.pyenv/versions/partseg3.6-pyside/lib/python3.6/site-packages/vispy/color/color_array.py", line 55, in _user_to_rgba
    color = np.atleast_2d(color).astype(np.float32)
ValueError: setting an array element with a sequence.
```

**Comment by kmuehlbauer** [comment]
Too many options in that if-else convolute:

https://github.com/vispy/vispy/blob/f1de04c52269d4288030b641d652afdac8e77183/vispy/color/color_array.py#L40-L55

In line 50 we would need to add `ColorArray` in the isinstance-check, for that to work, AFAICS. PullRequest welcome :smiley:
