### ISSUE TITLE
updating_property breaks sphinx docs generation

### ISSUE THREAD

**Issue by djhoese** [vispy/vispy#1862]
This seems to come from the `updating_property` added as part of #1792. When I run:

```
python make website html
```

It ends in an exception where it leads to a log file with:

```
Traceback (most recent call last):
  File "/home/davidh/miniconda3/envs/vispy_pyqt5_py37/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/davidh/miniconda3/envs/vispy_pyqt5_py37/lib/python3.7/site-packages/sphinx/application.py", line 348, in build
    self.builder.build_update()
  File "/home/davidh/miniconda3/envs/vispy_pyqt5_py37/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/home/davidh/miniconda3/envs/vispy_pyqt5_py37/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/home/davidh/miniconda3/envs/vispy_pyqt5_py37/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/home/davidh/miniconda3/envs/vispy_pyqt5_py37/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/home/davidh/miniconda3/envs/vispy_pyqt5_py37/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/davidh/miniconda3/envs/vispy_pyqt5_py37/lib/python3.7/site-packages/sphinx/io.py", line 221, in read_doc
    pub.publish()
  File "/home/davidh/miniconda3/envs/vispy_pyqt5_py37/lib/python3.7/site-packages/docutils/core.py", line 219, in publish
    self.apply_transforms()
  File "/home/davidh/miniconda3/envs/vispy_pyqt5_py37/lib/python3.7/site-packages/docutils/core.py", line 200, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/home/davidh/miniconda3/envs/vispy_pyqt5_py37/lib/python3.7/site-packages/sphinx/transforms/__init__.py", line 86, in apply_transforms
    super().apply_transforms()
  File "/home/davidh/miniconda3/envs/vispy_pyqt5_py37/lib/python3.7/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/home/davidh/miniconda3/envs/vispy_pyqt5_py37/lib/python3.7/site-packages/sphinx/transforms/__init__.py", line 376, in apply
    self.app.emit('doctree-read', self.document)
  File "/home/davidh/miniconda3/envs/vispy_pyqt5_py37/lib/python3.7/site-packages/sphinx/application.py", line 445, in emit
    return self.events.emit(event, *args)
  File "/home/davidh/miniconda3/envs/vispy_pyqt5_py37/lib/python3.7/site-packages/sphinx/events.py", line 107, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/davidh/miniconda3/envs/vispy_pyqt5_py37/lib/python3.7/site-packages/sphinx/ext/linkcode.py", line 60, in doctree_read
    uri = resolve_target(domain, info)
  File "/home/davidh/repos/git/vispy/_website/conf.py", line 401, in linkcode_resolve
    source, lineno = inspect.getsourcelines(obj)
  File "/home/davidh/miniconda3/envs/vispy_pyqt5_py37/lib/python3.7/inspect.py", line 955, in getsourcelines
    lines, lnum = findsource(object)
  File "/home/davidh/miniconda3/envs/vispy_pyqt5_py37/lib/python3.7/inspect.py", line 768, in findsource
    file = getsourcefile(object)
  File "/home/davidh/miniconda3/envs/vispy_pyqt5_py37/lib/python3.7/inspect.py", line 684, in getsourcefile
    filename = getfile(object)
  File "/home/davidh/miniconda3/envs/vispy_pyqt5_py37/lib/python3.7/inspect.py", line 666, in getfile
    type(object).__name__))
TypeError: module, class, method, function, traceback, frame, or code object was expected, got updating_property
```

CC @tlambert03

**Comment by tlambert03** [comment]
just submitted a patch (more than a fix) at https://github.com/vispy/vispy-website/pull/28 

very odd error...
