### ISSUE TITLE
Undefined symbol during installation on a clean virtualenv

### ISSUE THREAD

**Issue by lightspot21** [vispy/vispy#1895]
I'm trying to install the latest version of vispy under a `pipenv` environment, but installation fails with the following error:

```
   ERROR: Command errored out with exit status 1:
   command: /home/lightspot21/.local/share/virtualenvs/vispy-test-ZpCqmU5I/bin/python3 /home/lightspot21/.local/share/virtualenvs/vispy-test-ZpCqmU5I/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpqtfbl43g
       cwd: /tmp/pip-install-1amtdn8j/vispy
  Complete output (42 lines):
  Traceback (most recent call last):
    File "/tmp/pip-build-env-r6b47mh2/overlay/lib/python3.8/site-packages/numpy/core/__init__.py", line 16, in <module>
      from . import multiarray
  ImportError: /tmp/pip-build-env-r6b47mh2/overlay/lib/python3.8/site-packages/numpy/core/multiarray.cpython-38-x86_64-linux-gnu.so: undefined symbol: cblas_cdotc_sub
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/lightspot21/.local/share/virtualenvs/vispy-test-ZpCqmU5I/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/lightspot21/.local/share/virtualenvs/vispy-test-ZpCqmU5I/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/lightspot21/.local/share/virtualenvs/vispy-test-ZpCqmU5I/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-r6b47mh2/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-r6b47mh2/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-r6b47mh2/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 248, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-r6b47mh2/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 36, in <module>
      import numpy as np
    File "/tmp/pip-build-env-r6b47mh2/overlay/lib/python3.8/site-packages/numpy/__init__.py", line 142, in <module>
      from . import add_newdocs
    File "/tmp/pip-build-env-r6b47mh2/overlay/lib/python3.8/site-packages/numpy/add_newdocs.py", line 13, in <module>
      from numpy.lib import add_newdoc
    File "/tmp/pip-build-env-r6b47mh2/overlay/lib/python3.8/site-packages/numpy/lib/__init__.py", line 8, in <module>
      from .type_check import *
    File "/tmp/pip-build-env-r6b47mh2/overlay/lib/python3.8/site-packages/numpy/lib/type_check.py", line 11, in <module>
      import numpy.core.numeric as _nx
    File "/tmp/pip-build-env-r6b47mh2/overlay/lib/python3.8/site-packages/numpy/core/__init__.py", line 26, in <module>
      raise ImportError(msg)
  ImportError:
  Importing the multiarray numpy extension module failed.  Most
  likely you are trying to import a failed build of numpy.
  If you're working with a numpy git repo, try `git clean -xdf` (removes all
  files not under version control).  Otherwise reinstall numpy.
  
  Original error was: /tmp/pip-build-env-r6b47mh2/overlay/lib/python3.8/site-packages/numpy/core/multiarray.cpython-38-x86_64-linux-gnu.so: undefined symbol: cblas_cdotc_sub
  
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/lightspot21/.local/share/virtualenvs/vispy-test-ZpCqmU5I/bin/python3 /home/lightspot21/.local/share/virtualenvs/vispy-test-ZpCqmU5I/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpqtfbl43g Check the logs for full command output.
```

I've trying clearing cache, using clean environments in both `virtualenv` and `pipenv`, and reinstalled numpy as instructed by the thrown error, but nothing worked.

**Python version:** 3.8.0
**vispy version:** 0.6.4

Thanks in advance!

**Comment by djhoese** [comment]
Are you able to run `python -c "import numpy"` from the terminal in these environment?

**Comment by djhoese** [comment]
And also, what version of pip are you using?

**Comment by lightspot21** [comment]
@djhoese I'm running pip 20.1.1 (on Manjaro 20.0.3). `python -c "import numpy"` runs correctly, the error shows up when trying to install vispy.

**Comment by djhoese** [comment]
What if you try installing from github:

```
pip install git+https://github.com/vispy/vispy.git
```

I'm 90% all our recent changes to setup.py have been released but this may be worth a shot. We don't currently have a wheel released for python 3.8. We should have the proper `pyproject.toml` stuff for this to install (actually this may have been recently updated to work for py38 so maybe the github install will work).

**Comment by lightspot21** [comment]
Installing from git did the trick. Thank you!

**Comment by djhoese** [comment]
Great, glad it worked. This should be fixed in the next release. It is an issue with a missing numpy dependency for python 3.8 in our pyproject.toml that hasn't been released yet.
