### ISSUE TITLE
Error instantiating ZColormapFilter

### ISSUE THREAD

**Issue by HaaPut** [vispy/vispy#1916]
I was trying out an example of filters using following modified version vispy lines example 
```python
import numpy as np
from vispy import app, visuals
from vispy.visuals.transforms import STTransform
from vispy.visuals.filters import ZColormapFilter

# vertex positions of data to draw
N = 400
pos = np.zeros((N, 2), dtype=np.float32)
pos[:, 0] = np.linspace(0, 350, N)
pos[:, 1] = np.random.normal(size=N, scale=20, loc=0)


class Canvas(app.Canvas):
    def __init__(self):
        self.line = visuals.LineVisual(pos=pos)
        self.line.transform = STTransform(translate=(0, 50))
        self.filter = ZColormapFilter('fire')
        self.line.attach(self.filter)
        app.Canvas.__init__(self, keys='interactive', size=(800, 800))
        self.show(True)

    def on_draw(self, ev):
        self.context.clear('black', depth=True)
        self.line.draw()


if __name__ == '__main__':
    win = Canvas()
    import sys

    if sys.flags.interactive != 1:
        app.run()

```
I get the following error, which I think is a bug.

> Traceback (most recent call last):
  File "vispyExample.py", line 29, in <module>
    win = Canvas()
  File "vispyExample.py", line 18, in __init__
    self.filter = ZColormapFilter('fire')
  File "/home/path/lib/python3.7/site-packages/vispy/visuals/filters/color.py", line 174, in __init__
    self.fshader['cmap'] = self.cmap
  File "/home/path/lib/python3.7/site-packages/vispy/visuals/shaders/function.py", line 210, in __setitem__
    raise KeyError('Invalid template variable %r' % key)
KeyError: "Invalid template variable 'cmap'"

Vispy version: 0.6.4

**Comment by kmuehlbauer** [comment]
@HaaPut Thanks for reporting. It looks like `ZColormapFilter` is currently broken.

**Comment by kmuehlbauer** [comment]
In the implementation of ZColormapFilter `FRAG_SHADER` and `VERT_SHADER` shader code is swapped. But this doesn't help, because `position` can't be retrieved from `visual.shared_program.vert['position']` (`KeyError`).

See: https://github.com/vispy/vispy/blob/1a900cf8f5bbb34b1b0ff356457001aa071988f1/vispy/visuals/filters/color.py#L154-L181

The only other mention of ZColormapFilter is in:

https://github.com/vispy/vispy/blob/a6ec64bb7b56739b463e3c16245a31940ca4f5f7/examples/basics/scene/surface_plot.py#L34-L37

but it's out-commented there. I'm unsure if this ever worked.

**Comment by djhoese** [comment]
@kmuehlbauer I think this was a typo when converting these filters to be from the same base class. See:

https://github.com/vispy/vispy/commit/288e248bdacf7cd3de777627afcd50d54fc31ce7#diff-7887cec54bcb1d547ebb27477d343aa4L163-L173

**Comment by kmuehlbauer** [comment]
@djhoese Yes, and we didn't catch it because it isn't tested :-(  But anyway, I've fixed this locally but the `position` problem remains...

```
  File "/home/kai/miniconda3/envs/vispy_new/lib/python3.8/site-packages/vispy/visuals/visual.py", line 644, in attach
    v.attach(filt, v)
  File "/home/kai/miniconda3/envs/vispy_new/lib/python3.8/site-packages/vispy/visuals/visual.py", line 492, in attach
    filt._attach(view)
  File "/home/kai/miniconda3/envs/vispy_new/lib/python3.8/site-packages/vispy/visuals/filters/color.py", line 191, in _attach
    self.position(visual.shared_program.vert['position'])
  File "/home/kai/miniconda3/envs/vispy_new/lib/python3.8/site-packages/vispy/visuals/shaders/multiprogram.py", line 136, in __getitem__
    return self._set_items[key]
KeyError: 'position'
```

**Comment by djhoese** [comment]
What is this line:

```
self.position(visual.shared_program.vert['position'])
```

I don't see it.

**Comment by kmuehlbauer** [comment]
I've tested locally, It's this line: self.vshader['position'] = visual.shared_program.vert['position']

**Comment by djhoese** [comment]
But why does it show up like that in the error log? The color.py in master doesn't have 191 lines. I'm not sure I understand `self.position(...)`.

**Comment by kmuehlbauer** [comment]
I've added a position property locally...Below without my fiddling:

```
    self.line.attach(self.filter)
  File "/home/kai/miniconda3/envs/vispy_new/lib/python3.8/site-packages/vispy/visuals/visual.py", line 644, in attach
    v.attach(filt, v)
  File "/home/kai/miniconda3/envs/vispy_new/lib/python3.8/site-packages/vispy/visuals/visual.py", line 492, in attach
    filt._attach(view)
  File "/home/kai/miniconda3/envs/vispy_new/lib/python3.8/site-packages/vispy/visuals/filters/color.py", line 182, in _attach
    self.vshader['position'] = visual.shared_program.vert['position']
  File "/home/kai/miniconda3/envs/vispy_new/lib/python3.8/site-packages/vispy/visuals/shaders/multiprogram.py", line 136, in __getitem__
    return self._set_items[key]
KeyError: 'position'
```

**Comment by djhoese** [comment]
From what I can gather the problem is that the filter is trying to get access to the `position` buffer of the LineVisual. However, that doesn't get set in the LineVisual until draw time. This may differ from how other Visuals in vispy work which at least attach various buffers before the draw and then set the data later.

However, if I try to hack a solution that grabs the buffer directly I get:

```
TypeError: Unknown data type <class 'vispy.gloo.buffer.VertexBuffer'> for variable <Variable "None None position" at 0x7f21f4590090>
```

Likely because the buffer hasn't been properly set in the LineVisual yet or because the shader in the filter doesn't have a type defined for it. I'm not sure how to interpret the error message.
