### ISSUE TITLE
RuntimeError when taking a screenshot inside a QGraphicsProxyWidget's embedded Canvas

### ISSUE THREAD

**Issue by Kusefiru** [vispy/vispy#2021]
Hey,

My app is using a vispy `app.Canvas` embedded inside a `QGraphicsProxyWidget`.
Using the `_screenshot` method cause a `RuntimeError` and result in a fully transparent image.

I have done a few researched and noticed the following :
- First, the issue is not directly caused by the `_screenshot` method, but seems caused by a `drawEvent` emitted somewhat after. Is it an event sent by Vispy or Qt ?
- Second, by adding a native `app.Canvas` widget alongside my `QGraphicsView` widget (which embeds the QGraphicsProxyWidget one) ,the first screenshot is taken correctly with no error. But when taking a second screenshot, as soon as the focus is lost from the `QGraphicsProxyWidget`, the RuntimeError occurs.

The Qt documentation does note the following concerning widgets embedded through QGraphicsProxyWidget, which I don't know if it applies here : 
> Note that widgets with the Qt::WA_PaintOnScreen widget attribute set and widgets that wrap an external application or controller cannot be embedded. Examples are QOpenGLWidget and QAxWidget.

Versions used : 
- Vispy 0.6.5
- PySide2 5.15.1

Here is a minimum reproducible code : 
```python
import numpy as np
import vispy.app
import vispy.color
import vispy.gloo
import vispy.io

from PySide2 import QtWidgets

FRAG_SHADER = """
#version 120

void main() {
    gl_FragColor = vec4(1.0,0.0,0.0,1.0);
}
"""

VERT_SHADER = """
#version 120

// Data (arrays)
attribute float x;
attribute float y;

void main() {
    // Plot the position
    gl_Position = vec4(x, y, 0.0, 1.0);
}
"""

vispy.app.use_app("pyside2")

class AdvancedCanvas(vispy.app.Canvas):
    def __init__(self, size=(800, 600), config={"samples":2}, parent=None):
        self.parent = parent
        vispy.app.Canvas.__init__(self, keys='interactive', size=size, config=config, dpi=75)
        self.program = vispy.gloo.Program(VERT_SHADER, FRAG_SHADER)
        self.program['x'] = vispy.gloo.VertexBuffer(np.linspace(-1, 1, 50, dtype='float32'))
        self.program['y'] = vispy.gloo.VertexBuffer(np.linspace(-1, 1, 50, dtype='float32'))
        # Set state of the canvas
        vispy.gloo.set_clear_color(color="black")

    #==== Redefined methods
    def on_mouse_press(self, event):
        # Take screenshot on right click
        if event.button == 2:
            vispy.io.write_png("test_screen.png", vispy.gloo.util._screenshot())
            print("=====png written")

    def on_draw(self, event):
        vispy.gloo.clear()
        vispy.gloo.set_viewport(0, 0, self.physical_size[0], self.physical_size[1])
        self.program.draw('line_strip')

class MyWindow(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        # Create two canvases
        self.canvas1 = AdvancedCanvas()
        self.canvas2 = AdvancedCanvas()

        # Create a GraphicsView to embed the canvas
        self.view = QtWidgets.QGraphicsView()
        self.view.setScene(QtWidgets.QGraphicsScene())
        self.proxy = QtWidgets.QGraphicsProxyWidget()
        self.proxy.setWidget(self.canvas2.native)
        self.view.scene().addItem(self.proxy)

        layout = QtWidgets.QVBoxLayout(self)
        layout.addWidget(self.canvas1.native)
        layout.addWidget(self.view)

if __name__ == "__main__":
    app = QtWidgets.QApplication()
    w = MyWindow()
    w.show()
    app.exec_()
```

And here's a trace of a typical execution : 
```
PS F:\work> & C:/Users/kusefiru/AppData/Local/Programs/Python/Python37/python.exe f:/work/test_vispy.py
=====png written
=====png written
WARNING: Traceback (most recent call last):
  File "f:/work/test_vispy.py", line 76, in <module>
    app.exec_()
  File "C:\Users\kusefiru\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\app\backends\_qt.py", line 508, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "C:\Users\kusefiru\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\app\backends\_qt.py", line 508, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "C:\Users\kusefiru\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\app\backends\_qt.py", line 825, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "C:\Users\kusefiru\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "C:\Users\kusefiru\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\util\event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "C:\Users\kusefiru\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "f:/work/test_vispy.py", line 54, in on_draw
    self.program.draw('line_strip')
  File "C:\Users\kusefiru\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\gloo\program.py", line 533, in draw
    canvas.context.flush_commands()
  File "C:\Users\kusefiru\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\gloo\context.py", line 176, in flush_commands
    self.glir.flush(self.shared.parser)
  File "C:\Users\kusefiru\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\gloo\glir.py", line 572, in flush
    self._shared.flush(parser)
  File "C:\Users\kusefiru\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\gloo\glir.py", line 494, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "C:\Users\kusefiru\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\gloo\glir.py", line 819, in parse
    self._parse(command)
  File "C:\Users\kusefiru\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\gloo\glir.py", line 779, in _parse
    ob.draw(*args)
  File "C:\Users\kusefiru\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\gloo\glir.py", line 1322, in draw
    gl.check_error('Check before draw')
  File "C:\Users\kusefiru\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\gloo\gl\__init__.py", line 207, in check_error
    raise err
RuntimeError: OpenGL got errors (Check before draw): GL_INVALID_OPERATION
ERROR: Invoking <bound method AdvancedCanvas.on_draw of <AdvancedCanvas (PySide2) at 0x127f3cc8>> for DrawEvent
```

**Comment by djhoese** [comment]
> The Qt documentation does note the following concerning widgets embedded through QGraphicsProxyWidget, which I don't know if it applies here :
> 
>>    Note that widgets with the Qt::WA_PaintOnScreen widget attribute set and widgets that wrap an external application or controller cannot be embedded. Examples are QOpenGLWidget and QAxWidget.

That is exactly what VisPy uses:

https://github.com/vispy/vispy/blob/e33aae23847e8e5f43248ba9d014cc4aea211a90/vispy/app/backends/_qt.py#L81

You mentioned on gitter that the real issue is that _screenshot includes your entire Window and not just the VisPy Canvas, right? If so, let me find a little bit of workaround code. This happens (at least my understanding) because Qt5+ now uses OpenGL for all its Widgets and the context seems to get shared with VisPy. So when VisPy says "show me what's on the buffer" it gets *everything*.

**Comment by djhoese** [comment]
Ah, ok I was wrong. The issue is that when Qt draws its own elements it somehow takes over what the default buffer is. To fix this, you'll need to make sure to draw the vispy canvas right before you request/call _screenshot. In your case, calling `self.on_draw(None)` and then calling `_screenshot` should work. Let me know how ti goes.

**Comment by Kusefiru** [comment]
> You mentioned on gitter that the real issue is that _screenshot includes your entire Window and not just the VisPy Canvas, right? If so, let me find a little bit of workaround code. This happens (at least my understanding) because Qt5+ now uses OpenGL for all its Widgets and the context seems to get shared with VisPy. So when VisPy says "show me what's on the buffer" it gets _everything_.

That's more of a side issue, which can be solved by calling `_screenshot` with the following parameters : 
```python
vispy.gloo.util._screenshot(self.native.geometry().getRect())
```

Adding the `self.on_draw(None)` doesn't resolve the issue.

> That is exactly what VisPy uses:
> 
> https://github.com/vispy/vispy/blob/e33aae23847e8e5f43248ba9d014cc4aea211a90/vispy/app/backends/_qt.py#L81

Indeed, but somehow this doesn't stop the `app.Canvas` from working inside a `QGraphicsProxyWidget`. I can add controls to this embedded canvas fine (my final application use mouse_press, mouse_wheel, mouse_drag events fine). The main issue is the `RuntimeError` which occurs after taking a screenshot.

As I mentionned on gitter, I used before the `render` method which works fine (not accounting the visual artefacts I talked about on gitter earlier as well - maybe this need its own separate issue).

**Comment by djhoese** [comment]
Actually, removing the `config` from your canvases seems to fix the QGraphicsProxyWidget usage too. At least for me. And it no longer does a screenshot of the whole window.

**Comment by Kusefiru** [comment]
> About your weird results with render, did you purposely set samples to 2 in the config? From reading up on it, it can generate anti-aliased looking results: https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glSampleCoverage.xhtml
> Actually, removing the config from your canvases seems to fix the QGraphicsProxyWidget usage 

I wanted to get an anti-aliased look, so yes that was the goal. Turning it off indeed fix the `_screenshot` error, but it does not remove the white artifacts around the plots (more at the bottom).

I guess that multisampling breaks the `_screenshot` method somehow.

> So do you absolutely need the `QGraphicsProxyWidget`? Does doing a more "traditional" method of adding a scrollbar (if that's what you need) to a QWidget work?

Unfortunately, yes. The code above is just a quick example to reproduce the issue.
My graphes are embedded in a more complexe `QGraphicsScene` in which user can connect blocks and visualize data after processing it. The main appeal is the ability to have multiple graphes, thus the need to embed them as `QGraphicsProxyWidget`.

---

Strangely enough, the "white artifacts" issue does not appear on the previous code example.
In order for it to be visible, we have to include an `AxisVisual` to the canvas, here's the new `AdvancedCanvas` using my previous example : 

```python
class AdvancedCanvas(vispy.app.Canvas):
    def __init__(self, size=(800, 600), parent=None):
        self.parent = parent
        vispy.app.Canvas.__init__(self, keys='interactive', size=size, dpi=75)
        self.program = vispy.gloo.Program(VERT_SHADER, FRAG_SHADER)
        self.program['x'] = vispy.gloo.VertexBuffer(np.linspace(-1, 1, 50, dtype='float32'))
        self.program['y'] = vispy.gloo.VertexBuffer(np.linspace(-1, 1, 50, dtype='float32'))
        self.axis = vispy.visuals.AxisVisual(pos=((0,10), (self.physical_size[0],10)))
        self.axis.transforms.configure(canvas=self, viewport=self.context.get_viewport())
        # Set state of the canvas
        vispy.gloo.set_clear_color(color="black")

    #==== Redefined methods
    def on_mouse_press(self, event):
        '''Redefined. Handles mouse press interaction.'''
        # Take screenshot on right click
        if event.button == 2:
            # vispy.io.write_png("test_screen.png", vispy.gloo.util._screenshot())
            # self.on_draw(None)
            vispy.io.write_png("test_screen.png", vispy.gloo.util._screenshot(self.native.geometry().getRect()))
            print("=====png written")

    def on_draw(self, event):
        vispy.gloo.clear()
        vispy.gloo.set_viewport(0, 0, self.physical_size[0], self.physical_size[1])
        self.program.draw('line_strip')
        self.axis.draw()
```

Now we can see the following : 
- With no `samples` in the config, the white artifact appears only on the `QGraphicsProxyWidget` plot. It also appears in the screenshot. 
- With `samples` in the config, the white artifact does not appears, both on the plot and the screenshot. 

I guess there's an issue on Qt side with `QGraphicsProxyWidget` - as they mentionned, it is not entirely compatible with OpenGL widgets.

**Comment by djhoese** [comment]
> So somehow, it shouldn't even work with the .native canvas right ?

You mean with the multi-sampling? Yeah it would seem so. :shrug: 

> In any case, maybe there should be some sort of warning somewhere, or the _screenshot method should be improved to support multisampling ?

I'm not opposed to it, but you're also the first person I've ever seen try to do this so with everything else going on I'm not sure we can make it a priority.

> Strangely enough, the "white artifacts" issue does not appear on the previous code example.
In order for it to be visible, we have to include an AxisVisual to the canvas

I wonder if the `AxisVisual` is changing the `set_gl_state` to something incompatible with your GL program. For example,

https://github.com/vispy/vispy/blob/e33aae23847e8e5f43248ba9d014cc4aea211a90/vispy/visuals/text/text.py#L433-L434

> My graphes are embedded in a more complexe QGraphicsScene in which user can connect blocks and visualize data after processing it. The main appeal is the ability to have multiple graphes, thus the need to embed them as QGraphicsProxyWidget.

Cool! I guess I've never used these widgets before so if you say it is necessary then OK.

**Comment by Kusefiru** [comment]
So after more digging, the culprit happens to be the antialiasing of the `LineVisuals` inside the `AxisVisual`.

If I disable it like so : 
```python
self.axis._line.antialias = False
self.axis._ticks.antialias = False
```

I am now getting a clean image inside my `QGraphicsProxyWidget` : 
![test_screen](https://user-images.githubusercontent.com/19759836/117945820-fe29d300-b30e-11eb-95fe-5c35b29879f0.png)

**Comment by djhoese** [comment]
Wow, good job. Interesting that it made such a huge difference.

**Comment by Kusefiru** [comment]
I guess that this is because it uses the `GL_LINE_SMOOTH` which, from what I read, is deprecated.

This is also mentionned in this issue : #1435

But since the issue only arise for `QGraphicsProxyWidget` which are said to not support completly OpenGL apps, it's hard to say if that is something that should be changed inside Vispy or not.
