### ISSUE TITLE
EGL: eglMakeCurrent fails with EGL_BAD_ACCESS

### ISSUE THREAD

**Issue by asnt** [vispy/vispy#2075]
I am trying to use EGL for off-screen rendering. Launching the snippet at the end with `python snippet.py` fails with
```
/home/user/src/vispy/vispy/visuals/graphs/layouts/networkx_layout.py:10: UserWarning: Networkx not found, please install network to use its layouts
  warnings.warn(
Platform: Linux-5.12.10-arch1-1-x86_64-with-glibc2.10
Python:   3.8.10 (default, May 19 2021, 18:05:58)  [GCC 7.3.0]
NumPy:    1.20.2
Backend:  egl
pyqt4:    None
pyqt5:    ('PyQt5', '5.12.3', '5.12.9')
pyside:   None
pyside2:  None
pyside6:  None
pyglet:   pyglet 1.5.17
glfw:     glfw (3, 3, 4)
sdl2:     None
wx:       None
egl:      EGL 1.5 Mesa Project: OpenGL OpenGL_ES
osmesa:   OSMesa
tkinter:  None
_test:    None

App info-gathering error:
Traceback (most recent call last):
  File "/home/user/src/vispy/vispy/util/config.py", line 429, in sys_info
    canvas = Canvas('Test', (10, 10), show=False, app=app)
  File "/home/user/src/vispy/vispy/app/canvas.py", line 214, in __init__
    self.create_native()
  File "/home/user/src/vispy/vispy/app/canvas.py", line 231, in create_native
    self._app.backend_module.CanvasBackend(self, **self._backend_kwargs)
  File "/home/user/src/vispy/vispy/app/backends/_egl.py", line 174, in __init__
    self._vispy_canvas.set_current()
  File "/home/user/src/vispy/vispy/app/canvas.py", line 413, in set_current
    self._backend._vispy_set_current()
  File "/home/user/src/vispy/vispy/app/backends/_egl.py", line 205, in _vispy_set_current
    egl.eglMakeCurrent(_EGL_DISPLAY, self._surface, self._surface,
  File "/home/user/src/vispy/vispy/ext/egl.py", line 356, in eglMakeCurrent
    raise RuntimeError('Could not make the context current.')
RuntimeError: Could not make the context current.

Traceback (most recent call last):
  File "debug/offscreen/mesh.py", line 24, in <module>
    canvas = scene.SceneCanvas(bgcolor=bgcolor)
  File "/home/user/src/vispy/vispy/scene/canvas.py", line 135, in __init__
    super(SceneCanvas, self).__init__(
  File "/home/user/src/vispy/vispy/app/canvas.py", line 214, in __init__
    self.create_native()
  File "/home/user/src/vispy/vispy/app/canvas.py", line 231, in create_native
    self._app.backend_module.CanvasBackend(self, **self._backend_kwargs)
  File "/home/user/src/vispy/vispy/app/backends/_egl.py", line 174, in __init__
    self._vispy_canvas.set_current()
  File "/home/user/src/vispy/vispy/app/canvas.py", line 413, in set_current
    self._backend._vispy_set_current()
  File "/home/user/src/vispy/vispy/app/backends/_egl.py", line 205, in _vispy_set_current
    egl.eglMakeCurrent(_EGL_DISPLAY, self._surface, self._surface,
  File "/home/user/src/vispy/vispy/ext/egl.py", line 356, in eglMakeCurrent
    raise RuntimeError('Could not make the context current.')
RuntimeError: Could not make the context current.
```
With this change,
```diff
diff --git a/doc b/doc
index 8c7779f5..bcd8b57b 160000
--- a/doc
+++ b/doc
@@ -1 +1 @@
-Subproject commit 8c7779f597186acee27e8e876e742e4391aa5e33
+Subproject commit bcd8b57bb1f8b72e97a6834465fb1cb6f188a5ac-dirty
diff --git a/vispy/ext/egl.py b/vispy/ext/egl.py
index ae93273e..d0687ee9 100644
--- a/vispy/ext/egl.py
+++ b/vispy/ext/egl.py
@@ -351,8 +351,11 @@ def eglCreateContext(display, config, shareContext=EGL_NO_CONTEXT,
 
 def eglMakeCurrent(display, draw, read, context):
     res = _lib.eglMakeCurrent(display, draw, read, context)
-    if res == EGL_FALSE:
-        raise RuntimeError('Could not make the context current.')
+    # if res == EGL_FALSE:
+    #     raise RuntimeError('Could not make the context current.')
+    error_int = _lib.eglGetError()
+    print("res =", res)
+    print("error =", hex(error_int))
 
 
 def eglBindAPI(api):
```
the image is rendered and saved correctly, but, as seen in the log below, EGL indicates the error 0x3002, `EGL_BAD_ACCESS` ([egl reference card](https://www.khronos.org/files/egl-1-4-quick-reference-card.pdf)). Not sure if there is something else I should configure.

The output with the diff above applied:
```
res = 0
error = 0x3002
res = 0
error = 0x3002
res = 0
error = 0x3002
Platform: Linux-5.12.10-arch1-1-x86_64-with-glibc2.10
Python:   3.8.10 (default, May 19 2021, 18:05:58)  [GCC 7.3.0]
NumPy:    1.20.2
Backend:  egl
pyqt4:    None
pyqt5:    ('PyQt5', '5.12.3', '5.12.9')
pyside:   None
pyside2:  None
pyside6:  None
pyglet:   pyglet 1.5.17
glfw:     glfw (3, 3, 4)
sdl2:     None
wx:       None
egl:      EGL 1.5 Mesa Project: OpenGL OpenGL_ES
osmesa:   OSMesa
tkinter:  None
_test:    None

GL version:  '4.6 (Compatibility Profile) Mesa 21.1.2'
MAX_TEXTURE_SIZE: 16384
[...]
res = 0
error = 0x3002
res = 0
error = 0x3002
res = 0
error = 0x3002
res = 0
error = 0x3002
```

Snippet:
```python
import vispy
vispy.use(app="egl")
print(vispy.sys_info())
from vispy import scene
from vispy.io import read_mesh, load_data_file
from vispy.scene.visuals import Mesh
from vispy.visuals import transforms

mesh_file = load_data_file('orig/triceratops.obj.gz')
vertices, faces, _, _ = read_mesh(mesh_file)
mesh = Mesh(vertices, faces, shading='smooth')
mesh.shading_filter.light_dir = (-0.2, -0.1, 1)

transform = transforms.MatrixTransform()
transform.rotate(90, (1, 0, 0))
mesh.transform = transform

bgcolor = 'white'
canvas = scene.SceneCanvas(bgcolor=bgcolor)
view = canvas.central_widget.add_view()
view.camera = 'arcball'
view.camera.depth_value = 1e3
view.add(mesh)

if __name__ == "__main__":
    image = canvas.render()
    import imageio
    imageio.imwrite("rendered.png", image)
```

**Comment by djhoese** [comment]
There are a couple existing issues (maybe closed) regarding EGL that may provide hints to what is going on. I don't have the time right now to find them and I don't have the experience with EGL to understand them or what is going on for you.

**Comment by asnt** [comment]
Thanks @djhoese . I'm looking into past issues.

**Comment by asnt** [comment]
For reference, [this](https://github.com/vispy/vispy/pull/1637#issuecomment-491343195) describes additions needed using EGL completely without an X server. It hasn't been handled in this issue and I couldn't find an issue/PR with it.

**Comment by asnt** [comment]
This issue is gone by removing `print(vispy.sys_info())`.
