### ISSUE TITLE
scene.visuals.Markers will crash when drawing more than 80 millions points

### ISSUE THREAD

**Issue by vitsensei** [vispy/vispy#2112]
OS: Ubuntu 18.04
Python version: 3.9
vispy version: 0.6.6

```python
from PyQt5 import QtWidgets
from vispy import scene, color
import numpy as np

class Plotter3D(QtWidgets.QWidget):
    def __init__(self, parent):
        # Create a canvas to draw
        super().__init__(parent)

        canvas = scene.SceneCanvas(keys=None, bgcolor=color.Color(color="white"))
        canvas.create_native()
        canvas.native.setParent(self)

        layout = QtWidgets.QHBoxLayout()
        layout.setContentsMargins(0, 0, 0, 0)

        layout.addWidget(canvas.native)
        self.setLayout(layout)

        # Set up a viewbox to display the image with interactive pan/zoom
        self.view = canvas.central_widget.add_view()
        self.view.camera = scene.cameras.TurntableCamera()

        # Add axes
        self.view.add(scene.visuals.XYZAxis())

        # Markers visual that store the point clouds
        self._scatter = scene.visuals.Markers()
        self.view.add(self._scatter)

    def plot(self, cloud):
        self._scatter.set_data(cloud[:, :3], edge_color=(1, 1, 1, 1), face_color=(0, 0, 1, 1), size=1)

    def clear_plot(self):
        self._scatter.set_data(np.ones((0, 3)))

if __name__ == '__main__':
    import sys

    app = QtWidgets.QApplication(sys.argv)

    plotter = Plotter3D(None)
    plotter.plot(np.random.normal(size=(80000000, 3), scale=50))
    plotter.show()

    app.exec()

```
Error that I got:
```
WARNING: Error drawing visual <Markers at 0x7fdd3d87f550>
WARNING: Traceback (most recent call last):
  File "/home/atran/PycharmProjects/visualisation/Visualisation.py", line 146, in <module>
    plotter.show()
  File "/home/atran/PycharmProjects/visualisation/venv/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 508, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "/home/atran/PycharmProjects/visualisation/venv/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 508, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "/home/atran/PycharmProjects/visualisation/venv/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 825, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/home/atran/PycharmProjects/visualisation/venv/lib/python3.9/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/home/atran/PycharmProjects/visualisation/venv/lib/python3.9/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  << caught exception here: >>
  File "/home/atran/PycharmProjects/visualisation/venv/lib/python3.9/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/home/atran/PycharmProjects/visualisation/venv/lib/python3.9/site-packages/vispy/scene/canvas.py", line 217, in on_draw
    self._draw_scene()
  File "/home/atran/PycharmProjects/visualisation/venv/lib/python3.9/site-packages/vispy/scene/canvas.py", line 266, in _draw_scene
    self.draw_visual(self.scene)
  File "/home/atran/PycharmProjects/visualisation/venv/lib/python3.9/site-packages/vispy/scene/canvas.py", line 304, in draw_visual
    node.draw()
  File "/home/atran/PycharmProjects/visualisation/venv/lib/python3.9/site-packages/vispy/scene/visuals.py", line 99, in draw
    self._visual_superclass.draw(self)
  File "/home/atran/PycharmProjects/visualisation/venv/lib/python3.9/site-packages/vispy/visuals/visual.py", line 442, in draw
    self._program.draw(self._vshare.draw_mode,
  File "/home/atran/PycharmProjects/visualisation/venv/lib/python3.9/site-packages/vispy/visuals/shaders/program.py", line 101, in draw
    Program.draw(self, *args, **kwargs)
  File "/home/atran/PycharmProjects/visualisation/venv/lib/python3.9/site-packages/vispy/gloo/program.py", line 533, in draw
    canvas.context.flush_commands()
  File "/home/atran/PycharmProjects/visualisation/venv/lib/python3.9/site-packages/vispy/gloo/context.py", line 176, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/home/atran/PycharmProjects/visualisation/venv/lib/python3.9/site-packages/vispy/gloo/glir.py", line 572, in flush
    self._shared.flush(parser)
  File "/home/atran/PycharmProjects/visualisation/venv/lib/python3.9/site-packages/vispy/gloo/glir.py", line 494, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/home/atran/PycharmProjects/visualisation/venv/lib/python3.9/site-packages/vispy/gloo/glir.py", line 819, in parse
    self._parse(command)
  File "/home/atran/PycharmProjects/visualisation/venv/lib/python3.9/site-packages/vispy/gloo/glir.py", line 779, in _parse
    ob.draw(*args)
  File "/home/atran/PycharmProjects/visualisation/venv/lib/python3.9/site-packages/vispy/gloo/glir.py", line 1322, in draw
    gl.check_error('Check before draw')
  File "/home/atran/PycharmProjects/visualisation/venv/lib/python3.9/site-packages/vispy/gloo/gl/__init__.py", line 207, in check_error
    raise err
RuntimeError: OpenGL got errors (Check before draw): GL_INVALID_VALUE
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt5) at 0x7fdd4a285970>> for DrawEvent

Process finished with exit code 0
```

**Comment by vitsensei** [comment]
Not sure if this is the best way to plot 80 millions point cloud but here we go.
I don't think it is my GPU because I was able to load in bigger cloud through CloudCompare.

**Comment by djhoese** [comment]
My baby isn't sleeping so I'm awake and reading emails...

This is a lot of points. Cool. I've never tried this many. Based on your mention of 80m, I assume less than that works for you?

I'm not familiar with CloudCompare and I'm not sure how our implementations differ, but there is a lot of wiggle room for how this is implemented. For example, what if you make 2 MarkersVisuals with 40m points each? Also, VisPy is currently targeting an old version of OpenGL. I'm sure there are techniques in newer OpenGL that could work better, not to mention Vulkan or other graphics framework/technology.

**Comment by asnt** [comment]
It works on my side, although slowly.

Increasing to 160M points, I get
```
RuntimeError: OpenGL got errors (Check before draw): GL_OUT_OF_MEMORY
```
With 1G points, I get
```
MemoryError: Unable to allocate 48.4 GiB for an array with shape (1000000000,) and data type [('a_position', '<f4', (3,)), ('a_fg_color', '<f4', (4,)), ('a_bg_color', '<f4', (4,)), ('a_size', '<f4'), ('a_edgewidth', '<f4')]
```

**Comment by vitsensei** [comment]
@djhoese Interesting suggestion. It seems to me that 2 40mil point clouds works. Based on @asnt experiment, I assume this is just an optimisation problem.

**Comment by vitsensei** [comment]
I just finished installing the master branch and it seems to me that the problem is not there anymore :). 

Increase to 160mil did not crash for me. I assume my overpriced laptop did most of that.

**Comment by djhoese** [comment]
Wow, very interesting. I don't see any changes that would effect this specifically done in the markers.py module. It must be one of the other changes in VisPy. Good to know it improves things. I was just about to comment that the 80m works for me too, but I was using the `main` branch.

I looked at CloudCompare and it is definitely hard to compete with software that was specifically designed to display large amounts of points. VisPy isn't really optimized to do the **best** job at it, but apparently it is doing OK.

I guess we can close this. Let me know otherwise. Feel free to continue the discussion even if it is closed.
