### ISSUE TITLE
Is there way to visualize two volume at the same time? I mean in a composite way.

### ISSUE THREAD

**Issue by Yuvi-416** [vispy/vispy#2252]
Hello everyone,
I started to use vispy recently previously I used to use the VTK package.
As I have four volumes and I want to visualize all four-volume on the same canvas within the same scene. I couldn't find an example for this case. I found one example as here: https://github.com/vispy/vispy/blob/main/examples/scene/volume.py but it's not what I am looking for. 

So far I tried below code: 
```
from vispy import scene
import SimpleITK as sitk

directory1 = "/home/yuvi/Desktop/DATASETS_&_OUTPUTS/Local-Dataset/CLSM/16-bit_TO_8-bit/Channel_-sub-6232_20x_MsGcg_RbCol4_SMACy3_islet1-2/"
directory2 = "/home/yuvi/Desktop/DATASETS_&_OUTPUTS/Local-Dataset/CLSM/LSM-DATA/output/Channel_-01-1"

itk_image = sitk.ImageSeriesReader()
dicom_names1 = itk_image.GetGDCMSeriesFileNames(directory1)
itk_image.SetFileNames(dicom_names1)
image1 = itk_image.Execute()
i1 = sitk.GetArrayFromImage(image1)

itk_image1 = sitk.ImageSeriesReader()
dicom_names2 = itk_image1.GetGDCMSeriesFileNames(directory2)
itk_image1.SetFileNames(dicom_names2)
image2 = itk_image1.Execute()
i2 = sitk.GetArrayFromImage(image2)

# Prepare the canvas
canvas = scene.SceneCanvas(keys='interactive', bgcolor='w')
canvas.measure_fps()

# Set up a viewbox to display the image with interactive pan/zoom
view1 = canvas.central_widget.add_view()
view2 = canvas.central_widget.add_view()


vol1 = scene.visuals.Volume(i1, cmap="Greens", method='mip', raycasting_mode='volume',
                            parent=view1.scene)  # this can be used to visualize volume image
vol2 = scene.visuals.Volume(i2, cmap="Blues", method='mip', raycasting_mode='volume',
                            parent=view2.scene) 

fov = 60
cam1 = scene.cameras.TurntableCamera(elevation=0, azimuth=0, parent=view1.scene, fov=fov)
cam2 = scene.cameras.TurntableCamera(elevation=0, azimuth=0, parent=view2.scene, fov=fov)

view1.camera = cam1  # Select turntable at first
view2.camera = cam2 

canvas.show()
canvas.app.run()
```
As you can see the output in the below picture. 
![Screenshot from 2021-11-09 23-20-42](https://user-images.githubusercontent.com/65744819/141021310-0a067103-cdc0-4489-8e73-46c9ce75def1.png)
Can you tell me how to add two views and visualize them in the same canvas? Is there something like add actor in VTK that helps to combine two views?
And one more thing, when I try to rotate the output image in 360 degrees like we can do in napari or in VTK but in vispy I couldn't rotate the image in 360. It gets stuck when I try to rotate the image vertically. I mean the generated image doesn't flip in a 360 degree.

Any help will be appreciated.
Thank you!

**Comment by djhoese** [comment]
Is there a reason you need two views? I could be misunderstanding what your goal is, but you want to view the volumes on top of each other right? If that is the case, then does using a single view where you pass `parent=view1.scene` to both Volumes work for you?

Otherwise maybe @brisvag or @alisterburt can give some ideas once we know what you're looking for. @Yuvi-416 do you have a screenshot from VTK of what you're expecting as the final output?

**Comment by Yuvi-416** [comment]
Hi there,
Thanks for the quick reply.
Actually, I have a confocal LSM image with four-channel and I have each channel saved in DICOM standard. Now I want to create a 3D viewer where I can view it in 3D with each channel shown in a different colour. 
For example, this is what I achieved by using the VTK package:
![Screenshot from 2021-11-10 10-02-31](https://user-images.githubusercontent.com/65744819/141093636-23fc80ae-0c5a-4650-a566-82ed7b0e3ed3.png)
And I did what you told me above to do it work but the image doesn't seem to be in the right position, even though both image has the same height, weight and depth. 
Here are the screenshots:
![Screenshot from 2021-11-10 10-05-35](https://user-images.githubusercontent.com/65744819/141094124-bda5c148-070f-4804-8173-5537067c3caa.png)
![Screenshot from 2021-11-10 10-05-42](https://user-images.githubusercontent.com/65744819/141094135-a5d766de-6ff1-4092-b5f1-ab712fbf26a3.png)

And when I try to visualize just one channel in Isosurface view I get an error as below with a blank black screen:
I just pass the below command instead of volume:
```
scene.visuals.Isosurface(i1, level=0.001, shading='smooth',
                         parent=view.scene)
```
```
WARNING: Traceback (most recent call last):
  File "/home/yuvi/PycharmProjects/REST_API_PYP/Vispy_PACK/Temp-Poly-data.py", line 43, in <module>
    canvas.app.run()
  File "/home/yuvi/anaconda3/envs/REST_API_PYP/lib/python3.7/site-packages/vispy/app/application.py", line 160, in run
    return self._backend._vispy_run()
  File "/home/yuvi/anaconda3/envs/REST_API_PYP/lib/python3.7/site-packages/vispy/app/backends/_qt.py", line 335, in _vispy_run
    return exec_func()
  File "/home/yuvi/anaconda3/envs/REST_API_PYP/lib/python3.7/site-packages/vispy/app/backends/_qt.py", line 567, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "/home/yuvi/anaconda3/envs/REST_API_PYP/lib/python3.7/site-packages/vispy/app/backends/_qt.py", line 897, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/home/yuvi/anaconda3/envs/REST_API_PYP/lib/python3.7/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/home/yuvi/anaconda3/envs/REST_API_PYP/lib/python3.7/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/home/yuvi/anaconda3/envs/REST_API_PYP/lib/python3.7/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/home/yuvi/anaconda3/envs/REST_API_PYP/lib/python3.7/site-packages/vispy/scene/canvas.py", line 218, in on_draw
    self._draw_scene()
  File "/home/yuvi/anaconda3/envs/REST_API_PYP/lib/python3.7/site-packages/vispy/scene/canvas.py", line 277, in _draw_scene
    self.draw_visual(self.scene)
  File "/home/yuvi/anaconda3/envs/REST_API_PYP/lib/python3.7/site-packages/vispy/scene/canvas.py", line 315, in draw_visual
    node.draw()
  File "/home/yuvi/anaconda3/envs/REST_API_PYP/lib/python3.7/site-packages/vispy/scene/visuals.py", line 99, in draw
    self._visual_superclass.draw(self)
  File "/home/yuvi/anaconda3/envs/REST_API_PYP/lib/python3.7/site-packages/vispy/visuals/visual.py", line 442, in draw
    if self._prepare_draw(view=self) is False:
  File "/home/yuvi/anaconda3/envs/REST_API_PYP/lib/python3.7/site-packages/vispy/visuals/isosurface.py", line 110, in _prepare_draw
    color=self._color)
  File "/home/yuvi/anaconda3/envs/REST_API_PYP/lib/python3.7/site-packages/vispy/visuals/mesh.py", line 183, in set_data
    self._bounds = self._meshdata.get_bounds()
  File "/home/yuvi/anaconda3/envs/REST_API_PYP/lib/python3.7/site-packages/vispy/geometry/meshdata.py", line 210, in get_bounds
    bounds = [(v[:, ax].min(), v[:, ax].max()) for ax in range(v.shape[1])]
  File "/home/yuvi/anaconda3/envs/REST_API_PYP/lib/python3.7/site-packages/vispy/geometry/meshdata.py", line 210, in <listcomp>
    bounds = [(v[:, ax].min(), v[:, ax].max()) for ax in range(v.shape[1])]
  File "/home/yuvi/anaconda3/envs/REST_API_PYP/lib/python3.7/site-packages/numpy/core/_methods.py", line 44, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt5) at 0x7f46d19ceb10>> for DrawEvent
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt5) at 0x7f46d19ceb10>> repeat 2

Process finished with exit code 0
```

**Comment by almarklein** [comment]
> ValueError: zero-size array to reduction operation minimum which has no identity

I suspect that the threshold is not good, causing no surface to be found, i.e. the array of vertices is empty.

To answer the original question, you *should* be able to render multiple volumes as long as you use a render mode that produces opaque fragments at a specific depth, like the surface render method.

**Comment by alisterburt** [comment]
Hi @Yuvi-416 

I'm not sure what's going on with your data (it appears the different channels are arrays with different shapes?) but for compositing images of data from different channels you can set the gl state to additive with `VolumeVisual.set_gl_state(preset='additive')` 

You may (or may not) be interested in [napari](https://napari.org) which is built around vispy and provides lots of conveniences around this sort of problem. e.g. https://napari.org/tutorials/fundamentals/image.html#blending-layers

**Comment by brisvag** [comment]
@Yuvi-416 to follow up on alister's message, here's an example with some sample data from scikit-image (but you can just use yours):

```python
from vispy import scene

# sample data, should work just fine with your data though
from skimage import data
i1 = data.cells3d()[:, 0]
i2 = data.cells3d()[:, 1]

# Prepare the canvas
canvas = scene.SceneCanvas(keys='interactive', bgcolor='black')
canvas.measure_fps()

# Set up a viewbox to display the image with interactive pan/zoom
view = canvas.central_widget.add_view()

vol1 = scene.visuals.Volume(i1, cmap="Greens", method='mip', raycasting_mode='volume',
                            parent=view.scene, opacity=0.5)  # this can be used to visualize volume image
vol2 = scene.visuals.Volume(i2, cmap="Blues", method='mip', raycasting_mode='volume',
                            parent=view.scene, opacity=0.5) 

# set blending mode
vol1.set_gl_state(preset='additive')
vol2.set_gl_state(preset='additive')

fov = 60
cam = scene.cameras.TurntableCamera(elevation=0, azimuth=0, parent=view.scene, fov=fov)

view.camera = cam  # Select turntable at first

canvas.show()
canvas.app.run()
```

I'm not sure why, but white background and additive seem to fuck up for some reason, so I changed to black...

Unfortunately, transparency is a bit broken in vispy at the moment, so depending on what you're trying to do, some things might not work out. 

I see you mentioned you tried already napari before; what are you trying to achieve here that napari does not allow?

As for the rotation issues: the problem is that you're using a `TurnTableCamera` instead of an `ArcBallCamera`!

**Comment by alisterburt** [comment]
afaik with white background the value of the white background gets added to the value from the visual -> it can't get any more white so you end up with a white canvas

**Comment by brisvag** [comment]
> afaik with white background the value of the white background gets added to the value from the visual -> it can't get any more white so you end up with a white canvas

Yup, that's definitely it :)

**Comment by Yuvi-416** [comment]
Hello everyone,
Good afternoon,
Thank you all for the quick help and suggestion. Today I learned a lot about vispy but still need to learn more. 
I got some outputs but not as desired ones for volume rendering, 
First of all, I included what @alisterburt and @brisvag suggest to include and the output which I received are below:
![Screenshot from 2021-11-10 16-10-50](https://user-images.githubusercontent.com/65744819/141150522-7c60d3b1-aac8-4db6-901c-636c4e319dcf.png)
I tried to balance opacity but I didn't get success to find the right one. Any help to balance this one so that output will be similar to napari?
And this was the code:
```
directory1 = "/home/yuvi/Desktop/DATASETS_&_OUTPUTS/Local-Dataset/CLSM/LSM-DATA/output/Channel_-01-0/"
directory2 = "/home/yuvi/Desktop/DATASETS_&_OUTPUTS/Local-Dataset/CLSM/LSM-DATA/output/Channel_-01-1/"
directory3 = "/home/yuvi/Desktop/DATASETS_&_OUTPUTS/Local-Dataset/CLSM/LSM-DATA/output/Channel_-01-2/"

print(vispy.__version__)

itk_image1 = sitk.ImageSeriesReader()
dicom_names1 = itk_image1.GetGDCMSeriesFileNames(directory1)
itk_image1.SetFileNames(dicom_names1)
image1 = itk_image1.Execute()
i1 = sitk.GetArrayFromImage(image1)

itk_image2 = sitk.ImageSeriesReader()
dicom_names2 = itk_image2.GetGDCMSeriesFileNames(directory2)
itk_image2.SetFileNames(dicom_names2)
image2 = itk_image2.Execute()
i2 = sitk.GetArrayFromImage(image2)

itk_image3 = sitk.ImageSeriesReader()
dicom_names3 = itk_image3.GetGDCMSeriesFileNames(directory3)
itk_image3.SetFileNames(dicom_names3)
image3 = itk_image3.Execute()
i3 = sitk.GetArrayFromImage(image3)

# from skimage import data
# # i1 = data.cells3d()[:, 0]
# # i2 = data.cells3d()[:, 1]


canvas = scene.SceneCanvas(keys='interactive', bgcolor='black')
canvas.measure_fps()

view = canvas.central_widget.add_view()

vol1 = scene.visuals.Volume(i1, cmap="Greens", method='mip', raycasting_mode='volume', gamma="1.0",
                            interpolation='linear', parent=view.scene)
vol2 = scene.visuals.Volume(i2, cmap="Reds", method='mip', raycasting_mode='volume', gamma="1.0",
                            interpolation='linear', parent=view.scene)
vol3 = scene.visuals.Volume(i3, cmap="Blues", method='mip', raycasting_mode='volume', gamma="1.0",
                            interpolation='linear', parent=view.scene)

# set blending mode
vol1.set_gl_state(preset='additive')
vol1.opacity = 0.2
vol2.set_gl_state(preset='additive')
vol2.opacity = 0.2
vol3.set_gl_state(preset='additive')
vol3.opacity = 0.2

fov = 60
cam = scene.cameras.ArcballCamera(fov=fov)
view.camera = cam  # Select turntable at first

canvas.show()
canvas.app.run()
```
And here's the samples which I am currently using to render in vispy: https://uapt33090-my.sharepoint.com/:f:/g/personal/ygupta_ua_pt/Eid-ApTMirlMugJlzkGXV4wB6fKoy8TauRnHsPJ32MAeVw?e=fLkMbE

I have previously visualized these samples with napari and it worked fine over there:
![Screenshot from 2021-11-10 15-52-03](https://user-images.githubusercontent.com/65744819/141151433-26be1665-ba0b-4c83-8f6c-3bdad1928739.png)
![Screenshot from 2021-11-10 15-53-15](https://user-images.githubusercontent.com/65744819/141151455-edac2639-aea0-4d6d-8219-8710203256d1.png)
And the generated outputs are also more visible than vispy ones.
So, I would like to know what are the things which I need to add like functions that help vispy canvas output similar to napari ones as I know napari use vispy to render the image.

@almarklein Thanks for your comment. I finally learned how to find the correct threshold values. And you can see the output below image:
![Screenshot from 2021-11-10 17-08-57](https://user-images.githubusercontent.com/65744819/141160005-a1572760-1cbf-4a6b-8c09-ad2ee262ed82.png)
Just a little help need from you. I think now the plotted image is centred or might be at (0,0,0). So what change do I have to perform so that it will plot like volume rendering or like a napari more centred with no zoom?

@brisvag Yeah, I can use napari but my final project goal is to create a web-based 3D visualization as the project aim is to visualize CLSM, FIB-SEM, and WSI images into it. Previously, I tried to plot with VTK and I got quite a well-desired output but I couldn't pass the object or array of an output of VTK Python to Javascript, therefore, now I am looking after vispy package. Well, I still need to figure out whether I can transfer vispy render output to javascript or not.

**Comment by djhoese** [comment]
> Yeah, I can use napari but my final project goal is to create a web-based 3D visualization as the project aim is to visualize CLSM, FIB-SEM, and WSI images into it. Previously, I tried to plot with VTK and I got quite a well-desired output but I couldn't pass the object or array of an output of VTK Python to Javascript, therefore, now I am looking after vispy package. Well, I still need to figure out whether I can transfer vispy render output to javascript or not.

Using the new `jupyter_rfb` backend you could send vispy renders to a jupyter notebook. Interactions (keyboard and mouse events) work with this backend as well. However, it is limited to notebooks. There is no direct javascript execution of VisPy as it depends on OpenGL and no longer supports webgl (even when it did it was very limited). You could render the results on the backend and then send them to the client, but besides getting a numpy array of the display there is nothing builtin to do a javascript client for vispy. @almarklein can add anything I may be forgetting.

**Comment by alisterburt** [comment]
@Yuvi-416 it looks like you just need to play with the `clim` property of your volumes to get something more similar to the napari output. +1 to David's suggestion of looking at `jupyter-rfb` for getting the vispy canvas into a notebook

**Comment by brisvag** [comment]
About the position of the volumes relative to the camera: you have two options if you want to move them relative to the camera view:

1) add a transform to your volumes to move them where you want them, somethin like:
```
vol1.transform = scene.transforms.STTransform(translate=(x, y, z))
```

2) move your camera instead
```
cam.transform = ...
```

However, the example I gave you properly centers the volume in the view. Are you having issues with that?

**Comment by Yuvi-416** [comment]
Hello, @brisvag thanks for the reply.
Volume rendering is working fine just having a problem with opacity but with the help of `clim` command, I can fix it. But I having trouble with the Isosurface plot. 
```
Everyting is same beside below line:
vol1 = scene.visuals.Isosurface(i1, level=i1.max() / 3, shading='smooth', color=(1, 0, 0, 1),
                                parent=view.scene)
```
And the output which it generates has a centred at one corner:
![Screenshot from 2021-11-11 12-37-17](https://user-images.githubusercontent.com/65744819/141299917-10c28faa-a9da-4b0c-a8bd-2cf6e307ad5d.png)

 In volume rendering case, the camera allows me to rotate the image from any corner but in isosurface, it is just possible from one. So I was wondering how can I have more control over it.
 
 @djhoese and @alisterburt thanks for this one. I will go through it and check whether it will be feasible in my case or not.

**Comment by brisvag** [comment]
I never used `visuals.Isosurface`, so I'm not sure what (if anything) is going wrong there. If you want the same result as napari's isosurface, we obtain that by using the `iso` rendering method on a `Volume` visual:

```python
vol1 = scene.visuals.Volume(i1, method='iso', threshold=0.5, parent=view.scene)
```

**Comment by djhoese** [comment]
If I remember right this was a bug in Isosurface that was fixed. Let me see if I can find the pull request with the fix.

**Comment by djhoese** [comment]
Ok so there is https://github.com/vispy/vispy/issues/2064 which is closed. My second suggestion in this comment https://github.com/vispy/vispy/issues/2064#issuecomment-859661138 could be helpful here. There is also https://github.com/vispy/vispy/pull/2070 where I apparently fixed the main problem from that issue. That should be fixed for vispy 0.7+.

**Comment by Yuvi-416** [comment]
Hi guys,
Thanks, @brisvag that worked pretty well.
@djhoese Thanks for the solution, it worked perfectly. 
```
vol1 = scene.visuals.Isosurface(i1, level=i1.max() / 3, shading='smooth', color=(1, 0, 0, 1),
                                parent=view.scene)
vol1._prepare_draw(vol1)
```
The above command is able to generate the image but the image has some shadows like below:
![Screenshot from 2021-11-11 16-34-21](https://user-images.githubusercontent.com/65744819/141336427-78360785-cf2f-4736-8bb1-9e99d8a5740d.png)
![Screenshot from 2021-11-11 16-34-31](https://user-images.githubusercontent.com/65744819/141336456-8c8be2cd-a055-4c5b-ba93-99458c1f34f4.png)

I also run the same image in VTK and it doesn't show that shadows. I think it is something to do with colour?
And is there a better way to just pass solid colour name for isosurface rather than passing colour values `color=(1, 0, 0, 1)`.

And I also notice that generated image front slide is shining whereas the back side is dim.

**Comment by brisvag** [comment]
@Yuvi-416 I think we need a bit more (sample data and a minimal code example) to get a better idea on this... My first guess is that it's some sort of inside-outside shading issue, but it;s hard to tell from the still image.
