### ISSUE TITLE
Installation issues under Windows 10

### ISSUE THREAD

**Issue by asteppke** [vispy/vispy#2275]
I am trying to get vispy to run on my Windows 10 machine but so far it looks like there is something not working correctly. To get a better understanding of the issue I created a new conda environment so that no dependency issues appear including some backends:

````
conda create -c conda-forge -n vispy_env vispy nose pytest flake8 pyqt pyglet sdl2
````
So this installs a fresh set including these packages:
````
  numpy              conda-forge/win-64::numpy-1.21.4-py39h6635163_0
  pyglet             conda-forge/win-64::pyglet-1.5.16-py39hcbf5309_0
  pyqt               conda-forge/win-64::pyqt-5.12.3-py39hcbf5309_8
  python             conda-forge/win-64::python-3.9.7-h7840368_3_cpython
  qt                 conda-forge/win-64::qt-5.12.9-h5909a2a_4
  sdl2               conda-forge/win-64::sdl2-2.0.12-h0e60522_1
  vispy              conda-forge/win-64::vispy-0.9.4-py39h5d4886f_0
````
which looks good and shows that vispy recognized my hardware and environment:
````
>>> vispy.sys_info()
"Platform: Windows-10-10.0.19044-SP0\nPython:   3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:15:42) [MSC v.1916 64 bit (AMD64)]\nNumPy:    1.21.4\nBackend:  PyQt5\npyqt4:    None\npyqt5:    ('PyQt5', '5.12.3', '5.12.9')\npyqt6:    None\npyside:   None\npyside2:  None\npyside6:  None\npyglet:   pyglet 1.5.16\nglfw:     None\nsdl2:     None\nwx:       None\negl:      None\nosmesa:   None\njupyter_rfb: None\n_test:    None\n\nGL version:  '4.6.0 NVIDIA 466.63'\nMAX_TEXTURE_SIZE: 32768\nExtensions: 'GL_AMD_multi_draw_indirect GL_AMD_seamless_cubemap_per_texture GL_AMD_vertex_shader_viewport_index GL_AMD_vertex_shader_layer GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_fragment_shader_interlock GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_post_depth_coverage GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_locations GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shader_viewport_layer_array GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_sparse_buffer GL_ARB_sparse_texture GL_ARB_sparse_texture2 GL_ARB_sparse_texture_clamp GL_ARB_spirv_extensions GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_filter_anisotropic GL_ARB_texture_filter_minmax GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ARB_window_pos GL_ATI_draw_buffers GL_ATI_texture_float GL_ATI_texture_mirror_once GL_S3_s3tc GL_EXT_texture_env_add GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_Cg_shader GL_EXT_depth_bounds_test GL_EXT_direct_state_access GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXTX_framebuffer_mixed_formats GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_multiview_texture_multisample GL_EXT_multiview_timer_query GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_polygon_offset_clamp GL_EXT_post_depth_coverage GL_EXT_provoking_vertex GL_EXT_raster_multisample GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_shader_objects GL_EXT_separate_specular_color GL_EXT_shader_image_load_formatted GL_EXT_shader_image_load_store GL_EXT_shader_integer_mix GL_EXT_shadow_funcs GL_EXT_sparse_texture2 GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture3D GL_EXT_texture_array GL_EXT_texture_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_latc GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_filter_minmax GL_EXT_texture_integer GL_EXT_texture_lod GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_object GL_EXT_texture_shadow_lod GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_decode GL_EXT_texture_storage GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback2 GL_EXT_vertex_array GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_EXT_window_rectangles GL_EXT_import_sync_object GL_IBM_rasterpos_clip GL_IBM_texture_mirrored_repeat GL_KHR_context_flush_control GL_KHR_debug GL_EXT_memory_object GL_EXT_memory_object_win32 GL_NV_memory_object_sparse GL_EXT_win32_keyed_mutex GL_KHR_parallel_shader_compile GL_KHR_no_error GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_EXT_semaphore GL_EXT_semaphore_win32 GL_NV_timeline_semaphore GL_KHR_shader_subgroup GL_KTX_buffer_region GL_NV_alpha_to_coverage_dither_control GL_NV_bindless_multi_draw_indirect GL_NV_bindless_multi_draw_indirect_count GL_NV_bindless_texture GL_NV_blend_equation_advanced GL_NV_blend_equation_advanced_coherent GL_NVX_blend_equation_advanced_multi_draw_buffers GL_NV_blend_minmax_factor GL_NV_blend_square GL_NV_clip_space_w_scaling GL_NV_command_list GL_NV_compute_program5 GL_NV_compute_shader_derivatives GL_NV_conditional_render GL_NV_conservative_raster GL_NV_conservative_raster_dilate GL_NV_conservative_raster_pre_snap GL_NV_conservative_raster_pre_snap_triangles GL_NV_conservative_raster_underestimation GL_NV_copy_depth_to_color GL_NV_copy_image GL_NV_depth_buffer_float GL_NV_depth_clamp GL_NV_draw_texture GL_NV_draw_vulkan_image GL_NV_ES1_1_compatibility GL_NV_ES3_1_compatibility GL_NV_explicit_multisample GL_NV_feature_query GL_NV_fence GL_NV_fill_rectangle GL_NV_float_buffer GL_NV_fog_distance GL_NV_fragment_coverage_to_color GL_NV_fragment_program GL_NV_fragment_program_option GL_NV_fragment_program2 GL_NV_fragment_shader_barycentric GL_NV_fragment_shader_interlock GL_NV_framebuffer_mixed_samples GL_NV_framebuffer_multisample_coverage GL_NV_geometry_shader4 GL_NV_geometry_shader_passthrough GL_NV_gpu_program4 GL_NV_internalformat_sample_query GL_NV_gpu_program4_1 GL_NV_gpu_program5 GL_NV_gpu_program5_mem_extended GL_NV_gpu_program_fp64 GL_NV_gpu_shader5 GL_NV_half_float GL_NV_light_max_exponent GL_NV_memory_attachment GL_NV_mesh_shader GL_NV_multisample_coverage GL_NV_multisample_filter_hint GL_NV_occlusion_query GL_NV_packed_depth_stencil GL_NV_parameter_buffer_object GL_NV_parameter_buffer_object2 GL_NV_path_rendering GL_NV_path_rendering_shared_edge GL_NV_pixel_data_range GL_NV_point_sprite GL_NV_primitive_restart GL_NV_query_resource GL_NV_query_resource_tag GL_NV_register_combiners GL_NV_register_combiners2 GL_NV_representative_fragment_test GL_NV_sample_locations GL_NV_sample_mask_override_coverage GL_NV_scissor_exclusive GL_NV_shader_atomic_counters GL_NV_shader_atomic_float GL_NV_shader_atomic_float64 GL_NV_shader_atomic_fp16_vector GL_NV_shader_atomic_int64 GL_NV_shader_buffer_load GL_NV_shader_storage_buffer_object GL_NV_shader_subgroup_partitioned GL_NV_shader_texture_footprint GL_NV_shading_rate_image GL_NV_stereo_view_rendering GL_NV_texgen_reflection GL_NV_texture_barrier GL_NV_texture_compression_vtc GL_NV_texture_env_combine4 GL_NV_texture_multisample GL_NV_texture_rectangle GL_NV_texture_rectangle_compressed GL_NV_texture_shader GL_NV_texture_shader2 GL_NV_texture_shader3 GL_NV_transform_feedback GL_NV_transform_feedback2 GL_NV_uniform_buffer_unified_memory GL_NV_vertex_array_range GL_NV_vertex_array_range2 GL_NV_vertex_attrib_integer_64bit GL_NV_vertex_buffer_unified_memory GL_NV_vertex_program GL_NV_vertex_program1_1 GL_NV_vertex_program2 GL_NV_vertex_program2_option GL_NV_vertex_program3 GL_NV_viewport_array2 GL_NV_viewport_swizzle GL_NVX_conditional_render GL_NVX_linked_gpu_multicast GL_NV_gpu_multicast GL_NVX_gpu_multicast2 GL_NVX_progress_fence GL_NVX_gpu_memory_info GL_NVX_multigpu_info GL_NVX_nvenc_interop GL_NV_shader_thread_group GL_NV_shader_thread_shuffle GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OVR_multiview GL_OVR_multiview2 GL_SGIS_generate_mipmap GL_SGIS_texture_lod GL_SGIX_depth_texture GL_SGIX_shadow GL_SUN_slice_accum GL_WIN_swap_hint WGL_EXT_swap_control '\n"
>>>
````
Now running the test suite as advised
````
import vispy
vispy.test()
````

leads to a large number of failed tests:
````
_VISPY_TESTING_APP=pyqt5 C:\tools\miniconda3\envs\vispy_env\python.exe -m pytest -m vispy_app_test -ra C:\tools\miniconda3\envs\vispy_env\lib\site-packages\vispy
================================================= test session starts =================================================
platform win32 -- Python 3.9.7, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: C:\tools\miniconda3\envs\vispy_env\lib\site-packages
collected 1015 items / 648 deselected / 1 skipped / 366 selected


vispy\app\backends\tests\test_offscreen_util.py .F                                                               [  0%]
vispy\app\backends\tests\test_rfb.py s                                                                           [  0%]
vispy\app\tests\test_app.py ......                                                                               [  2%]
vispy\app\tests\test_backends.py .                                                                               [  2%]
vispy\app\tests\test_canvas.py ...                                                                               [  3%]
vispy\app\tests\test_context.py .x                                                                               [  4%]
vispy\app\tests\test_qt.py s                                                                                     [  4%]
vispy\app\tests\test_simultaneous.py .                                                                           [  4%]
vispy\gloo\gl\tests\test_basics.py ..ss                                                                          [  5%]
vispy\gloo\gl\tests\test_functionality.py ..ss                                                                   [  6%]
vispy\gloo\tests\test_glir.py ..                                                                                 [  7%]
vispy\gloo\tests\test_program.py .                                                                               [  7%]
vispy\gloo\tests\test_use_gloo.py ....                                                                           [  8%]
vispy\gloo\tests\test_wrappers.py ..                                                                             [  9%]
vispy\plot\tests\test_plot.py ..                                                                                 [  9%]
vispy\scene\cameras\tests\test_perspective.py F.                                                                 [ 10%]
vispy\scene\tests\test_canvas.py ....                                                                            [ 11%]
vispy\scene\tests\test_node.py .                                                                                 [ 11%]
vispy\scene\widgets\tests\test_colorbar.py F                                                                     [ 11%]
vispy\util\tests\test_config.py .                                                                                [ 12%]
vispy\util\tests\test_vispy.py s                                                                                 [ 12%]
vispy\visuals\tests\test_arrows.py FFF.                                                                          [ 13%]
vispy\visuals\tests\test_axis.py .....                                                                           [ 14%]
vispy\visuals\tests\test_collections.py .                                                                        [ 15%]
vispy\visuals\tests\test_colorbar.py FF...                                                                       [ 16%]
vispy\visuals\tests\test_colormap.py FFFFFF                                                                      [ 18%]
vispy\visuals\tests\test_ellipse.py FFFF                                                                         [ 19%]
vispy\visuals\tests\test_histogram.py F                                                                          [ 19%]
vispy\visuals\tests\test_image.py FF............................................................................ [ 40%]
................................................................................................................ [ 71%]
..........................                                                                                       [ 78%]
vispy\visuals\tests\test_infinite_line.py F                                                                      [ 78%]
vispy\visuals\tests\test_linear_region.py FFF                                                                    [ 79%]
vispy\visuals\tests\test_markers.py F                                                                            [ 79%]
vispy\visuals\tests\test_mesh.py ssssssssssssssss                                                                [ 84%]
vispy\visuals\tests\test_mesh_normals.py sssssss                                                                 [ 86%]
vispy\visuals\tests\test_polygon.py sss                                                                          [ 86%]
vispy\visuals\tests\test_rectangle.py FFF.                                                                       [ 88%]
vispy\visuals\tests\test_regular_polygon.py FFF                                                                  [ 88%]
vispy\visuals\tests\test_sdf.py .                                                                                [ 89%]
vispy\visuals\tests\test_spectrogram.py F                                                                        [ 89%]
vispy\visuals\tests\test_text.py F..                                                                             [ 90%]
vispy\visuals\tests\test_volume.py sssssssssssssssssssssssssssssssssss                                           [ 99%]
vispy\visuals\tests\test_windbarb.py F                                                                           [100%]
[...]
````
So then going through the errors it turns out that many tests such as `test_arrows` require `pillow` to be installed as well (it is listed as an optional dependency after all but it looks like it is kind of essential). So after installing `pillow` the situation appears better but still this tests fails:

````
______________________________________________ test_frame_buffer_helper _______________________________________________

    @requires_application()
    def test_frame_buffer_helper():
        canvas = FakeCanvas()
        gl_context = OffscreenContext()
        fbh = FrameBufferHelper()

        gl_context.make_current()
        fbh.set_physical_size(43, 67)
        with fbh:
            gloo.set_clear_color((0, 0.5, 1))
            gloo.clear()
            canvas.flush()
            array = fbh.get_frame()

        assert array.shape == (67, 43, 4)
        assert np.all(array[:, :, 0] == 0)
>       assert np.all(array[:, :, 1] == 128)
E       assert False
E        +  where False = <function all at 0x000001D9B55FDB80>(array([[127, 127, 127, ..., 127, 127, 127],\n       [127, 127, 127, ..., 127, 127, 127],\n       [127, 127, 127, ..., 12..., 127, 127, 127],\n       [127, 127, 127, ..., 127, 127, 127],\n       [127, 127, 127, ..., 127, 127, 127]], dtype=uint8) == 128)
E        +    where <function all at 0x000001D9B55FDB80> = np.all
vispy\app\backends\tests\test_offscreen_util.py:48: AssertionError
````

The test suite at this point wants to run again using other backends but stalls in the same section
````
_VISPY_TESTING_APP=pyglet C:\tools\miniconda3\envs\vispy_env\python.exe -m pytest -m vispy_app_test -ra C:\tools\miniconda3\envs\vispy_env\lib\site-packages\vispy
================================================= test session starts =================================================
platform win32 -- Python 3.9.7, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: C:\tools\miniconda3\envs\vispy_env\lib\site-packages
collected 1015 items / 648 deselected / 1 skipped / 366 selected

vispy\app\backends\tests\test_offscreen_util.py .F                                                               [  0%]
vispy\app\backends\tests\test_rfb.py s                                                                           [  0%]
vispy\app\tests\test_app.py

====================================================== FAILURES =======================================================
______________________________________________ test_frame_buffer_helper _______________________________________________

    @requires_application()
    def test_frame_buffer_helper():
        canvas = FakeCanvas()
        gl_context = OffscreenContext()
        fbh = FrameBufferHelper()

        gl_context.make_current()
        fbh.set_physical_size(43, 67)
        with fbh:
            gloo.set_clear_color((0, 0.5, 1))
            gloo.clear()
            canvas.flush()
            array = fbh.get_frame()

        assert array.shape == (67, 43, 4)
        assert np.all(array[:, :, 0] == 0)
>       assert np.all(array[:, :, 1] == 128)
E       assert False
E        +  where False = <function all at 0x000001B72CC4CB80>(array([[127, 127, 127, ..., 127, 127, 127],\n       [127, 127, 127, ..., 127, 127, 127],\n       [127, 127, 127, ..., 12..., 127, 127, 127],\n       [127, 127, 127, ..., 127, 127, 127],\n       [127, 127, 127, ..., 127, 127, 127]], dtype=uint8) == 128)
E        +    where <function all at 0x000001B72CC4CB80> = np.all

vispy\app\backends\tests\test_offscreen_util.py:48: AssertionError
================================================== warnings summary ===================================================
vispy/app/tests/test_app.py::test_run
  C:\tools\miniconda3\envs\vispy_env\lib\site-packages\_pytest\unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function OffscreenContext.__del__ at 0x000001B72DD48160>

  Traceback (most recent call last):
    File "C:\tools\miniconda3\envs\vispy_env\lib\site-packages\vispy\app\backends\_offscreen_util.py", line 83, in __del__
      self.close()
    File "C:\tools\miniconda3\envs\vispy_env\lib\site-packages\vispy\app\backends\_offscreen_util.py", line 80, in close
      self._canvas.close()
    File "C:\tools\miniconda3\envs\vispy_env\lib\site-packages\vispy\app\canvas.py", line 464, in close
      self._backend._vispy_close()
    File "C:\tools\miniconda3\envs\vispy_env\lib\site-packages\vispy\app\backends\_pyglet.py", line 268, in _vispy_close
      self.close()
    File "C:\tools\miniconda3\envs\vispy_env\lib\site-packages\pyglet\window\win32\__init__.py", line 319, in close
      super(Win32Window, self).close()
    File "C:\tools\miniconda3\envs\vispy_env\lib\site-packages\pyglet\window\__init__.py", line 838, in close
      app.windows.remove(self)
    File "C:\tools\miniconda3\envs\vispy_env\lib\_weakrefset.py", line 114, in remove
      self.data.remove(ref(item))
  KeyError: <weakref at 0x000001B72DBBD180; to 'CanvasBackend' at 0x000001B72DA64B50>

    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/warnings.html
````

How can I narrow this issue down?

**Comment by kmuehlbauer** [comment]
@asteppke Thanks for bringing this up here. I can't say much about the `test_frame_buffer_helper` problem. But for the `pillow` problem we should definitely skip those tests if pillow isn't installed.

**Comment by kmuehlbauer** [comment]
@asteppke I've created a new issue for the `pillow`-part, so we can concentrate on the frame buffer problem here.

**Comment by djhoese** [comment]
Sadly I'm also not sure what is going on with those failures. @asteppke could you try running just the image tests by doing `pytest vispy\visuals\tests\test_image.py` and see which tests are the failing ones? You might be able to get that information from your existing output too. I noticed that the `test_colormap.py` tests are all using ImageVisual so it makes me wonder if this is related to something specific to the ImageVisual or to the use of textures in a certain way. However, I also notice that that frame buffer test output seems to show that the values are only off by 1 (127 instead of the expected 128) so maybe all these failures are something specific to how your display/GPU are rendering things. I don't have a lot of experience with system/display settings (especially on Windows) that would effect this.

**Comment by asteppke** [comment]
Thank you for looking into this. If I understand the test code correctly it sets some color value as (0,0.5,1.0) and then compares this with the expectation of (0, 128, 255). So maybe this is "just" a change in rounding somewhere as 255/2=127.5. My hardware is pretty standard though, Nvidia RTX 2070, so nothing that should work differently in OpenGL than other hardware.
