### ISSUE TITLE
Trouble including vispy with pyinstaller on MacOS

### ISSUE THREAD

**Issue by djhoese** [vispy/vispy#2300]
Hi,

I am on MacOS, with Ubuntu it works properly.

I am having a similar problem. I use vispy==0.9 and pyinstaller==4.3, changed .spec file like you did, but I got this error:

```
Traceback (most recent call last):
  File "/Users/alessandrosestini/miniconda3/envs/prova/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/Users/alessandrosestini/miniconda3/envs/prova/lib/python3.6/site-packages/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/alessandrosestini/miniconda3/envs/prova/lib/python3.6/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/alessandrosestini/miniconda3/envs/prova/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Users/alessandrosestini/miniconda3/envs/prova/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 684, in build
    exec(code, spec_namespace)
  File "main.spec", line 23, in <module>
    noarchive=False)
  File "/Users/alessandrosestini/miniconda3/envs/prova/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 242, in __init__
    self.__postinit__()
  File "/Users/alessandrosestini/miniconda3/envs/prova/lib/python3.6/site-packages/PyInstaller/building/datastruct.py", line 160, in __postinit__
    self.assemble()
  File "/Users/alessandrosestini/miniconda3/envs/prova/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 468, in assemble
    redirects=self.binding_redirects))
  File "/Users/alessandrosestini/miniconda3/envs/prova/lib/python3.6/site-packages/PyInstaller/depend/bindepend.py", line 226, in Dependencies
    for lib, npth in selectImports(pth, xtrapath):
  File "/Users/alessandrosestini/miniconda3/envs/prova/lib/python3.6/site-packages/PyInstaller/depend/bindepend.py", line 500, in selectImports
    dlls = getImports(pth)
  File "/Users/alessandrosestini/miniconda3/envs/prova/lib/python3.6/site-packages/PyInstaller/depend/bindepend.py", line 752, in getImports
    return _getImports_macholib(pth)
  File "/Users/alessandrosestini/miniconda3/envs/prova/lib/python3.6/site-packages/PyInstaller/depend/bindepend.py", line 630, in _getImports_macholib
    m = MachO(pth)
  File "/Users/alessandrosestini/miniconda3/envs/prova/lib/python3.6/site-packages/macholib/MachO.py", line 117, in __init__
    with open(filename, "rb") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'GLESv2.framework/GLESv2'
```

_Originally posted by @SestoAle in https://github.com/vispy/vispy/issues/1643#issuecomment-1032398495_

**Comment by djhoese** [comment]
@SestoAle I've moved your comment to a separate issue so we can organize discussion better.

Are you able to run your vispy application on your MacOS system before using pyinstaller? Can you paste your .spec file here?

**Comment by SestoAle** [comment]
Yes I am able to run the application on MacOS before Pyinstaller.

Here is my .spec file

```
# -*- mode: python ; coding: utf-8 -*-
block_cipher = None
import vispy.gloo
import vispy.glsl
import vispy.io
import freetype

data_files = [
    ('arrays', 'arrays'), 
    ('saved', 'saved'), 
    (os.path.dirname(vispy.gloo.__file__), os.path.join("vispy", "gloo")), 
    (os.path.dirname(vispy.glsl.__file__), os.path.join("vispy", "glsl")),
    (os.path.join(os.path.dirname(vispy.io.__file__), "_data"), os.path.join("vispy", "io", "_data")),   
    (os.path.dirname(freetype.__file__), os.path.join("freetype"))
]

hidden_imports = [
    "vispy.ext.osmesa",
    "vispy.ext.egl",
    "freetype",
    "vispy.app.backends._pyqt5",
    "vispy.app.backends._pyqt4",
    "vispy.app.backends._egl"]

a = Analysis(['worldmodel_analysis.py'],
             pathex=['architectures'],
             binaries=[],
             datas=data_files,
             hiddenimports=hidden_imports,
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='worldmodel_analysis',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='worldmodel_analysis')

```

**Comment by djhoese** [comment]
It has been some time since I've used pyinstaller and I no longer have a Mac to test this on. I've asked some coworkers if they have any idea.

Otherwise, out of curiosity why do you have pyqt4, pyqt5, egl, and osmesa all included in your hidden imports?

**Comment by rayg-ssec** [comment]
This originally smelled related to https://github.com/vispy/vispy/issues/1885 , in which Apple's new (Big Sur and after) take on deprecation and/or limiting system introspection - have a library be available for linking by name, but not visible as files - led to ctypes/cffi having some issues. I'm not as sure of this as I was when I started poking around, but still probably worth some testing.

Assuming pyinstaller is trying to traverse binaries to extract the dependency tree, I'd try exempting the GLESv2 and see if the resulting app has a runtime link failure. I'm not able to find a GLESv2 framework, though I do see a libGLESv2.dylib via Adobe - It could still be an invisible subframework of another system framework?

**Comment by djhoese** [comment]
So @rayg-ssec, what you're saying is is that GLESv2 is going to be handled in an odd way by any modern MacOS system given Apple's deprecation of OpenGL. I'm not sure if you can tell pyinstaller to ignore one of the dependencies, but like I said it's been a while for me and pyinstaller.

**Comment by rayg-ssec** [comment]
My brother went through his collection of historical dev SDKs and could not find evidence that GLESv2 was previously a system framework - possibly see what output you get from `mdfind "kMDItemDisplayName=='*GLESv2.framework*'" ` (roughly a spotlight equivalent of locate command) to see if it's just not finding it in the right place?

**Comment by djhoese** [comment]
>  Pyqt4 and pyqt5 are included because the application ask for them.

Vispy can only use one at a time so for bundling a pyinstaller application I don't see a reason to use both.

**Comment by JacobBumgarner** [comment]
Random thought, so I apologize if it's not helpful or you've already considered this.

Have you tried building this outside of a miniconda3 environment? I have had the best success with pyinstaller bundling using pyenv.

**Comment by edwardsmith999** [comment]
Hi All, any progress on this. I have a similar problem building my wxpython GUI on MacOS with vispy. I get the following error:

```
21734 INFO: Processing module hooks...
21736 INFO: Loading module hook 'hook-scipy.special._ufuncs.py' from '/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/hooks'...
21789 WARNING: Hidden import "importlib_resources.trees" not found!
22044 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from '/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/hooks'...
22091 INFO: Loading module hook 'hook-scipy.special._ellip_harm_2.py' from '/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/hooks'...
22209 INFO: Loading module hook 'hook-pkg_resources.py' from '/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/hooks'...
23148 INFO: Loading module hook 'hook-matplotlib.backends.py' from '/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/hooks'...
23149 INFO: Matplotlib backend selection method: automatic discovery of used backends
23522 INFO: Trying determine the default backend as first importable candidate from the list: ['MacOSX', 'Qt5Agg', 'Gtk3Agg', 'TkAgg', 'WxAgg']
24290 INFO: Selected matplotlib backends: ['MacOSX']
24305 INFO: Loading module hook 'hook-scipy.stats._stats.py' from '/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/hooks'...
24403 INFO: Processing pre-safe import module hook win32com from '/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-win32com.py'.
24505 INFO: Loading module hook 'hook-distutils.util.py' from '/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/hooks'...
24944 INFO: Looking for ctypes DLLs
25101 INFO: Analyzing run-time hooks ...
25116 INFO: Including run-time hook '/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py'
25119 INFO: Including run-time hook '/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
25122 INFO: Including run-time hook '/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_mplconfig.py'
25124 INFO: Including run-time hook '/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgres.py'
25129 INFO: Including run-time hook '/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
25169 INFO: Looking for dynamic libraries
/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/building/build_main.py:177: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(package)
h5py package not avilable -- using ascii conversion
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.8.16/x64/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
  File "/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/__main__.py", line 194, in _console_script_run
    run()
  File "/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 979, in main
    build(specfile, distpath, workpath, clean_build)
  File "/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 901, in build
    exec(code, spec_namespace)
  File "pyDataView_apple1.spec", line 12, in <module>
    a = Analysis( ['pyDataView.py'],
  File "/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 414, in __init__
    self.__postinit__()
  File "/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/building/datastruct.py", line 173, in __postinit__
    self.assemble()
  File "/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 697, in assemble
    isolated.call(find_binary_dependencies, list(self.binaries), self.binding_redirects, collected_packages)
  File "/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/isolated/_parent.py", line 372, in call
    return isolated.call(function, *args, **kwargs)
  File "/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/isolated/_parent.py", line 302, in call
    raise RuntimeError(f"Child process call to {function.__name__}() failed with:\n" + output)
RuntimeError: Child process call to find_binary_dependencies() failed with:
  File "/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/isolated/_child.py", line 63, in run_next_command
    output = function(*args, **kwargs)
  File "/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 195, in find_binary_dependencies
    return bindepend.Dependencies(binaries, redirects=binding_redirects, xtrapath=extra_libdirs)
  File "/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/depend/bindepend.py", line 289, in Dependencies
    for lib, npth in selectImports(pth, xtrapath):
  File "/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/depend/bindepend.py", line 548, in selectImports
    dlls = getImports(pth)
  File "/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/depend/bindepend.py", line 795, in getImports
    return _getImports_macholib(pth)
  File "/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/PyInstaller/depend/bindepend.py", line 689, in _getImports_macholib
    m = MachO(pth)
  File "/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/macholib/MachO.py", line 121, in __init__
    with open(filename, "rb") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'user32.framework/user32'
Error: Process completed with exit code 1.
```
These error appear on a GitHub Actions build here with various versions of MacOS and Python (currently 11 and 3.8 respectively):
https://github.com/edwardsmith999/pyDataView/actions/runs/4484257272/jobs/7884556909

This error is introduced when I add to the spec file the lines:

```
import vispy.glsl
import vispy.io

data_files = [
    (os.path.dirname(vispy.glsl.__file__), os.path.join("vispy", "glsl")),
    (os.path.join(os.path.dirname(vispy.io.__file__), "_data"), os.path.join("vispy", "io", "_data"))
]

hidden_imports = [
        "vispy.ext._bundled.six",
        "vispy.app.backends._wx",    
    ]
a = Analysis(['pyDataView.py'],
             pathex=[],
             binaries=[],
             datas=**data_files**,
             hiddenimports=**hidden_imports**,
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
```
I've managed to run the GUI locally on Mac 11.5 with Python 3.

What is stranger, is I've managed to get this to build in stages by first using

`pyinstaller --windowed pyDataView.py`

which builds an app which doesn't find vispy glsl, so adding in the datafiles line by line, first adding to the spec file

```
import vispy.io
data_files = [
    (os.path.join(os.path.dirname(vispy.io.__file__), "_data"), os.path.join("vispy", "io", "_data"))
]

a = Analysis(['pyDataView.py'],
             pathex=[],
             binaries=[],
             datas=**data_files**,
```
Then adding in glsl,

```
import vispy.io
import vispy.glsl
data_files = [
    (os.path.dirname(vispy.glsl.__file__), os.path.join("vispy", "glsl")),
    (os.path.join(os.path.dirname(vispy.io.__file__), "_data"), os.path.join("vispy", "io", "_data"))
]

a = Analysis(['pyDataView.py'],
             pathex=[],
             binaries=[],
             datas=**data_files**,
```
the resulting application then works locally as expected. When I try on Actions this fails however.

**Comment by djhoese** [comment]
As far as I can tell user32 is supposed to be a Windows only thing, but the `.framework` part of that directory makes me think MacOS. What's really strange is that the log messages and error message talk about loading binary dependencies failing but you don't have any binaries defined in the `.spec` you've pasted here. Maybe you could hack in some `prints` to pyinstaller to try to figure out what dependencies are leading down this path to `user32`? Otherwise, I know longer have a mac and I don't use pyinstaller so I'm not sure I have the experience to help much.

Side note: You can remove the hidden `six` import. It is no longer bundled or used by modern vispy.

**Comment by edwardsmith999** [comment]
Hi @djhoese, thanks for the quick reply  (didn't come up on notifications so only just seen). It's a fairly reproducable error on the different MacOS on github Actions as well as a local laptop I have. Maybe the hooks try to include the binaries, I don't know enough about how Pyinstaller works but will see if dropping in some prints give some insight. Is it worth cross posting this issue on the Pyinstaller Github too? 
Good to know i can remove `six` import, it also seems that maybe `.backends.wx` isn't needed either when this does work. Under matplotlib, MacOS is listed as the backend (although this might be misleading, I'm not a native Mac user either and just trying to build this so a student can use it).

**Comment by djhoese** [comment]
> It's a fairly reproducable error on the different MacOS on github Actions as well as a local laptop I have.

You said in your original post that you didn't reproduce this on one of your local machines right? So you have a MacOS system locally that does show the error and one that doesn't?

> Good to know i can remove six import, it also seems that maybe .backends.wx isn't needed either when this does work. Under matplotlib, MacOS is listed as the backend (although this might be misleading, I'm not a native Mac user either and just trying to build this so a student can use it).

What vispy backend does your application use? I'm not sure what you mean about matplotlib. Matplotlib's backends are separate from vispy's backends. If your debugging wouldn't have shown that including the `glsl` directory triggers this I would have guessed that Wx was the problem and/or pyopengl. I'm not sure what about vispy's imports would trigger trying to load `user32`...which I still have know idea what that is.

**Comment by edwardsmith999** [comment]
Sorry, should have been clearer. I reproduce the same "No such file or directory: 'user32.framework/user32'" error on local laptop with MacOS 11.5, as well as on all the MacOS versions on Github Actions. Locally I did find a work around that built up the spec file in stages which seemed to avoid this error but it's not a good solution as I have no idea why it works and cannot reproduce on Actions.

The reason I was confused about backend is I got a
```
23522 INFO: Trying determine the default backend as first importable candidate from the list: ['MacOSX', 'Qt5Agg', 'Gtk3Agg', 'TkAgg', 'WxAgg']
24290 INFO: Selected matplotlib backends: ['MacOSX']
```
which I thought meant MacOS does something else in terms of backend. I use vispy in wxPython based on https://github.com/vispy/vispy/blob/main/examples/tutorial/app/simple_wx.py
but I notice nowhere do I actually use `vispy.app.backends._wx`

I'll try increasing the logging level `[--log-level](https://pyinstaller.org/en/v5.9.0/usage.html#cmdoption-log-level)` in pyinstaller and see if `Wx` and/or `pyopengl` are causing errors. Thanks again for the help here!

**Comment by djhoese** [comment]
That wx import is needed if you set the vispy app backend or it is the only backend available.
