### ISSUE TITLE
wrong comments in turntable.py

### ISSUE THREAD

**Issue by petaflot** [vispy/vispy#2392]
https://github.com/vispy/vispy/blob/16d8c5bd8694df9c18086e6fad31ffbaa08abaf4/vispy/scene/cameras/turntable.py#L27

but https://github.com/vispy/vispy/blob/16d8c5bd8694df9c18086e6fad31ffbaa08abaf4/vispy/scene/cameras/turntable.py#L64 

this is clearly wrong.

**Comment by djhoese** [comment]
Ah good catch. Would you mind updating this and making a PR for it to be more accurate?

**Comment by petaflot** [comment]
I course I mind, I'm lazy ;-)

 worse than that: `fov` was never set properly in Base3DRotationCamera.__init__() ! see https://github.com/vispy/vispy/blob/main/vispy/scene/cameras/base_camera.py#L91

considering this, I'm surprised there's any perspective at all : I found references in  vispy/visuals/transforms/linear.py but since it was set to 0.0 it should be ortho! can someone check?

**Comment by petaflot** [comment]
also, and since I'm pretty new to this "making changes to libs", can someone help me set up my environment so it points to my fork?

I did

```
cd ~/.local/lib/python3.10/site-packages
ls vispy # yes it's here
pip uninstall vispy
ln -s ~/_git/vispy/vispy # this looked like a reasonable thing to do
```
but when I try to run my code again I get 
```
Traceback (most recent call last):
  File "/home/meta/Documents/pulsar/./supervispy.py", line 17, in <module>
    from vispy import scene, app
  File "/home/meta/.local/lib/python3.10/site-packages/vispy/scene/__init__.py", line 33, in <module>
    from .visuals import *  # noqa
  File "/home/meta/.local/lib/python3.10/site-packages/vispy/scene/visuals.py", line 18, in <module>
    from .. import visuals
  File "/home/meta/.local/lib/python3.10/site-packages/vispy/visuals/__init__.py", line 14, in <module>
    from .axis import AxisVisual  # noqa
  File "/home/meta/.local/lib/python3.10/site-packages/vispy/visuals/axis.py", line 13, in <module>
    from .text import TextVisual
  File "/home/meta/.local/lib/python3.10/site-packages/vispy/visuals/text/__init__.py", line 7, in <module>
    from .text import TextVisual  # noqa
  File "/home/meta/.local/lib/python3.10/site-packages/vispy/visuals/text/text.py", line 18, in <module>
    from ._sdf_cpu import _calc_distance_field
ModuleNotFoundError: No module named 'vispy.visuals.text._sdf_cpu'
```

it would obviously be appreciable if I could make some tests before doing some commits/pushes

**Comment by djhoese** [comment]
`fov` is set in the base classes in `perspective.py`:

https://github.com/vispy/vispy/blob/main/vispy/scene/cameras/perspective.py#L38

For contributing, see https://vispy.org/installation.html#dev-install for installing vispy from the github source. You don't want to modify the code in `site-packages`, but rather install the package in "editable" mode. In the `git clone` command on that page you would specify your fork instead of `vispy/vispy` (ex. `petaflot/vispy.git`).
