### ISSUE TITLE
error with pyside2 backend on macOS arm64

### ISSUE THREAD

**Issue by psobolewskiPhD** [vispy/vispy#2406]
Originally I noted this with `napari`, see: https://github.com/napari/napari/issues/5231

But it seems to be a vispy issue, because if you install:
`mamba create --name test-env3 python=3.9 pyside2 vispy`
then examples fail, for example https://vispy.org/gallery/scene/turntable_box.html#sphx-glr-gallery-scene-turntable-box-py
Error:
`AttributeError: 'CanvasBackendDesktop' object has no attribute 'defaultFramebufferObject'`

```
Traceback (most recent call last):
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 913, in paintGL
    context.flush()
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/gloo/wrappers.py", line 573, in flush
    context.flush_commands()  # Process GLIR commands
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/gloo/context.py", line 168, in flush_commands
    fbo = canvas._backend._vispy_get_fb_bind_location()
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 875, in _vispy_get_fb_bind_location
    return self.defaultFramebufferObject()
AttributeError: 'CanvasBackendDesktop' object has no attribute 'defaultFramebufferObject'
WARNING: Error drawing visual <vispy.visuals.mesh.MeshVisual object at 0x132dd85b0>
WARNING: Traceback (most recent call last):
  File "/Users/piotrsobolewski/Downloads/turntable_box.py", line 30, in <module>
    canvas.app.run()
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/app/application.py", line 160, in run
    return self._backend._vispy_run()
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 335, in _vispy_run
    return exec_func()
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 567, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 903, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  << caught exception here: >>
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/scene/canvas.py", line 218, in on_draw
    self._draw_scene()
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/scene/canvas.py", line 277, in _draw_scene
    self.draw_visual(self.scene)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/scene/canvas.py", line 315, in draw_visual
    node.draw()
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/scene/visuals.py", line 103, in draw
    self._visual_superclass.draw(self)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/visuals/visual.py", line 605, in draw
    v.draw()
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/visuals/visual.py", line 451, in draw
    self._program.draw(self._vshare.draw_mode,
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/visuals/shaders/program.py", line 102, in draw
    Program.draw(self, *args, **kwargs)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/gloo/program.py", line 526, in draw
    canvas.context.flush_commands()
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/gloo/context.py", line 168, in flush_commands
    fbo = canvas._backend._vispy_get_fb_bind_location()
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 875, in _vispy_get_fb_bind_location
    return self.defaultFramebufferObject()
AttributeError: 'CanvasBackendDesktop' object has no attribute 'defaultFramebufferObject'
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PySide2) at 0x1028f5b20>> for DrawEvent
```
Env details:
`pyside2                   5.15.6           py39hf5e3978_2    conda-forge`
`vispy                     0.11.0           py39h04ce77e_0    conda-forge`

note that `mamba create --name test-env3 python=3.9 pyqt vispy`
works fine with 
```
╰─ conda list | grep pyqt                                         (test-env3) ─╯
pyqt                      5.15.7           py39h7fba1b6_1    conda-forge
pyqt5-sip                 12.11.0          py39h23fbdae_1    conda-forge
```
`vispy                     0.11.0           py39h04ce77e_0    conda-forge`

**Comment by djhoese** [comment]
Do we know if this is specific to MacOS? Specific to ARM64 macs? Specific to the version of Qt that PySide 2 is using?

**Comment by djhoese** [comment]
As far as I can tell that method should exist in PySide2:

https://doc.qt.io/qtforpython-5/PySide2/QtWidgets/QOpenGLWidget.html?highlight=qopenglwidget#PySide2.QtWidgets.PySide2.QtWidgets.QOpenGLWidget.defaultFramebufferObject

**Comment by psobolewskiPhD** [comment]
> Do we know if this is specific to MacOS? Specific to ARM64 macs? Specific to the version of Qt that PySide 2 is using?

Sorry I don't have access to any other machine at the moment. It could be all of those.

**Comment by psobolewskiPhD** [comment]
I ran the pyside2 example: https://github.com/pyside/pyside2-setup/blob/5.15/examples/widgets/widgets/tetrix.py
and it works fine in the conda-forge pyside2 env
<img width="662" alt="image" src="https://user-images.githubusercontent.com/76622105/196395679-f5334224-1180-4806-8725-a519bf199b94.png">
So maybe it's some interaction between arm64 pyside2 and vispy?

**Comment by djhoese** [comment]
I could be missing something but I don't see pyside2 wheels for non-intel macs here:

https://pypi.org/project/PySide2/#files

I'm surprised it installed at all.

**Comment by psobolewskiPhD** [comment]
> I could be missing something but I don't see pyside2 wheels for non-intel macs here:
> 
> https://pypi.org/project/PySide2/#files
> 
> I'm surprised it installed at all.

pyside2 is built for arm64 macOS on conda-forge:
```
Executing the query pyside2

conda-forge/osx-arm64                              @   3.0MB/s  1.3s
conda-forge/noarch                                 @   4.1MB/s  2.7s


 Name    Version Build           Channel              
───────────────────────────────────────────────────────
 pyside2 5.15.6  py310h1ceb87a_0 conda-forge/osx-arm64
 pyside2 5.15.6  py310h1ceb87a_1 conda-forge/osx-arm64
 pyside2 5.15.6  py310h1ceb87a_2 conda-forge/osx-arm64
 pyside2 5.15.6  py38h9ecd3b8_0  conda-forge/osx-arm64
 pyside2 5.15.6  py38h9ecd3b8_1  conda-forge/osx-arm64
 pyside2 5.15.6  py38h9ecd3b8_2  conda-forge/osx-arm64
 pyside2 5.15.6  py39hf5e3978_0  conda-forge/osx-arm64
 pyside2 5.15.6  py39hf5e3978_1  conda-forge/osx-arm64
 pyside2 5.15.6  py39hf5e3978_2  conda-forge/osx-arm64
 pyside2 5.15.5  py310h5219f08_1 conda-forge/osx-arm64
 pyside2 5.15.5  py38h465b20c_1  conda-forge/osx-arm64
 pyside2 5.15.5  py39h46bc059_1  conda-forge/osx-arm64
```

I hit the issue when napari installed from conda-forge pulled pyside2 backend instead of pyqt5.

**Comment by djhoese** [comment]
Looks like that pyside2 opengl example is using the old GL API by using the `QGLWidget` instead of the newer (Qt 5+) API with `QOpenGLWidget` like VisPy does:

https://github.com/vispy/vispy/blob/8bf4f9e538dee5cb986779006b84f62eed81ed7c/vispy/app/backends/_qt.py#L130

**Comment by psobolewskiPhD** [comment]
@Czaki is helping with some testing in the napari issue thread:
> @psobolewskiPhD could you run this code (from script) and paste output
> 
> ```python
> import qtpy
> from vispy import app
> 
> # set vispy application to the appropriate qt backend
> app.use_app(qtpy.API_NAME)
> 
> from vispy.app.backends import _qt as vqt
> 
> print("qt new",  vqt.QT5_NEW_API)
> print("pyqt6",  vqt.PYQT6_API)
> print("pyside6",  vqt.PYSIDE6_API)
> print("egl", vqt.USE_EGL)
> print("attr",  vqt.QGLWidget, hasattr(vqt.QGLWidget, "defaultFramebufferObject"))
> ```

Here's what I get with pyside2
and the env with `"napari=*=*pyside2*"`
```
╰─ python test_pyside2.py                                         (test-env2) ─╯
qt new True
pyqt6 False
pyside6 False
egl False
attr <class 'PySide2.QtWidgets.QOpenGLWidget'> False
```
vs Here's my regular pyqt env:
```
╰─ python test_pyside2.py                                        (napari-dev) ─╯
qt new True
pyqt6 False
pyside6 False
egl False
attr <class 'PyQt5.QtWidgets.QOpenGLWidget'> True
```

**Comment by Czaki** [comment]
This is pyside2 (probably feedstock) problem.

Here Linux pyside2 output.

```
$ python py_vispy.py 
qt new True
pyqt6 False
pyside6 False
egl False
attr <class 'PySide2.QtWidgets.QOpenGLWidget'> True
```

**Comment by psobolewskiPhD** [comment]
What version of pyside2 and installed from where?

**Comment by psobolewskiPhD** [comment]
Ok, so generally the same. 🤷‍♂️

**Comment by Czaki** [comment]
Also it is mentioned in pyside2 docs:

https://doc.qt.io/qtforpython-5/PySide2/QtWidgets/QOpenGLWidget.html#PySide2.QtWidgets.PySide2.QtWidgets.QOpenGLWidget.defaultFramebufferObject

so it looks like a bug in the build process.

**Comment by psobolewskiPhD** [comment]
FYI: I made a python 3.10 env, which has a different build number for pyside2 and get the same error.

**Comment by psobolewskiPhD** [comment]
Update: it's not a conda-forge specific issue.
pyside2 arm64 from homebrew also has the same problem, see:
https://github.com/napari/packaging/issues/35#issuecomment-1307204473

**Comment by psobolewskiPhD** [comment]
Update2: it's been reported up-stream by Julien Schueller
https://bugreports.qt.io/browse/PYSIDE-2187

**Comment by psobolewskiPhD** [comment]
https://github.com/conda-forge/pyside2-feedstock/pull/175
has been merged and I can confirm the issue is solved!
`hasattr(QOpenGLWidget, "defaultFramebufferObject")`
reports `True` on macOS 13.1 arm64 for pyside2 build live on conda-forge.
Everything works as far as I can tell.
