### ISSUE TITLE
error with pyside6 6.4.0 backend on macOS arm64

### ISSUE THREAD

**Issue by psobolewskiPhD** [vispy/vispy#2407]
Making a fresh env, python 3.9 or python 3.10, then installing pyside6 `pip install pyside6` and vispy (0.11.0) works, but running
https://vispy.org/gallery/scene/turntable_box.html#sphx-glr-gallery-scene-turntable-box-py
fails with error:
```
╰─ python turntable_box.py                                        (test-env3) ─╯
Traceback (most recent call last):
  File "/Users/piotrsobolewski/Downloads/turntable_box.py", line 17, in <module>
    canvas = scene.SceneCanvas(keys='interactive', size=(800, 600), show=True)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/scene/canvas.py", line 135, in __init__
    super(SceneCanvas, self).__init__(
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/app/canvas.py", line 211, in __init__
    self.create_native()
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/app/canvas.py", line 228, in create_native
    self._app.backend_module.CanvasBackend(self, **self._backend_kwargs)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 372, in __init__
    self._init_specific(p, kwargs)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 791, in _init_specific
    glformat = _set_config(p.context.config)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env3/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 283, in _set_config
    glformat.setSwapBehavior(glformat.DoubleBuffer if c['double_buffer']
AttributeError: 'PySide6.QtGui.QSurfaceFormat' object has no attribute 'DoubleBuffer'
```

(by comparison the same but with `pip install pyqt6` works fine.)

**Comment by djhoese** [comment]
Just so we keep a record: see related #2335 and #2406.

It seems like we might need to add yet another test environment for pyside2 (based on #2406). For this PySide6 stuff I'm hoping we can just live with user testing for now. I can't find it right now but I believe there was another issue around with someone getting a seg fault on macOS with Qt6 installed. That might have been specific to their environment though.

@psobolewskiPhD do you or someone on the napari team (@brisvag?) think you could add a new CI environment to vispy that uses pyside2 to run the examples? Or if you want pyside6 instead?

**Comment by psobolewskiPhD** [comment]
> Just so we keep a record: see related #2335 and #2406.
> 
> It seems like we might need to add yet another test environment for pyside2 (based on #2406). For this PySide6 stuff I'm hoping we can just live with user testing for now. I can't find it right now but I believe there was another issue around with someone getting a seg fault on macOS with Qt6 installed. That might have been specific to their environment though.
> 
> @psobolewskiPhD do you or someone on the napari team (@brisvag?) think you could add a new CI environment to vispy that uses pyside2 to run the examples? Or if you want pyside6 instead?

At least from a napari PoV Qt6 (so pyside6) is really experimental and not officially supported. But pyside2 is supported and maybe even cleaner from a licensing PoV, so I think CI tests with it would be a good idea. napari tests windows and ubuntu with PySide2==5.15.2.1 and ubuntu with pyside6, so this issue could be mac specific or conda-forge specific or version specific.

**Comment by psobolewskiPhD** [comment]
Based on some sleuthing by @czaki I tried python 3.10 and pyside6 (latest, 6.4.0) but it still gave the same error. However! Using pyside6 6.3.0 and 6.3.2 was fine, so this issue is specific to something that's changed in pyside 6 6.40. I've edited the title.

**Comment by Czaki** [comment]
Yes. Phis is pyside 6.4.0 proble and requires a new qtpy release
https://github.com/spyder-ide/qtpy/pull/374

**Comment by Czaki** [comment]
could you show traceback? 
Is the code working with 6.3.1 and/or 6.3.2.

**Comment by psobolewskiPhD** [comment]
Traceback is in the OP and yes both 6.3.0 and 6.3.2 work (https://github.com/vispy/vispy/issues/2407#issuecomment-1283776193)

**Comment by Czaki** [comment]
Could you report it to vispy?

**Comment by psobolewskiPhD** [comment]
> Could you report it to vispy?

How? This is a vispy issue... Sorry if i'm missing something, it's been a long day.

**Comment by Czaki** [comment]
It is a long day, and this is the proper diagnosis for me. I war pretty sure that I'm in napari repository.

**Comment by djhoese** [comment]
@psobolewskiPhD I'm trying to look through pyside6 source code, but their git web UI is not helpful. Since I don't see it defined here, what are the minimal number of steps to reproduce this (what commands create the environment)? Are you able to do an import of the exact PySide6 module and access this attribute it is failing on?

```
from PySide6.QtGui import QSurfaceFormat
print(hasattr(QSurfaceFormat, "DoubleBuffer"))
```

**Comment by djhoese** [comment]
Scratch that code, try this:

```
from PySide6.QtGui import QSurfaceFormat
qsf = QSurfaceFormat()
print(hasattr(qsf, "DoubleBuffer"))
print(hasattr(qsf.SwapBehavior, "DoubleBuffer"))
```

This "SwapBehavior" version matches what vispy is doing for PyQt6 so maybe PySide6 6.4.0+ is matching PyQt6 for this interface...or something similar.

**Comment by psobolewskiPhD** [comment]
Replicating the env:
```
mamba create -n vispy-clean -c conda-forge python=3.9 
conda activate wispy-clean
pip install pyside6
pip install vispy
```
Here's the output I get on my arm64 macOS 12.6:
```
>>> from PySide6.QtGui import QSurfaceFormat
>>> qsf = QSurfaceFormat()
>>> print(hasattr(qsf, "DoubleBuffer"))
False
>>> print(hasattr(qsf.SwapBehavior, "DoubleBuffer"))
True
>>> 
```

**Comment by djhoese** [comment]
Great! I see the same thing on my Ubuntu system. Note that the vispy installation isn't actually necessary for this simple test.

So it looks like PySide6 6.4.0 uses the same interfaces as PyQt6. This should be a simple but yet another version check we need to do in `_qt.py`. @psobolewskiPhD or @Czaki would you be willing and have the time to make a PR for this?

I think the main change is here:

https://github.com/vispy/vispy/blob/8bf4f9e538dee5cb986779006b84f62eed81ed7c/vispy/app/backends/_qt.py#L281-L287

I'm not sure if this is the only change. We may need to rename `PYSIDE6_API` to `PYSIDE6_LEGACY_API` and create a new `PYSIDE6_API` that is used in the same locations as `PYQT6_API`. *If* there are more name changes that effect vispy then it may be that PyQt6 and PySide6 now have equivalent interfaces. In that case importing PySide6 6.4+ could just set `PYQT6_API` to True.

**Comment by psobolewskiPhD** [comment]
Awesome 👏 
I can try to take a look over the weekend. 
❤️

**Comment by psobolewskiPhD** [comment]
@djhoese I ran your tests on PySide6 6.3.2:
```
>>> from PySide6.QtGui import QSurfaceFormat
>>> qsf = QSurfaceFormat()
>>> print(hasattr(qsf, "DoubleBuffer"))
True
>>> print(hasattr(qsf.SwapBehavior, "DoubleBuffer"))
True
```
So if I'm understanding correctly, so it looks like `DoubleBuffer` was removed in 6.4, but SwapBehavior was already changed in 6.3—I can't test older, due to lack of arm64 binaries.
I also can't figure out how to check when the change was made via pyside6 docs.


Also, I tried to run tests and get a seg fault—with or without any changes (aka from `main`). This happens with pyside6 6.3.2 (where the example runs without any changes) or 6.4.0 (which requires the fix) but not pyqt5 or pyqt6.
```
vispy/app/tests/test_context.py Fatal Python error: Segmentation fault

Current thread 0x0000000103284580 (most recent call first):
  File "/Users/piotrsobolewski/Dev/vispy/vispy/testing/_testing.py", line 215 in deco
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/_pytest/python.py", line 192 in pytest_pyfunc_call
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/_pytest/python.py", line 1761 in runtest
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/_pytest/runner.py", line 166 in pytest_runtest_call
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/_pytest/runner.py", line 259 in <lambda>
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/_pytest/runner.py", line 338 in from_call
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/_pytest/runner.py", line 258 in call_runtest_hook
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/_pytest/runner.py", line 219 in call_and_report
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/_pytest/runner.py", line 130 in runtestprotocol
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/_pytest/runner.py", line 111 in pytest_runtest_protocol
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/_pytest/main.py", line 347 in pytest_runtestloop
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/_pytest/main.py", line 322 in _main
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/_pytest/main.py", line 268 in wrap_session
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/_pytest/main.py", line 315 in pytest_cmdline_main
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/_pytest/config/__init__.py", line 164 in main
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/lib/python3.9/site-packages/_pytest/config/__init__.py", line 187 in console_main
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/vispy-clean/bin/pytest", line 8 in <module>
fish: Job 1, 'pytest .' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by psobolewskiPhD** [comment]
I've used both approaches:
using PYSIDE6_LEGACY_API vs. PYSIDE6_API:
https://github.com/psobolewskiPhD/vispy/tree/use_pyside6_legacy
```
    if QT5_NEW_API or PYSIDE6_LEGACY_API:
        # Qt5 >= 5.4.0 - below options automatically enabled if nonzero.
        glformat.setSwapBehavior(glformat.DoubleBuffer if c['double_buffer']
                                 else glformat.SingleBuffer)
    elif PYQT6_API or PYSIDE6_API:
        glformat.setSwapBehavior(glformat.SwapBehavior.DoubleBuffer if c['double_buffer']
                                 else glformat.SwapBehavior.SingleBuffer)
```

Or just using PYSIDE6_API along side PYQT6 for the SwapBehavior related to DoubleBuffer:
https://github.com/psobolewskiPhD/vispy/tree/use_pyqt6
```
    if QT5_NEW_API:
        # Qt5 >= 5.4.0 - below options automatically enabled if nonzero.
        glformat.setSwapBehavior(glformat.DoubleBuffer if c['double_buffer']
                                 else glformat.SingleBuffer)
    elif PYQT6_API or PYSIDE6_API:
        glformat.setSwapBehavior(glformat.SwapBehavior.DoubleBuffer if c['double_buffer']
                                 else glformat.SwapBehavior.SingleBuffer)
```
I will try and figure out when the change was made in pyside6.

**Comment by psobolewskiPhD** [comment]
The segfault in the `test_contexts` may be related to: https://github.com/vispy/vispy/blob/8bf4f9e538dee5cb986779006b84f62eed81ed7c/vispy/app/backends/_qt.py#L308-L315
I will poke around some more.

**Comment by psobolewskiPhD** [comment]
OK, so `test_context` has `xfail` for pyqt5, pyqt6, but not pyside2 or pyside6.
Meanwhile, in `_qt.py` `use_shared_context()` is set to false for pyside6:
https://github.com/vispy/vispy/blob/8bf4f9e538dee5cb986779006b84f62eed81ed7c/vispy/app/backends/_qt.py#L237-L245

So either the test needs pyside6 added to xfail... or pyside6 needs to have `use_shared_context()` set True. The docs do indicate that pyside6 supports it: 
https://doc.qt.io/qtforpython-6/PySide6/QtOpenGLWidgets/QOpenGLWidget.html?highlight=context#context-sharing
If I do that, then the tests pass for me locally with pyside6 6.3.2.

**Comment by psobolewskiPhD** [comment]
> So if I'm understanding correctly, so it looks like `DoubleBuffer` was removed in 6.4, but SwapBehavior was already changed in 6.3—I can't test older, due to lack of arm64 binaries.
> I also can't figure out how to check when the change was made via pyside6 docs.

I found the Qt 6.2 (LTS) docs. The swap behavior was already present.
https://doc.qt.io/qt-6.2/qsurfaceformat.html#SwapBehavior-enum
https://doc.qt.io/qtforpython-6.2/PySide6/QtGui/QSurfaceFormat.html#PySide6.QtGui.PySide6.QtGui.QSurfaceFormat.SwapBehavior

So I think the 2nd option above is better—I'll make a PR with that. There's a chance somehow pyside6 6.0 or 6.1 won't work, but it seems slim.
