### ISSUE TITLE
GlirParser._gl_initialize Enables capabilities before checking GL Version

### ISSUE THREAD

**Issue by camblomquist** [vispy/vispy#2451]
I was trying to run a Python script that uses vispy on an M1 MacBook Air and it fails to run. The stack trace points me to
```
File "vispy/gloo/glir.py", line 839, in _gl_initialize
    gl.glEnable(GL_POINT_SPRITE)
```
After this line, the function appears to check for the version of OpenGL.

The `GL_POINT_SPRITE` enum was deprecated and later removed pretty early in GL3.X and the behavior it enabled became the default according to my quick search.

`GL_VERTEX_PROGRAM_POINT_SIZE` is not providing this error, but I do not see it in the list of [supported capabilities in GL4](https://registry.khronos.org/OpenGL-Refpages/gl4/html/glEnable.xhtml), so it would likely present the same error if some shader wanted version 4XX.

Instead of checking for a mobile or desktop environment, the OpenGL version should be checked first and then the capabilities can be enabled based on what is returned.

I could be misunderstanding this as I'm not all too familiar with OpenGL. I don't know how or where GlirParser is constructed so it's possible that it's my responsibility to ensure that the version is valid before GlirParser is contructed. Or maybe you only support OpenGL 3.1.

**Comment by djhoese** [comment]
Hhhhmm this is interesting, concerning, and confusing all at the same time. So VisPy's original design was to support OpenGL 2 and OpenGL ES 2 (yes, very old at this point). As time has gone on we've been able to support slightly fancier functionality by using CONSTANTS and APIs made available via OpenGL extensions. These extensions basically mean we can run OpenGL 2.x functionality but still use some of the newer features of GL 3 or sometimes GL 4. They *don't* mean that we *must* use OpenGL 3 or 4 APIs and can't use GL 2 APIs.

Now if we/you/someone wanted to only use 3/4 APIs then there are ways to initialize OpenGL and/or your GUI framework (ex. PyQt5/6) so that everybody follows the same rules. This idea is generally encapsulated in "OpenGL Profiles" where you have compatibility profiles (typically the default) and core profiles. The compatibility profile(s) will typically give you access to a version of the OpenGL API that uses features from different versions of OpenGL and is generally backwards compatible. Using a "core" profile is more strict and means you have to use only the new API. At least this is my understanding.

So the fact that you're getting this error (could you please provide the entire traceback?) suggests one of a couple possibilities:

1. You are telling your script or your GUI framework to use a different OpenGL profile/API.
2. Your video/GPU driver or OSX has finally said "No more old OpenGL". Apple/OSX said they were deprecating OpenGL support a long time ago, but I've lost track of what the actual plan for that is/was.

I don't have a macbook let alone a M1/M2 macbook, so I'm not sure how much testing I can do myself. I do know that in the past when I did have a macbook and I tried to force it to use a Core profile so I could use some newer/fancier OpenGL features it yelled at me for the way VisPy was initializing its drawing or rather the order of steps VisPy was taking to prepare for a draw.

**Comment by camblomquist** [comment]
I can try to get you an MRE because the [script I'm working with](https://github.com/danilw/shadertoy-to-video-with-FBO) is quite long and possibly doing something questionable. I have no idea when I'll be able to get to that though.

I've gone and tried multiple backends (and removed the use parameter in the aforementioned script,) to check for differences in behavior. Pyglet is actually the only one I've tested that produces this issue.
```
Traceback (most recent call last):
  File "/Users/cameron/Documents/sketch-test/sketch.py", line 1272, in <module>
    canvas.app.run()
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/vispy/app/application.py", line 160, in run
    return self._backend._vispy_run()
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/vispy/app/backends/_pyglet.py", line 157, in _vispy_run
    return pyglet.app.run()
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/pyglet/app/__init__.py", line 72, in run
    event_loop.run(interval)
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/pyglet/app/base.py", line 151, in run
    timeout = self.idle()
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/pyglet/app/base.py", line 212, in idle
    self.clock.call_scheduled_functions(dt)
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/pyglet/clock.py", line 227, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/pyglet/app/base.py", line 118, in _redraw_windows
    window.dispatch_event('on_draw')
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/pyglet/window/__init__.py", line 1328, in dispatch_event
    super().dispatch_event(*args)
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/pyglet/event.py", line 387, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/vispy/app/backends/_pyglet.py", line 227, in on_draw
    self.our_draw_func()
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/vispy/app/backends/_pyglet.py", line 324, in our_draw_func
    self._vispy_canvas.events.draw(region=None)
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  << caught exception here: >>
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/Users/cameron/Documents/sketch-test/sketch.py", line 650, in on_draw
    self.draw()
  File "/Users/cameron/Documents/sketch-test/sketch.py", line 634, in draw
    self.program.draw()
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/vispy/gloo/program.py", line 543, in draw
    canvas.context.flush_commands()
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/vispy/gloo/context.py", line 172, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/vispy/gloo/glir.py", line 584, in flush
    self._shared.flush(parser)
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/vispy/gloo/glir.py", line 506, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/vispy/gloo/glir.py", line 824, in parse
    self._parse(command)
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/vispy/gloo/glir.py", line 786, in _parse
    ob.draw(*args)
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/vispy/gloo/glir.py", line 1325, in draw
    gl.check_error('Check before draw')
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/vispy/gloo/gl/__init__.py", line 204, in check_error
    raise err
RuntimeError: OpenGL got errors (Check before draw): GL_INVALID_ENUM
ERROR: Invoking <bound method RenderingCanvas.on_draw of <RenderingCanvas (Pyglet) at 0x106270f40>> for DrawEvent
```

GLFW (and I believe PyQt6 but I don't have the trace in front of me) fail much faster, refusing to compile the shader at all.
```Shader failed to compile:
in.glsl(-35): error: '' :  version '140' is not supported
in.glsl(-33): error: extension 'GL_ARB_shader_bit_encoding' is not supported
in.glsl(-32): error: extension 'GL_ARB_gpu_shader5' is not supported

Exception ignored on calling ctypes callback function: <function CanvasBackend._on_draw at 0x10648add0>
Traceback (most recent call last):
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/glfw/__init__.py", line 666, in callback_wrapper
    return func(*args, **kwargs)
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/vispy/app/backends/_glfw.py", line 406, in _on_draw
    self._vispy_canvas.events.draw(region=None)  # (0, 0, w, h))
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/Users/cameron/Documents/sketch-test/sketch.py", line 650, in on_draw
    self.draw()
  File "/Users/cameron/Documents/sketch-test/sketch.py", line 523, in draw
    exit(1)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1
Shader failed to compile:
in.glsl(-35): error: '' :  version '140' is not supported
in.glsl(-33): error: extension 'GL_ARB_shader_bit_encoding' is not supported
in.glsl(-32): error: extension 'GL_ARB_gpu_shader5' is not supported
```
I actually have not been able to find a version that is supported for either of these. I also imagine this is a different issue but I don't know enough about anything going on here to make any claims.

**Comment by camblomquist** [comment]
Examples are a good place to start. I tested `gloo/rotate_cube.py` and `offscreen/simple_egl.py`. For former was able to run but provided the following trace
```
2023-02-13 18:42:46.157 Python[31304:7321690] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/vq/lnb26_l90mvdrv5h1vw8d6xc0000gn/T/org.python.python.savedState
WARNING: Traceback (most recent call last):
  File "/Users/cameron/Documents/sketch-test/rotate_cube.py", line 171, in <module>
    canvas = Canvas()
  File "/Users/cameron/Documents/sketch-test/rotate_cube.py", line 103, in __init__
    app.Canvas.__init__(self, keys='interactive', size=(800, 600))
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/vispy/app/canvas.py", line 211, in __init__
    self.create_native()
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/vispy/app/canvas.py", line 228, in create_native
    self._app.backend_module.CanvasBackend(self, **self._backend_kwargs)
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/vispy/app/backends/_glfw.py", line 298, in __init__
    self._on_resize(self._id, size[0], size[1])
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/vispy/app/backends/_glfw.py", line 394, in _on_resize
    self._vispy_canvas.events.resize(
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  << caught exception here: >>
  File "/Users/cameron/Documents/sketch-test/.venv/lib/python3.10/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/Users/cameron/Documents/sketch-test/rotate_cube.py", line 149, in on_resize
    self.program['u_projection'] = self.projection
AttributeError: 'Canvas' object has no attribute 'program'
ERROR: Invoking <bound method Canvas.on_resize of <Canvas (Glfw) at 0x1165aefb0>> for ResizeEvent
```
Which I can imagine is from examples lagging behind from the current API. Once again doesn't strike at the original issue.

The latter was not able to use `egl` but removing the `use` and `assert` had it run without any issue.
It did produce the following though
```
2023-02-13 18:44:21.449 Python[31319:7322268] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/vq/lnb26_l90mvdrv5h1vw8d6xc0000gn/T/org.python.python.savedState
```
Which is a general issue with running windowed applications in Python on MacOS if StackOverflow is to be believed, so not an issue with how vispy works.

Most of what I've encountered so far appears unrelated to the original issue. I don't know what is worth investigating and what isn't.

**Comment by djhoese** [comment]
Unless I'm forgetting something huge `rotating_cube.py` should work fine. The API and the examples haven't changed *that* much that the Canvas would completely not have the `.program` attribute. If there were other exceptions further up then that might explain it (something didn't get initialized properly).

If you can try PyQt5 that would be a good starting point as that is probably the most heavily tested backend. That said, the error you got about compiling the shaders seems like it is still trying to do something with a newer version of OpenGL. Is this custom shader code or builtin vispy? Are you using Geometry shaders or something beyond basic vertex and fragment shaders?
