### ISSUE TITLE
vispy.test() failed. What should I do?

### ISSUE THREAD

**Issue by ManHinnn0509** [vispy/vispy#2466]
Hello, thank you for the library.
I installed vispy in my venv today and when I run `vispy.test()` it seemed like it failed.
I created a [gist](https://gist.github.com/ManHinnn0509/f9392e74dfe571baffae3ee045bbf18b) for this. Full log, sys info and even pip list is in there.

Here's the short summary info:
```
====================================================== short test summary info ====================================================== 
SKIPPED [1] vispy\util\tests\test_gallery_scraper.py:15: Skipping sphinx-gallery tests
SKIPPED [1] _pytest\unittest.py:367: Triangulation differences on Py3k
SKIPPED [1] vispy\gloo\gl\tests\test_names.py:63: Requires PyOpenGL
SKIPPED [1] vispy\gloo\gl\tests\test_names.py:71: Requires PyOpenGL
SKIPPED [1] vispy\gloo\gl\tests\test_use.py:13: Requires PyOpenGL
SKIPPED [1] vispy\gloo\tests\test_glir.py:125: Requires PyOpenGL
SKIPPED [1] vispy\gloo\tests\test_glir.py:169: Requires PyOpenGL
SKIPPED [1] vispy\gloo\tests\test_glir.py:215: Requires PyOpenGL
SKIPPED [1] vispy\gloo\tests\test_glir.py:261: Requires PyOpenGL
SKIPPED [1] vispy\gloo\tests\test_texture.py:310: Requires PyOpenGL
SKIPPED [1] vispy\gloo\tests\test_texture.py:439: Requires PyOpenGL
SKIPPED [1] vispy\gloo\tests\test_texture.py:653: Requires PyOpenGL
SKIPPED [1] vispy\gloo\tests\test_texture.py:659: Requires PyOpenGL
SKIPPED [1] vispy\gloo\tests\test_texture.py:665: Requires PyOpenGL
SKIPPED [1] vispy\gloo\tests\test_texture.py:707: Requires PyOpenGL
SKIPPED [1] vispy\gloo\tests\test_texture.py:713: Requires PyOpenGL
SKIPPED [32] vispy\gloo\tests\test_texture.py:718: Requires PyOpenGL
SKIPPED [1] vispy\io\tests\test_image.py:36: imageio or PIL required
SKIPPED [1] vispy\util\tests\test_docstring_parameters.py:84: numpydoc is required
SKIPPED [1] vispy\util\tests\test_import.py:111: Requires PyOpenGL
SKIPPED [1] vispy\visuals\graphs\tests\test_networkx_layout.py:20: 'networkx' required
SKIPPED [1] vispy\visuals\tests\test_isosurface.py:9: Requires PyOpenGL
SKIPPED [1] vispy\visuals\tests\test_mesh.py:16: Requires PyOpenGL
SKIPPED [1] vispy\visuals\tests\test_mesh.py:189: Requires PyOpenGL
SKIPPED [1] vispy\visuals\tests\test_volume.py:14: Requires PyOpenGL
SKIPPED [1] vispy\visuals\tests\test_volume.py:51: Requires PyOpenGL
SKIPPED [1] vispy\visuals\tests\test_volume.py:238: Requires PyOpenGL
SKIPPED [1] vispy\visuals\tests\test_volume.py:263: Requires PyOpenGL
XFAIL vispy/util/fonts/tests/test_font.py::test_font_glyph[Bahnschrift] - reason:
XFAIL vispy/util/fonts/tests/test_font.py::test_font_glyph[Bahnschrift Condensed] - reason:
XFAIL vispy/util/fonts/tests/test_font.py::test_font_glyph[Bahnschrift Light] - reason:
XFAIL vispy/util/fonts/tests/test_font.py::test_font_glyph[Bahnschrift Light Condensed] - reason:
XFAIL vispy/util/fonts/tests/test_font.py::test_font_glyph[Bahnschrift Light SemiCondensed] - reason:
XFAIL vispy/util/fonts/tests/test_font.py::test_font_glyph[Bahnschrift SemiBold] - reason:
XFAIL vispy/util/fonts/tests/test_font.py::test_font_glyph[Bahnschrift SemiBold Condensed] - reason:
XFAIL vispy/util/fonts/tests/test_font.py::test_font_glyph[Bahnschrift SemiBold SemiConden] - reason:
XFAIL vispy/util/fonts/tests/test_font.py::test_font_glyph[Bahnschrift SemiCondensed] - reason:
XFAIL vispy/util/fonts/tests/test_font.py::test_font_glyph[Bahnschrift SemiLight] - reason:
XFAIL vispy/util/fonts/tests/test_font.py::test_font_glyph[Bahnschrift SemiLight Condensed] - reason:
XFAIL vispy/util/fonts/tests/test_font.py::test_font_glyph[Bahnschrift SemiLight SemiConde] - reason:
FAILED vispy/util/fonts/tests/test_font.py::test_font_glyph[Microsoft YaHei] - AssertionError
FAILED vispy/util/fonts/tests/test_font.py::test_font_glyph[Microsoft YaHei Light] - AssertionError
FAILED vispy/util/fonts/tests/test_font.py::test_font_glyph[NSimSun] - AssertionError
FAILED vispy/util/fonts/tests/test_font.py::test_font_glyph[SimSun] - AssertionError
======================== 4 failed, 327 passed, 59 skipped, 397 deselected, 12 xfailed, 10 warnings in 9.09s ========================= 
Failed: unit failure (1)
Skipping example test: Cannot test examples unless in vispy git directory
Skipping line endings check on Windows
Passed

Skipping flake8 test, flake8 not installed
Passed

Testing failed (['pyqt5', 'nobackend'] failed, ['pyqt4', 'pyqt6', 'pyside', 'pyside2', 'pyside6', 'pyglet', 'glfw', 'sdl2', 'wx', 'egl', 'osmesa', 'jupyter_rfb', '_test', 'examples'] skipped) in 188.622 seconds
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\User\Documents\GitHub\Neogenesis\venv\lib\site-packages\vispy\util\wrappers.py", line 153, in test
    return _test(*args, **kwargs)
  File "C:\Users\User\Documents\GitHub\Neogenesis\venv\lib\site-packages\vispy\testing\_runners.py", line 446, in test
    raise RuntimeError('FAILURE')
RuntimeError: FAILURE
```

I wonder if I have to pass all of them beforing using the library or I can still use it.
Thanks!

**Comment by djhoese** [comment]
No need to have all the tests pass for the library to be usable. As some of the XFAIL messages say you could install `pyopengl` which is needed for some tests and some features in vispy. For the remaining failures, they seem related to fonts. If I had to guess some of the fonts are rendering properly on your system or they are not being found or something similar. So I wouldn't be too concerned unless you want to use those exact fonts inside a TextVisual.

**Comment by ManHinnn0509** [comment]
Thank you for replying, then I think I can close the issuse :D
