### ISSUE TITLE
Headless rendering without sudo

### ISSUE THREAD

**Issue by SimiPixel** [vispy/vispy#2510]
Dear Vispy authors,

is there a known configuration such that one can make `vispy` work on a headless machine on which i have no sudo access (a cluster node). The machines all run a (customized) version of Ubuntu(?).
I tried simply `conda install -c conda-forge mesalib`, and whilst this seems to work going only from the output of `print(vispy.sys_info())`
```
Platform: Linux-4.18.0-477.13.1.el8_8.x86_64-x86_64-with-glibc2.28
Python:   3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]
NumPy:    1.24.2
Backend:  osmesa
pyqt4:    None
pyqt5:    None
pyqt6:    None
pyside:   None
pyside2:  None
pyside6:  None
pyglet:   None
glfw:     None
sdl2:     None
wx:       None
egl:      None
osmesa:   OSMesa
tkinter:  None
jupyter_rfb: None
_test:    None

GL version:  ''
MAX_TEXTURE_SIZE: ()
Extensions: ''
```

 once i actually render, it throws the error

```
>>> scene.render()
WARNING: OpenGL version could not be determined, which might be a sign that OpenGL is not loaded correctly.
WARNING: Error drawing visual <vispy.visuals.mesh.MeshVisual object at 0x7f48cc36c460>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding/lib/python3.10/site-packages/x_xy/render.py", line 72, in render
    return self._render()
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding/lib/python3.10/site-packages/x_xy/render.py", line 284, in _render
    return self.canvas.render(alpha=True)
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding/lib/python3.10/site-packages/vispy/scene/canvas.py", line 264, in render
    self._draw_scene(bgcolor=bgcolor)
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding/lib/python3.10/site-packages/vispy/scene/canvas.py", line 277, in _draw_scene
    self.draw_visual(self.scene)
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding/lib/python3.10/site-packages/vispy/scene/canvas.py", line 315, in draw_visual
    node.draw()
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding/lib/python3.10/site-packages/vispy/scene/visuals.py", line 103, in draw
    self._visual_superclass.draw(self)
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding/lib/python3.10/site-packages/vispy/visuals/visual.py", line 605, in draw
    v.draw()
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding/lib/python3.10/site-packages/vispy/visuals/visual.py", line 451, in draw
    self._program.draw(self._vshare.draw_mode,
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding/lib/python3.10/site-packages/vispy/visuals/shaders/program.py", line 102, in draw
    Program.draw(self, *args, **kwargs)
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding/lib/python3.10/site-packages/vispy/gloo/program.py", line 543, in draw
    canvas.context.flush_commands()
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding/lib/python3.10/site-packages/vispy/gloo/context.py", line 172, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding/lib/python3.10/site-packages/vispy/gloo/glir.py", line 584, in flush
    self._shared.flush(parser)
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding/lib/python3.10/site-packages/vispy/gloo/glir.py", line 506, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding/lib/python3.10/site-packages/vispy/gloo/glir.py", line 824, in parse
    self._parse(command)
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding/lib/python3.10/site-packages/vispy/gloo/glir.py", line 798, in _parse
    ob.attach(*args)
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding/lib/python3.10/site-packages/vispy/gloo/glir.py", line 1795, in attach
    self.deactivate()
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding/lib/python3.10/site-packages/vispy/gloo/glir.py", line 1766, in deactivate
    gl.glBindFramebuffer(gl.GL_FRAMEBUFFER, stack[-1])
IndexError: list index out of range
```

Then, i stumbled upon the following instructions to setup the conda environment
```
$ conda activate mujoco_env
$ conda install -c conda-forge glew
$ conda install -c conda-forge mesalib
$ conda install -c anaconda mesa-libgl-cos6-x86_64
$ conda install -c menpo glfw3
``` 
from [pytorch](https://pytorch.org/rl/reference/generated/knowledge_base/MUJOCO_INSTALLATION.html).
However, they can not be resolved by conda due to conflicts.

Any pointers would be great! :)

**Comment by SimiPixel** [comment]
This was for a CPU-only node. As soon as i connect to a node with a GPU (A40 here), and i only install vispy (using `pip install vispy`), then it works just fine. 
For completeness, this is the output on such a node then:

```
Platform: Linux-4.18.0-477.13.1.el8_8.x86_64-x86_64-with-glibc2.28
Python:   3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]
NumPy:    1.25.1
Backend:  egl
pyqt4:    None
pyqt5:    None
pyqt6:    None
pyside:   None
pyside2:  None
pyside6:  None
pyglet:   None
glfw:     None
sdl2:     None
wx:       None
egl:      EGL 1.5 NVIDIA: OpenGL_ES OpenGL
osmesa:   None
tkinter:  None
jupyter_rfb: None
_test:    None

GL version:  '4.6.0 NVIDIA 535.54.03'
```

**Comment by Charles23R** [comment]
Hi @SimiPixel 

Have you found a solution to this problem? I have the exact same error :

`WARNING: OpenGL version could not be determined, which might be a sign that OpenGL is not loaded correctly.
Traceback (most recent call last):
 [ ... Omitted a part of the stack trace ... ]
  File "/usr/local/lib/python3.10/site-packages/vispy/gloo/program.py", line 543, in draw
    canvas.context.flush_commands()
  File "/usr/local/lib/python3.10/site-packages/vispy/gloo/context.py", line 172, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/usr/local/lib/python3.10/site-packages/vispy/gloo/glir.py", line 584, in flush
    self._shared.flush(parser)
  File "/usr/local/lib/python3.10/site-packages/vispy/gloo/glir.py", line 506, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/usr/local/lib/python3.10/site-packages/vispy/gloo/glir.py", line 824, in parse
    self._parse(command)
  File "/usr/local/lib/python3.10/site-packages/vispy/gloo/glir.py", line 798, in _parse
    ob.attach(*args)
  File "/usr/local/lib/python3.10/site-packages/vispy/gloo/glir.py", line 1798, in attach
    self.deactivate()
  File "/usr/local/lib/python3.10/site-packages/vispy/gloo/glir.py", line 1769, in deactivate
    gl.glBindFramebuffer(gl.GL_FRAMEBUFFER, stack[-1])
IndexError: list index out of range`


Here is the output of `print(vispy.sys_info())`: 
`Platform: Linux-5.15.0-97-generic-x86_64-with-glibc2.36
Python:   3.10.13 (main, Nov  1 2023, 14:09:24) [GCC 12.2.0]
NumPy:    1.26.1
Backend:  osmesa
pyqt4:    None
pyqt5:    None
pyqt6:    None
pyside:   None
pyside2:  None
pyside6:  None
pyglet:   None
glfw:     None
sdl2:     None
wx:       None
egl:      None
osmesa:   OSMesa
tkinter:  None
jupyter_rfb: None
_test:    None

GL version:  ''
MAX_TEXTURE_SIZE: ()
Extensions: ''`
