### ISSUE TITLE
IndexError: list index out of range [Only when running with ROS2]

### ISSUE THREAD

**Issue by AjinJayan** [vispy/vispy#2627]
I am running 6dpose estimation inference script, it runs successfully without any errors when executed as a standalone Python script. By when running with ros2, ie., calling script inside ros2 node, the following error occurs. This error is happening at the pose refinement stage where it renders scene.

The error occurs at the line "used_program.draw("triangles", model.index_buffer)" inside [renderer.py.](https://github.com/shanice-l/gdrnpp_bop2022/blob/main/lib/render_vispy/renderer.py)
I also tried changing app backends and gl backends, but same error

```

WARNING: OpenGL version could not be determined, which might be a sign that OpenGL is not loaded correctly.
2024-09-09 14:01:55,310 - WARNING - OpenGL version could not be determined, which might be a sign that OpenGL is not loaded correctly.
Traceback (most recent call last):
File "/home/rack/Workspace/projects/xrm/install/xrm_perception_iris/lib/xrm_perception_iris/perception.server.v2.py", line 283, in
main()
File "/home/rack/Workspace/projects/xrm/install/xrm_perception_iris/lib/xrm_perception_iris/perception.server.v2.py", line 273, in main
executor.spin()
File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 294, in spin
self.spin_once()
File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 794, in spin_once
self._spin_once_impl(timeout_sec)
File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 791, in _spin_once_impl
future.result()
File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/task.py", line 94, in result
raise self.exception()
File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/task.py", line 239, in call
self._handler.send(None)
File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 437, in handler
await call_coroutine(entity, arg)
File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 391, in _execute_service
response = await await_or_execute(srv.callback, request, srv.srv_type.Response())
File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 107, in await_or_execute
return callback(*args)
File "/home/rack/Workspace/projects/xrm/install/xrm_perception_iris/lib/xrm_perception_iris/perception.server.v2.py", line 239, in srv_task_callback
self.perception.inference_call(request)
File "/home/rack/Workspace/projects/xrm/install/xrm_perception_iris/local/lib/python3.10/dist-packages/xrm_perception_iris/pipeline/pipeline_v2/init.py", line 85, in inference_call
self.pipeline.inference_call()
File "/home/rack/Workspace/projects/xrm/install/xrm_perception_iris/local/lib/python3.10/dist-packages/xrm_perception_iris/pipeline/pipeline_v2/pipeline.py", line 139, in inference_call
self.gdrnpp1.inference(self.data.color.copy(), self.data.depth.copy(), target_obj )
File "/home/rack/Workspace/projects/xrm/install/xrm_perception_modules/local/lib/python3.10/dist-packages/xrm_perception_modules/models/gdrnpp/get6dpose.py", line 64, in inference
poses = self.gdrn_predictor.postprocessing(data_dict, out_dict)
File "/home/rack/Workspace/projects/xrm/install/xrm_perception_modules/local/lib/python3.10/dist-packages/xrm_perception_modules/models/gdrnpp/predictor_gdrn.py", line 216, in postprocessing
self.process_depth_refine(data_dict, out_dict)
File "/home/rack/Workspace/projects/xrm/install/xrm_perception_modules/local/lib/python3.10/dist-packages/xrm_perception_modules/models/gdrnpp/predictor_gdrn.py", line 281, in process_depth_refine
self.ren.draw_model(
_**File "/home/rack/Workspace/projects/3rdparty/gdrnpp_ws/gdrnpp/lib/render_vispy/renderer.py", line 407, in draw_model
used_program.draw("triangles", model.index_buffer)
File "/home/rack/.pyenv/versions/gdrnpp/lib/python3.10/site-packages/vispy/gloo/program.py", line 543, in draw
canvas.context.flush_commands()
File "/home/rack/.pyenv/versions/gdrnpp/lib/python3.10/site-packages/vispy/gloo/context.py", line 172, in flush_commands
self.glir.flush(self.shared.parser)
File "/home/rack/.pyenv/versions/gdrnpp/lib/python3.10/site-packages/vispy/gloo/glir.py", line 584, in flush
self._shared.flush(parser)
File "/home/rack/.pyenv/versions/gdrnpp/lib/python3.10/site-packages/vispy/gloo/glir.py", line 506, in flush
parser.parse(self._filter(self.clear(), parser))
File "/home/rack/.pyenv/versions/gdrnpp/lib/python3.10/site-packages/vispy/gloo/glir.py", line 824, in parse
self._parse(command)
File "/home/rack/.pyenv/versions/gdrnpp/lib/python3.10/site-packages/vispy/gloo/glir.py", line 798, in _parse
ob.attach(*args)
File "/home/rack/.pyenv/versions/gdrnpp/lib/python3.10/site-packages/vispy/gloo/glir.py", line 1803, in attach
self.deactivate()
File "/home/rack/.pyenv/versions/gdrnpp/lib/python3.10/site-packages/vispy/gloo/glir.py", line 1774, in deactivate
gl.glBindFramebuffer(gl.GL_FRAMEBUFFER, stack[-1])
IndexError: list index out of range**_
The following exception was never retrieved: cannot use Destroyable because destruction was requested
[ros2run]: Process exited with failure 1

```

**Comment by djhoese** [comment]
> I am running 6dpose estimation inference script, it runs successfully without any errors when executed as a standalone Python script. By when running with ros2, ie., calling script inside ros2 node, the following error occurs. 

I don't know what "6dpose estimation inference" is. Does it matter for this issue? I don't know what "ros2" is. The warning at the top says that the OpenGL version couldn't be determined and then you're getting a low level OpenGL error. It is likely that your OpenGL/video driver isn't properly installed or configured on this machine.

**Comment by djhoese** [comment]
It also looks like you are mixing 3 or more different python environments. Is that intentional?

```
/home/rack/.pyenv/versions/gdrnpp/lib/python3.10/
/home/rack/Workspace/projects/3rdparty/
/home/rack/Workspace/projects/xrm/
/opt/ros/humble/local/lib/python3.10/
```


Or I guess the Workspace ones are just "editable" installs of those packages?

**Comment by AjinJayan** [comment]
yes, workspace are for the editable installs.

**Comment by AjinJayan** [comment]
Running as a standalone script using with python virtual environment no such low level warning is showing. I don't why OpenGL warning is showing when running with ROS2. Is it because of two python environments?

And also want how to configure OpenGL properly.

**Comment by djhoese** [comment]
What is ROS2? Please answer the question.

OpenGL shouldn't be affected by your python environments. It has something to do with how OpenGL is installed on this system (likely as part of your video drivers or other system-level libraries).

**Comment by AmanSriv97** [comment]
ROS 2 (Robot Operating System 2) is a flexible framework for building robotic applications. It provides a set of tools and libraries that handle common tasks like communication, hardware abstraction, and software management, allowing developers to focus on the unique aspects of their robotic projects.

**Comment by djhoese** [comment]
Thank you @AmanSriv97. So the next question would be, does it provide any video/graphics functionality? How does it compare to a more "standard" linux system?

@AjinJayan Do you have a display attached to the ROS2 system? If not, are you creating a fake/virtual display for vispy to write/draw to?

**Comment by AjinJayan** [comment]
ROS2 offers strong integration for video and graphics, primarily for robotics-focused tasks, using OpenCV, RViz2, Gazebo, and image transport libraries, but is more specialized than general Linux systems which have broader multimedia applications.

Yes, a display is attached to the system.

**Comment by AmanSriv97** [comment]
ROS2 typically runs on a standard Linux system, such as Ubuntu. It does not have its own graphics or video subsystem; instead, it uses whatever graphical system is available on the host machine (Linux).

It relies on the host's system to provide OpenGL or similar libraries for graphics acceleration.

**Comment by djhoese** [comment]
> ROS2 typically runs on a standard Linux system

Oh, so this operating system is not an operating system and likely has very little to do with the issues encountered here. Right?

@AjinJayan Could you please provide the output of running:

```bash
python -c "import vispy; print(vispy.sys_info())"
```

**Comment by AjinJayan** [comment]
(gdrnpp) rack@rack-tcs:~$ python -c "import vispy; print(vispy.sys_info())"
Platform: Linux-6.8.0-45-generic-x86_64-with-glibc2.35
Python:   3.10.12 (main, Jul 16 2024, 18:01:04) [GCC 11.4.0]
NumPy:    1.23.5
Backend:  PyQt5
pyqt4:    None
pyqt5:    ('PyQt5', '5.15.0', '5.15.0')
pyqt6:    None
pyside:   None
pyside2:  None
pyside6:  None
pyglet:   pyglet 2.0.17
glfw:     glfw 2.7.0
sdl2:     None
wx:       None
egl:      EGL 1.5 NVIDIA: OpenGL_ES OpenGL
osmesa:   OSMesa
tkinter:  None
jupyter_rfb: None
_test:    None

GL version:  '4.6.0 NVIDIA 535.183.01'
MAX_TEXTURE_SIZE: 32768
Extensions: 'GL_AMD_multi_draw_indirect GL_AMD_seamless_cubemap_per_texture GL_AMD_vertex_shader_viewport_index GL_AMD_vertex_shader_layer GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_cl_event GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_fragment_shader_interlock GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_post_depth_coverage GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_locations GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shader_viewport_layer_array GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_sparse_buffer GL_ARB_sparse_texture GL_ARB_sparse_texture2 GL_ARB_sparse_texture_clamp GL_ARB_spirv_extensions GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_filter_anisotropic GL_ARB_texture_filter_minmax GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ARB_window_pos GL_ATI_draw_buffers GL_ATI_texture_float GL_ATI_texture_mirror_once GL_S3_s3tc GL_EXT_texture_env_add GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_Cg_shader GL_EXT_depth_bounds_test GL_EXT_direct_state_access GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXTX_framebuffer_mixed_formats GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_multiview_tessellation_geometry_shader GL_EXT_multiview_texture_multisample GL_EXT_multiview_timer_query GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_polygon_offset_clamp GL_EXT_post_depth_coverage GL_EXT_provoking_vertex GL_EXT_raster_multisample GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_shader_objects GL_EXT_separate_specular_color GL_EXT_shader_image_load_formatted GL_EXT_shader_image_load_store GL_EXT_shader_integer_mix GL_EXT_shadow_funcs GL_EXT_sparse_texture2 GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture3D GL_EXT_texture_array GL_EXT_texture_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_latc GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_filter_minmax GL_EXT_texture_integer GL_EXT_texture_lod GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_object GL_EXT_texture_shadow_lod GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_decode GL_EXT_texture_storage GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback2 GL_EXT_vertex_array GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_EXT_window_rectangles GL_EXT_x11_sync_object GL_EXT_import_sync_object GL_NV_robustness_video_memory_purge GL_NVX_shared_sync_object GL_IBM_rasterpos_clip GL_IBM_texture_mirrored_repeat GL_KHR_context_flush_control GL_KHR_debug GL_EXT_memory_object GL_EXT_memory_object_fd GL_NV_memory_object_sparse GL_KHR_parallel_shader_compile GL_KHR_no_error GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_EXT_semaphore GL_EXT_semaphore_fd GL_NV_timeline_semaphore GL_KHR_shader_subgroup GL_KTX_buffer_region GL_NV_alpha_to_coverage_dither_control GL_NV_bindless_multi_draw_indirect GL_NV_bindless_multi_draw_indirect_count GL_NV_bindless_texture GL_NV_blend_equation_advanced GL_NV_blend_equation_advanced_coherent GL_NVX_blend_equation_advanced_multi_draw_buffers GL_NV_blend_minmax_factor GL_NV_blend_square GL_NV_clip_space_w_scaling GL_NV_command_list GL_NV_compute_program5 GL_NV_conditional_render GL_NV_conservative_raster GL_NV_conservative_raster_dilate GL_NV_conservative_raster_pre_snap_triangles GL_NV_copy_depth_to_color GL_NV_copy_image GL_NV_deep_texture3D GL_NV_depth_buffer_float GL_NV_depth_clamp GL_NV_draw_texture GL_NV_draw_vulkan_image GL_NV_ES1_1_compatibility GL_NV_ES3_1_compatibility GL_NV_explicit_multisample GL_NV_feature_query GL_NV_fence GL_NV_fill_rectangle GL_NV_float_buffer GL_NV_fog_distance GL_NV_fragment_coverage_to_color GL_NV_fragment_program GL_NV_fragment_program_option GL_NV_fragment_program2 GL_NV_fragment_shader_interlock GL_NV_framebuffer_mixed_samples GL_NV_framebuffer_multisample_coverage GL_NV_geometry_shader4 GL_NV_geometry_shader_passthrough GL_NV_gpu_program4 GL_NV_internalformat_sample_query GL_NV_gpu_program4_1 GL_NV_gpu_program5 GL_NV_gpu_program5_mem_extended GL_NV_gpu_program_fp64 GL_NV_gpu_shader5 GL_NV_half_float GL_NV_light_max_exponent GL_NV_memory_attachment GL_NV_multisample_coverage GL_NV_multisample_filter_hint GL_NV_occlusion_query GL_NV_packed_depth_stencil GL_NV_parameter_buffer_object GL_NV_parameter_buffer_object2 GL_NV_path_rendering GL_NV_path_rendering_shared_edge GL_NV_pixel_data_range GL_NV_point_sprite GL_NV_primitive_restart GL_NV_query_resource GL_NV_query_resource_tag GL_NV_register_combiners GL_NV_register_combiners2 GL_NV_sample_locations GL_NV_sample_mask_override_coverage GL_NV_shader_atomic_counters GL_NV_shader_atomic_float GL_NV_shader_atomic_float64 GL_NV_shader_atomic_fp16_vector GL_NV_shader_atomic_int64 GL_NV_shader_buffer_load GL_NV_shader_storage_buffer_object GL_NV_shader_subgroup_partitioned GL_NV_stereo_view_rendering GL_NV_texgen_reflection GL_NV_texture_barrier GL_NV_texture_compression_vtc GL_NV_texture_env_combine4 GL_NV_texture_multisample GL_NV_texture_rectangle GL_NV_texture_rectangle_compressed GL_NV_texture_shader GL_NV_texture_shader2 GL_NV_texture_shader3 GL_NV_transform_feedback GL_NV_transform_feedback2 GL_NV_uniform_buffer_unified_memory GL_NV_uniform_buffer_std430_layout GL_NV_vdpau_interop GL_NV_vdpau_interop2 GL_NV_vertex_array_range GL_NV_vertex_array_range2 GL_NV_vertex_attrib_integer_64bit GL_NV_vertex_buffer_unified_memory GL_NV_vertex_program GL_NV_vertex_program1_1 GL_NV_vertex_program2 GL_NV_vertex_program2_option GL_NV_vertex_program3 GL_NV_viewport_array2 GL_NV_viewport_swizzle GL_NVX_sysmem_buffer GL_NVX_conditional_render GL_NV_gpu_multicast GL_NVX_progress_fence GL_NVX_gpu_memory_info GL_NVX_nvenc_interop GL_NV_shader_thread_group GL_NV_shader_thread_shuffle GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OVR_multiview GL_OVR_multiview2 GL_SGIS_generate_mipmap GL_SGIS_texture_lod GL_SGIX_depth_texture GL_SGIX_shadow GL_SUN_slice_accum '

**Comment by djhoese** [comment]
Side note: I've updated your comment to format the output as a literal.

It looks like that ran fine so it must not be OpenGL. Can you narrow down your code to a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by aganders3** [comment]
>  it runs successfully without any errors when executed as a standalone Python script. By when running with ros2, ie., calling script inside ros2 node, the following error occurs

@AjinJayan just to make sure: you mentioned that it runs fine as a standalone script. Is the output you shared of `print(vispy.sys_info())` from execution as a standalone script or from inside a ros2 node? To me it looks like you ran that from the CLI but maybe that's a ros2 shell or something.

**Comment by AjinJayan** [comment]
when using "egl" as backend, output of print(vispy.sys_info()) is as follows
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Platform: Linux-6.8.0-47-generic-x86_64-with-glibc2.35
Python:   3.10.12 (main, Jul 16 2024, 18:01:04) [GCC 11.4.0]
NumPy:    1.23.5
Backend:  egl
pyqt4:    None
pyqt5:    None
pyqt6:    None
pyside:   None
pyside2:  None
pyside6:  ('PySide6', '6.8.0.1', '6.8.0')
pyglet:   pyglet 2.0.17
glfw:     glfw 2.7.0
sdl2:     None
wx:       None
egl:      EGL 1.5 NVIDIA: OpenGL_ES OpenGL
osmesa:   OSMesa
tkinter:  None
jupyter_rfb: None
_test:    None

App info-gathering error:
Traceback (most recent call last):
  File "/home/rack/.pyenv/versions/3.10.12/envs/gdrnpp/lib/python3.10/site-packages/vispy/util/config.py", line 429, in sys_info
    canvas = Canvas('Test', (10, 10), show=False, app=app)
  File "/home/rack/.pyenv/versions/3.10.12/envs/gdrnpp/lib/python3.10/site-packages/vispy/app/canvas.py", line 211, in __init__
    self.create_native()
  File "/home/rack/.pyenv/versions/3.10.12/envs/gdrnpp/lib/python3.10/site-packages/vispy/app/canvas.py", line 228, in create_native
    self._app.backend_module.CanvasBackend(self, **self._backend_kwargs)
  File "/home/rack/.pyenv/versions/3.10.12/envs/gdrnpp/lib/python3.10/site-packages/vispy/app/backends/_egl.py", line 173, in __init__
    self._vispy_canvas.set_current()
  File "/home/rack/.pyenv/versions/3.10.12/envs/gdrnpp/lib/python3.10/site-packages/vispy/app/canvas.py", line 412, in set_current
    self._backend._vispy_set_current()
  File "/home/rack/.pyenv/versions/3.10.12/envs/gdrnpp/lib/python3.10/site-packages/vispy/app/backends/_egl.py", line 204, in _vispy_set_current
    egl.eglMakeCurrent(_EGL_DISPLAY, self._surface, self._surface,
  File "/home/rack/.pyenv/versions/3.10.12/envs/gdrnpp/lib/python3.10/site-packages/vispy/ext/egl.py", line 355, in eglMakeCurrent
    raise RuntimeError('Could not make the context current.')
RuntimeError: Could not make the context current.

**Comment by djhoese** [comment]
These are on the same system? I'm a little confused how two different Qt libraries were found (pyqt5 in one, pyside6 in the other)?
