### ISSUE TITLE
Shader compilation error

### ISSUE THREAD

**Issue by jvtrudel** [vispy/vispy#732]
This problem is quite similar to the closed issue #578...

```
WARNING: Traceback (most recent call last):
  File "example7.py", line 5, in <module>
    canvas = vp.plot([1, 6, 2, 4, 3, 8, 5, 7, 6, 3])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy/plot/plot.py", line 20, in plot
    canvas.show()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy/app/canvas.py", line 320, in show
    return self._backend._vispy_set_visible(visible)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy/app/backends/_qt.py", line 288, in _vispy_set_visible
    self.showNormal()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy/app/backends/_qt.py", line 334, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy/util/event.py", line 418, in __call__
    self._invoke_callback(cb, event)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy/util/event.py", line 446, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy/util/event.py", line 435, in _invoke_callback
    cb(event)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy/scene/canvas.py", line 148, in on_draw
    self.draw_visual(self.scene)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy/scene/canvas.py", line 181, in draw_visual
    visual.draw(scene_event)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy/scene/subscene.py", line 41, in draw
    self.process_system(event, 'draw')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy/scene/subscene.py", line 49, in process_system
    self._systems[system_name].process(event, self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy/scene/systems.py", line 22, in process
    self._process_entity(event, subscene, force_recurse=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy/scene/systems.py", line 47, in _process_entity
    self._process_entity(event, sub_entity)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy/scene/systems.py", line 33, in _process_entity
    _handle_exception(False, 'reminders', self, entity=entity)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy/scene/systems.py", line 29, in _process_entity
    entity.draw(event)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy/scene/widgets/widget.py", line 169, in draw
    self._visual.draw(event)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy/scene/visuals/line/line.py", line 355, in draw
    self._gl_draw(event)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy/scene/visuals/line/line.py", line 388, in _gl_draw
    self._gl_program.draw('line_strip')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy/gloo/program.py", line 491, in draw
    self.activate()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy/gloo/globject.py", line 56, in activate
    self._activate()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy/gloo/program.py", line 202, in _activate
    self._build()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy/scene/shaders/program.py", line 66, in _build
    super(ModularProgram, self)._build()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy/gloo/program.py", line 246, in _build
    shader.activate()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy/gloo/globject.py", line 56, in activate
    self._activate()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy/gloo/shader.py", line 93, in _activate
    self._compile_shader()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy/gloo/shader.py", line 125, in _compile_shader
    (self, errormsg))
RuntimeError: Shader compilation error in Vertex Shader 2 (<string>):
    on line 42: 'input' : Reserved word.
      vec4 vec2to4(vec2 input) {
    on line 42: 'input' : syntax error: syntax error
      vec4 vec2to4(vec2 input) {
WARNING: Error invoking callback <bound method SceneCanvas.on_draw of <Vispy canvas (PyQt4 (qt) backend) at 0x10e19ca10>> for event: <DrawEvent blocked=False handled=False native=None region=None source=<Vispy canvas (PyQt4 (qt) backend) at 0x10e19ca10> sources=[<Vispy canvas (PyQt4 (qt) backend) at 0x10e19ca10>] type=draw>
Traceback (most recent call last):
  File "example7.py", line 10, in <module>
    image = canvas.render(size=(canvas.size[0]*scale, canvas.size[1]*scale))
AttributeError: 'SceneCanvas' object has no attribute 'render'  
```

**Comment by Eric89GXL** [comment]
Are you running latest the master / development version?

**Comment by Eric89GXL** [comment]
...if so, please post a minimal example and I'll see if I can replicate.

**Comment by jvtrudel** [comment]
The problem seems to be in the line.py file. "input" has not been replaced by "inp" in my not up-to-date version just installed with Macports :-( 

Sorry guys. I close the issue.

**Comment by Eric89GXL** [comment]
Ahh, good to hear. Feel free to re-open if you have problems with the latest version.
