### ISSUE TITLE
All collection examples are broken on master

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#815]
```
Traceback (most recent call last):
  File "examples/collections/triangle_collection.py", line 52, in <module>
    paths["linewidth"] = 1.0
  File "/data/git/vispy/vispy/visuals/collections/collection.py", line 180, in __setitem__
    for name, (storage, _, _) in program._code_variables.items():
ValueError: too many values to unpack (expected 3)
```

**Comment by rossant** [comment]
Closed by e7a2f852cf785bf42eab0b648437918b71c4f0a3.
