### ISSUE TITLE
Problem with collection example

### ISSUE THREAD

**Issue by sylm21** [vispy/vispy#849]
Hi,

When i launch an example about collection i  always the same error :

WARNING: Traceback (most recent call last):
  File "C:\Users\moynesy\Desktop\projet_python\vispy-master\examples\collections\choropleth.py", line 86, in <module>
    app.run()
  File "C:\Python27\lib\site-packages\vispy-0.4.0_dev-py2.7.egg\vispy\app\_default_app.py", line 61, in run
    return default_app.run()
  File "C:\Python27\lib\site-packages\vispy-0.4.0_dev-py2.7.egg\vispy\app\application.py", line 123, in run
    return self._backend._vispy_run()
  File "C:\Python27\lib\site-packages\vispy-0.4.0_dev-py2.7.egg\vispy\app\backends\_qt.py", line 217, in _vispy_run
    return app.exec_()
  File "C:\Python27\lib\site-packages\vispy-0.4.0_dev-py2.7.egg\vispy\app\backends\_qt.py", line 617, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "C:\Python27\lib\site-packages\vispy-0.4.0_dev-py2.7.egg\vispy\util\event.py", line 436, in __call__
    self._invoke_callback(cb, event)
  File "C:\Python27\lib\site-packages\vispy-0.4.0_dev-py2.7.egg\vispy\util\event.py", line 452, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "C:\Python27\lib\site-packages\vispy-0.4.0_dev-py2.7.egg\vispy\util\event.py", line 448, in _invoke_callback
    cb(event)
  File "C:\Users\moynesy\Desktop\projet_python\vispy-master\examples\collections\choropleth.py", line 71, in on_draw
    polys.draw()
  File "C:\Python27\lib\site-packages\vispy-0.4.0_dev-py2.7.egg\vispy\visuals\collections\collection.py", line 197, in draw
    program.draw(mode, self._indices_buffer)
  File "C:\Python27\lib\site-packages\vispy-0.4.0_dev-py2.7.egg\vispy\gloo\program.py", line 463, in draw
    canvas.context.flush_commands()
  File "C:\Python27\lib\site-packages\vispy-0.4.0_dev-py2.7.egg\vispy\gloo\context.py", line 144, in flush_commands
    self.glir.flush(self.shared.parser)
  File "C:\Python27\lib\site-packages\vispy-0.4.0_dev-py2.7.egg\vispy\gloo\glir.py", line 157, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "C:\Python27\lib\site-packages\vispy-0.4.0_dev-py2.7.egg\vispy\gloo\glir.py", line 368, in parse
    ob.set_shaders(*args)
  File "C:\Python27\lib\site-packages\vispy-0.4.0_dev-py2.7.egg\vispy\gloo\glir.py", line 507, in set_shaders
    (type_ + ' shader', errormsg))
RuntimeError: Shader compilation error in vertex shader:
    on line 14: 'collections' : syntax error syntax error
ERROR: Invoking <function on_draw at 0x044BA6F0> for DrawEvent
ERROR: Invoking <function on_draw at 0x044BA6F0> repeat 2

have you an idea ?

I'm on windows 7, python 2.7.9, pyqt4, numpy 1.9.2

Thanks,

**Comment by rossant** [comment]
what is your GPU and GPU driver?

**Comment by sylm21** [comment]
Intel HD Graphics 4000

**Comment by rossant** [comment]
you have the latest master version of vispy?

there is a command to get OpenGL diagnostics, @Eric89GXL or @almarklein can you remind me what it is?

Also, do you have the very latest version of your GPU driver?

**Comment by sylm21** [comment]
latest version of vispy and update driver after your comment

**Comment by Eric89GXL** [comment]
@sylm21 can you try on latest master? I feel like we fixed an issue with compiles a couple of weeks ago that might have helped. Also you could try the debugging steps listed in #867

**Comment by Eric89GXL** [comment]
Closing for now (works on latest master on Intel hardware for me), feel free to reopen if this one isn't fixed for you @sylm21

**Comment by sylm21** [comment]
It's OK for me now

Thanks
