### ISSUE TITLE
`vispy.plot` doesn't work in WebGL

### ISSUE THREAD

**Issue by davidtrem** [vispy/vispy#875]
In an IPython 3.1 notebook cell:
```javascript
import vispy.app
vispy.app.use_app('ipynb_webgl')

from vispy import plot as vp

fig = vp.Fig(show=False)
fig1 = fig[0, 0]
fig1.plot(range(10000),marker_size=0)
fig.show(run=True)
```
leads to this traceback:
```
WARNING: Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/dtremoui/py34/lib/python/site-packages/IPython/kernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/Users/dtremoui/py34/lib/python/site-packages/IPython/config/application.py", line 574, in launch_instance
    app.start()
  File "/Users/dtremoui/py34/lib/python/site-packages/IPython/kernel/zmq/kernelapp.py", line 373, in start
    ioloop.IOLoop.instance().start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zmq/eventloop/ioloop.py", line 151, in start
    super(ZMQIOLoop, self).start()
  File "/Users/dtremoui/py34/lib/python/site-packages/tornado-4.2.dev1-py3.4-macosx-10.10-x86_64.egg/tornado/ioloop.py", line 808, in start
    self._run_callback(callback)
  File "/Users/dtremoui/py34/lib/python/site-packages/tornado-4.2.dev1-py3.4-macosx-10.10-x86_64.egg/tornado/ioloop.py", line 592, in _run_callback
    ret = callback()
  File "/Users/dtremoui/py34/lib/python/site-packages/tornado-4.2.dev1-py3.4-macosx-10.10-x86_64.egg/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/dtremoui/py34/lib/python/site-packages/vispy-0.4.0.dev0-py3.4.egg/vispy/app/backends/_ipynb_webgl.py", line 207, in _draw_event
    self._vispy_canvas.events.draw()
  File "/Users/dtremoui/py34/lib/python/site-packages/vispy-0.4.0.dev0-py3.4.egg/vispy/util/event.py", line 436, in __call__
    self._invoke_callback(cb, event)
  File "/Users/dtremoui/py34/lib/python/site-packages/vispy-0.4.0.dev0-py3.4.egg/vispy/util/event.py", line 452, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/Users/dtremoui/py34/lib/python/site-packages/vispy-0.4.0.dev0-py3.4.egg/vispy/util/event.py", line 448, in _invoke_callback
    cb(event)
  File "/Users/dtremoui/py34/lib/python/site-packages/vispy-0.4.0.dev0-py3.4.egg/vispy/scene/canvas.py", line 151, in on_draw
    self._draw_scene()
  File "/Users/dtremoui/py34/lib/python/site-packages/vispy-0.4.0.dev0-py3.4.egg/vispy/scene/canvas.py", line 194, in _draw_scene
    self.draw_visual(self.scene, viewport=viewport)
  File "/Users/dtremoui/py34/lib/python/site-packages/vispy-0.4.0.dev0-py3.4.egg/vispy/scene/canvas.py", line 227, in draw_visual
    vp = (0, 0) + self.physical_size if viewport is None else viewport
TypeError: can only concatenate tuple (not "list") to tuple
WARNING:vispy:Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/dtremoui/py34/lib/python/site-packages/IPython/kernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/Users/dtremoui/py34/lib/python/site-packages/IPython/config/application.py", line 574, in launch_instance
    app.start()
  File "/Users/dtremoui/py34/lib/python/site-packages/IPython/kernel/zmq/kernelapp.py", line 373, in start
    ioloop.IOLoop.instance().start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zmq/eventloop/ioloop.py", line 151, in start
    super(ZMQIOLoop, self).start()
  File "/Users/dtremoui/py34/lib/python/site-packages/tornado-4.2.dev1-py3.4-macosx-10.10-x86_64.egg/tornado/ioloop.py", line 808, in start
    self._run_callback(callback)
  File "/Users/dtremoui/py34/lib/python/site-packages/tornado-4.2.dev1-py3.4-macosx-10.10-x86_64.egg/tornado/ioloop.py", line 592, in _run_callback
    ret = callback()
  File "/Users/dtremoui/py34/lib/python/site-packages/tornado-4.2.dev1-py3.4-macosx-10.10-x86_64.egg/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/dtremoui/py34/lib/python/site-packages/vispy-0.4.0.dev0-py3.4.egg/vispy/app/backends/_ipynb_webgl.py", line 207, in _draw_event
    self._vispy_canvas.events.draw()
  File "/Users/dtremoui/py34/lib/python/site-packages/vispy-0.4.0.dev0-py3.4.egg/vispy/util/event.py", line 436, in __call__
    self._invoke_callback(cb, event)
  File "/Users/dtremoui/py34/lib/python/site-packages/vispy-0.4.0.dev0-py3.4.egg/vispy/util/event.py", line 452, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/Users/dtremoui/py34/lib/python/site-packages/vispy-0.4.0.dev0-py3.4.egg/vispy/util/event.py", line 448, in _invoke_callback
    cb(event)
  File "/Users/dtremoui/py34/lib/python/site-packages/vispy-0.4.0.dev0-py3.4.egg/vispy/scene/canvas.py", line 151, in on_draw
    self._draw_scene()
  File "/Users/dtremoui/py34/lib/python/site-packages/vispy-0.4.0.dev0-py3.4.egg/vispy/scene/canvas.py", line 194, in _draw_scene
    self.draw_visual(self.scene, viewport=viewport)
  File "/Users/dtremoui/py34/lib/python/site-packages/vispy-0.4.0.dev0-py3.4.egg/vispy/scene/canvas.py", line 227, in draw_visual
    vp = (0, 0) + self.physical_size if viewport is None else viewport
TypeError: can only concatenate tuple (not "list") to tuple
ERROR: Invoking <bound method Fig.on_draw of <Fig (ipynb_webgl) at 0x10d979b38>> for DrawEvent
ERROR:vispy:Invoking <bound method Fig.on_draw of <Fig (ipynb_webgl) at 0x10d979b38>> for DrawEvent
WARNING: Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/dtremoui/py34/lib/python/site-packages/IPython/kernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/Users/dtremoui/py34/lib/python/site-packages/IPython/config/application.py", line 574, in launch_instance
    app.start()
  File "/Users/dtremoui/py34/lib/python/site-packages/IPython/kernel/zmq/kernelapp.py", line 373, in start
    ioloop.IOLoop.instance().start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zmq/eventloop/ioloop.py", line 151, in start
    super(ZMQIOLoop, self).start()
  File "/Users/dtremoui/py34/lib/python/site-packages/tornado-4.2.dev1-py3.4-macosx-10.10-x86_64.egg/tornado/ioloop.py", line 808, in start
    self._run_callback(callback)
  File "/Users/dtremoui/py34/lib/python/site-packages/tornado-4.2.dev1-py3.4-macosx-10.10-x86_64.egg/tornado/ioloop.py", line 592, in _run_callback
    ret = callback()
  File "/Users/dtremoui/py34/lib/python/site-packages/tornado-4.2.dev1-py3.4-macosx-10.10-x86_64.egg/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/dtremoui/py34/lib/python/site-packages/vispy-0.4.0.dev0-py3.4.egg/vispy/app/backends/_ipynb_webgl.py", line 207, in _draw_event
    self._vispy_canvas.events.draw()
  File "/Users/dtremoui/py34/lib/python/site-packages/vispy-0.4.0.dev0-py3.4.egg/vispy/util/event.py", line 436, in __call__
    self._invoke_callback(cb, event)
  File "/Users/dtremoui/py34/lib/python/site-packages/vispy-0.4.0.dev0-py3.4.egg/vispy/util/event.py", line 452, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/Users/dtremoui/py34/lib/python/site-packages/vispy-0.4.0.dev0-py3.4.egg/vispy/util/event.py", line 448, in _invoke_callback
    cb(event)
  File "/Users/dtremoui/py34/lib/python/site-packages/vispy-0.4.0.dev0-py3.4.egg/vispy/gloo/context.py", line 144, in flush_commands
    self.shared.parser.parse([('CURRENT', 0)])
  File "/Users/dtremoui/py34/lib/python/site-packages/vispy-0.4.0.dev0-py3.4.egg/vispy/app/backends/_ipynb_webgl.py", line 108, in parse
    self._widget.send_glir_commands(commands)
AttributeError: 'NoneType' object has no attribute 'send_glir_commands'
WARNING:vispy:Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/dtremoui/py34/lib/python/site-packages/IPython/kernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/Users/dtremoui/py34/lib/python/site-packages/IPython/config/application.py", line 574, in launch_instance
    app.start()
  File "/Users/dtremoui/py34/lib/python/site-packages/IPython/kernel/zmq/kernelapp.py", line 373, in start
    ioloop.IOLoop.instance().start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zmq/eventloop/ioloop.py", line 151, in start
    super(ZMQIOLoop, self).start()
  File "/Users/dtremoui/py34/lib/python/site-packages/tornado-4.2.dev1-py3.4-macosx-10.10-x86_64.egg/tornado/ioloop.py", line 808, in start
    self._run_callback(callback)
  File "/Users/dtremoui/py34/lib/python/site-packages/tornado-4.2.dev1-py3.4-macosx-10.10-x86_64.egg/tornado/ioloop.py", line 592, in _run_callback
    ret = callback()
  File "/Users/dtremoui/py34/lib/python/site-packages/tornado-4.2.dev1-py3.4-macosx-10.10-x86_64.egg/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/dtremoui/py34/lib/python/site-packages/vispy-0.4.0.dev0-py3.4.egg/vispy/app/backends/_ipynb_webgl.py", line 207, in _draw_event
    self._vispy_canvas.events.draw()
  File "/Users/dtremoui/py34/lib/python/site-packages/vispy-0.4.0.dev0-py3.4.egg/vispy/util/event.py", line 436, in __call__
    self._invoke_callback(cb, event)
  File "/Users/dtremoui/py34/lib/python/site-packages/vispy-0.4.0.dev0-py3.4.egg/vispy/util/event.py", line 452, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/Users/dtremoui/py34/lib/python/site-packages/vispy-0.4.0.dev0-py3.4.egg/vispy/util/event.py", line 448, in _invoke_callback
    cb(event)
  File "/Users/dtremoui/py34/lib/python/site-packages/vispy-0.4.0.dev0-py3.4.egg/vispy/gloo/context.py", line 144, in flush_commands
    self.shared.parser.parse([('CURRENT', 0)])
  File "/Users/dtremoui/py34/lib/python/site-packages/vispy-0.4.0.dev0-py3.4.egg/vispy/app/backends/_ipynb_webgl.py", line 108, in parse
    self._widget.send_glir_commands(commands)
AttributeError: 'NoneType' object has no attribute 'send_glir_commands'
ERROR: Invoking <bound method GLContext.flush_commands of <GLContext at 0x10db71e80>> for DrawEvent
ERROR:vispy:Invoking <bound method GLContext.flush_commands of <GLContext at 0x10db71e80>> for DrawEvent
ERROR: Invoking <bound method Fig.on_draw of <Fig (ipynb_webgl) at 0x10d979b38>> repeat 2
ERROR:vispy:Invoking <bound method Fig.on_draw of <Fig (ipynb_webgl) at 0x10d979b38>> repeat 2
ERROR: Invoking <bound method GLContext.flush_commands of <GLContext at 0x10db71e80>> repeat 2
ERROR:vispy:Invoking <bound method GLContext.flush_commands of <GLContext at 0x10db71e80>> repeat 2
ERROR: Invoking <bound method Fig.on_draw of <Fig (ipynb_webgl) at 0x10d979b38>> repeat 3
ERROR:vispy:Invoking <bound method Fig.on_draw of <Fig (ipynb_webgl) at 0x10d979b38>> repeat 3
ERROR: Invoking <bound method GLContext.flush_commands of <GLContext at 0x10db71e80>> repeat 3
ERROR:vispy:Invoking <bound method GLContext.flush_commands of <GLContext at 0x10db71e80>> repeat 3
```

**Comment by hadim** [comment]
Same error, using conda:

```
$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.10.0
  conda-build version : 1.11.0
       python version : 3.4.3.final.0
     requests version : 2.6.0
     root environment : /home/hadim/local/conda  (writable)
  default environment : /home/hadim/local/conda/envs/st
     envs directories : /home/hadim/local/conda/envs
        package cache : /home/hadim/local/conda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

- vispy f57eb089689699a9e3c9912de1fab6f3a184fba8
- ipython 3.1.0

**Comment by Eric89GXL** [comment]
I think I have a workaround in mind...

**Comment by firestructure** [comment]
Ok, I am pretty new to this. I have had the same problem for days. But what is the workaround that @larsoner  had in mind? I can't find the solution?

**Comment by djhoese** [comment]
@firestructure This is an old issue and a lot of things have changed in jupyter notebooks. Please try installing vispy from the github master branch and let me know if you have any issues by filing a new github issue or bringing it up on https://gitter.im/vispy/vispy.

**Comment by yiakwy** [comment]
@davidtrem @hadim @larsoner this issue should not be closed cause we still have in python 3.6 jupyter notebook with latest vispy package installation. The OS is ubuntu 18.

**Comment by yiakwy** [comment]
@djhoese Installing from github repo is extremely slow. It takes a long time before downloading all npm dependencies.

**Comment by djhoese** [comment]
@yiakwy I know you've already filed another issue, but please read the discussion before commenting. In my last comment I pointed out that so much has changed with notebooks and notebook support that this issue's discussion is no longer relevant and that any new issues should be filed separately. As for the slow installation, if you have suggestions on how to improve that please let me know. I am doing everything as suggested by the ipywidgets (jupyter widgets) project so this may be something that needs to be filed with them assuming I'm not doing something wrong.
