### ISSUE TITLE
point_collection (no key in -> program.vert['transform'] )

### ISSUE THREAD

**Issue by gabyx** [vispy/vispy#878]
When I try to run the example point_collection 
https://github.com/vispy/vispy/blob/master/examples/collections/point_collection.py
with the ``mode='raw' or 'agg'``
the following error occures: 

```
KeyError                                  Traceback (most recent call last)
<ipython-input-11-7efb2e73af81> in <module>()
     15 panzoom = PanZoomTransform(canvas)
     16 
---> 17 points = PointCollection("raw", color="shared")
     18 points.append(np.random.normal(0.0, 0.5, (10000, 3)), itemsize=5000)
     19 points["color"] = (1, 0, 0, 1), (0, 0, 1, 1)

/opt/python3.4env/lib/python3.4/site-packages/vispy-0.4.0_dev-py3.4.egg/vispy/visuals/collections/point_collection.py in PointCollection(mode, *args, **kwargs)
     17 
     18     if mode == "raw":
---> 19         return RawPointCollection(*args, **kwargs)
     20     return AggPointCollection(*args, **kwargs)

/opt/python3.4env/lib/python3.4/site-packages/vispy-0.4.0_dev-py3.4.egg/vispy/visuals/collections/raw_point_collection.py in __init__(self, user_dtype, transform, vertex, fragment, **kwargs)
     71         # Set hooks if necessary
     72         program = self._programs[0]
---> 73         program.vert['transform'] = self.transform
     74 
     75     def append(self, P, itemsize=None, **kwargs):

/opt/python3.4env/lib/python3.4/site-packages/vispy-0.4.0_dev-py3.4.egg/vispy/visuals/shaders/function.py in __setitem__(self, key, val)
    222                 storage = self._expressions
    223             else:
--> 224                 raise KeyError('Invalid template variable %r' % key)
    225         else:
    226             raise TypeError('In `function[key]` key must be a string or '

KeyError: "Invalid template variable 'transform'"
```

**Comment by campagnola** [comment]
It works for me.. are you using the latest from github?

**Comment by gabyx** [comment]
I am using the version: (so the latest pull)

Merge: 402cf95 6deb4e7
Author: Eric Larson <larson.eric.d@gmail.com>
Date:   Tue Apr 14 19:31:27 2015 -0700

     Merge pull request #868 from campagnola/perspective

     Perspective correction

Strange problem...

**Comment by gabyx** [comment]
the simple code 
```
from vispy.visuals.collections import PointCollection
points = PointCollection()
```

Does not work

**Comment by brickgao** [comment]
It doesn't for me in latest version, too.

```
Traceback (most recent call last):
  File "point_collection.py", line 17, in <module>
    points = PointCollection("agg", color="shared", transform=panzoom)
  File "/home/brickgao/workspace/venv2/lib/python2.7/site-packages/vispy-0.4.0.dev0-py2.7.egg/vispy/visuals/collections/point_collection.py", line 20, in PointCollection
    return AggPointCollection(*args, **kwargs)
  File "/home/brickgao/workspace/venv2/lib/python2.7/site-packages/vispy-0.4.0.dev0-py2.7.egg/vispy/visuals/collections/agg_point_collection.py", line 54, in __init__
    vertex=vertex, fragment=fragment, **kwargs)
  File "/home/brickgao/workspace/venv2/lib/python2.7/site-packages/vispy-0.4.0.dev0-py2.7.egg/vispy/visuals/collections/raw_point_collection.py", line 73, in __init__
    program.vert['transform'] = self.transform
  File "/home/brickgao/workspace/venv2/lib/python2.7/site-packages/vispy-0.4.0.dev0-py2.7.egg/vispy/visuals/shaders/function.py", line 224, in __setitem__
    raise KeyError('Invalid template variable %r' % key)
KeyError: "Invalid template variable 'transform'"
```

**Comment by campagnola** [comment]
Try this:
1. Run `python -m pdb examples/collections/point_collection.py`
2. Type `c [enter]` to start the program
3. When the error appears, type `print self.code`. At the bottom of the print, you should see:
    ```
        gl_Position = $transform(vec4(position, 1));
    ```
    If not, post the code output you see. Also post the contents of `vispy/glsl/collections/raw-point.vert`, which is the original source of the `$transform` template variable.
4. If you type `print self.template_vars`, you should get `set(['transform'])`

**Comment by gabyx** [comment]
Will do this tomorrow, I installed the latest on my Mac here, and it works,  something is strange with my python stuff at work :-)

**Comment by gabyx** [comment]
Syntax Output (no ``gl_position`` there):

```
python3 -m pdb examples/collections/point_collection.py 
> /home/zfmgpu/Downloads/vispy/examples/collections/point_collection.py(5)<module>()
-> import sys
(Pdb) c
Traceback (most recent call last):
  File "/usr/lib/python3.4/pdb.py", line 1661, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.4/pdb.py", line 1542, in _runscript
    self.run(statement)
  File "/usr/lib/python3.4/bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/zfmgpu/Downloads/vispy/examples/collections/point_collection.py", line 5, in <module>
    import sys
  File "/opt/python3.4env/lib/python3.4/site-packages/vispy-0.4.0_dev-py3.4.egg/vispy/visuals/collections/point_collection.py", line 19, in PointCollection
    return RawPointCollection(*args, **kwargs)
  File "/opt/python3.4env/lib/python3.4/site-packages/vispy-0.4.0_dev-py3.4.egg/vispy/visuals/collections/raw_point_collection.py", line 73, in __init__
    program.vert['transform'] = self.transform
  File "/opt/python3.4env/lib/python3.4/site-packages/vispy-0.4.0_dev-py3.4.egg/vispy/visuals/shaders/function.py", line 224, in __setitem__
    raise KeyError('Invalid template variable %r' % key)
KeyError: "Invalid template variable 'transform'"
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /opt/python3.4env/lib/python3.4/site-packages/vispy-0.4.0_dev-py3.4.egg/vispy/visuals/shaders/function.py(224)__setitem__()
-> raise KeyError('Invalid template variable %r' % key)
```
```
(Pdb) print(self.code)

uniform   sampler2D uniforms;
uniform   vec3      uniforms_shape;
attribute float     collection_index;

varying vec4  color;

void fetch_uniforms() {
    float rows   = uniforms_shape.x;
    float cols   = uniforms_shape.y;
    float count  = uniforms_shape.z;
    float index  = collection_index;
    int index_x  = int(mod(index, (floor(cols/(count/4.0))))) * int(count/4.0);
    int index_y  = int(floor(index / (floor(cols/(count/4.0)))));
    float size_x = cols - 1.0;
    float size_y = rows - 1.0;
    float ty     = 0.0;
    if (size_y > 0.0)
        ty = float(index_y)/size_y;
    int i = index_x;
    vec4 _uniform;

    _uniform = texture2D(uniforms, vec2(float(i++)/size_x,ty));
    color.xyzw = _uniform.xyzw;
}

uniform float size;
attribute vec3 position;
collections/raw-point.vert
```

```
(Pdb) print(self.template_vars)
set()
(Pdb) 

```

this is `` vispy/glsl/collections/raw-point.vert``
```
// ----------------------------------------------------------------------------
// Copyright (c) 2014, Nicolas P. Rougier. All Rights Reserved.
// Distributed under the (new) BSD License.
// ----------------------------------------------------------------------------

// Externs
// ------------------------------------
// extern vec3 position;
// extern float size;
// extern vec4 color;
// vec4 transform(vec3 position);


// Varyings
// ------------------------------------
varying float v_size;
varying vec4  v_color;


// Main (hooked)
// ------------------------------------
void main()
{
    fetch_uniforms();

    v_size = size;
    v_color = color;

    gl_Position = $transform(vec4(position, 1));
    gl_PointSize = size;
}
```

**Comment by campagnola** [comment]
Thanks! It looks like one of the GLSL files is not being loaded correctly (the "collections/raw-point.vert" at the end of the shader code indicates the file was not found. @rougier, can you have a look? I see this in `vispy/glsl/__init__.py`:

```
def get(name):
    """Retrieve code from the given filename."""

    filename = find(name)
    if filename is None:
        return name
    with open(filename) as fid:
        return fid.read()
```

Is the `return name` line necessary? It would be much nicer to just raise an exception here.

**Comment by bollu** [comment]
I'm having the same error when I tried to run ```tiger.py``` and ```choropleth.py```among the collections example. I'll take a look at this tomorrow after my Mech end semester exam.

I have a feeling that the error will crop up among all collections.


Just for the record - I'm running the Windows 10 technical preview with ```Python2.7```

***python version***
```
{lamb} python --version
Python 2.7.9
```

***installed packages***
```
{lamb} pip list
ipython (3.1.0)
numpy (1.9.2)
pip (6.1.1)
PyOpenGL (3.1.0)
PyQt4 (4.11.3)
pyreadline (2.0)
requests (2.7.0)
scipy (0.15.1)
setuptools (7.0)
vispy (0.4.0.dev0)
```

***tiger.py***
```
{lamb} python tiger.py
Downloading data from https://github.com/vispy/demo-data/raw/master/tiger/tiger.svg (108 kB)
[........................................] 100.00000 / downloading
File saved as C:\Users\siddu\AppData\Local\vispy\data\tiger\tiger.svg.
WARNING: Unhandled SVG tag (metadata)
WARNING: Unhandled SVG tag (defs)
Traceback (most recent call last):
  File "tiger.py", line 25, in <module>
    "agg+", linewidth='shared', color="shared", transform=panzoom)
  File "F:\software\Python2.7\lib\site-packages\vispy-0.4.0_dev-py2.7.egg\vispy\visuals\collections\path_collection.py", line 23, in PathCollection
    return AggPathCollection(*args, **kwargs)
  File "F:\software\Python2.7\lib\site-packages\vispy-0.4.0_dev-py2.7.egg\vispy\visuals\collections\agg_path_collection.py", line 99, in __init__
    self._programs[0].vert['transform'] = self.transform
  File "F:\software\Python2.7\lib\site-packages\vispy-0.4.0_dev-py2.7.egg\vispy\visuals\shaders\function.py", line 224, in __setitem__
    raise KeyError('Invalid template variable %r' % key)
KeyError: "Invalid template variable 'transform'"
```

***choropleth.py***
```
 python choropleth.py
Downloading data from https://github.com/vispy/demo-data/raw/master/uscounties/uscounties.geojson (8.2 MB)
[........................................] 100.00000 \ downloading
File saved as C:\Users\siddu\AppData\Local\vispy\data\uscounties\uscounties.geojson.
Traceback (most recent call last):
  File "choropleth.py", line 46, in <module>
    paths = PathCollection(mode="agg+", color="global", transform=panzoom)
  File "F:\software\Python2.7\lib\site-packages\vispy-0.4.0_dev-py2.7.egg\vispy\visuals\collections\path_collection.py", line 23, in PathCollection
    return AggPathCollection(*args, **kwargs)
  File "F:\software\Python2.7\lib\site-packages\vispy-0.4.0_dev-py2.7.egg\vispy\visuals\collections\agg_path_collection.py", line 99, in __init__
    self._programs[0].vert['transform'] = self.transform
  File "F:\software\Python2.7\lib\site-packages\vispy-0.4.0_dev-py2.7.egg\vispy\visuals\shaders\function.py", line 224, in __setitem__
    raise KeyError('Invalid template variable %r' % key)
KeyError: "Invalid template variable 'transform'"
```

**Comment by Eric89GXL** [comment]
@bollu it would be great if you could try to diagnose this ... @rougier any reason you can think of why this would be happening?

@bollu BTW if you do `python setup.py develop` instead of `python setup.py install`, then whatever version of `vispy` you have checked out via `git` will be the active one in the next Python session you start.

**Comment by rougier** [comment]
Th culprit seems to be in vispy/glsl/__init__.py. @gabyx , coudl add debug message in the find function to check the reason why the file has not been found ?

**Comment by Eric89GXL** [comment]
I bet `setup.py` needs to be updated. Looking into it now. @rougier okay if we delete the `return name` line? I agree with @campagnola that it seems dangerous.

**Comment by rougier** [comment]
Yes returning name was a bad idea.
