### ISSUE TITLE
error with render_transform

### ISSUE THREAD

**Issue by eendebakpt** [vispy/vispy#883]
The following test code gives an error:

<pre><code>
import vispy
import vispy.scene
rr=vispy.scene.SceneCanvas()    
rr.render_transform
</pre></code>

The error generated is:

<pre>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eendebakpt/.local/lib/python2.7/site-packages/vispy-0.4.0_dev-py2.7.egg/vispy/scene/canvas.py", line 408, in render_transform
    return self.fb_ndc_transform * self.canvas_fb_transform
  File "/home/eendebakpt/.local/lib/python2.7/site-packages/vispy-0.4.0_dev-py2.7.egg/vispy/scene/canvas.py", line 392, in fb_ndc_transform
    x, y, w, h = self._vp_stack[-1]
IndexError: list index out of range
</pre>

Also with visuals added to the canvas the error occurs.

**Comment by almarklein** [comment]
Outdated. The `render_transform` is no longer an attribute of the canvas, and the underlying issue has likely been fixed.
