### ISSUE TITLE
pyglet backend

### ISSUE THREAD

**Issue by rougier** [vispy/vispy#91]
Just added app.use("pyglet") in examples/demos/atom.py (after import), got:

```
Traceback (most recent call last):
  File "atom.py", line 15, in <module>
    app.use("pyglet")
  File "/usr/locaL/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy-0.2.1-py2.7.egg/vispy/app/_default_app.py", line 33, in use
    return default_app.use(backend_name)
  File "/usr/locaL/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vispy-0.2.1-py2.7.egg/vispy/app/application.py", line 167, in use
    raise RuntimeError(msg)
RuntimeError: Could not import backend "Pyglet":
cannot import name keys
```

**Comment by edisonchensy** [comment]
Traceback (most recent call last):
  File "/home/Edison/SSD-6D/ssd-6d-master/rendering/utils.py", line 18, in <module>
    from rendering.renderer import Renderer
  File "/home/Edison/SSD-6D/ssd-6d-master/rendering/renderer.py", line 8, in <module>
    app.use_app('pyglet')   # Set backend
  File "/home/Edison/anaconda3/lib/python3.6/site-packages/vispy/app/_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "/home/Edison/anaconda3/lib/python3.6/site-packages/vispy/app/application.py", line 49, in __init__
    self._use(backend_name)
  File "/home/Edison/anaconda3/lib/python3.6/site-packages/vispy/app/application.py", line 223, in _use
    raise RuntimeError(msg)
RuntimeError: Could not import backend "Pyglet":
Cannot connect to "None"

I have the similar problem on Pyglet, I have no idea what's going on, can you plz take a look?

**Comment by davidh-ssec** [comment]
@edisonchensy Please make a new issue.
