### ISSUE TITLE
 `vispy.plot` doesn't work in WebGL with images 

### ISSUE THREAD

**Issue by josephwinston** [vispy/vispy#957]
At git  commit `e18e2ab1b9149268a345f7b2ad2d7787c4c64159`, using `anaconda` on an up to date OS X system.  

The following code taken from http://vispy.org/examples/basics/plotting/volume.html without the volume rendering fails:

``` python
import vispy.app
vispy.app.use_app('ipynb_webgl')

import numpy as np

from vispy import io, plot as vp

fig = vp.Fig(show=False)

data = np.load(io.load_data_file('brain/mri.npz'))['data']
data = np.flipud(np.rollaxis(data, 1))
vol_data = data.copy(order='C') # make c continous
print vol_data.flags

clim = [32, 192]
#vol_pw = fig[0, 0]
#vol_pw.volume(vol_data, clim=clim)
#vol_pw.camera.elevation = 30
#vol_pw.camera.azimuth = 30
#vol_pw.camera.scale_factor /= 1.5

shape = vol_data.shape
fig[1, 0].image(vol_data[:, :, shape[2] // 2], cmap='grays', clim=clim)
fig[0, 1].image(vol_data[:, shape[1] // 2, :], cmap='grays', clim=clim)
fig[1, 1].image(vol_data[shape[0] // 2, :, :].T, cmap='grays', clim=clim)

fig.show(run=True)
```

The output is:

``` python
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
:0: FutureWarning: IPython widgets are experimental and may change in the future.
WARNING: Traceback (most recent call last):
  File "/Users/hb55683/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/hb55683/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 574, in launch_instance
    app.start()
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/IPython/kernel/zmq/kernelapp.py", line 373, in start
    ioloop.IOLoop.instance().start()
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 151, in start
    super(ZMQIOLoop, self).start()
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/tornado/ioloop.py", line 784, in start
    self._run_callback(callback)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/tornado/ioloop.py", line 568, in _run_callback
    ret = callback()
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/app/backends/_ipynb_webgl.py", line 209, in _draw_event
    self._vispy_canvas.events.draw()
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/event.py", line 436, in __call__
    self._invoke_callback(cb, event)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/event.py", line 452, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/event.py", line 448, in _invoke_callback
    cb(event)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/canvas.py", line 189, in on_draw
    self._draw_scene()
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/canvas.py", line 232, in _draw_scene
    self.draw_visual(self.scene, viewport=viewport)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/canvas.py", line 282, in draw_visual
    visual.draw(scene_event)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/subscene.py", line 50, in draw
    self.process_system(event, 'draw')
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/subscene.py", line 60, in process_system
    self._systems[system_name].process(event, self)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/systems.py", line 37, in process
    self.process(event, sub_node)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/systems.py", line 37, in process
    self.process(event, sub_node)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/systems.py", line 37, in process
    self.process(event, sub_node)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/systems.py", line 28, in process
    _handle_exception(False, 'reminders', self, node=node)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/systems.py", line 23, in process
    node.draw(event)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/widgets/viewbox.py", line 324, in draw
    self.scene.draw(event)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/subscene.py", line 50, in draw
    self.process_system(event, 'draw')
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/subscene.py", line 60, in process_system
    self._systems[system_name].process(event, self)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/systems.py", line 37, in process
    self.process(event, sub_node)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/systems.py", line 28, in process
    _handle_exception(False, 'reminders', self, node=node)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/systems.py", line 23, in process
    node.draw(event)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/visuals/image.py", line 306, in draw
    self._program.draw('triangles')
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/visuals/shaders/program.py", line 89, in draw
    Program.draw(self, *args, **kwargs)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/program.py", line 467, in draw
    canvas.context.flush_commands()
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/context.py", line 170, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/glir.py", line 231, in flush
    self._shared.flush(parser)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/glir.py", line 145, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/app/backends/_ipynb_webgl.py", line 110, in parse
    self._widget.send_glir_commands(commands)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/app/backends/ipython/_widget.py", line 78, in send_glir_commands
    msg = create_glir_message(commands, 'base64')
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/app/backends/_ipynb_util.py", line 97, in create_glir_message
    for buffer in buffers]
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/logs.py", line 345, in _serialize_buffer
    'buffer': base64.b64encode(buffer).decode('ascii')
  File "/Users/hb55683/anaconda/lib/python2.7/base64.py", line 53, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
ValueError: ndarray is not C-contiguous
WARNING:vispy:Traceback (most recent call last):
  File "/Users/hb55683/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/hb55683/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 574, in launch_instance
    app.start()
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/IPython/kernel/zmq/kernelapp.py", line 373, in start
    ioloop.IOLoop.instance().start()
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 151, in start
    super(ZMQIOLoop, self).start()
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/tornado/ioloop.py", line 784, in start
    self._run_callback(callback)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/tornado/ioloop.py", line 568, in _run_callback
    ret = callback()
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/app/backends/_ipynb_webgl.py", line 209, in _draw_event
    self._vispy_canvas.events.draw()
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/event.py", line 436, in __call__
    self._invoke_callback(cb, event)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/event.py", line 452, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/event.py", line 448, in _invoke_callback
    cb(event)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/canvas.py", line 189, in on_draw
    self._draw_scene()
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/canvas.py", line 232, in _draw_scene
    self.draw_visual(self.scene, viewport=viewport)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/canvas.py", line 282, in draw_visual
    visual.draw(scene_event)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/subscene.py", line 50, in draw
    self.process_system(event, 'draw')
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/subscene.py", line 60, in process_system
    self._systems[system_name].process(event, self)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/systems.py", line 37, in process
    self.process(event, sub_node)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/systems.py", line 37, in process
    self.process(event, sub_node)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/systems.py", line 37, in process
    self.process(event, sub_node)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/systems.py", line 28, in process
    _handle_exception(False, 'reminders', self, node=node)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/systems.py", line 23, in process
    node.draw(event)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/widgets/viewbox.py", line 324, in draw
    self.scene.draw(event)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/subscene.py", line 50, in draw
    self.process_system(event, 'draw')
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/subscene.py", line 60, in process_system
    self._systems[system_name].process(event, self)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/systems.py", line 37, in process
    self.process(event, sub_node)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/systems.py", line 28, in process
    _handle_exception(False, 'reminders', self, node=node)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/scene/systems.py", line 23, in process
    node.draw(event)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/visuals/image.py", line 306, in draw
    self._program.draw('triangles')
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/visuals/shaders/program.py", line 89, in draw
    Program.draw(self, *args, **kwargs)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/program.py", line 467, in draw
    canvas.context.flush_commands()
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/context.py", line 170, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/glir.py", line 231, in flush
    self._shared.flush(parser)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/gloo/glir.py", line 145, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/app/backends/_ipynb_webgl.py", line 110, in parse
    self._widget.send_glir_commands(commands)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/app/backends/ipython/_widget.py", line 78, in send_glir_commands
    msg = create_glir_message(commands, 'base64')
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/app/backends/_ipynb_util.py", line 97, in create_glir_message
    for buffer in buffers]
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/logs.py", line 345, in _serialize_buffer
    'buffer': base64.b64encode(buffer).decode('ascii')
  File "/Users/hb55683/anaconda/lib/python2.7/base64.py", line 53, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
ValueError: ndarray is not C-contiguous
ERROR: Invoking <bound method Fig.on_draw of <Fig (ipynb_webgl) at 0x10a08c150>> for DrawEvent
ERROR:vispy:Invoking <bound method Fig.on_draw of <Fig (ipynb_webgl) at 0x10a08c150>> for DrawEvent
```

And the images are not correct either.  The code without the 

``` python
import vispy.app
vispy.app.use_app('ipynb_webgl')
```

runs as expected.

Likewise so does the code found in issue #875.

**Comment by rossant** [comment]
in `File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/util/logs.py", line 345, in _serialize_buffer
    'buffer': base64.b64encode(buffer).decode('ascii')`

can you try to replace `buffer` with `buffer.copy()`?

**Comment by Eric89GXL** [comment]
Or try doing `np.ascontiguousarray(buffer)`, that would avoid any unnecessary copies.

**Comment by josephwinston** [comment]
When I make the change

```bash
345c345
<                 'buffer': base64.b64encode(buffer.copy()).decode('ascii')
---
>                 'buffer': base64.b64encode(buffer).decode('ascii')
```
There is no output at all.

**Comment by josephwinston** [comment]
@Eric89GXL I'll be happy to reduce the number of copies once everything works.

**Comment by Eric89GXL** [comment]
@rossant any other ideas?

**Comment by josephwinston** [comment]
As suggested by @Eric89GXL, I've reduced the code to:

```python
import vispy.app
vispy.app.use_app('ipynb_webgl')

import numpy as np

from vispy import io, plot as vp

fig = vp.Fig(show=False)

vol_data = np.load(io.load_data_file('brain/mri.npz'))['data']
vol_data = np.flipud(np.rollaxis(vol_data, 1))

clim = [32, 192]
#vol_pw = fig[0, 0]
#vol_pw.volume(vol_data, clim=clim)
#vol_pw.camera.elevation = 30
#vol_pw.camera.azimuth = 30
#vol_pw.camera.scale_factor /= 1.5

shape = vol_data.shape
fig[1, 0].image(vol_data[:, :, shape[2] // 2], cmap='grays', clim=clim)
fig[0, 1].image(vol_data[:, shape[1] // 2, :], cmap='grays', clim=clim)
fig[1, 1].image(vol_data[shape[0] // 2, :, :].T, cmap='grays', clim=clim)

fig.show(run=True)
```

with the patch to `vispy/util/logs.py`, but the images aren't correct.  

On firefox 38.0.5 running on OS X 10.10.4 the JavaScript console reports the following:

```bash
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
"Default extension for cell metadata editing loaded." default.js:48:8
"Raw Cell Format toolbar preset loaded." rawcell.js:82:4
"Slideshow extension for metadata editing loaded." slideshow.js:43:8
Use of Mutation Events is deprecated. Use MutationObserver instead. jquery.min.js:5:0
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:5:0
"Session: kernel_created (f37e832f-f461-4128-ba61-8dd122beca26)" session.js:52:12
"Starting WebSockets:" "ws://localhost:8888/api/kernels/8eec3684-fab1-4ed5-a366-413b582373a1" kernel.js:437:8
"Kernel: kernel_connected (8eec3684-fab1-4ed5-a366-413b582373a1)" kernel.js:98:12
"Kernel: kernel_ready (8eec3684-fab1-4ed5-a366-413b582373a1)" kernel.js:98:12
"Event loop started." vispy.min.js:1:1785
Error: WebGL: uniform1i: No program is currently bound. vispy.min.js:1:14296
Error: WebGL: uniform1i: This uniform location corresponds to a different program. vispy.min.js:1:14296
TypeError: e._ns[n] is undefined vispy.min.js:1:15016
"Event loop stopped." vispy.min.js:1:1934
```

It looks like there is a WebGL error.  Is there anything I can do to help debug this further?

**Comment by campagnola** [comment]
> Error: WebGL: uniform1i: No program is currently bound. vispy.min.js:1:14296
> Error: WebGL: uniform1i: This uniform location corresponds to a different program. vispy.min.js:1:14296

It would be nice if we could see the GLIR commands that led to this. @rossant, is that already implemented somewhere?

**Comment by rossant** [comment]
i think @izaid contributed a vispy-export CLI option to export the glir commands in an HTML or JS file

**Comment by josephwinston** [comment]
The command to export a file is documented here <https://github.com/vispy/vispy.js/issues/13>.  Running this on the program produces:

```bash
:0: FutureWarning: IPython widgets are experimental and may change in the future.
Traceback (most recent call last):
  File "foo.py", line 25, in <module>
    fig.show(run=True)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy/app/canvas.py", line 429, in show
    self._backend._vispy_set_visible(visible)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy/app/backends/_ipynb_webgl.py", line 199, in _vispy_set_visible
    self._widget = VispyWidget()
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/vispy/app/backends/ipython/_widget.py", line 46, in __init__
    super(VispyWidget, self).__init__(**kwargs)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/IPython/html/widgets/widget.py", line 481, in __init__
    super(DOMWidget, self).__init__(*pargs, **kwargs)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/IPython/html/widgets/widget.py", line 156, in __init__
    self.open()
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/IPython/html/widgets/widget.py", line 174, in open
    self.comm = Comm(**args)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/IPython/kernel/comm/comm.py", line 63, in __init__
    self.open(data)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/IPython/kernel/comm/comm.py", line 96, in open
    raise RuntimeError("Comms cannot be opened without a kernel "
RuntimeError: Comms cannot be opened without a kernel and a comm_manager attached to that kernel.
```

I'm guessing that:

```python
import vispy.app
vispy.app.use_app('ipynb_webgl')
```
Isn't correct but removing the lines don't produce the html.

**Comment by josephwinston** [comment]
Fat fingers -- I didn't mean to close

**Comment by rossant** [comment]
the webgl backend should *not* be used when exporting the commands
what command are you running exactly?

**Comment by josephwinston** [comment]
Using:

```python
import numpy as np

from vispy import io, plot as vp

fig = vp.Fig(show=False)

vol_data = np.load(io.load_data_file('brain/mri.npz'))['data']
vol_data = np.flipud(np.rollaxis(vol_data, 1))

clim = [32, 192]
#vol_pw = fig[0, 0]
#vol_pw.volume(vol_data, clim=clim)
#vol_pw.camera.elevation = 30
#vol_pw.camera.azimuth = 30
#vol_pw.camera.scale_factor /= 1.5

shape = vol_data.shape
fig[1, 0].image(vol_data[:, :, shape[2] // 2], cmap='grays', clim=clim)
fig[0, 1].image(vol_data[:, shape[1] // 2, :], cmap='grays', clim=clim)
fig[1, 1].image(vol_data[shape[0] // 2, :, :].T, cmap='grays', clim=clim)

fig.show(run=True)
```

in a file called foo.py and invoking as `~/anaconda/bin/python foo.py --vispy-export=myviz.html` produces:

![example](https://cloud.githubusercontent.com/assets/226217/8150780/ca46c7b2-12bc-11e5-8ad3-e20bd9d5ac83.png)

Exiting with and `escape` key press does not produce `pyviz.html`

**Comment by rossant** [comment]
hmm, one possibility might be my bad memory: https://github.com/vispy/vispy/blob/bc2d3047acf26a81f1c0d8f9175324e044e89459/vispy/util/config.py#L117 ...

**Comment by josephwinston** [comment]
Running with `~/anaconda/bin/python foo.py   --vispy-glir-file=myviz.html` produces <https://gist.githubusercontent.com/josephwinston/74d7f5425cf8386c79e7/raw/myviz.html>

**Comment by rossant** [comment]
ok this is a JS file -- can you open it from test_commands.html in the vispy.js repo?

**Comment by josephwinston** [comment]
No output from firefox 38.0.5.  The console reports:

```bash
OpenGL compositor Initialized Succesfully.
Version: 2.1 INTEL-10.0.31
Vendor: Intel Inc.
Renderer: Intel HD Graphics 3000 OpenGL Engine
FBO Texture Target: TEXTURE_2D
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. d1793.js:26:0
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
HTTPS Everywhere WARN: Malformed host passed to potentiallyApplicableRulesets: 
rs is null HTTPSRules.js:514:0
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:5:0
ReferenceError: vispy is not defined test_commands.html:21:10
OpenGL compositor Initialized Succesfully.
Version: 2.1 INTEL-10.0.31
Vendor: Intel Inc.
Renderer: Intel HD Graphics 3000 OpenGL Engine
FBO Texture Target: TEXTURE_2D
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] update.xml
```

It looks like the JavaScript version of vispy isn't installed.

**Comment by izaid** [comment]
It's been a while, so hopefully I'll be able to help. I think you have to install vispy.js, have you done that?

**Comment by josephwinston** [comment]
By the way, `display_points.json` in the example directory fails the same way in firefox as well as safari 8.0.7.  Might be a user error here.

**Comment by josephwinston** [comment]
I'm using head of vispy.js (75034785d094ffee8a61865ac9eb9b39b4aabfcd)

**Comment by josephwinston** [comment]
Following the install instructions in vispy.js

``` bash
npm install
./node_modules/.bin/gulp
```
Makes `test_commands.html` work.

Here is the output, the same thing I see in the browser.

![untitled](https://cloud.githubusercontent.com/assets/226217/8151028/2b1a9ece-12c7-11e5-9ac3-9dfe0107202c.png)

The error looks to be the same too.

![untitled2](https://cloud.githubusercontent.com/assets/226217/8151042/81faff86-12c7-11e5-8e73-1d5f16f2f228.png)

**Comment by izaid** [comment]
Are you volume rendering? If yes, that's the problem.

**Comment by izaid** [comment]
Not all of VisPy works in the browser because not all of OpenGL is supported in the browser. Volume rendering is one such example.

We've been trying to get it there, but haven't done so yet.

**Comment by josephwinston** [comment]
I thought that I commented out the volume rendering.

```python
#vol_pw = fig[0, 0]
#vol_pw.volume(vol_data, clim=clim)
#vol_pw.camera.elevation = 30
#vol_pw.camera.azimuth = 30
#vol_pw.camera.scale_factor /= 1.5
```

But I'm a new vispy user and could be wrong.

**Comment by izaid** [comment]
Yeah, it's not just the volume rendering that doesn't work in the browser, but some of the underlying scene graph stuff. This might be what vispy.plot uses -- @campagnola @almarklein are the people that know.

In any case, we need to fix the WebGL issues. We're aware of that...

**Comment by campagnola** [comment]
My SciPy presentation is on Wednesday.. If anyone happens to be available to bang on this and get the scenegraph working in the next few days, that would make an awesome addition to the demos  :) 
@izaid @rossant @almarklein

**Comment by Eric89GXL** [comment]
Which bits do you need working? Last I knew, on `master` lines and text worked fine, so you could at least do plots. Not sure if that's still the case for `scenegraph-update`, though.

**Comment by campagnola** [comment]
Actually, scenegraph-update uses picking for mouse interaction, which won't work on ipython until we can return data from the browser.  .. so most likely I will just run ipython demos from masster.

**Comment by campagnola** [comment]
Here, this would be the important demo for ipython:

    from vispy import app, plot
    app.use_app('ipynb_webgl')
    fig = plot.Fig()
    fig[0, 0].plot([1,5,2,4,3])

It fails in master.

**Comment by Eric89GXL** [comment]
Add `fig.show(run=True)` to the end and it should work. You can also enable that backend using our new IPython syntax, too:
```
%load_ext vispy.ipython
from vispy import plot as vp

fig = vp.Fig(show=False)
fig[0, 0].plot([1,5,2,4,3])
fig.show(run=True)
```

**Comment by djhoese** [comment]
This should be working now in current master and 0.6. At least to a limited sense (animation/event handling will be slow).
